BloomBooks/BloomDesktop

- DistFiles/localization/Big Book/ReadMe-en.xlf
- DistFiles/localization/Picture Dictionary/ReadMe-en.xlf
- DistFiles/localization/Wall Calendar/ReadMe-en.xlf
- src/BloomBrowserUI/templates/template books/Big Book/ReadMe-en.md
- src/BloomBrowserUI/templates/template books/Picture Dictionary/ReadMe-en.md
- src/BloomBrowserUI/templates/template books/Wall Calendar/ReadMe-en.md
* Big Book, Picture Dictionary and Wall Calendar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2032)
> BL-5360 Remove Feedback section from templates

- DistFiles/localization/Big Book/ReadMe-en.xlf
- DistFiles/localization/Picture Dictionary/ReadMe-en.xlf
- DistFiles/localization/Wall Calendar/ReadMe-en.xlf
- src/BloomBrowserUI/templates/template books/Big Book/ReadMe-en.md
- src/BloomBrowserUI/templates/template books/Picture Dictionary/ReadMe-en.md
- src/BloomBrowserUI/templates/template books/Wall Calendar/ReadMe-en.md
* cherry-pick from 4.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2035)
> BL-5360 Remove Feedback from template readmes

- src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2042)
> Warn and show data if synphony is null in AddWordsFromFile (BL-5246)

- DistFiles/localization/README.md
- src/BloomExe/ApplicationContainer.cs
- src/BloomExe/Book/RuntimeInformationInjector.cs
- src/BloomExe/Program.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
- src/BloomExe/web/I18NHandler.cs
Also update the localizations/README.md file to explain how to use this new feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2040)
> Add --harvest-for-localization command line option

- src/BloomBrowserUI/bookEdit/css/editMode.less
- src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less
- src/BloomBrowserUI/bookEdit/css/origami.less
- src/BloomBrowserUI/bookEdit/css/origamiEditing.less
- src/BloomBrowserUI/bookEdit/pageThumbnailList/TemplatePagesThumbnailList.less
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
- src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less
- src/BloomBrowserUI/bookEdit/toolbox/readerTools.less
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.less
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
- src/BloomBrowserUI/bookLayout/basePage.less
- src/BloomBrowserUI/bookPreview/previewMode.less
- src/BloomBrowserUI/ePUB/bloomEPUBPreview.less
- src/BloomBrowserUI/pageChooser/page-chooser.less
- src/BloomBrowserUI/templates/common-mixins.less
- src/BloomBrowserUI/templates/template books/Big Book/Big Book.less
- src/BloomBrowserUI/templates/template books/Wall Calendar/wallCalendar.less
- src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.less
* unfortunately, some spacing issues I cleaned up
might confuse things a bit, but I'm just refactoring.
* there is probably more that could be done here, but it's
a bit open-ended.
* from now on, we should strive to put any reuseable colors
in the common-mixins.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2049)
> BL-5326 Move colors to common-mixins

- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
- src/BloomExe/Wizard/WinForms/WizardPage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2052)
> Fix crash changing UI language when creating collection (BL-5402)

- debian/README
- debian/bloom-betainternal
- debian/bloom-betainternal.appdata.xml
- debian/bloom-betainternal.desktop
- debian/changelog
- debian/control
- debian/copyright
- debian/install
- debian/rules
THIS SHOULD NOT BE MERGED ONTO MASTER!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2057)
> Rename Linux package to -newbeta for 4.1 branch

- debian/bloom-alpha.appdata.xml
- debian/changelog
- debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2062)
> Update the Linux packaging version to 4.2

- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/en/Palaso.xlf
- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
- src/BloomExe/Book/RuntimeInformationInjector.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/Publish/Android/file/FilePublisher.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/Publish/PublishView.Designer.cs
Also tweak a few source files to correct localization related errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2053)
> Update the Bloom.xlf and Palaso.xlf for Bloom 4.0 and later

- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/en/Palaso.xlf
- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
- src/BloomExe/Book/RuntimeInformationInjector.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/Publish/Android/file/FilePublisher.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/Publish/PublishView.Designer.cs
Also tweak a few source files to correct localization related errors.
(This is a cherry-pick from master)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2069)
> Update the Bloom.xlf and Palaso.xlf for Bloom 3.9 and later

- src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2076)
> Remove unwanted HTML encoding from translations (BL-5469)

- DistFiles/localization/fr/Bloom.xlf
- DistFiles/localization/pbu/Bloom.xlf
- DistFiles/localization/pbu/Palaso.xlf
- DistFiles/localization/prs/Bloom.xlf
- DistFiles/localization/prs/Palaso.xlf
This is a cherry-pick from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2080)
> Update translations from Crowdin since yesterday (20180119)

- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2077)
> BL-5437 Get talking ePub to Save

- DistFiles/localization/Big Book/ReadMe-tr.xlf
- DistFiles/localization/Template Starter/ReadMe-tr.xlf
- DistFiles/localization/Wall Calendar/ReadMe-tr.xlf
- DistFiles/localization/es/Bloom.xlf
- DistFiles/localization/es/Palaso.xlf
- DistFiles/localization/pbu/Bloom.xlf
- DistFiles/localization/prs/Bloom.xlf
- DistFiles/localization/tr/Bloom.xlf
- DistFiles/localization/tr/IntegrityFailureAdvice.xlf
- DistFiles/localization/tr/Palaso.xlf
- DistFiles/localization/tr/Publish-Android-Troubleshooting.xlf
- DistFiles/localization/tr/TrainingVideos.xlf
- DistFiles/localization/tr/bloomEpubPreview.xlf
- DistFiles/localization/tr/leveledReaderInfo.xlf
This is a cherry-pick from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2084)
> Merge new translations from Crowdin (20180122)

- src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2079)
> Handle Spanish and Portuguese license localizations (BL-5473)

- src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2088)
> Fix tests for fixing Spanish localization search (BL-5473)

- src/BloomExe/Workspace/WorkspaceView.cs
* won't close if just hovering over help menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2098)
> BL-5476 Make UI Language menu stay up

- src/BloomExe/Edit/PageControlsApi.cs
* save page first
* checked other page control functions for
proper behavior
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2101)
> [4.1] BL-5421 Lock/unlock book lost typing

- DistFiles/localization/README.md
- build/getDependencies-Linux.sh
- build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2095)
> Update Crowdin merge process to use CheckOrFixXliff

- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2106)
> Display end page better in ePUB books (BL-5495)

- src/BloomExe/MiscUI/ProblemReporterDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2108)
> Suppress youtrack port number and use ssl

- src/BloomTests/Book/BookTestsBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2107)
> Fix broken epub unit tests (related to BL-5495)

- DistFiles/localization/en/bloomEpubPreview.xlf
- src/BloomBrowserUI/ePUB/bloomEpubPreview-en.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2110)
> Adjust our wording for the new Gitden settings dialog (BL-5496)

- DistFiles/localization/en/bloomEpubPreview.xlf
- src/BloomBrowserUI/ePUB/bloomEpubPreview-en.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2113)
> Merge from4.0

- DistFiles/localization/en/bloomEpubPreview.xlf
- src/BloomBrowserUI/ePUB/bloomEpubPreview-en.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2114)
> Merge from4.1 to master

- DistFiles/localization/Template Starter/ReadMe-fr.xlf
- DistFiles/localization/Template Starter/ReadMe-pbu.xlf
- DistFiles/localization/Template Starter/ReadMe-prs.xlf
- DistFiles/localization/Template Starter/ReadMe-pt.xlf
- DistFiles/localization/az/bloomEpubPreview.xlf
- DistFiles/localization/es/Bloom.xlf
- DistFiles/localization/es/TrainingVideos.xlf
- DistFiles/localization/es/bloomEpubPreview.xlf
- DistFiles/localization/es/leveledReaderInfo.xlf
- DistFiles/localization/fr/Bloom.xlf
- DistFiles/localization/fr/Palaso.xlf
- DistFiles/localization/fr/TrainingVideos.xlf
- DistFiles/localization/fr/bloomEpubPreview.xlf
- DistFiles/localization/fr/leveledReaderInfo.xlf
- DistFiles/localization/pbu/TrainingVideos.xlf
- DistFiles/localization/pbu/bloomEpubPreview.xlf
- DistFiles/localization/pbu/leveledReaderInfo.xlf
- DistFiles/localization/prs/TrainingVideos.xlf
- DistFiles/localization/prs/bloomEpubPreview.xlf
- DistFiles/localization/prs/leveledReaderInfo.xlf
- DistFiles/localization/pt/Bloom.xlf
- DistFiles/localization/pt/Palaso.xlf
- DistFiles/localization/pt/TrainingVideos.xlf
- DistFiles/localization/pt/bloomEpubPreview.xlf
- DistFiles/localization/pt/leveledReaderInfo.xlf
- DistFiles/localization/tr/TrainingVideos.xlf
- DistFiles/localization/tr/bloomEpubPreview.xlf
- DistFiles/localization/tr/leveledReaderInfo.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2117)
> Merge new translations from Crowdin (20180129)

- src/BloomBrowserUI/ePUB/baseEPUB.less
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2116)
> Fix ePUB End Page display without side-effects (BL-5495)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2124)
> [4.1]BL-5435 Localize formatting style names in Format Dialog

- src/BloomBrowserUI/ePUB/baseEPUB.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2125)
> Fix ePUB branding with multiple images (BL-5495)

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/templates/Sample Shells/The Moon and the Cap/The Moon and the Cap.htm
- src/BloomBrowserUI/templates/bloom-foundation-mixins.pug
- src/BloomExe/Book/Book.cs
- src/BloomTests/Book/BookTests.cs
* just needed to set the data-i18n attribute correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2134)
> [4.0]BL-5313 Localize PageLabels

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2128)
> Fix a pair of i18n problems in TypeScript code (BL-5314)

- src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs
- src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2140)
> Sort language names by native name if Latin alphabet (BL-5463)

- src/BloomExe/NonFatalProblem.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
* Like download internet issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2139)
> BL-5493 Don't yellow screen for known issues

- debian/README
- debian/bloom
- debian/bloom.appdata.xml
- debian/bloom.desktop
- debian/changelog
- debian/control
- debian/copyright
- debian/install
- debian/rules
DO NOT MERGE TO Version4.1 or master!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2141)
> Change Linux package to release bloom-desktop 4.0

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/js/bloomImages.ts
- src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs
- src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2143)
> Merge4.1 to master 20180205

- debian/README
- debian/bloom-beta
- debian/bloom-beta.appdata.xml
- debian/bloom-beta.desktop
- debian/changelog
- debian/control
- debian/copyright
- debian/install
- debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2144)
> Update Linux package to release bloom-desktop-beta 4.1

- src/BloomBrowserUI/ePUB/baseEPUB.less
- src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.less
- src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2149)
> Remove "The End" notices

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2148)
> Make BL.org download progress bar more accurate (BL-5443)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
* if the shell has original copyright info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2145)
> BL-5563 Allow upload of shell, no copyright

- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2150)
> Fix setting zoom for non-English systems (BL-5579)

- src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2151)
> Set limit of 300% for zooming (BL-5579)

- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2154)
> Fix (Linux) filename case sensitivity bug (BL-5580)

- src/BloomExe/NonFatalProblem.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2153)
> [4.0]BL-5493 Fix message box

- DistFiles/localization/en/IntegrityFailureAdvice.xlf
- DistFiles/localization/en/bloomEpubPreview.xlf
- src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2164)
> Preserve generated xliff files better when building Bloom

- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
* Publish -> Android thumbnail color select
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2167)
> [4.1]BL-5340 Click outside to cancel

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/web/controllers/ImageApi.cs
- src/BloomTests/web/controllers/ImageApiTests.cs
* add ndash separator
* ignore placeholder1.png, placeholder2.png, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2162)
> [4.1]BL-5441 BL-5442 Paste Image Credits

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2172)
> Use collection level settings in Bloom books (BL-5384)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomTests/Book/BookStorageTests.cs
This is the same change proposed earlier for Version4.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2183)
> Fix broken reference to "Big Books/Big Book.html" (BL-5620)

- src/BloomExe/CLI/HydrateBookCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2182)
> Update hydration code to reflect the latest reality

- src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
- src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
This link appears only in the info (hint) tab of the source bubble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2187)
> Add link for adding credits in source bubble tab (BL-5611)

- DistFiles/BloomBlankPage.htm
- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2189)
> Use real file for blank page display (BL-5598)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Collection/CollectionSettings.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2191)
> Allow custom names for national/regional languages (BL-5311)

- src/BloomBrowserUI/npm-shrinkwrap.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2193)
> npm shrinkwrap (BL-5485)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/templates/template books/Basic Book/template/Picture on Left-landscape.svg
- src/BloomBrowserUI/templates/template books/Basic Book/template/Picture on Left.svg
- src/BloomBrowserUI/templates/template books/Decodable Reader/template/Picture on Left-landscape.svg
- src/BloomBrowserUI/templates/template books/Decodable Reader/template/Picture on Left.svg
- src/BloomBrowserUI/templates/template books/Leveled Reader/template/Picture on Left-landscape.svg
- src/BloomBrowserUI/templates/template books/Leveled Reader/template/Picture on Left.svg
- src/BloomBrowserUI/templates/template books/standard-page-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2192)
> Add Picture on Left standard page template (BL-5633)

- DistFiles/localization/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2207)
> Tweak the Crowdin translation merge instructions

- DistFiles/localization/Big Book/ReadMe-en.xlf
- src/BloomBrowserUI/templates/template books/Big Book/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2208)
> [4.0]BL-5635 Update link in Big Book readme

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/ApplicationUpdateSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2196)
> Update the Restart message to remove ambiguity (BL-5623)

- src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2218)
> L10nSharp can handle approximate language codes (BL-5479)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxPanel.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2219)
> Fix help link for Talking Book Tool (BL-5631)

- DistFiles/localization/Big Book/ReadMe-ar.xlf
- DistFiles/localization/Big Book/ReadMe-az.xlf
- DistFiles/localization/Big Book/ReadMe-bn.xlf
- DistFiles/localization/Big Book/ReadMe-es.xlf
- DistFiles/localization/Big Book/ReadMe-fr.xlf
- DistFiles/localization/Big Book/ReadMe-id.xlf
- DistFiles/localization/Big Book/ReadMe-pbu.xlf
- DistFiles/localization/Big Book/ReadMe-prs.xlf
- DistFiles/localization/Big Book/ReadMe-pt.xlf
- DistFiles/localization/Big Book/ReadMe-sw.xlf
- DistFiles/localization/Big Book/ReadMe-tr.xlf
- DistFiles/localization/Big Book/ReadMe-zh-CN.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2220)
> Follow-up to BL-5635

- DistFiles/localization/Big Book/ReadMe-ar.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2224)
> Add PDF link to Arabic Big Book ReadMe (BL-5635)

- DistFiles/localization/en/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2226)
> Add TemplateBooks.PageLabel.Bloom Reader Quiz to Bloom.xlf (BL-5536)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/CollectionTab/BloomLibraryLinkVerification.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2230)
> Internationalize Bloom Library shell book message (BL-5512)

- src/BloomExe/Publish/Android/usb/AndroidDeviceUsbConnection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2236)
> Prevent unneeded nasty messages if we fail to check if a book is on the device (BL-5548)

- crowdin.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2237)
> Try something else for crowdin.yml to get zh-CN

- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2227)
> Don't report missing L10N for HelpMenu.Help Menu (BL-5610)

- DistFiles/localization/fr/Bloom.xlf
This is a cherry-pick from master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2244)
> New translations Bloom.xlf (French)

- DistFiles/localization/fr/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2246)
> Fix broken French translation that slipped through

- DistFiles/localization/fr/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2247)
> Merge4.0 to4.1 20180305

- DistFiles/localization/fr/Bloom.xlf
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/templates/template books/Multimedia/Multimedia.pug
- src/BloomExe/Book/BookCopyrightAndLicense.cs
- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2248)
> Merge 4.1 to master

- src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2249)
> BL-5696 Chg error msg sending to BR via wifi

- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishView.cs
* or 4.0 never installed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2250)
> [4.0]BL-5706 Safeguard against LAME uninstall

- src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2253)
> Fix a new test that was failing on Linux

- src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2259)
> Merge from4.1 to master 20180307

- src/BloomExe/Browser.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
- src/BloomExe/CollectionTab/BloomLibraryLinkVerification.cs
- src/BloomExe/Edit/JpegWarningDialog.cs
- src/BloomExe/MiscUI/ProblemReporterDialog.cs
- src/BloomExe/Registration/RegistrationDialog.cs
- src/BloomExe/Shell.cs
- src/BloomExe/WebLibraryIntegration/LoginDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2254)
> For Linux, use PortableClipboard where needed in dialogs (BL-5681)

- src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2260)
> Update book display when collection languages change (BL-5444)

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/Edit/PageControlsApi.cs
- src/BloomExe/Workspace/WorkspaceView.cs
- src/BloomExe/Workspace/ZoomControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2261)
> Reinstate zoom wheel functionality (BL-5584)

- src/BloomExe/Browser.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
- src/BloomExe/CollectionTab/BloomLibraryLinkVerification.cs
- src/BloomExe/Edit/JpegWarningDialog.cs
- src/BloomExe/MiscUI/ProblemReporterDialog.cs
- src/BloomExe/Registration/RegistrationDialog.cs
- src/BloomExe/Shell.cs
- src/BloomExe/WebLibraryIntegration/LoginDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2262)
> Merge4.1 into master

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2264)
> BL-5731 exclude *.md files from upload

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2263)
> Fix the direction of zooming for wheel scrolling (BL-5584)

- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2266)
> Handle decodable markup when using Keyman (BL-5440)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomExe/web/BloomWebSocketServer.cs
- src/BloomExe/web/IBloomWebSocketServer.cs
- src/BloomExe/web/WebSocketProgress.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Book/BookTestsBase.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
- src/BloomTests/Publish/UsbPublisherTests.cs
- src/BloomTests/web/WebSocketServerSpy.cs
* fixed misspelled function
* added WebSocketServerSpy to test output to
Bloom's WebSocket
* added MockUsbPublisher to throw Disk is Full Exception
* added test for Disk Full Exception catch
* added test for file size calculation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2257)
> BL-5710 Not enough space on device

- src/BloomTests/Publish/UsbPublisherTests.cs
fails on TeamCity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2269)
> BL-5710 Ignore Async test

- src/Bloom-ChorusPlugin/app.config
- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
- src/BloomExe/app.config
- src/BloomExe/packages.config
- src/BloomTests/app.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2272)
> BL-5748 Make background music level non-linear

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
This includes a null merge of files in the debian folder that were  changed for Version4.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2274)
> Merge from4.2 to master 20180314

- debian/bloom-alpha.appdata.xml
- debian/changelog
- debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2276)
> Update Linux packages to version 4.3 on master branch

- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2280)
> BL-5710 try to fix Not Enough Space message

- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
- src/BloomTests/Publish/UsbPublisherTests.cs
* It's a COMException!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2282)
> BL-5710 try #3 USB device full

- src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2285)
> Remove unneeded logging during gulp build (BL-5767)

- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomExe/web/controllers/ImageApi.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
- src/BloomTests/Publish/UsbPublisherTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2286)
> Merge from Version4.1 to Version4.2

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/bookLayout/bookFeatures.less
- src/BloomBrowserUI/gulpfile.js
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomExe/web/controllers/ImageApi.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
- src/BloomTests/Publish/UsbPublisherTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2287)
> Merge from Version4.2 to master

- src/BloomBrowserUI/publish/android/androidPublishUI.html
- src/BloomBrowserUI/publish/android/androidPublishUI.less
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/publish/android/colorChooser.less
- src/BloomBrowserUI/react_components/colorChooser.tsx
* Created a reusable color chooser component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2279)
> BL-5741 Created a reusable color chooser component

- build/getDependencies-Linux.sh
- build/getDependencies-windows.sh
- src/BloomExe/BloomExe.csproj
- src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/Program.cs
- src/BloomExe/Publish/Android/file/FilePublisher.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/web/ReadersApi.cs
- src/BloomExe/web/controllers/MusicApi.cs
Also update the getDependencies scripts to include DIalogAdapters.dll
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2291)
> Use GTK file dialogs on Linux (BL-5541)

- src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2292)
> Fix crash in setting removed language 3 (BL-5795)

- DistFiles/localization/en/Palaso.xlf
This won't have any effect until it is merged to master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2294)
> Add new string in Palaso.xlf for image chooser change (BL-5541)

- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2295)
> BL-5710 Log device full message

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/web/controllers/MusicApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2296)
> Warn users about known invalid mp3 music files (BL-5742)

- build/getDependencies-Linux.sh
- build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2297)
> Update the getDependencies scripts for libpalaso-4.1 branch

- build/getDependencies-Linux.sh
- build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2302)
> Update the getDependencies scripts on the master branch

- src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2300)
> Produce Jpeg thumbnail from Jpeg cover if smaller (BL-5605)

- src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2301)
> BL-5734 delete MP3 along with wav

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/Publish/Android/usb/AndroidDeviceUsbConnection.cs
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomTests/Publish/MockUsbPublisher.cs
- src/BloomTests/Publish/UsbPublisherTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2309)
> Merge Version 4.1 to Version 4.2 (20180326)

- src/BloomExe/Collection/CollectionSettings.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/Collection/ScriptSettingsDialog.Designer.cs
- src/BloomExe/Collection/ScriptSettingsDialog.cs
- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2311)
> Provide settings flag for line breaking only at spaces (BL-5761)

- src/BloomExe/web/UrlLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2316)
> Do not report url lookup as modal, even on Alpha (BL-5718)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookInfo.cs
- src/BloomTests/Book/BookInfoTests.cs
*Country
*Province
*District
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2317)
> BL-5411 Add Fields to Meta.Json

- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
* Assigned the cursor to be a pointer
(finger like on a web link)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2324)
> BL-4502 Cursor on Thumbnails changes

- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
- src/BloomExe/Edit/WebThumbNailList.cs
* also prevented default click response
* with Wendy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2328)
> BL-4502 Add invisible thumbnail covers

- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionCreating/LanguageIdControl.cs
- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
* removed some unused usings
* changed setting that displays checkbox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2334)
> BL-5755 Missing "regional" checkbox

- DistFiles/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2338)
> Merge from 4.1 to 4.2 (20180413)

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
- src/BloomBrowserUI/tslint.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2339)
> Merge from Version4.2 to master (20180413)

- DistFiles/localization/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2337)
> Update instructions for merging from Crowdin (20180413)

- src/BloomExe/Edit/AudioRecording.cs
This may not directly address the issue, but does improve error
handling when something bad happens during recording.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2325)
> Handle errors in sound recording better (BL-5833)

- src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx
In this case, less fiddling is generally better...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2349)
> Fix page zoom scale adjustments for pan & zoom (BL-5699)

- src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
- src/BloomExe/CollectionTab/BloomLibraryLinkVerification.Designer.cs
- src/BloomExe/CollectionTab/LibraryBookView.Designer.cs
- src/BloomExe/Edit/JpegWarningDialog.Designer.cs
- src/BloomExe/Edit/PageListView.Designer.cs
- src/BloomExe/Edit/SourceTextControl.Designer.cs
- src/BloomExe/MiscUI/TipDialog.designer.cs
- src/BloomExe/MiscUI/ToastNotifier.designer.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.Designer.cs
- src/BloomExe/Workspace/ZoomControl.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2351)
> Change "Microsoft Sans Serif" to "Segoe UI" (BL-5677)

- src/BloomTests/FluentAssertXml.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2352)
> Get Export Epub tests running on Linux (BL-4867)

- src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2358)
> Fix bug which caused unit test to spin indefinitely (related to BL-5824)

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2360)
> Add page number source to epub metadata (BL-5890)

- src/BloomTests/WebLibraryIntegration/BloomLinkArgsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2363)
> Exclude failing test not needed on Linux

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/FluentAssertXml.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2364)
> Add page-list nav element to epub navigation page (BL-5891)

- src/BloomBrowserUI/templates/xMatter/TemplateStarter-XMatter/TemplateStarter-XMatter.pug
- src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.pug
- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
- src/BloomExe/Book/BookData.cs
- src/BloomExe/Book/DataSet.cs
- src/BloomTests/Book/BookDataTests.cs
- src/BloomTests/CLI/HydrateBookCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2359)
> Persist music settings on front cover (BL-5904)

- src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2368)
> BL-5736 Small tweak to language searching

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2366)
> Add epub:type attributes where useful (BL-5893)

- DistFiles/localization/en/Bloom.xlf
* added 7 strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2371)
> [4.2]BL-5937 (5943/5947) Add Motion xlf strings

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2365)
> Add required epub accessibility metadata (BL-5895)

- DistFiles/localization/en/Bloom.xlf
* removed Pan and Zoom entries
* copied some note fields to the new Motion entries
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2373)
> [4.2]BL-5937 Clean up .xlf file

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
Also get epub output to pass conformance test as much as possible with
regard to these attributes and the epub:type attributes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2381)
> Add aria attributes for accessibility (BL-5894)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2385)
> Remove obsolete data-duration attributes (BL-3671)

- src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
- src/BloomBrowserUI/templates/xMatter/Traditional-XMatter/Traditional-XMatter.pug
- src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.pug
- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
* Factory, Traditional, Device, SIL-PNG,
SuperPaperSaver, and Video XMatters updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2388)
> BL-5944 remember XMatter Music settings

- DistFiles/localization/az/Bloom.xlf
- DistFiles/localization/az/Palaso.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2394)
> Merge existing Azerbaijani localizations from tmx files (BL-5887)

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/videoRecorder/videoTool.tsx
* due to Peak Audio Level monitor fix
* imageDescriptionTool
* videoTool (marked missing member access levels)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2393)
> Prepare 4.3 for ITool breaking change

- src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts
- src/BloomBrowserUI/bookEdit/toolbox/motionTool/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2395)
> Merge 4.2 to master

- src/BloomBrowserUI/templates/template books/Special/Special.pug
- src/BloomExe/Book/Book.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Book/BookCompressorTests.cs
- src/BloomTests/Book/BookTests.cs
- src/BloomTests/Publish/ExportEpubTests.cs
* migrate nonprinting class to bloom-nonprinting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2383)
> Rename a couple of classes

- src/BloomExe/AboutMemory.cs
- src/BloomExe/Browser.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/HelpLauncher.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/WebLibraryIntegration/LoginDialog.cs
- src/BloomExe/Workspace/WorkspaceView.cs
- src/BloomExe/web/controllers/ExternalLinkController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2401)
> Display websites on Linux if Firefox not default browser (BL-5993)

- src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2406)
> Fix crash from multiple newlines in a title (BL-5979)

- build/Bloom.proj
- src/BloomExe/XmlHtmlConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2418)
> Revert "Cherry pick updated l10n to4.2 20180518"

- build/Bloom.proj
- src/BloomExe/XmlHtmlConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2424)
> Restore two unrelated changes that got lost earlier today

- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Book/BookCompressorTests.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2387)
> Reduce images when creating epubs (BL-4731)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/ProjectContext.cs
- src/BloomExe/Properties/Settings.Designer.cs
- src/BloomExe/Properties/Settings.settings
- src/BloomExe/app.config
- src/BloomExe/web/controllers/FeatureControlApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2414)
> Hide experimental tools unless requested (BL-5864)

- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2433)
> Handle threading conflict on Publish tab (BL-6009)

- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/PageEditingModel.cs
- src/BloomExe/XmlHtmlConverter.cs
- src/BloomTests/Book/BookStorageTests.cs
* 1st commit moves video files to video folder
* 2nd commit causes unused video files to be removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2435)
> BL-5866 5867 Video folder and remove unused

- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2439)
> Remove ePUB img title and nondescriptive alt attributes (BL-6035)

- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2436)
> Fix publish tab state machine to handle only checked on (BL-6032)

- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.html
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.less
- src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/learnAboutAccessibility.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.html
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/publish/sectionScreen.less
- src/BloomBrowserUI/react_components/link.tsx
- src/BloomExe/ApplicationContainer.cs
- src/BloomExe/Browser.cs
- src/BloomExe/NavigationIsolator.cs
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.Designer.cs
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomExe/Registration/LicenseDialog.cs
- src/BloomExe/web/ServerBase.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomExe/web/controllers/ApiRequest.cs
- src/BloomTests/Book/BookTestsBase.cs
- src/BloomTests/Edit/ConfiguratorTest.cs
- src/BloomTests/NavigationIsolatorTests.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
The goals of this spike are:
1) to flush out major problems (and it did... could not make an exe).
2) to make it convenient for devs and testers to test our epubs for compatibility.
There are several things that will have to follow this spike eventually. Currently
*     you have to install node and ace itself
*    the stylesheets still come from an online cdn
*     you have to manually save the epub before running a check
*    there is no feedback while generating, and if it ran out of time, you'd just get an error. 
*   I haven't really looked at what happens as you change books while leaving the screen open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2451)
> Spike Ace-by-Daisy checker integration

- src/BloomBrowserUI/bookEdit/css/editMode.less
- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/bookLayout/basePage.less
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Edit/EditingModel.cs
* insert div with .bloom-videoOverlay before video
container while recording
* add a "Recording" label while recording
* remove it all when we're done
* also repaired sign language l10n keys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2449)
> BL-5869 User feedback while recording

- DistFiles/localization/en/Bloom.xlf
* I initially started this as part of BL-5989, but discovered it's
already been done. This PR is actually part of BL-6003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2453)
> BL-6003 Fix Image Desc Tool header l10n

- src/BloomBrowserUI/bloomUI.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.html
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomBrowserUI/react_components/apiBackedCheckbox.tsx
- src/BloomBrowserUI/react_components/checkbox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2456)
> Start on UI for A11y checklist (ours, not Daisy's)

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/web/EnhancedImageServer.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomExe/web/controllers/ApiRequest.cs
A lot of code just to store 2 bits!
Note: intentionally allows public access to BookInfo.MetaData to be public, so we don't have to write code for every single property twice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2457)
> BL-6079 Remember A11y Checkoffs

- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2462)
> Revise method to try to track failing test better

- build/dependencies.config
This was already a bloom-desktop runtime dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2463)
> Add lame to build & test dependencies for TeamCity Bloom

- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2469)
> Fix BL-6021 by resetting the video when it is done playing

- DistFiles/localization/am/Bloom.xlf
- DistFiles/localization/ar/Bloom.xlf
- DistFiles/localization/az/Bloom.xlf
- DistFiles/localization/bn/Bloom.xlf
- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/es/Bloom.xlf
- DistFiles/localization/fr/Bloom.xlf
- DistFiles/localization/ha/Bloom.xlf
- DistFiles/localization/hi/Bloom.xlf
- DistFiles/localization/id/Bloom.xlf
- DistFiles/localization/km/Bloom.xlf
- DistFiles/localization/lo/Bloom.xlf
- DistFiles/localization/my/Bloom.xlf
- DistFiles/localization/ne/Bloom.xlf
- DistFiles/localization/pbu/Bloom.xlf
- DistFiles/localization/prs/Bloom.xlf
- DistFiles/localization/pt/Bloom.xlf
- DistFiles/localization/ru/Bloom.xlf
- DistFiles/localization/rw/Bloom.xlf
- DistFiles/localization/sw/Bloom.xlf
- DistFiles/localization/ta/Bloom.xlf
- DistFiles/localization/te/Bloom.xlf
- DistFiles/localization/th/Bloom.xlf
- DistFiles/localization/tr/Bloom.xlf
- DistFiles/localization/zh-CN/Bloom.xlf
- src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs
- src/BloomExe/CollectionCreating/NewCollectionWizard.cs
* I figured if "Choose the main language..." needed
changing then "Choose the collection type"
probably did too.
* I also added periods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2431)
> BL-5750 Changed to sentence casing in 2 cases

- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomExe/web/controllers/ImageApi.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Book/AccessibilityCheckersTests.cs
- src/BloomTests/Book/BookCompressorTests.cs
- src/BloomTests/Book/BookTestsBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2466)
> BL-6080 Check for descriptions on all images

- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2470)
> Fix BL-6090 Duplicate book should have unique guid

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/motion/motion.less
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
- src/BloomBrowserUI/react_components/l10n.tsx
* put common .less code from motion too in toolbox.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2472)
> BL-6075 Add help link to Image Description Tool

- src/BloomExe/Book/BookStorage.cs
- src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2473)
> BL-6090 part 2... let's not duplicate .bak, .bloombookorder, .pdf

- src/BloomExe/SplashScreen.Designer.cs
- src/BloomExe/SplashScreen.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2476)
> Make copyright year on splash screen update automatically

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
One was easy to reproduce, the other I couldn't figure out how to make
happen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2475)
> Fix a couple of glitches caught by epubcheck (BL-6046)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2478)
> BL-6038 Backport sentence detection fix

- DistFiles/ffmpeg/BuildingFfmpeg.md
- DistFiles/ffmpeg/LICENCE-libogg
- DistFiles/ffmpeg/LICENCE-libvorbis
- DistFiles/ffmpeg/LICENCE-libx264
- DistFiles/ffmpeg/LICENSE-ffmpeg.md
- DistFiles/ffmpeg/LICENSE-libvpx
- src/BloomExe/BloomExe.csproj
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2465)
> Add ffmpeg processing for video duration metadata (BL-6022)

- src/BloomExe/Program.cs
* targets 4.2 so that Beta Internal can be used to bulk upload books
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2483)
> [4.2]BL-6019 Fix upload to use analytics

- src/BloomExe/web/controllers/PageTemplatesApi.cs
This would also help on Windows if Bloom were to be installed in
the system program folder instead of the user's AppData folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2484)
> Handle creating page type thumbnails on Linux (BL-6045)

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Linux/packages.config
- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/app.config
- src/BloomExe/packages.config
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomTests/Book/AccessibilityCheckersTests.cs
Currently does not distinguish body text from image descriptions. That will come with BL-6098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2477)
> BL-6095 Check All text has recorded audio

- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.less
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomTests/Book/AccessibilityCheckersTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2485)
> BL-6098 CheckAudioForImageDescriptionText() 

- src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2487)
> Fix gulpfile to not build ffmpeg .md files

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
First part is in libpalaso, but this can be merged independently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2491)
> Second part of Bl-6109 epub manager hangs if temp file is locked

- src/BloomExe/web/ServerBase.cs
I can't even reproduce it now, but about 3 times in a row I had been able to get Bloom to hang by opening the a11y window and then going to Collections tab and clicking "Other Collection". It was hanging on a join() call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2495)
> BL-6115 Don't hang if you can't close a listener

- src/BloomExe/BloomExe.csproj
- src/BloomExe/MiscUI/HtmlLinkDialog.Designer.cs
- src/BloomExe/MiscUI/HtmlLinkDialog.cs
- src/BloomExe/MiscUI/HtmlLinkDialog.resx
- src/BloomExe/Publish/PublishView.cs
This is almost asking for a browser-based error report option.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2494)
> Give user suggestions when out of memory making PDFs (BL-5467)

- DistFiles/ffmpeg/BuildingFfmpeg.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2497)
> Build faster, but bigger, ffmpeg for Windows (BL-6022)

- src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
And also handle ace-by-daisy failures robustly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2489)
> BL-6054 try harder to find where global node_modules might live

- src/BloomBrowserUI/bloomUI.less
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2500)
> Hide the link to a nonexistent Bloom training video (BL-6033)

- src/BloomBrowserUI/bloomUI.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
- src/BloomBrowserUI/publish/epub/EpubPreview.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.less
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/react_components/apiBackedCheckbox.tsx
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.Designer.cs
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2496)
> BL-6096 A11y Checks auto refresh

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/images/ImportVideo.svg
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2499)
> Add "Import Video" to the sign language tool (BL-5871)

- src/BloomExe/Book/BookStorage.cs
* related to BL-6099
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2506)
> Fix PathToExistingHtml

- src/BloomExe/AboutMemory.Designer.cs
- src/BloomExe/AboutMemory.cs
- src/BloomExe/Browser.cs
- src/BloomExe/CollectionTab/LibraryBookView.Designer.cs
- src/BloomExe/CollectionTab/LibraryBookView.cs
- src/BloomExe/Edit/ConfigurationDialog.cs
- src/BloomExe/Edit/EditingView.Designer.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/Edit/PageListView.Designer.cs
- src/BloomExe/Edit/PageListView.cs
- src/BloomExe/Edit/WebThumbNailList.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/Publish/HtmlPublishPanel.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomExe/web/WebLibraryView.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2509)
> BL-6069 Remove public NavigationIsolator

- src/BloomBrowserUI/bookEdit/img/changeVideoButton.svg
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2511)
> Tweak the video import UI (BL-5871)

- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2512)
> BL-6118 Require internet to use Ace by Daisy report

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
- src/BloomBrowserUI/publish/epub/EpubPreview.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/react_components/apiBackedCheckbox.tsx
- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/CollectionTab/LibraryView.Designer.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/Epub/EpubPublishUiSettings.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/web/EnhancedImageServer.cs
- src/BloomExe/web/controllers/ApiRequest.cs
- src/BloomTests/PretendRequestInfo.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
- src/BloomTests/Publish/ExportEpubWithLinksTests.cs
- src/BloomTests/web/EnhancedImageServerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2490)
> BL-6055 Save Epub UI settings to meta.json

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
- src/BloomTests/Publish/ExportEpubWithLinksTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2510)
> Move non-xml files to subfolders in epubs (BL-6037)

- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2515)
> Fix broken Book tests

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/bloomFrames.ts
- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomBrowserUI/bookEdit/js/origami.ts
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
- src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/web/controllers/BookSettingsApi.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
* when clicking on a video placeholder
* 1st commit is just cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2516)
> BL-6123 Auto select Sign Lang Tool

- src/BloomExe/Program.cs
Linux Bloom periodically crashes due to finding invalid/expired processes in the list
of processes.  I think the reorganized code makes a clearer distinction between
Windows and Linux, and even saves a little time on Linux.  (These crashes may
be due to corrupted L10NSharp output being read in at startup.  At least that
seemed to be the case yesterday, but I had no clue of that until this code was
written and running.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2518)
> Fix Bloom process counting to be more failsafe (20180620)

- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2519)
> BL-6123 fix bug where experimental is off

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2521)
> BL-6128 Migrate videos in Change Layout

- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2523)
> BL-5977 Wire up Epub help

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
- src/BloomTests/Publish/ExportEpubWithVideoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2522)
> Add video to epubs (BL-6008)

- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2528)
> BL-6137 Restore video placeholder on delete

- src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2529)
> BL-6108 fix cherry-picked from 4.3

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomExe/Publish/Epub/EpubMaker.cs
* also created appropriate l10n help keys and put
them in the .xlf file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2525)
> BL-6092 Fix capitalization of ePUB

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2527)
> BL-6137 Disable Import btn while recording

- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
* a bit of overkill, but making the base method
private will prevent this from happening again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2531)
> BL-6154 Fix error due to missing directory

- src/BloomExe/web/UrlLookup.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2532)
> Improve BL-6118 by pinging example.com instead of s3.

- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomExe/web/controllers/FeatureControlApi.cs
* refactored bloomVideo.ts some
* used asyncGetText instead of getText to get the
localized Change Video tooltip
* hid Change Video button when not using
Enterprise features
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2533)
> BL-6133 Make Import video button Enterprise

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2530)
> Control experimental template with tool as feature (BL-6047)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2534)
> BL-6074 Sign Language Tool help link

- src/BloomExe/Publish/Epub/EpubMaker.cs
* for now we can pull in the smallCoverCredits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2538)
> BL-6111 ePUB author

- DistFiles/InstallAce.sh
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2541)
> Make it possible to run Daisy ace on Linux

- DistFiles/InstallAce.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2543)
> Fix Linux InstallAce.sh script for user owned files

- src/BloomExe/CollectionTab/LibraryListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2544)
> Always show the user's books, even if experimental (BL-6047)

- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.less
- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomTests/Book/AccessibilityCheckersTests.cs
Also improved the display of server errors like this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2550)
> BL-6185 A11y checklist error if there is no audio folder

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2551)
> Rename method to ShowThisBookAsSource (BL-6047)

- DistFiles/InstallAce.sh
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2570)
> Keep Linux users from breakage when running InstallAce.sh (BL-6212)

- src/BloomBrowserUI/templates/xMatter/SIL-PNG-XMatter/SIL-PNG-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2572)
> BL-6051 Move the PNG Copyright

- debian/bloom-alpha.appdata.xml
- debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2583)
> Change the linux package version to 4.4 on master

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
- src/BloomBrowserUI/publish/accessibilityCheck/learnAboutAccessibility.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2577)
> Normalize l10n ids for toolbox tools (BL-6210)

- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2585)
> Handle images for Ace by Daisy reports on Windows (BL-6197)

- src/BloomBrowserUI/Readium/scripts/readium-all.js
- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2586)
> Fix javascript errors going from Edit to A11y Checker (BL-6226)

- src/BloomExe/HtmlThumbNailer.cs
- src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2588)
> Cancel thumbnail threads when changing/creating collections (BL-6214)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
* epubPublishUI - Save ePUB
* Accessibility Checker
* fix Style editor Char Tab description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2587)
> BL-6188 Finish L10N for 4.3 UI

- src/BloomExe/HtmlThumbNailer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2590)
> Fix a failing thumbnailer test (20180716)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/react_components/l10n.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2592)
> BL-6188 Localize Accessibility screen tabs

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2601)
> [v4.2]BL-6235 reworked Music tool methods

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2604)
> Merge 4.2 to 4.3

- src/BloomBrowserUI/templates/xMatter/SIL-PNG-XMatter/SIL-PNG-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2605)
> [v4.2] BL-6274 SIL-PNG Title page reduce wording

- src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2608)
> BL-6262 Fix Video Xmatter Pages' Label

- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2609)
> BL-6277 Change translator info bubble

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
- src/BloomBrowserUI/bookEdit/toolbox/motion/motion.less
- src/BloomBrowserUI/bookEdit/toolbox/music/music.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/publish/android/androidPublishUI.less
- src/BloomBrowserUI/webpack.config.js
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2615)
> BL-5846 Redux

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
- src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2617)
> [v4.2]BL-6277 Fix translator info bubble more places

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/RequestInfo.cs
Should this target (or be cherry-picked to) Version4.2?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2620)
> Do not cache ePUB export files (BL-6253)

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2618)
> Make wheel zoom setup independent of ckeditor (BL-6272)

- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2621)
> Save edits when switching to epub a11y window (BL-6228)

- src/BloomBrowserUI/templates/xMatter/SIL-PNG-XMatter/SIL-PNG-XMatter.pug
* some words to be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2626)
> BL-6285 SIL PNG option - credits page bubble

- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.less
- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.pug
- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/description-en.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2623)
> BL-6280 Custom XMatter Pack for SIL Mexico

- src/BloomExe/HtmlThumbNailer.cs
The new Windows code works fine on Linux, and better than what was
there before for Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2628)
> Use same code for thumbnail generation on Linux (BL-6257)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2624)
> Add back-matter pages to ePUB table of contents (BL-6231)

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2632)
> Fix failing ePUB export tests (20180725)

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2637)
> Ensure proper display of multilingual title in ePUBs (BL-6299)

- src/BloomExe/web/RequestInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2640)
> Prevent ePUB export file caching on Windows (BL-6253)

- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2642)
> BL-6304 update a11y screen when book is renamed

- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.less
- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.pug
- src/BloomBrowserUI/templates/customXMatter/ReleaseProcess.txt
* rework spacing of fields
* revise release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2635)
> BL-6280 Custom XMatter for SIL Mexico

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2616)
> [v4.2]BL-6273 Handle hand-edited Html errors better

- src/BloomTests/Publish/ExportEpubTests.cs
This is on Version 4.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2645)
> Fix tests for multilingual ordering (BL-6299)

- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2643)
> Provide enough memory for pdfjs to work reliably (BL-6247)

- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2649)
> Fix crash in sorting text by language class (BL-6299)

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2647)
> Fix tests that fail after merge from Version4.2

- src/BloomBrowserUI/bloomDialog.less
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/yarn.lock
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/Book.cs
- src/BloomExe/ProjectContext.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2661)
> BL-6171 Add read-only properties to metadata dialog

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2660)
> BL-6314 ePUB export multiple image descriptions

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2662)
> Fix failing ePUB tests

- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.less
- src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2651)
> BL-6280 Custom XMatter for MXB

- src/BloomBrowserUI/bookEdit/editViewFrame.ts
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2665)
> BL-6296 don't abort loading new page for problem unloading

- src/BloomBrowserUI/bookEdit/editViewFrame.ts
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2667)
> Merge Version4.3 into master

- src/BloomBrowserUI/bookEdit/editViewFrame.ts
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/Edit/PageControlsApi.cs
- src/BloomExe/web/BloomWebSocketServer.cs
* text over picture
* page thumbnail lists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2666)
> BL-6129 Upgrade Legacy WebSockets Clients

- src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2670)
> Ensure English license is displayed LTR (BL-6256)

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/tsconfig.json
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
Note: BL-6336 will address the labels
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2668)
> BL-6174 Some Editable Rows For Metadata Dialog

- .prettierignore
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.less
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/publish/metadata/SubjectTreeNode.ts
- src/BloomBrowserUI/publish/metadata/ThemaData.json
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
This is only a first-pass solution with some rough edges and no
localization.  The final solution may look rather different.
The display from the react-dropdown-tree-select is less than ideal
although it does give us a good tree picker that handles the 7100+
nodes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2676)
> Add Thema subject selection to the epub metadata dialog (BL-6173)

- DistFiles/branding/SIL-LEAD/credits-page-bottom.svg
* credits-page-bottom.svg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2679)
> BL-6301 Create Branding for SIL LEAD

- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/accessibleImage/accessibleImage.tsx
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
- src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/publish/epub/EpubPreview.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomBrowserUI/react_components/apiBackedCheckbox.tsx
- src/BloomBrowserUI/react_components/colorChooser.tsx
- src/BloomBrowserUI/react_components/l10n.tsx
- src/BloomBrowserUI/react_components/progressBox.tsx
- src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2678)
> BL-6172 Prepare For React Breaking Change

- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2684)
> Reset Readium preview to first page on publishing ePUB (BL-6286)

- src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2687)
> Ensure localized custom template shows proper hints (BL-6256)

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2686)
> BL-6333 Book Metadata Help Button To Help Topic

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2688)
> Adjust padding for textarea in metadata catalog (BL-6350)

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomBrowserUI/react_components/bloomButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2689)
> BL-6367 Internationalize Buttons On Book Metadata Dialog

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/react_components/checkbox.tsx
- src/BloomBrowserUI/react_components/l10n.tsx
- src/BloomBrowserUI/react_components/stringListCheckbox.tsx
- src/BloomExe/web/controllers/BookMetadataApi.cs
* last remaining question is what to do about Subject tree dropdown
(I'm assuming it isn't localized?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2681)
> BL-6336 L18n of Metadata dialog

- src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
- src/BloomBrowserUI/publish/metadata/SubjectTreeNode.ts
- src/BloomBrowserUI/publish/metadata/SubjectTreeNodeSpec.ts
- src/BloomBrowserUI/webpack.config.js
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2692)
> [WIP]BL-6178 Add Metadata to ePUB

- src/BloomExe/Book/Page.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2699)
> Fix failing tests

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomExe/web/controllers/BookMetadataApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2698)
> Reset data when the user cancels Book Metadata dialog (BL-6376)

- src/BloomBrowserUI/react_components/l10n.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2704)
> BL-6396 Fix our React L10n's to update when l10nkey changes

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2702)
> BL-6340 Change how Bloom reports missing camera

- src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2709)
> BL-6178 fix for null subjects

- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
- src/BloomBrowserUI/bookEdit/js/bloomImages.ts
- src/BloomBrowserUI/bookEdit/js/origami.ts
- src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/tsconfig.json
- src/BloomBrowserUI/tslint.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2713)
> Enhance tslint.json and tsconfig.json (BL-6345)

- src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2703)
> Fix disappearing source bubble for some overflows (BL-6295)

- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/Collection/ScriptSettingsDialog.cs
- src/BloomExe/CollectionTab/ListHeader.cs
- src/BloomExe/Extensions.cs
- src/BloomExe/MiscUI/LanguageFontDetails.cs
- src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2717)
> Replace Graphics.MeasureString with TextRenderer.MeasureText (BL-6400)

- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomExe/Book/Book.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
- src/BloomTests/Publish/ExportEpubWithVideoTests.cs
* a11yFeatures
* a11y Hazards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2714)
> BL-6178 Finish accessibility features -> ePUB

- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2712)
> BL-6391 Fix RunningOnUiThread assert in tests

- src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditorSpec.ts
- src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
- src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
- src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
- src/BloomBrowserUI/bookEdit/js/origami.ts
- src/BloomBrowserUI/typings/jquery/jquery.d.ts
This is about 20-25% of the work needed for BL-6389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2719)
> Fix 9 source files and 1 definition file for strictNulls (BL-6389)

- DistFiles/localization/en/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2725)
> Fix L10N ID for Impairment Visualizer (BL-6431)

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2726)
> Update epub preview after editing metadata (BL-6427)

- src/BloomExe/Collection/CollectionSettingsDialog.cs
* in Collection Settings dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2728)
> BL-6433 Hook up help for Enterprise tab

- src/BloomExe/web/controllers/CommonApi.cs
* if code was empty, copy crashed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2729)
> BL-6439 Fix crash on copy Enterprise code

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.tsx
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
- src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
- src/BloomBrowserUI/react_components/checkbox.tsx
* 8 .ts and .tsx files
* mostly doing null checks, but when I see a 'var'
I am changing it to 'let' or 'const' as appropriate too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2734)
> BL-6398 strictNullCheck

- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2737)
> BL-6388 Impairment Visualizer L10N message

- DistFiles/license.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2738)
> BL-6386 Update Copyright on License Screen

- src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderSettings.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
* the major refactoring is in motionTool, where I
tried to break up a 300+ line method
* also made each file conform to 'prefer-const'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2736)
> BL-6398 strict null checks for next block of 7 files

- src/BloomBrowserUI/bookEdit/toolbox/readers/directoryWatcher.ts
- src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Edit/WebThumbNailList.cs
- src/BloomExe/ProjectContext.cs
- src/BloomExe/web/BloomApiHandler.cs
- src/BloomExe/web/I18NApi.cs
- src/BloomExe/web/ReadersApi.cs
- src/BloomExe/web/controllers/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2739)
> Move actual handlers out of BloomApiHandler (BL-6450)

- src/BloomBrowserUI/bloomUI.less
- src/BloomBrowserUI/react_components/l10n.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2745)
> Clean up code useful for finding strings which have not been internationalized

- src/BloomBrowserUI/react_components/l10n.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2747)
> Fix translation of a few items which never get updated (BL-6468)

- src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderSettings.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.d.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/react_components/checkbox.tsx
* checkbox.tsx: ref type is HTMLInputElement | null
* readerSetup.ui.ts has a lot of casts to HTMLElement
before setting innerHTML, mostly because
getElementById returns HTMLElement | null
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2743)
> BL-6398 Third set of files for strict null check

- src/BloomBrowserUI/publish/accessibilityCheck/learnAboutAccessibility.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2748)
> BL-6363 Learn about Impairment Visualizer link

- src/BloomExe/Publish/Epub/EpubMaker.cs
* Get the ePUB image descriptions to use the right
font.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2750)
> [4.4] BL-6383 ePUB ImageDescription font

- src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
- src/BloomBrowserUI/react_components/l10n.tsx
- src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2749)
> Actually really report accurately if there is a problem localizing a react l10n component (BL-6468)

- debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2755)
> BL-6477 fix version 4.4 linux dependency

- debian/control
- src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
- src/BloomBrowserUI/react_components/l10n.tsx
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2756)
> Bl 6477 fix linux package dependency on master

- debian/bloom-alpha.appdata.xml
- debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2757)
> Fix Linux package on master to version 4.5

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/metadata/A11yLevelChooser.less
- src/BloomBrowserUI/publish/metadata/A11yLevelChooser.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.less
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/react_components/bloomSelect.tsx
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/BookMetadataApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2761)
> Add epub a11y conformance to book metadata (BL-5896)

- src/BloomBrowserUI/templates/bloom-foundation-mixins.pug
- src/BloomBrowserUI/templates/template books/Sign Language/Sign Language.pug
- src/BloomBrowserUI/templates/template books/standard-page-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2764)
> BL-6399 Sign Language Htm to Pug

- src/BloomBrowserUI/branding/Local-Community/summary.htm
- src/BloomBrowserUI/collection/enterpriseSettings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2765)
> BL-6435 Remove "What's This" link and Add Period

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
- src/BloomExe/web/controllers/BookMetadataApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2767)
> Add Metadata "What's this?" links and remove test output (BL-5896)

- src/BloomBrowserUI/bloomUI.less
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2768)
> UI tweaks for a11y checker (BL-6502)

- src/BloomBrowserUI/bloomModalDialog.less
- src/BloomBrowserUI/publish/metadata/A11yLevelChooser.less
- src/BloomBrowserUI/publish/metadata/A11yLevelChooser.tsx
- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
- src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
- src/BloomBrowserUI/publish/metadata/SubjectChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2770)
> BL-6507 Pretty-up Metadata dialog

- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2772)
> Improve error reporting in Bloom.Book.Book (BL-6511)

- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2782)
> Fix branding related problem on Linux (BL-6516)

- src/BloomBrowserUI/bloomModalDialog.less
- src/BloomBrowserUI/themes/bloom-jqueryui-theme/jquery-ui-dialog.custom.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2773)
> Give HTML dialogs same title and bottom-row button styling (BL-6504)

- src/BloomBrowserUI/branding/SIL-LEAD/branding.json
- src/BloomBrowserUI/branding/SIL-LEAD/branding.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2786)
> Tweak SIL LEAD branding credits page styling to fit vertically on more layouts (BL-6524)

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2793)
> Exclude commented-out fonts in ePUBs (BL-6528)

- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2795)
> Copy and rename video files when copying a page (BL-6536)

- src/BloomBrowserUI/branding/SIL-LEAD/branding.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2797)
> Add Device16x9Landscape to branding layout fix (BL-6524)

- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2777)
> Spread impairment visualizer radio buttons further apart (BL-6520)

- src/BloomExe/Edit/DecodableReaderToolSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2798)
> Fix C syntax in C# code

- src/BloomBrowserUI/publish/metadata/SubjectChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2796)
> Fix broken Subject chooser in Metadata dialog (BL-6540)

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/PageMigrationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2800)
> Fix test failures due to non-castable nodes

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
- src/BloomBrowserUI/react_components/radio.tsx
* handle state in a better manner in a few places
* made pausePlayer() safer
* fix a warning in radio.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2806)
> BL-6568 Fix Music tool to respect No Music

- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/CLI/UploadCommand.cs
- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.resx
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomExe/web/controllers/MusicApi.cs
- src/BloomTests/Book/BookStorageTests.cs
- src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2802)
> Upload audio to Bloom Library (BL-4322)

- src/BloomExe/Edit/EditingView.cs
Note that this fix is on the Version4.3 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2805)
> Fix crash due to zooming too quickly (BL-6580)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Edit/LameEncoder.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2810)
> Prevent crash if mp3 file cannot be deleted due to antivirus (BL-6605)

- debian/control
This is the latest version of Art of Reading, with the new licenses and
and the new filesystem layout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2811)
> Update Linux Bloom package to suggest art-of-reading3

- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/web/WebSocketProgress.cs
- src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2809)
> Add Done message for writing Bloomd to disk (BL-6597)

- debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2814)
> Update Linux 4.4 package to suggest art-of-reading3

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/pageChooser/page-chooser-main.pug
- src/BloomBrowserUI/pageChooser/page-chooser.less
- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomExe/web/controllers/AddOrChangePageApi.cs
* 3 commits
* 1st is just var -> const/let refactor
* 2nd handles UI and gets a flag to C#-land
* 3rd uses said flag to change layout for all pages of similar ancestry
* My PR in 4.3 will be required in master before this can be tested properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2778)
> BL-6124 Change layout for all similar pages

- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2813)
> Fix ePUB output to pass ePUB 3.0.1 checker (BL-6610)

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/HtmlDomTests.cs
* the code was functioning correctly, but it was
unclear
* added a test to prove correct function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2807)
> BL-6591 Fix transmission of styles when copying to page layout

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Edit/PageEditingModel.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2817)
> Handle videos with spaces or punctuation in names better (BL-6025)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2818)
> BL-6157 Video statistics for Sign Lg Tool

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2820)
> Add features to upload screen (BL-6609)

- DistFiles/localization/Template Starter/ReadMe-am.xlf
- DistFiles/localization/Template Starter/ReadMe-ar.xlf
- DistFiles/localization/Template Starter/ReadMe-az.xlf
- DistFiles/localization/Template Starter/ReadMe-bn.xlf
- DistFiles/localization/Template Starter/ReadMe-en.xlf
- DistFiles/localization/Template Starter/ReadMe-es.xlf
- DistFiles/localization/Template Starter/ReadMe-fr.xlf
- DistFiles/localization/Template Starter/ReadMe-fuc.xlf
- DistFiles/localization/Template Starter/ReadMe-ha.xlf
- DistFiles/localization/Template Starter/ReadMe-hi.xlf
- DistFiles/localization/Template Starter/ReadMe-id.xlf
- DistFiles/localization/Template Starter/ReadMe-km.xlf
- DistFiles/localization/Template Starter/ReadMe-lo.xlf
- DistFiles/localization/Template Starter/ReadMe-my.xlf
- DistFiles/localization/Template Starter/ReadMe-ne.xlf
- DistFiles/localization/Template Starter/ReadMe-pbu.xlf
- DistFiles/localization/Template Starter/ReadMe-prs.xlf
- DistFiles/localization/Template Starter/ReadMe-pt.xlf
- DistFiles/localization/Template Starter/ReadMe-ru.xlf
- DistFiles/localization/Template Starter/ReadMe-rw.xlf
- DistFiles/localization/Template Starter/ReadMe-sw.xlf
- DistFiles/localization/Template Starter/ReadMe-ta.xlf
- DistFiles/localization/Template Starter/ReadMe-te.xlf
- DistFiles/localization/Template Starter/ReadMe-th.xlf
- DistFiles/localization/Template Starter/ReadMe-tr.xlf
- DistFiles/localization/Template Starter/ReadMe-zh-CN.xlf
- src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2822)
> Remove version number reference from Template Starter instructions (BL-6599)

- debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2827)
> Fix new jenkins crash in Linux packaging for Version4.3

- debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2828)
> Merge from4.3 to4.4 20181022

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
Also fix a source of javascript errors related to such files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2831)
> Get video filenames with encoded chars to display in epubs (BL-6025)

- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2832)
> Bring up Sign Language Tool by clicking on video frame (BL-6149)

- src/BloomBrowserUI/bookEdit/css/rc-slider-bloom.less
- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
2 commits
* 1st is just tslint stuff: var -> const/let
* 2nd adds slider and handle for starting point
After this is merged, I will create another PR for the
video end point and using ffmpeg to trim published
video.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2830)
> BL-6120 Trim Sign Lg Video

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
The previous fix for BL-6654 made it significantly less likely to reach a bad state, but didn't fix the stuck state if you do reach it (which is still theoretically possible, just unlikely). This change addresses the 2nd half of the problem and will allow it to attempt to escape the bad state and get into an acceptable state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2841)
> More robust handling/recovery if audioCurrent is missing (BL-6654)

- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2842)
> Restore fix for video files with nonalphanumeric filenames (BL-6025)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2844)
> Keep video camera off when not enterprise enabled (BL-6261)

- DistFiles/localization/en/BloomMediumPriority.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2853)
> Add initial BloomMediumPriority.xlf for experiment (BL-6539)

- src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
- src/BloomBrowserUI/utils/measureText.ts
Add two more files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2854)
> BL-6398 4th set of files for strict null check

- src/BloomBrowserUI/collection/enterpriseSettings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2856)
> Link Enterprise "Learn More" to Bloom help, not website (BL-6677)

- DistFiles/localization/en/BloomMediumPriority.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2857)
> Add 2 more strings to BloomMediumPriority.xlf (BL-6539)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomExe/web/controllers/SignLanguageApi.cs
* add end slider for trimming video
* still need to use ffmpeg to do actual trimming
for Publication
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2846)
> BL-6656 Add End Slider

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Book/TranslationGroupManager.cs
- src/BloomTests/Book/TranslationGroupManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2849)
> Prevent Normal style underline from controlling every style (BL-6282)

- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2859)
> Re-enable rectangles when re-enable motion on page (BL-6480)

- src/BloomExe/Book/SizeAndOrientation.cs
This error had nothing to do with the issue BL-6282 itself.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2861)
> Fix a file not found toast found while testing BL-6282

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Book/VersionRequirements.cs
- src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2869)
> Merge4.4 into master 20181105

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/bloomImages.ts
- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
- src/BloomBrowserUI/bookEdit/js/origami.ts
- src/BloomBrowserUI/lib/jquery.i18n.custom.ts
- src/BloomBrowserUI/pageChooser/launch-page-chooser.ts
- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
- src/BloomBrowserUI/publish/metadata/SubjectChooserSpec.ts
- src/BloomBrowserUI/publish/metadata/SubjectTreeNodeSpec.ts
- src/BloomBrowserUI/utils/bloomApi.ts
Second set of files for this issue.  More to come.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2871)
> Update TS to use arrow functions, part 2 (BL-6401)

- DistFiles/localization/en/Palaso.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2864)
> Enhance message for ImageGalleryControl (BL-6442)

- src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
- src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2865)
> Bring overflow warning icon to the front (BL-6467)

- environ
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
- src/BloomExe/Program.cs
- src/BloomExe/packages.config
It's still a long ways from working, but at least it compiles on Linux and Bloom runs without immediately crashing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2878)
> Get Geckofx60 to compile with Linux Bloom

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2701)
> Fix video recording after move to Geckofx60 (BL-6387)

- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2885)
> Fix bug introduced by improper arrow function (BL-6684)

- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/en/BloomMediumPriority.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2890)
> Another test of BloomMediumPriority.xlf (BL-6539)

- DistFiles/localization/README.md
- DistFiles/localization/am/Bloom.xlf
- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/en/BloomMediumPriority.xlf
- src/BloomExe/Program.cs
- src/BloomExe/web/I18NApi.cs
Also update the Crowdin merge instructions and fix a bug that crept
in during the latest merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2895)
> Process the new BloomMediumPriority.xlf files (BL-6539)

- DistFiles/localization/README.md
- DistFiles/localization/am/Bloom.xlf
- src/BloomExe/Program.cs
- src/BloomExe/web/I18NApi.cs
- src/SquirrelInstaller/DownloadPointers.htm
src/BloomExe/web/I18NApi.cs deserves at least a cursory examination since I had to adjust it for
changes that had already been made to that file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2899)
> Merge 4.4 into master 20181116

- src/BloomBrowserUI/bookEdit/editViewFrame.ts
- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
- src/BloomTests/Book/BookCompressorTests.cs
- src/BloomTests/Book/BookTests.cs
* 1st commit is just refactoring
* 2nd commit publishes trimmed video files for
- ePUBs
- bloomd files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2877)
> BL-6656 Publish trimmed videos

- src/BloomExe/web/BloomServer.cs
Discovered during BL-6660, but I forgot to include it in the PR :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2907)
> Refactor out a hard-coded number

- src/BloomExe/Book/BookStarter.cs
- src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2908)
> Fix missing branding files during publishing (BL-6660)

- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
* enables upload/download of sign language videos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2914)
> BL-6120 Get upload to trim videos

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
* Don't let timings inserted in 4.5 make videos
in 4.3 get deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2920)
> [4.3]BL-6120 Backport video fix

- src/BloomExe/Publish/PublishModel.cs
And also generate simple PDFs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2918)
> Allow users to upload books with Device layouts (BL-6722)

- src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
- src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
- src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
- src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2923)
> Next set of 9 TS files checked for strict nulls (BL-6398)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2926)
> Fix video import for Linux (BL-6723)

- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2927)
> Fix determination of bookshelf names for bulk upload

- src/BloomBrowserUI/publish/epub/baseEPUB.less
- src/BloomExe/Collection/CollectionSettings.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2931)
> Get EPUB output to pass the epubcheck tool (BL-6106)

- src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
If you think this is safe enough, I could close this PR and move the fix to 4.4, or we could cherry-pick the fix back to 4.4 after merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2934)
> Fix nonlinear music volume slider problems (BL-6726)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.less
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
- src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
- src/BloomBrowserUI/react_components/expandable.tsx
- src/BloomBrowserUI/react_components/requiresBloomEnterprise.less
- src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/Workspace/WorkspaceView.cs
- src/BloomExe/web/controllers/CommonApi.cs
This probably needs a UI review before a code review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2929)
> Obscure (not hide) Enterprise tools when not enabled (BL-6705)

- src/BloomExe/Book/BookData.cs
- src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2937)
> BL-6736 Enable branding to specify a default copyright

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
- src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2940)
> Adjust to latest libpalaso version

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
* Also renamed a badly named getPage() to
getPageDocBody()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2935)
> [4.4]BL-6737 disable "Record by textbox" for xMatter

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2941)
> Fix broken video input recording (BL-6743)

- src/BloomBrowserUI/publish/epub/EpubPreview.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2942)
> Keep Ace by Daisy check from clearing ePUB preview  (BL-6733)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
* Forgot a couple of small booleans...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2944)
> BL-6737 Front Cover Audio fixup

- src/BloomExe/Palette.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2946)
> Fix the Palette class to compile on Linux/Mono

- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/PageListView.cs
- src/BloomExe/Edit/WebThumbNailList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2955)
> Get page popup menu to close properly on Linux (BL-6753)

- debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2956)
> Fix Linux package layout to match Windows installer (BL-6754)

- src/BloomBrowserUI/publish/epub/epubPublishUI.html
- src/BloomBrowserUI/publish/sectionScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2952)
> Fix problem with Readium link in ePUB preview (BL-6729)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2959)
> Remove obsolete video statistics when changing pages (BL-6752)

- src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2961)
> Don't copy tsx files to output (part of BL-6755)

- DistFiles/ffmpeg/BuildingFfmpeg.md
- debian/control
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/Book/Book.cs
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/Edit/LameEncoder.cs
- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/web/BloomServer.cs
- src/BloomTests/Publish/ExportEpubTests.cs
Also get rid of sox (use ffmpeg instead)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2962)
> Playback audio based on mp3 rather than wav (BL-6739)

- src/BloomExe/Publish/Epub/EpubMaker.cs
This may be needed only for old books since I think we set these times
in Typescript code nowadays.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2965)
> Set audio times accurately on Linux for publishing epubs (BL-6760)

- src/BloomBrowserUI/utils/bloomApi.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2964)
> Enhance BloomApi.postDebugMessage to serialize messages

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2963)
> Fix problem with sign language Trim settings on Windows (BL-6752)

- debian/rules
- src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2967)
> Change the Linux build and packaging to use yarn instead of npm

- debian/bloom-alpha.appdata.xml
- debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2973)
> Update Linux alpha package (master branch) to version 4.6

- build/Bloom.proj
- src/BloomExe/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2974)
> Promote master to 4.6 and update assembly copyright dates

- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/web/BloomApiHandler.cs
- src/BloomExe/web/controllers/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2982)
> Prevent confusing yellow crash dialog in ePUB preview (BL-6763)

- src/BloomBrowserUI/bookEdit/js/bloomImages.ts
I left a file out of the commit on Friday
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2984)
> Add missing comment (BL-6787)

- src/BloomBrowserUI/branding/PNG-RISE/branding.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2992)
> Fix huge SIL icon on title page for PNG-RISE branding (BL-6794)

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2990)
> Fix confusing image description checkbox behavior (BL-6798)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
* delete unused function
* simplify trim slider calculations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2988)
> [4.5]BL-6752 SL trimming refactor

- src/BloomBrowserUI/bloom-player/bloom-player-core.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2993)
> Fix Bloom build to incorporate bloom-player properly

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2995)
> Fix silent (no talking) Motion preview (BL-6811)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/web/controllers/ApiRequest.cs
* try a different method of loading the audio
(using load when file is ready instead of preload)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2989)
> [4.5]BL-6789 re-recorded sentence fix

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2996)
> [4.5]BL-6797 Disable Talking Book Tool if no text

- src/BloomExe/Edit/AudioRecording.cs
Update several functions to check the lock to see if the recording has finished flushing to disk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3008)
> Talking Book: Fix timing issues for Check (Play) button (BL-6789)

- src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3009)
> Delete mp3 file when we begin the recording process to ensure we don't play a stale file (BL-6789)

- src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3013)
> Enable better diagnostics from HtmlXliff during Bloom builds

- src/BloomExe/Edit/Configurator.cs
- src/BloomTests/Edit/ConfiguratorTest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3015)
> BL-6584 Handle colons in calendar day/month names

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Browser.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishHelper.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Publish/BloomReaderFileMakerTests.cs
- src/BloomTests/Publish/BloomReaderPublishTests.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This also fixes an annoying javascript error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3007)
> First stage of refactoring electronic publication (BL-6850)

- src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
* just for 4.5, hopefully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3017)
> [4.5]BL-6781 Make Sign Lg Tool experimental

- DistFiles/localization/en/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3019)
> Add L10Ns for publish Features which were missed (BL-6815)

- src/BloomBrowserUI/templates/template books/Sign Language/meta.json
* tell Bloom the SL template is experimental
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3020)
> [4.5]BL-6781 followup

- src/BloomExe/Book/BloomReaderFileMaker.cs
- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3002)
> Remove unused images from Bloom Reader books (BL-6835)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3004)
> Talking Book: Setting is on a per-text-box basis

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3021)
> Forced alignment dup sentence

- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3022)
> Add AutoScroll to BloomLibraryUploadControl (BL-6859)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
* checkboxes -> links
* for now each link points to the same page that
shows all of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3026)
> [4.5]BL-6893 Change Image Description UI

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This reverts commit e20cd70eef0a3f8bd4f808e760dd34d47505556d.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3028)
> Revert "BL-6893 Change Image Description UI"

- src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3029)
> Remove tabindex when publishing to Bloom Reader (BL-6849)

- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3030)
> Prevent branding image copying error for sample shells (BL-6852)

- src/BloomBrowserUI/modified_libraries/gridly/jquery.gridly.js
Most of the changes are due to prettier being applied to this javascript
file for the first time.  Only three lines of code (and six lines of
comment) were added: look for BL-6382 in three comment lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3035)
> Prevent dragging after right-click in page thumbnails (BL-6382)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3033)
> Fix false "Record by Sentences" message (BL-6904)

- src/BloomExe/web/controllers/AudioSegmentationApi.cs
Addresses https://issues.bloomlibrary.org/youtrack/issue/BL-6907
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3032)
> Forced alignment4.5 polish

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
* handles missing dependencies for
- Python
- eSpeak
- FFMPEG
- Aeneas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3018)
> [4.5]BL-6842 Tweak Aeneas messages

- src/BloomExe/Publish/PublishView.Designer.cs
The only real change is adding "this.tableLayoutPanel1.AutoScroll = true;".
All other changes where automatically generated by Designer, and merely
rename local variables or move code blocks around.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3040)
> Allow scrolling of the Publish Options panel (BL-6908)

- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3039)
> Make upload control size follow publish view size better (BL-6910)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/modified_libraries/gridly/jquery.gridly.js
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
- src/BloomExe/Publish/PublishView.Designer.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3042)
> Merge version4.5 to master 2019021

- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/publish/previewCommon.less
* Publish - Android
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3038)
> BL-6898 Remove Preview from orient. buttons

- src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
- src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3048)
> Fix unit tests for adjusted CC abbreviations (20190225)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/android/androidPublishUI.less
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
- src/BloomBrowserUI/publish/epub/epubPublishUI.less
- src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
- src/BloomBrowserUI/publish/previewCommon.less
- src/BloomBrowserUI/publish/sectionScreen.less
- src/BloomExe/Publish/PublishView.Designer.cs
* 1st commit is just Android refactor and common less file update
* 2nd commit brings ePUB screen into line with common file changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3050)
> BL-6900 and 6899 Tweaks to Android UI

- src/BloomExe/web/controllers/AddOrChangePageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3053)
> Ensure books with video pages have video-placeholder.svg (BL-6920)

- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Book/BookStarter.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
- src/BloomTests/Book/BookStarterTests.cs
- src/BloomTests/Book/BookStorageTests.cs
- src/BloomTests/CollectionTab/LibraryModelTests.cs
- src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
- src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
* making a book from a template
* making .bloompack s
* upload/download from S3
* duplicating a book
The first solves the problem, the others keep existing
books from expanding the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3058)
> BL-6081 filter .map files

- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
* If Swedish O/S, line spacing and paragraph spacing
should use comma as decimal separator
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3055)
> BL-5454 Format dlg localization

- src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3064)
> Don't store Enterprise codes in bloom packs (BL-6938)

- src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3066)
> Fix non-ASCII titled books to autosegment sound files with aeneas (BL-6927)

- src/BloomExe/Book/SizeAndOrientation.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3061)
> Avoid toast opening old books on Linux (triggered by BL-6923)

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/CollectionTab/LibraryListView.cs
- src/BloomExe/NonFatalProblem.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Book/BookInfoTests.cs
- src/BloomTests/WebLibraryIntegration/BookTransferDupIdTests.cs
* both for bulk upload and for any collection open
* purpose is to minimize problems due to manual
copying of book folders by the users
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3060)
> BL-6093 Auto-repair duplicate book ids

- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomExe/web/controllers/AddOrChangePageApi.cs
Also fix glitch that didn't count video blocks properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3063)
> Allow converting multiple pages despite possible data loss (BL-6921)

- src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3071)
> Make metadata dialog scroll when it should (BL-6948)

- src/BloomExe/Book/BookCopyrightAndLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3065)
> For CC0 license, store creator without displaying in book (BL-5612)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
- src/BloomBrowserUI/lib/localizationManager/localizationManagerSpec.ts
- src/BloomBrowserUI/react_components/l10n.tsx
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Book/AccessibilityCheckersTests.cs
- src/BloomTests/Publish/EPubMakerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3068)
> Revise Image Description Tool (BL-6893)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3075)
> Change "Size/Layout" to "Size/Orientation" (BL-6933)

- DistFiles/localization/ar/Bloom.xlf
- DistFiles/localization/az/Bloom.xlf
- DistFiles/localization/bn/Bloom.xlf
- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/es/Bloom.xlf
- DistFiles/localization/fr/Bloom.xlf
- DistFiles/localization/ha/Bloom.xlf
- DistFiles/localization/id/Bloom.xlf
- DistFiles/localization/ne/Bloom.xlf
- DistFiles/localization/pbu/Bloom.xlf
- DistFiles/localization/prs/Bloom.xlf
- DistFiles/localization/ru/Bloom.xlf
- DistFiles/localization/sw/Bloom.xlf
- DistFiles/localization/tr/Bloom.xlf
- DistFiles/localization/zh-CN/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/split_active.svg
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/split_enabled.svg
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/split_expected.svg
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug
- src/BloomExe/Edit/AudioRecording.cs
New UI buttons and new transitions between client states
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3056)
> Forced Alignment 4.5 New UI

- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3074)
> Fix "Delete Text Box..." to delete only the textbox (BL-6955)

- src/BloomTests/WebLibraryIntegration/BookTransferDupIdTests.cs
Also add report strings for test assertion failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3081)
> Fix unit test that fails on Linux (20190318)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3080)
> Forced Alignment: Handle scrollbar width

- src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3087)
> Ensure updating video file works for video box button (BL-6997)

- src/BloomExe/Linux/packages.config
- src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3089)
> Revert icu.net packages to 2.3.2 for older libpalaso (20190320)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3090)
> Reword message for not having aeneas installed (BL-7006)

- src/BloomExe/web/WebSocketProgress.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3091)
> Log publishing errors in the main log file (BL-7007)

- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3092)
> Fix exception if extraneous collection files are in book folder

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
- src/BloomTests/web/controllers/AudioSegmentationApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3093)
> Add eSpeak preview (BL-7014)

- src/BloomTests/WebLibraryIntegration/BookTransferDupIdTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3101)
> Try again to fix test failing for Linux on TeamCity (20190326)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Previously it was not disabled until AutoSegment() started running. AutoSegment is called asynchronously, so the UI can still register button clicks while AutoSegment() is in the queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3106)
> AutoSplit: Prevent double clicks on Split button (BL-7023)

- src/BloomBrowserUI/pageChooser/page-chooser.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3109)
> Ensure valid id is passed for translation requests (BL-6975)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/utils/bloomApi.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3110)
> Prevent mouse cursor from getting stuck in Progress state

- DistFiles/localization/en/BloomLowPriority.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/utils/bloomApi.ts
- src/BloomExe/BloomExe.csproj
- src/BloomExe/web/RequestInfo.cs
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
- src/BloomExe/web/controllers/OrthographyConverter.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Utilities.cs
- src/BloomTests/web/controllers/AudioSegmentationApiTests.cs
- src/BloomTests/web/controllers/OrthographyConverterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3105)
> AutoSplit: Orthography conversion (BL-7023)

- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
Note that this change is on Version4.4 as requested for the original issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3122)
> Remove superfluous "optional" from web upload page (BL-7022)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3120)
> Talking Book: vertically-center UI button and labels [BL-6912]

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
- src/BloomExe/web/controllers/OrthographyConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3121)
> Tweak audio segmentation transliteration and espeak preview (BL-7023)

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
- src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3124)
> Update SharpZipLib to 1.1.0 from 0.86.0 (BL-7078)

- src/BloomExe/Book/BookCompressor.cs
The fix sidesteps what is arguably a bug in the zip library we use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3123)
> Fix publishing Android books with some culture settings (BL-7078)

- src/BloomExe/BloomExe.csproj
- src/BloomTests/BloomTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3126)
> Fix BloomTests.csproj for new SharpZipLib (BL-6977, BL-7078)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Resources/current-service-urls.json
- src/BloomExe/Workspace/WorkspaceView.cs
- src/BloomExe/web/UrlLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3125)
> Add language menu link to Crowdin web page (BL-6949)

- src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
- src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs
- src/BloomExe/CollectionChoosing/OpenCreateCloneControl.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3129)
> BL-6905 Remember 9 collections

- src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3130)
> Fix for failing Linux tests on TeamCity (20190417)

- src/BloomExe/Browser.cs
- src/BloomExe/CollectionTab/LibraryBookView.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/Edit/WebThumbNailList.cs
- src/BloomExe/HtmlThumbNailer.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/web/BloomServer.cs
* reduce memory problems by replacing video
with a placeholder in thumbs
* all important changes are in BloomServer.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3134)
> BL-7074 SL Book thumbnail

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/templates/template books/Special/BloomIgnore.txt
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.Designer.cs
- src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.resx
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/web/WebSocketProgress.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomTests/Publish/BloomReaderPublishTests.cs
* in Publish -> ePUB screen
* in Accessibility Checker screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3136)
> BL-6896 Fix missing L10ns

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3143)
> Deal with ? (and + and *) in decodable list (BL-7075)

- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Android/usb/UsbPublisher.cs
- src/BloomExe/Publish/Android/wifi/WiFiAdvertiser.cs
- src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/Epub/PublishEpubApi.cs
- src/BloomExe/web/WebSocketProgress.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
- src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3144)
> Improve architecture of WebSocketProgress and derivative classes

- src/BloomExe/web/controllers/ExternalLinkController.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3147)
> Open links in default browser (BL-6952)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3141)
> Forced Alignment: Allow Ctrl+click to re-split audio (BL-7023)

- debian/control
- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
- src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3149)
> Update Geckofx60 to Windows 60.0.26 and Linux 60.0.27 (20190426)

- src/BloomExe/web/WebSocketProgress.cs
- src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3151)
> Simplify WebSocketProgress messaging to prevent exception during String.Format (BL-7150)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3150)
> Remove "Accessible to the Visually Impaired" upload checkbox (BL-7149)

- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js
- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3153)
> [4.5]BL- 7081Fix word break handling of ZWNJ

- DistFiles/localization/Template Starter/ReadMe-en.xlf
- DistFiles/localization/en/Publish-Android-Troubleshooting.xlf
- DistFiles/localization/en/TrainingVideos.xlf
- DistFiles/localization/en/leveledReaderInfo.xlf
These files are all generated by a new version of the HtmlXliff program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3157)
> Remove unwanted whitespace from English strings (BL-6758)

- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3166)
> Fix bug in XPath which causes too many elements to be selected.

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
- src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
- src/BloomBrowserUI/react_components/videoTrimSlider.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3168)
> BL-6827 Fix video trim slider sync problem

- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomTests/BloomTests.csproj
- src/BloomTests/Publish/PublishModelTests.cs
This removes all unwanted language data from uploaded books for Version4.5.
We need to decide whether this fix is safe enough for Version4.4 (or Version4.5 for that matter).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3135)
> Remove unwanted language data from uploaded books (BL-7124)

- src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3171)
> Restore the full size ACE by Daisy report view (BL-7153)

- src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
* Timing issues likely caused by setting PageAttached
prematurely, when async calls haven't finished.
* Solved by making pageAttached part of state and
setting it only when all async calls finish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3170)
> BL-6827 Fix Trim slider regression

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/web/controllers/SignLanguageApi.cs
- src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3172)
> Go back to only adding video controls for epub (BL-7083)

- src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3173)
> Fix test broken by previous commit for BL-7083

- src/BloomBrowserUI/react_components/colorChooser.tsx
* use better React standards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3178)
> Major refactor of colorChooser

- src/BloomExe/web/UrlLookup.cs
- src/BloomExe/web/controllers/AccessibilityCheckApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3180)
> Improve internet check for ACE by Daisy report (BL-7169)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/Publish/PDF/PdfMaker.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3169)
> Abort upload if making PDF fails (BL-6719)

- src/BloomExe/Book/BookData.cs
- src/BloomExe/Book/HtmlDom.cs
Also remove the ckeditor added attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3181)
> Remove <a> elements that have their content deleted (BL-6845)

- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3183)
> Upgrade bloom-player

- src/BloomExe/web/controllers/AddOrChangePageApi.cs
This change is on Version4.5 as requested in the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3184)
> Copy any needed stylesheets when changing page layout (BL-7170)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3185)
> Remove misleading/confusing word from message (BL-6999)

- src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3186)
> Allow language renaming in source collections (BL-6848)

- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/PublishHelper.cs
* pre-crop video before showing in preview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3187)
> BL-7163 Get Bloom Reader preview to trim video

- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3189)
> Ignore a common but irrelevant javascript error (BL-7076)

- src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3191)
> Properly handle empty decodable stages (BL-4721)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
- src/BloomExe/web/controllers/AudioSegmentationApi.cs
- src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
Generates books with start times embedded instead of physically splitting it up into multiple audio files.
Corresponding PR from the new Bloom Reader side: https://github.com/BloomBooks/bloom-player/pull/5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3158)
> Forced Alignment Timings (BL-7024)

- src/BloomExe/ApplicationContainer.cs
- src/BloomExe/Program.cs
- src/BloomExe/Workspace/WorkspaceView.cs
- src/BloomExe/web/I18NApi.cs
- src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
- src/BloomTests/Book/BookDataTests.cs
- src/BloomTests/web/BloomServerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3190)
> Migrate to L10NSharp 4.0

- src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs
The ghostscript bug may affect only Linux, but the fix is safe for
Windows.  This fix should perhaps be considered for Version 4.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3193)
> Work around ghostscript problem with Unicode filenames (BL-7177)

- src/BloomExe/Publish/Epub/FontFileFinder.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3194)
> Allow Bloom to find user-installed fonts for embedding (BL-7043)

- src/BloomExe/Book/SizeAndOrientation.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3198)
> Prevent bogus warning about missing customCollectionStyles.css (BL-7047)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3200)
> Internationalize quiz hint bubbles (BL-7193)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/publish/android/androidPublishUI.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3204)
> Add help link in Publish Android (BL-7067)

- DistFiles/localization/Decodable Reader/ReadMe-en.xlf
- DistFiles/localization/Leveled Reader/ReadMe-en.xlf
- src/BloomBrowserUI/templates/template books/Decodable Reader/ReadMe-en.md
- src/BloomBrowserUI/templates/template books/Leveled Reader/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3205)
> Fix wording in Decodable/Leveled Reader ReadMe files (BL-7057)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3202)
> Narration highlighting for ePubs (BL-7182)

- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3207)
> Narration highlighting for ePubs: Fix Linux unit test timings (BL-7182)

- src/BloomExe/BloomExe.csproj
- src/SquirrelInstaller/Bloom.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3208)
> Cleanup Windows installer and add missing files (BL-6755)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3195)
> Warn user of multiple html files and facilitate fixing (BL-7072)

- src/BloomBrowserUI/pageChooser/page-chooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3209)
> Scale page thumbnail images for page chooser dialog (BL-7196)

- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.ts
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3212)
> Fix window.BloomPlayer is not defined js error (BL-7214)

- src/BloomBrowserUI/lib/ckeditor/plugins/autolink/plugin.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3211)
> Get autolink pasting to work with Chrome and VS-Code (BL-6845)

- DistFiles/localization/en/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3213)
> Localize 'Quiz Page' (BL-7193)

- src/BloomBrowserUI/react_components/l10nComponents.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3215)
> Don't request unneeded translations from typescript (BL-7204)

- debian/bloom-beta.desktop
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3222)
> Merge from release to beta (20190530)

- DistFiles/localization/en/Bloom.xlf
- DistFiles/localization/en/Palaso.xlf
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug
- src/BloomExe/Book/AccessibilityCheckers.cs
- src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
- src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.Designer.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishView.cs
Also updated some strings and revised some of the new ids.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3225)
> Added new strings to Bloom.xlf and Palaso.xlf (BL-6759)

- src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3220)
> Restore Story Primer Wordfind grid functionality (BL-7061)

- src/BloomExe/Shell.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3234)
> Provide context menu screen resolution options in Alpha channel

- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3237)
> Use latest bloom-player

- src/BloomExe/ProjectContext.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3238)
> Fix forgotten epub folder reference change (20190605)

- src/BloomExe/Book/Book.cs
- src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
- src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3235)
> Make only cover images transparent (BL-4816)

- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3241)
> Don't show placeholder bloom image in Bloom Reader or ePUB (BL-7218)

- src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3240)
> Allow image description audio through to Bloom Reader books (BL-7237)

- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/webpack.core.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3244)
> Restore webpack notifier when running `yarn watch`

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookCompressor.cs
- src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3246)
> Fix transparent image check for publishing (BL-4816)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3252)
> Clean up a few things in the code before a forthcoming PR

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
- src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.less
- src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.pug
- src/BloomExe/Book/TranslationGroupManager.cs
- src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs
- src/BloomTests/Book/TranslationGroupManagerTests.cs
- src/BloomTests/TestLocalization/en/Bloom.xlf
- src/BloomTests/TestLocalization/es/Bloom.xlf
- src/BloomTests/TestLocalization/zh-CN/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3242)
> Make new quiz header editable and add translations we know (BL-7191)

- src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3254)
> Add page numbering systems for Kayah and Shan (BL-7285)

- src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3255)
> Auto restart when toggle showing unapproved l10ns (BL-7281)

- src/BloomExe/Program.cs
- src/BloomExe/Shell.cs
- src/BloomExe/ToPalaso/FontInstaller.cs
- src/BloomExe/Workspace/WorkspaceView.cs
Needs tests on all ways to restart:
* rename project
* change a key setting (e.g. a language)
* install Bloom when there is no andika basic installed yet
* change ui language to show/hide approved languages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3259)
> Related to BL-7281, which caused errors on Windows

- src/BloomExe/Book/Book.cs
- src/BloomExe/CollectionTab/LibraryBookView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3262)
> Allow a custom template book to display its ReadMe-en.md (BL-7287)

- src/BloomBrowserUI/publish/metadata/BookMetadataTable.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3263)
> Ensure "What's this?" link displays below label text (BL-7284)

- src/BloomExe/Properties/AssemblyInfo.cs
- src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3265)
> Harvester Dependency (BL-7249)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/pageChooser/launch-page-chooser.ts
- src/BloomBrowserUI/pageChooser/page-chooser.less
- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/pageChooser/templatePagePreview.tsx
- src/BloomBrowserUI/templates/template books/Special/simpleComprehensionQuiz.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3270)
> Change Quiz Page description and make dialog larger to accommodate descriptions (BL-7199)

- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx
* changed names of button handler and React
component
* removed JQuery from page-chooser.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3271)
> BL-7276 page-chooser cleanup

- src/BloomExe/Browser.cs
- src/BloomExe/HtmlThumbNailer.cs
1) Fix book thumbnail creation to show cover image
2) Fix Bloom code to use Calendar template setup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3272)
> Fixes for Geckofx60 (20190617)

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3275)
> Harvester upload (BL-7249)

- src/BloomExe/Publish/Epub/PublishEpubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3273)
> Fix initial ePUB preview to obey a11y settings (BL-7316)

- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3277)
> Get videos to play on Linux with Geckofx60 (20190624)

- src/BloomBrowserUI/templates/template books/Sign Language/ReadMe-en.md
A start on a ReadMe file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3276)
> BL-7030 Sign Language template ReadMe

- debian/control
- environ
- src/BloomExe/HelpLauncher.cs
This should also be considered for 4.5 (and maybe even 4.4).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3278)
> Allow chm viewers other than chmsee on Linux (BL-7244)

- src/BloomExe/Publish/Epub/PublishEpubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3283)
> Ensure ePUB preview works after DAISY check (BL-7309)

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3286)
> Upload collection settings to library as part of book (BL-7343)

- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3287)
> Allow quiz pages to be duplicated successfully (BL-7349)

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3289)
> Don't download collectionSettings folder from library (BL-7343)

- DistFiles/localization/en/BloomLowPriority.xlf
- src/BloomBrowserUI/collection/enterpriseSettings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3290)
> Change Enterprise Settings (None) message (BL-7351)

- src/BloomExe/Book/BookData.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomTests/Book/BookDataTests.cs
- src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3288)
> Avoid setting data-page-number value for xmatter pages (BL-7303)

- src/BloomBrowserUI/pageChooser/page-chooser.ts
- src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx
* does nothing if page is Enterprise-only and
enterprise is not available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3294)
> BL-7200 Fix dbl-click in add/change page dlg

- src/BloomBrowserUI/templates/template books/Sign Language/ReadMe-en.md
* suggested by Marlon
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3292)
> BL-7030 Sign Lg ReadMe improvements

- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3295)
> Revert bad collection settings idea in Bloom 4.5 (BL-7343)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Collection/CollectionSettings.cs
- src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/Collection/CollectionSettingsDialog.resx
* Part 1: CollectionSettings and its
CollectionSettingsDialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3297)
> BL-7352 Identify which sign language

- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js
- src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3299)
> Fix extra sentence-ending punctuation if there are multiple using upper U (BL-7372)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Collection/CollectionSettingsDialog.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
* Part 2: BloomLibraryUploadControl
* make ChangeLanguage() public
* handle link clicked in upload
*  allow user to chose sign language in Publish Upload
*  report error if trying to upload with sign language
feature checked, but no sign language chosen
* adjust upload of languages for a book to include the
specified sign language as the first language, if
selected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3301)
> BL-7352 Next steps to use sign lg collection setting

- src/BloomBrowserUI/Readium/bloomReadiumTweaks.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3302)
> Simplify Readium preview of ePUBs (BL-7310)

- src/BloomExe/Edit/AudioRecording.cs
This fixes a problem on Linux.  It doesn't really address the user's complaint, which hasn't been reproduced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3304)
> Tweak recording when no microphone device (BL-7272)

- src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3306)
> Handle possible exception looking for audio devices (BL-7272)

- DistFiles/localization/en/Publish-Android-Troubleshooting.xlf
Changes to our markdown and pug files should always have an accompanying change to the
corresponding xliff file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3307)
> Update English xliff to reflect change in markdown file (20190710)

- src/BloomExe/Book/BookInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3308)
> Add internetLimits to parse data (BL-7369)

- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3313)
> Allow 4.4 to publish books created in 4.6 (BL-7431)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3311)
> Ensure proper audio playback order in Bloom Reader (BL-7300)

- src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
- src/BloomBrowserUI/bookLayout/basePage.less
- src/BloomBrowserUI/branding/branding-base.less
- src/BloomBrowserUI/templates/common-mixins.less
- src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less
- src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
- src/BloomExe/Book/SizeAndOrientation.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3314)
> BL-7435 Add A3Portait and Legal Landscape page sizes

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3318)
> BL-7442 Talking Book Highlighting of Book Title Problem

- src/BloomExe/Book/BookStorage.cs
- src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3316)
> Allow 4.4 to read books with format version 2.1 (BL-7431)

- src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3319)
> Start writing Bloom format version 2.1 (BL-7431)

- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomTests/Book/BookTestsBase.cs
- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3320)
> Undo test hack by having relevant tests create real files (BL-7444)

- DistFiles/localization/en/Bloom.xlf
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3322)
> Remove a string for testers from being localized (BL-7383)

- src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3321)
> Eliminate bogus toast when updating settingsCollectionStyles (BL-7414)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishHelper.cs
- src/BloomTests/Book/BookTests.cs
- src/BloomTests/Publish/BloomReaderPublishTests.cs
- src/BloomTests/Publish/EPubMakerTests.cs
- src/BloomTests/Publish/EpubValidAndAccessible.cs
- src/BloomTests/Publish/ExportEpubTests.cs
- src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
- src/BloomTests/Publish/ExportEpubWithVideoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3317)
> Strip Bloom Enterprise-only features if BE off (BL-7221, BL-7222, BL-7223)

- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3323)
> BL-7408 Include all languages in Bloomds

- src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3326)
> Prevent reporting missing file for questions.json (BL-7221)

- src/BloomExe/web/BloomServer.cs
- src/BloomTests/web/BloomServerTests.cs
* replace thumb dom videos with video placeholder
image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3331)
> BL-7074 Sign Lang Memory usage

- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/web/controllers/ImageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3336)
> Fix localization of pasted image credits (BL-7494)

- src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3335)
> BL-7382 room for page nav buttons in quiz

- src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
Logically, the bug should not be happening but it is, quite consistently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3334)
> Patch around wifi publish broadcast failure (BL-7227)

- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3337)
> Look up Enterprise by CollectionSettings directly (BL-7500)

- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
* RBI bookshelf has a name that includes a comma
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3339)
> BL-7511 Bulk upload fix

- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3340)
> Update for bloom-player 0.9.35 (BL-7493)

- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3338)
> Allow picture books to be uploaded to bloomlibrary (BL-7514)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3341)
> BL-7518 Save license metadata, if changed

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/Android/PublishToAndroidApi.cs
- src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3342)
> BL-7127 Start adding quiz feature to meta.json

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Targeting 4.7 only, since 4.6 has already gone through the test plan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3344)
> Talking Book: Add fallback algo if currentTime field not set (BL-7537)

- src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3345)
> Fix saving of quiz answers (BL-7532)

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
- src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
I think these are all the changes needed for 4.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3347)
> Allow image description and obscuring without Bloom Enterprise (BL-7530)

- src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
- src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
- src/BloomExe/Publish/Epub/EpubMaker.cs
- src/BloomExe/Publish/PublishHelper.cs
Also allow impairment visualizer without Bloom Enterprise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3348)
> Publish image descriptions without Bloom Enterprise (BL-7530)

- debian/bloom-alpha.appdata.xml
- debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3349)
> Update Linux packaging for 4.7 alpha (20190816)

- src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3350)
> Revise tests for image description not needing enterprise (BL-7530)

- src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less
- src/BloomBrowserUI/publish/commonPublish/BasePublishScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3352)
> Prevent bogus scrollbar for publish Bloom Reader and ePUB (BL-7506)

- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3353)
> Update yarn.lock to match package.json for bloom-player (20190819)

- src/BloomBrowserUI/pageChooser/page-chooser.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3355)
> Fix Add Page dialog to show previous choice (BL-7472)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/TranslationGroupManager.cs
- src/BloomTests/Book/TranslationGroupManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3354)
> Prevent quiz header from adding book languages (BL-7546)

- src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.pug
- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/TranslationGroupManager.cs
- src/BloomTests/Book/BookTests.cs
- src/BloomTests/Book/TranslationGroupManagerTests.cs
The first commit just reverts the previous change for this issue which was completely reworked. So you probably want to review by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3356)
>  Prevent quiz header from adding book languages (BL-7546)

- DistFiles/localization/en/Bloom.xlf
- src/BloomBrowserUI/templates/template books/Sign Language/Sign Language.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3359)
> Add new sign language page layout (BL-7474)

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/Publish/PublishHelper.cs
- src/BloomTests/Book/BookStorageTests.cs
- src/BloomTests/Book/BookTests.cs
* change simpleComprehensionQuiz feature
back to 'quiz'
* fix broken Book.HasVideos()
including some tests for it
* Add Quiz, Talking Book, Motion, and
Sign Lg features to  web upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3358)
> BL-7127 Feature fix

- build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3360)
> Clean up old installer files after upload (BL-4359)

- src/BloomExe/BloomExe.csproj
- src/BloomExe/CLI/CreateArtifactsCommand.cs
- src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3361)
> Add new CLI option to create bloomd/epub to support Harvester (BL-7547)

- src/BloomExe/Book/BookData.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3368)
> Prevent newlines in metadata book titles (BL-7558)

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3369)
> Update to Geckofx60.*.Linux.60.0.36 (20190823)

- src/BloomExe/Book/SizeAndOrientation.cs
* don't look for Layout choices in this file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3373)
> BL-7584 Add defaultLangStyles.css to list

- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/HtmlDom.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
- src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
- src/BloomExe/Publish/PublishHelper.cs
- src/BloomExe/Publish/PublishModel.cs
- src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3362)
> Remove Enterprise features before upload if needed (BL-7559)

- src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3374)
> Restore localization of page labels (BL-7505)

- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
- src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3376)
> [4.6]BL-7588 Fix broken Record button for 4.6+

- src/BloomExe/BloomExe.csproj
- src/BloomExe/Book/Book.cs
- src/BloomExe/Book/BookCopyrightAndLicense.cs
- src/BloomExe/Book/BookInfo.cs
- src/BloomExe/Edit/BloomMetadataEditorDialog.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
- src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3378)
> Allow user to retain original copyright and license (BL-7381)

- src/BloomExe/CLI/CreateArtifactsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3381)
> Harvester - Ensure that no analytics are being sent

- src/BloomExe/Browser.cs
- src/BloomExe/Edit/Configurator.cs
- src/BloomExe/Publish/HtmlPublishPanel.Designer.cs
- src/BloomExe/Publish/PDF/PdfViewer.Designer.cs
- src/BloomExe/Publish/PublishView.Designer.cs
- src/BloomExe/Publish/PublishView.cs
- src/BloomExe/Registration/LicenseDialog.Designer.cs
This was already being done in a couple of places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3384)
> Dispose of GeckoWebBrowser objects properly (20190911)

- src/BloomBrowserUI/react_components/ContentEditable.tsx
- src/BloomBrowserUI/react_components/colorChooser.less
* Cover color for bloomd in Publish->BR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3386)
> BL-7576 Re-enable hex color entry

- src/BloomBrowserUI/react_components/ContentEditable.tsx
- src/BloomBrowserUI/react_components/colorChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3392)
> Merge from Version4.6 to master (20190917)

- src/BloomExe/Edit/BloomMetadataEditorDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3393)
> Tweak display of BloomMetadataEditorDialog (BL-7381)

- src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3390)
> Add a few missing mime types we actually see in epubs (20190916)

- src/BloomExe/Book/BookStorage.cs
- src/BloomExe/Edit/AudioRecording.cs
- src/BloomExe/Publish/AudioProcessor.cs
- src/BloomTests/Book/BookStorageTests.cs
* any book that gets selected will lose any .wav files
that were kept around for narration (not background
music)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3387)
> BL-7617 Don't keep .wav files

- src/BloomExe/Book/Book.cs
- src/BloomExe/CLI/CreateArtifactsCommand.cs
- src/BloomExe/Collection/CollectionSettings.cs
- src/BloomExe/Program.cs
- src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3395)
> Refactor HarvesterMode flag (BL-7655)

- src/BloomExe/Edit/EditingModel.cs
- src/BloomExe/Edit/EditingView.cs
- src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3396)
> Add more memory checking for diagnosing Geckofx60 (20190926)

- src/BloomTests/BloomFileLocatorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3400)
> Revert temporary TeamCity setup test (20190930)

- src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3402)
> Merge from master to geckfx60 20191003

- src/BloomExe/Book/TranslationGroupManager.cs
- src/BloomTests/Book/TranslationGroupManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3403)
> Fix bug where bloom-content1 not updated in bloomDataDiv too (BL-7713)

- src/BloomExe/Book/BookCopyrightAndLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3404)
> Don't modify original copyright when running harvester (BL-7734)

- .nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3407)
> Limit nuget to 5.2 on Linux for compatiblility with mono 4 (20191021)

- .nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3408)
> Merge from4.5 to4.6 20191021

- .nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3409)
> Merge from 4.6 to master (20191021)

- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/arcTail.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/bubble.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/bubbleSpec.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/comical.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/straightTail.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/tail.ts
- src/BloomBrowserUI/bookEdit/toolbox/callout/comical/uniqueId.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3411)
> Temporary fix to get Comical dependency from code instead of package

- src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
- src/BloomBrowserUI/package.json
- src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3414)
> Fix errors when deleting text-over-picture elements

- src/BloomBrowserUI/publish/commonPublish/BasePublishScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3418)
> Adjust publish tab to avoid ugly gap with short window (BL-7506)

- src/BloomExe/Book/Book.cs
* links to BP Language Menu logic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3420)
> BL-7610 Add comment linking logic

- src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3421)
> Text Over Picture: Reduce min height to 30px

- src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3422)
> Callout controls: Add more margin before "Add Child Bubble" link
