src/BloomExe/CollectionTab/LibraryListView.cs

The method LibraryListView.ShortenTitleIfNeeded() is throwing an ArgumentOutOfRangeException that is not being handled.

BL-867 Infinite messages when starting Bloom

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

If the .bloom-editable or any of its ancestors (including <body>) has the class "bloom-userCannotModifyStyles", then the controls that allow the user to adjust the styles will not be shown. This does not prevent the user from doing character styling, e.g. CTRL+b for bold.

Add bloom-userCannotModifyStyles to lock down fields, pages, or books

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

I'm not clear why, but previously the StyleEditor code assumed and required that user modified style rules began with ".bloom-editable". This made it impossible to have make a page where, if the user modified the style of some editable box, other elements on the page would change as well, in order to keep the page consistent. The particular page for which this came up was the credits page, where a big chunk of the page is not .bloom-editable's.

Allow user styles to effect divs that are not editable

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs

Our previous implementation of the S3ClientTests had the problem
that at the beginning of each test we emptied the test bucket.
This can cause test failures if the unit tests run at the same
time on multiple machines.
The new implementation only deletes the books the test uploaded.
This allows multiple tests to run in parallel, but has the
disadvantage that we might leave behind some test data if the
developer stops a debug session while debugging the unit tests.
However, I think this will happen rarely and it won't cause other
tests to fail.

Make S3 tests more robust

---

src/BloomBrowserUI/bookEdit/test/localizationManager.Test.js
src/BloomBrowserUI/lib/localizationManager.js
src/BloomBrowserUI/lib/localizationManager.ts

Gave incorrect results if a pattern similar to a place holder is used (see new tests).

Fix bug SimpleDotNetFormat

---

src/BloomExe/MiscUI/ProblemReporterDialog.cs

Very similar to WS-62 with a very similar change and
similar comments. On Linux systems, with specific fonts
such as Arial 12pt, entry into a text box displays with
characters oddly compressed and occasionally invisible.
This change corrects the display of those characters.
The JIRA  also reports issues with the cursor position.
Once displayed properly, the issue is somewhat less
apparent, but can still be seen towards the end of the
line. This change does not address that part of the
problem.  Changing the font by a point can be a workaround.

BL-822 Text entry is not usable

---

src/BloomExe/Collection/CollectionSettingsDialog.cs

This fixes BL-864 "[Linux] Fonts aren't listed in order".

Sort font names for combo box list (BL-864)

---

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
src/BloomTests/WebLibraryIntegration/BookTransferTests.cs

The previous test code had a race condition: when several instances
ran the GetLanguagePointers_CreatesLanguagesButDoesNotDuplicate at
the same time one instance could delete the languages that another
instance just created, causing spurious test failures. This
change creates a test specific random class path so that several
test instances can run in parallel.

Make BookTransferTests more robust

---

src/BloomTests/WebLibraryIntegration/BookTransferTests.cs

Another change to enable multiple test runs at the same time. The
books we create and upload to S3 need to have a unique id or they
will interfere with a concurrent test run.

Allow concurrent test runs

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/LibraryListView.Designer.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/LibraryListView.resx
src/BloomExe/NavigationIsolator.cs
src/BloomExe/XmlHtmlConverter.cs

- Remove commented code and timer variable
- Fix line endings in exception
- Use separate event handlers for gecko events
We raise the same event for two gecko events. Having two internal event handlers makes this a little bit more obvious when debugging and makes it possible to set a trace point outputting the information that geckofx gives us as argument.
- Use existing DOM instead of calling tidy again
The previous code re-read the HTML file and called tidy even though we already read the DOM before.

Several refactorings

---

src/BloomExe/Program.cs

The method name FinishStartup implies that we're still in the
startup phase. This can be confusing when looking at the call
stack. Renaming this method to Run makes it clearer what this
method does.

Rename FinishStartup method

---

src/BloomExe/Program.cs
src/BloomExe/Workspace/WorkspaceView.cs

The issues that caused the dialogs to be disabled have either been fixed (in Mono and L10NSharp), or else can't be reproduced.

Re-enable interactive L10NSharp dialogs (BL-656)

---

src/BloomExe/Book/Book.cs

I've seen reports of this one file generating error when in dropbox. Perhaps we write it and then write it again in rapid succession? In any case, now it is  handled by the palaso utility method that makes this tolerant of delays.

Fix BL-560: Add tolerance from Dropbox-locked languageDisplay.css

---

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomExe/Book/BookData.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Event.cs
src/BloomExe/ProjectContext.cs

Previously, you had to change pages and come back before the location would be updated. So the first step was to make a PageRefresh event that the settings could call. However, this lead to another problem, which is that the old location text would get sucked into the dataset, and then pushed back out. It was overriding the newly updated "location" value. It overrode it because the computed location value is currently in "neutral" language, "*", but on the page it goes into a box that asks for the national language. If there is none in the language, fine, the "*" one is copied in. But during refresh, the national language one gets sucked in, so now, as the new page is constructed, that sucked in (old) version of "location" wins out over the generic "*" version.
A otherwise reasonable fix …

Fix BL-912: immediate title page response to change of settings

---

DistFiles/ReleaseNotes.md
src/BloomBrowserUI/bookEdit/js/bloomEditing.js

This might have seemed like a good idea to help naive users, but it is preventing people from controlling the vertical position of text.

Fix BL-926 Bloom strips out leading paragraphs

---

src/BloomExe/web/I18NHandler.cs

I could not reproduce the bug immediately after it happened to me, even after removing my localization files. Looking at the l10nsharp code, the only way I can see us getting this error ("Collection was modified; enumeration operation may not execute.") is by re-entering the code on a different thread.
We could make the Bloom server be thread-safe, but we could also do that to L10nsharp.
Meanwhile, this patch catches the error and swallows it for users.
Needs review: previously, the code got the translation, then decided whether it needed the translation or not. Now it first decides if it needs it. Is there something I'm missing about the original approach?

Work around Bl-923: L10NSharp Crash when accessed from javascript

---

src/BloomExe/CollectionTab/LibraryModel.cs

Our zip library is capable of storing zip entries with names in
UTF-8, but needed to be told to do so.

BL-935, BloomPack zip should round-trip non-ascii filenames

---

src/BloomExe/CollectionTab/BloomLibraryLinkVerification.Designer.cs

The original bug was widget overlap clipping some text characters.
When that was fixed, the message was breaking lines in the middle of
words.  I fixed that by changing from a Label to a TextBox for the
message display.  This is very common in our code for multiline text
displays.

Fix dialog message display (BL-871)

---

src/BloomExe/ToPalaso/BetterToolTip.cs

This happens under difficult to reproduce situations, where some combination of changing UI language and opening a new collection leads to L10NSharp trying to change the text of the "Duplicate This Page" tooltip and then, farther into .net, getting a null reference exception. Assumption is that something (L10NSharp?) is holding onto the control that has been garbage collected, so doesn't appreciate being woken up to get a new label.
For now, this just detects the situation and swallows it in release mode.

Work around BL-938: Crash after changing UI Language

---

src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/RequestInfo.cs
src/BloomExe/web/ServerBase.cs
src/BloomTests/PretendRequestInfo.cs

2:26:12 PM	Book.UpdateImgMetdataAttributesToMatchImage() Image C:\Users\Hopper\Documents\Bloom\OT Kings\King Rehoboam Shames the Elders Rejects Wise Adv\OTK%201Kings%2012_8.jpg is missing 
2:26:19 PM	**EnhancedImageServer: File Missing: C:/Users/Hopper/Documents/Bloom/OT Kings/King Rehoboam Shames the Elders Rejects Wise Adv/ 
The first example above needs to be urldecoded, and the second is a request for the directory index, which should be denied by the server.

BL-962: Fix some "file missing" messages

---

src/BloomExe/Edit/EditingView.Designer.cs

Mono doesn't implement the Table style. The Flow style looks the same
for this code as Table style on Windows, and Mono does implement the
Flow style.

Ensure ToolStrip items all display for Edit view (BL-961)

---

src/BloomExe/Book/BookInfo.cs
src/BloomExe/WebLibraryIntegration/BookTransfer.cs
src/BloomTests/Book/BookInfoTests.cs

Prevent uploading a field that was recently added to BookMetaData
but which is not relevant to our website, and thus allow uploads
to work again even though Parse.com does not find the field.
Provides a general way to contro which fields get uploaded;
in future, new metadata fields should only be uploaded if actually
useful to the web site.

BL-928 Restrict Json uploaded to parse.com

---

src/BloomExe/Edit/EditingView.Designer.cs

This is necessary (but not sufficient) to fix BL-961.  The Hindi
menu strings were generating a height of 24 pixels each.  Leaving
two extra pixels in height seems prudent.  A fix to Mono is also
needed as it defaults to horizontal display of tall buttons for
Table style layout.

Increase height for editing menu toolstrip (BL-961)

---

src/BloomExe/BloomExe.csproj

This is a "Windows-only" fix. The "largeaddressaware" switch is a linker command that allows geckofx to access up to 2GB of memory.  See https://bitbucket.org/geckofx/geckofx-29.0/issue/181/enable-largeaddressaware-was-strange-out

BL-944: PDF viewer running out of memory too soon

---

build/Bloom.proj
debian/changelog
src/BloomExe/Properties/AssemblyInfo.cs
src/Installer/Installer.wixproj

A unique version number is necessary for the nightly packages on
Linux.

Change version number of master branch to 3.1

---

src/BloomExe/ApplicationContainer.cs

On Linux we don't use the Sparkle mechanism to update the
application. Instead we rely on the system packaging mechanism.
We can save a few milliseconds on startup if we don't download
the version table.

Don't download UpdateVersionTable on Linux

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

The limit for using small buttons on hovering over images needed raising some. The new value triggers small buttons for Story Primer's icons and works well with both A5 and A4 sizes on the screen.

BL-993 Change limit for using small buttons on image hovering

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/XMatterHelper.cs

This PR also makes the 2 messages encountered in this scenario localizable, and makes the edit and publish tabs be disabled if the select book has this kind of error. Previously, that happened only if the book's html could not validate.

Give a good error message if the called for xmatter is missing

---

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.htm
DistFiles/factoryCollections/Templates/Basic Book/Basic Book.jade
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/BookStarterTests.cs

In the past there were well-intentioned attempts to provide default title for new books. It turns out that this is fraught with unintended consequences that would just confuse the user. This PR overhauls this system, taking in to account differences such as:
- whether the book we're making is from a template (remove all titles, name the book's file "Book" until we have something better
- if we're making it from a Shell Book (leave all the titles)
- If we're just displaying a caption of a source book, in which case prefer the current UI Language but then keep digging in order of guess preferences until your find *some* label to show
- If we're just displaying a caption of one of the editable books in our collection, in which case just show "Title Missing" until they enter a title in the …

Fix BL-945 governing book captions and initial titles

---

DistFiles/ReleaseNotes.md
src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/JpegWarningDialog.Designer.cs
src/BloomExe/Edit/JpegWarningDialog.cs
src/BloomExe/Edit/JpegWarningDialog.resx
src/BloomExe/Edit/PageEditingModel.cs
src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/ImageProcessing/LowResImageCache.cs
src/BloomExe/Workspace/BloomClipboard.cs

Addresses BL-967 by being careful about file types and doing less
- fix situation where we would save a jpg as pngs
- pasted images are now named "image1",2,3, etc.
- images are no longer added with a temporary gibberish name; the original names are maintained.
- don't compress pngs (could return someday, but for now it's hard on people with slower machines, and sometimes increases the size)
- don't make pngs transparent (made pdfs ugly). Could return again, but this time as a run-time feature of the server delivering images
- simple heuristically-driven detection of images that look like they shouldn't really be jpegs, based on amount of white, number of colors, and grayscale vs. color.
- New dialog that warns people before adding suspicious jpegs.
- Log now contains record of memory …

BL-967 & BL-609 image import problems

---

src/BloomExe/Browser.Designer.cs
src/BloomExe/Browser.cs
src/BloomExe/Browser.resx
src/BloomExe/Edit/EditingView.Designer.cs
src/BloomExe/Edit/EditingView.cs

- Enable the timer only while EditingView is active
- Properly dispose the timer
- Remove Browser._updateCommandsTimer. Instead do what it used to
do from EditingView._editButtonsUpdateTimer.
I tried these changes while working on BL-866. Although it doesn't
fix the problem I think it is still an improvement.

 Refactor timer handling in Browser and EditingView

---

src/BloomExe/Edit/EditingView.Designer.cs

This is a slight adjustment for the final language that
still didn't work after Steve's previous change.  With
this change, Tegulu UI allows the menus to appear and
the other languages still work.

BL-961 Layout menus do not show in some languages

---

src/BloomExe/Book/Book.cs
src/BloomExe/ImageProcessing/ImageUtils.cs

Up through Bloom 3.0, we would make white areas transparent when importing images, in order to make them look good against the colored background of a book cover. This caused problems with some PDF viewers, so in Bloom 3.1, we switched to only making them transparent at runtime. This commit allows us to undo that transparency-making.

Make "Update Books" restore white to previously transparent-ified imgs

---

packages/repositories.config
src/BloomBrowserUI/packages.config
src/BloomExe/BloomExe.csproj
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/MiscUI/ProblemReporterDialog.Designer.cs
src/BloomExe/MiscUI/ProblemReporterDialog.cs
src/BloomExe/packages.config
src/BloomExe/web/EnhancedImageServer.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Book/BookStorageTests.cs
src/BloomTests/ProblemReporterDialogTests.cs
src/BloomTests/packages.config

This is done by switching to a different library to access JIRA.
This was necessary because of a mono bug that prevents the
deserialization of data received from Jira.
Additionally on Linux we have to use http instead of https, again
because of a bug in mono.

 Fix uploading of problems to JIRA (BL-821)

---

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/bloom-xmatter-common.less

Previously, LibPalaso was giving us little images, so the img never had a height or width, it just came out right. But the current version of libpalaso will be giving us large, print-ready images, so we need to explicitly declare the size.

Set explicit size for Creative Commons License Logos

---

src/BloomExe/BloomExe.csproj
src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/web/BloomServer.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/LowResImageProcessing/ImageServerTests.cs
src/BloomTests/LowResImageProcessing/RuntimeImageProcessingTests.cs
src/BloomTests/web/EnhancedImageServerTests.cs

Now that we deliver images over http (instead of "file:///" links), we get around the problem of gecko giving up on large local files too easily. Now, we can deliver very large images (I tried up to 9mb jpeg) directly, at gecko does a good job of showing a low-quality image quickly and then enhancing it a it gets time. So, for jpegs, we now don't touch the image at all, except to read it and push it over the wire.
Now, for PNGs, we do still redraw them in order to introduce transparency. It it is conceivable that we should still shrink png images, but it's not clear if we should, so I'm going with no shrinking for now as the simpler operation, and then we can reintroduce it if testing shows it is needed. The code is still there #if'd out.

Better transparency, no shrinking, hands-off jpegs

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

Some pages with several images (e.g. Story Primer alphabet charts) overflowed because the images were too big. Moving the Overflow handler setup to after the call to SetupImage fixes this.

Added overflow handler after SetupImage

---

src/BloomBrowserUI/bookEdit/css/editMode.css
src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less

Fixes BL-899:	"Initially after resizing, overflow indicator is stuck on unless you up-arrow so it all shows."
This is a wee bit experimental. Let's see if we like it.

BL-899: Make overflowing boxes actually overflow to help people see what's up

---

src/BloomExe/Command.cs
src/BloomExe/Edit/EditingView.Designer.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/ToPalaso/BetterToolTip.cs
src/BloomExe/ToPalaso/BetterTooltipTransparentOverlay.cs
src/BloomExe/Workspace/WorkspaceView.cs

The copy/paste etc buttons used to have different colors on Linux, depending on whether they had a tooltip or not. This made it hard to distinguish enabled from disabled state.
This change fixes the appearance as well as the BetterTooltip class to properly paint transparency. It also
adds some missing tooltips.
This removes the workaround for BL-348 because it is no longer needed with this proper fix.

Improve better tooltip

---

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js
src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts

If you change the letters of a stage and then close the
dialog, the accordion tool doesn't update to show the
new letters.

BL-838 Decodable Reader Letters are wrong if changed

---

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js
src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts

Decodable reader tool not displaying characters and words with
PUA characters.  If the user set the font for the current
languages to Charis SIL and entered PUA characters into
the Letters and Letters Combination, they displayed
correctly on the Stages Setup screen, but not on the
accordion screen displaying the letters and words for
the current stage.  The fix applies the user specified
font to the letters and words divs on the accordion screen
as they are applied on the setup screen.

BL-546 Decodable Reader Tool PUA character display issue

---

src/BloomExe/Edit/EditingView.cs

This is needed only for Linux.  The standard text box works fine on Windows.

Use gecko-based search text box in ArtOfReadingChooser (BL-964)

---

src/BloomBrowserUI/bookEdit/EditViewFrame.htm
src/BloomBrowserUI/bookEdit/EditViewFrame.jade
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Browser.cs
src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/PageListView.cs
src/BloomExe/Edit/TemplatePagesView.cs
src/BloomExe/Edit/ThumbNailList.cs
src/BloomExe/Edit/WebThumbNailList.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/TempFiles.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/SimulatedPageFile.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/HtmlDomTests.cs
src/BloomTests/web/EnhancedImageServerTests.cs

BL-642, Don't use <base> in temp files
The goal here is to use smarts in our
local server instead of <base> to find
images that the HTML refers to
just using filenames (without paths).
Works for the full html document
because it is in the same folder.
The core change is in
HtmlDom.BaseForRelativePaths and in
EnhancedImageServer.MakeSimulatedPageFileInBookFolder()
(see comment there).
The temp 'file' now only exists in the
local server memory, but the url
makes it seem to be in the book folder.
Since we're not using base, all temp
files that need to pretend to be in
the book folder must now use the
local server. This resulted in
changes to how we handle cases
where we want to use the full-resolution
images, like PDF generation.

BL-642, Don't use <base> in temp files

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

Made change so that it looks up the language name and uses that
in the message.  The name used now matches the name that appears
in the lower right in shadow within each text box.

BL-982 Format dialog showing a code when it should show a language name

---

src/BloomExe/Book/Book.cs
src/BloomExe/Edit/EditingModel.cs

Though we could never reproduce this bug, it did get reported several times. The last time, I had the user's collection, and found that Book A was being asked to save a page that came from book B. I'm unable to see how this is possible, or to reproduce it. However I did add in a bunch more logging which might help when the situation happens again. But even when it happens, we won't have the same failure because now it gets which book should do the saving from the page itself, rather than the "current book".

Fix BL-1060, Trying to save page in the wrong book

---

debian/bloom-desktop-unstable.sharedmimeinfo
debian/bloom-desktop.sharedmimeinfo

We won't know for sure if this fixes the problem until the Linux package is built.

BL-1085: Add mime info for bloom-desktop-unstable

---

DistFiles/ReleaseNotes.md
src/BloomBrowserUI/bookEdit/js/bloomEditing.js

This fix uses the following heuristic: if we know the text box we're pointing at uses up the full width of the marginbox, then it is safe, horizontally, to show it (it may still not be save vertically, this doesn't address that). Otherwise, error on the side of caution and only show the bubble when the user clicks in it.

Fix BL981 & BL1028, source bubbles & data-hint bubbles covering text

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

If you have the format dialog open in a text box and click in
another text box not currently in focus at exactly the point the
gear icon will appear in that box, focus shifts to the new box but
the format dialog for the original text box remains open.  The fix
makes sure that the focus event triggers the removal of any open
format dialogs as it shifts the gear icon from one box to the other.

BL-846 Format Dialog doesn't always close when another box gets focus

---

src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/BookPagesThumbnailList.htm

This commit helps some, but it appears the memory usage is directly related to how many pixels are visible. The thumbnails are only 80 pixels wide, but those 80 pixels are actually about 1200 pixels crammed into an 80 pixel space.  Running Bloom full screen takes much more memory than using a window that is just a portion of the screen. This is true on both Windows and Linux.

BL-987: Rework the thumbnail css to help reduce memory consumption

---

src/BloomExe/MiscUI/ProblemReporterDialog.Designer.cs
src/BloomExe/MiscUI/ProblemReporterDialog.cs

The Geckofx-based control refuses to display this message despite three or four different approaches (including multithreading) to get it to work.  Using a separate control is simple, even if not elegant.

Use a Label control to display "Submitting to server..." (BL-1004)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomTests/Book/BookDataTests.cs

1) Allow you to have lang={V} in the declaration of the book title template.
2) Bloom has been changed to prefer "No Title" or somesuch if the vernacular title is missing. But we have hundreds of books with only English in the SIL-LEAD/SHRP project. Fortunately these books have a set pattern for names, so this commit detects the situation and allows the English name to be displayed.

Book Titles for SHRP books

---

src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/BookPagesThumbnailList.htm
src/BloomExe/Edit/WebThumbNailList.cs

The CSS image-rendering attribute dramatically lowers the memory usage on Linux, but seems to not have the same affect on Windows. If it is applied on Windows, the image quality is degraded but the memory usage stays the same.

BL-987: Lower Linux memory use by changing thumbnail image rendering

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less

For BL-1033, the pics were cycling due to trying to show scrollbars. But the pics are already resizing to the correct size for the box, so no point in having scrollbars. I made the scrollbars stop happening and the pics are fine.
For BL-1034, the CustomPage textboxes were getting vertical scrollbars too soon primarily because of a basePage rule for min-height of 1.8em. Our normal pages want the average textbox to have a minimum size so things get spaced out well, but here the user is determining the spacing and if he wants to squash things together, I suppose we shouldn't complain too much. I just set the min-height to be equal to the line-height if the vertical scrollbars have been turned off. In the case of the CustomPage here, it doesn't matter if extra text is shown because it won't …

BL-1033/1034 Small pics cycled red overflow

---

DistFiles/localization/Bloom.en.tmx
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/bloom-xmatter-common.css
DistFiles/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/bookEdit/js/bloomEditing.js

Puts the topic qtip back where it belongs next to the topic instead of above it.
If there is no topic already chosen and we are NOT in translation mode,
this will add a button labeled "Choose Topic..." to the front cover in edit mode.
Choosing a topic will hide the button.

Bl 1125 add topic

---

src/BloomBrowserUI/bookEdit/js/origami.js

This also corrects BL-1043 which is essentially a duplicate. Creating
a split on a custom page, resizing it and then deleting it resulted in
the remaining split from the pair to be the wrong size.  This
occurred with either vertical or horizontal splits.  The fix provided
here saves the width and height of the original parent and applies it
to the updated sibling which is replacing it, as it currently saves the
class.

BL-1010 Deleting resized split on custom page produces error

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/lib/localizationManager/localizationManager.js
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts

If you are using a non-English UI, the bottom line of text in
the format dialog will initially appear in English.  If you
press the format dialog for another field on the same page, the
localized text will appear.
The localization manager GetText function, which is called to
retrieve the text by the StyleEditor.ts file, returns English
the first time it is called unless the strings are already loaded
into the dictionary.  This change loads the affected strings before
the code is called to correct the problem.

BL-1014 Format Dialog text not translated

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/InstallerSupport.cs
src/BloomExe/SplashScreen.cs
src/BloomExe/UpdateVersionTable.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomTests/UpdateVersionTableTests.cs

Add logging and enhanced error handling plus refactoring/clarifying
The central thing here was changing how we handle problems encountered when we look for the version table. We now create a result-object that has the url if we got one, and and the exception if we got one. The exception is logged and the user is notified at the point that we get it, instead of leaving it to clients. But clients get the full object, and can continue to decide what to do, as before.
This also normalized code for determining the channel name.
Logging happens so that if there is a problem, the log will tell us what happened.

Logging and error handling for a pp update

---

.gitignore
src/BloomExe/Browser.cs

1st commit .gitignores the Squirrel directory
2nd commit gives a nicer error message if Firefox is not in the PATH
If in Linux, the message doesn't specify Firefox, but System Browser, since we don't specifically call Firefox

Bl 1027 nice context menu error; also .gitignore

---

src/BloomExe/Publish/PdfViewer.cs

The print dialog appears behind Bloom on Linux except for the
first time it is displayed.
This solution is a compromise since I was unable to find a way
to resolve the issue by bringing the print dialog to the foreground
in all cases.  This solution minimizes Bloom when the print button
is pressed on a Linux system.  The print dialog displays.  When the
user either presses cancel or print, Bloom is restored to the
foreground at the same size it was before Print was pressed.

BL-788 [Trusty Linux] Print dialog opens behind Bloom window

---

DistFiles/xMatter/Factory-XMatter/description-en.txt
DistFiles/xMatter/SIL-Cameroon-XMatter/description-en.txt
DistFiles/xMatter/Traditional-XMatter/description-en.txt
src/BloomExe/Book/XMatterInfo.cs

Now localizers will be able to copy the description-en.txt file in an xmatter pack to description-xx.txt, where xx = another UI language code
and translate the English text.
If later, we change the English to [V2] or later, Bloom will use the English until the other UI language catches up.

BL-1013 Allow localization of xmatter pack descriptions

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

This was likely a problem only on Windows, but the fix is safe for
Linux.

Decrease length of download folder name (BL-1163, BL-1160)

---

src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/Shell.cs

This change adds the bookname to the application title bar.
When the application starts or a book has been deleted so that
there is no selection, the title appears without a book name.
Otherwise, any time a book is selected, it appears first, followed
by the collection name, followed by the release and build
date information.

BL-1040 Show book name while editing

---

src/BloomExe/Edit/EditingView.cs

Unfortunately this effectively reverts another fix for focus problems, but having a focus problem is much better than having a total system freeze.

Fix freeze on Wasta/Mint/Cinnamon (BL-1147)

---

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm
DistFiles/xMatter/bloom-xmatter-common.css
DistFiles/xMatter/bloom-xmatter-common.less
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomExe/Book/BookData.cs

Fix BL-1121 by making a number of fields to be copied when empty
The problem appears to be related to fields that are in a language, like credits, but which we really don't want to not show at all if the shell is used for some other language. These kinds of fields can be marked with a special class, bloom-copyFromOtherLanguageIfNecessary. This commit applies that to a few more fields. So far so good. However the original implementation didn't take into account the case of fields that are vernacular, like the front cover credits. I don't feel like I'm in a position to revisit that at the moment, so I made an exception for that one field. See the comments in the code.

Bl 1121 preserve credits across language changes

---

src/BloomExe/Publish/PdfViewer.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs

Added small pauses after minimizing and before restoring to
eliminate errors that were observed after the first fix.  Also
added changes to disable buttons in the publish view until
the print operation is actually complete.

BL-788 Print dialog appears behind Bloom (Linux)

---

src/BloomTests/Edit/ConfiguratorTest.cs

Fixes the one unit test that was a true failure.  The others
are Jenkins only environment failures that work fine when
run on developers systems.  This one runs into problems
because the ToString isn't supported for a type "object" and
clearly states that it doesn't.  It also isn't called in the
code base that way.  This creates the same string another
equivalent way and verifies that the LocalData segment is empty.

BL-831 Unit Test Hangs

---

src/BloomExe/Book/BookData.cs

This fixes BL-1117 the right way, not just patching one known
pattern of using characters reserved for HTML markup.

Fix license description to handle HTML markup characters

---

src/BloomExe/Edit/EditingView.cs

LicenseInfo.GetDescription() for a Custom license just returns the RightsStatement, which led to duplication. Bloom now detects this condition and prevents the duplication.

BL-1179 Keep Custom license RightsStatement from duplicating

---

src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooser.js
src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooser.ts
src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.js
src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts

These kept popping up in VS and were easy to fix (mostly files that got moved).
There are 2 left in synphonyApi.ts, but those are beyond my "easy/safe fix" scope right now.
There are a couple of references that I deleted because once the fixed ones were right, VS said they were already defined. I checked. Other references already referenced them.

Fix some annoying Typescript errors

---

src/BloomExe/CollectionTab/LibraryListView.cs

This uses a previously unused ToolTip object.  AutoEllipsis was
causing truncated tooltips to be shown on Windows, but no tooltips
were displayed on Linux for the book thumbnail buttons.  It doesn't
appear to me that the purpose for AutoEllipsis described in comments
was valid, so I just disabled it with a comment after removing the
previous comments.

Fix book thumbnail tooltips to show full titles (BL-817)

---

debian/control
src/BloomExe/Publish/PdfViewer.cs

This provides the equivalent of the print dialog shown on Windows.
The print system used by Ubuntu Linux (CUPS) handles PDF files
automatically, presumably by using ghostscript as needed.

Fix printing on Linux to use gtklp (BL-1192)

---

src/BloomExe/Workspace/WorkspaceView.cs

Without adjustment, the tab buttons can slide under the tool
panel when choosing a localization whose strings are wider
than the previous strings.

Adjust tool panel location for localizations (BL-1212)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Extensions.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/ServerBase.cs
src/BloomTests/PretendRequestInfo.cs

More characters could be added to the list of escaped characters,
but most of them are rarely if ever used in filenames, and many
of them are not legal for filenames in Windows.  See the JIRA issue
(https://jira.sil.org/browse/BL-951) for a list of ASCII characters
possibly escaped in Urls.

Allow more HTTP interpreted characters in pathnames (BL-951)

---

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js
src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts

Leveled Reader Tool's This Book counts inaccurate when used from
Decodable.  When you create a new page with the decodable reader
tab visible, enter text, and then switch to the leveled reader tab,
the counts are wrong until another word is entered.  This is because
the doMarkup code adds in the current page information, but it
is not added in with the call from updateWholeBookCounts.

BL-1138 Book counts inaccurate after switch from DR

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

The user will need to click in the box to start typing in a newly loaded page if Reader Tools are active.

BL-1139 Hack to solve quick typing problem in Reader Tools

---

src/BloomExe/Book/Page.cs
src/BloomExe/Edit/WebThumbNailList.cs

User should not re-order pages when translating a book

BL-569, prevent re-ordering in locked-down books

---

src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs

Absolute Linux paths start with '/' which means we need to strip
'file://' instead of 'file:///'.

Fix creation of PDF files on Linux

---

src/BloomExe/Book/TranslationGroupManager.cs
src/BloomTests/Book/TranslationGroupManagerTests.cs
src/BloomTests/XmlHtmlConverterTests.cs

Original code was converting underlined text in prototype
to empty <u> elements which somehow (still not sure) became
<u /> in HTML which messed things up badly.

BL-1222, don't make empty <u> elements for new langs

---

DistFiles/ReleaseNotes.md
src/BloomBrowserUI/bookEdit/bloomField/bloomField.js
src/BloomBrowserUI/bookEdit/bloomField/bloomField.ts
src/BloomExe/Browser.cs

CTRL+Click does a paste, and the pasted material is cleaned up, removing the extraneous line breaks that you get when copying out of a PDF.

Make ctrl+click do a paste that cleans up linebreaks from pdf

---

DistFiles/UnusedTemplates/Template Maker/Factory-XMatter.css
DistFiles/xMatter/BigBook-XMatter/editMode.css
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/bloom-xmatter-common.css
DistFiles/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/bookEdit/css/editPaneGlobal.css
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs

The problem was that we have stylesheets looking for this attribute to decide which language it was supposed to show, but the attribute wasn't being set when we make a PDF.
1) Changee "editMode" to "bookcreationtype" (which no more descriptive, but at least it is differentiated from "editMode.css", which is has nothing to do with this attribute).
2) Set this attribute when getting the preview/pdf html, instead of just the html for editing.

Fix BL-1226: Credits lost in PDF

---

src/BloomExe/XmlHtmlConverter.cs
src/BloomTests/XmlHtmlConverterTests.cs

We already had code that did this on read, but not on write. So the "active ingredient" in this fix is simply to factor out the bit of workaround code we were using during reading so that it can be re-used during writing.
To facilitate the processing of the content, I switched the xmlwriter to work in-memory.
I could have refactored this even further, but it's at the very core of things and I'm just trying to get a priority fix out for Uganda.

Fix BL-1242, when book is saved, span.bloom-linebreak gets removed

---

src/BloomExe/Workspace/WorkspaceView.Designer.cs
src/BloomExe/Workspace/WorkspaceView.cs

The original button text is preserved in the button tooltip.

Limit tab button widths by truncating text (BL-1212)

---

src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs

Also include stack trace in log message just in case it can be helpful.

Enable message for Dropbox check crash (BL-1246)

---

src/BloomExe/Edit/EditingModel.cs

This may help determine whether we have memory leaks, and whether
memory use is contributing to crashes that get reported.

Make memory check a major logging event when changing pages

---

src/BloomExe/Program.cs

Usually --squirrel launches terminate early, but
in at least one case finding exactly one such argument
got treated as a download order.

BL-1143 don't treat --squirrel launch as download attempt

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs

Creating a PDF file through gecko/xul on Windows requires at least
one printer and a default printer being assigned.  The wording of the
messages could certainly be improved, but that has to be done by
someone other than this particular programmer.
I  also fixed the existing message to be localizable.

Provide a better message when no printers exist (BL-1237)

---

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.js
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts

Fields with display:inline never have a width (much to my consternation), so were always red.

Don't bother trying to figure out if an element marked display:inline is overflowing itself

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

- If we can't delete destination directory or move otherwise
fails, try copy.
- If we can't copy a particular file, see if it already exists with
the right content, and if so count this as success
- If we really can't make the destination directory correct,
copy all we can, and give a helpful message

BL-1205, improve handling of locked files on download

---

src/SquirrelInstaller/Bloom.nuspec

I omitted AWSSDK because it is by far the biggest and not our code
so I think we are unlikely to care about line numbers in it.

Install PDBs

---

build/package.json
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.js
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts

Bloom 3.1 beta 2.
On pages with many editable controls, the overflow checking causes the program to freeze. This is especially true in the word search page of a story primer which has almost 500 editable controls.

BL-1260: disable overflow checks on some pages

---

src/BloomExe/Browser.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Workspace/WorkspaceView.cs

The memory leak is in the area of choosing images.  The browser
optimization may not do much, but I figure every little bit helps.
The additional checking gives a bit more information about where
memory is being consumed, and may catch growing memory a bit sooner.

Fix memory leak, try browser optimization, and more checks (BL-1234)

---

src/BloomBrowserUI/bookEdit/bloomField/bloomField.js
src/BloomBrowserUI/bookEdit/bloomField/bloomField.ts

Since embedded images come before the first editable text, going to the beginning of the field and pressing Backspace was moving the current paragraph into the caption of the image. Sigh.
As @JohnThomson pointed out, there are some situations where this will prevent backspacing even when it is safe, for example at the edge of a bold element that is in the first paragraph. This proved expensive to prevent, so since this whole scenario is already quite a niche thing (field with embedded image) we're going to just live with that for now.

Fix BL1259 Can Backspace a paragraph into a caption

---

src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs

As written, the code prevented PDF generation from ever working on
Linux.

Fix check for missing GeckofxHtmlToPdf.exe for Linux (BL-1249)

---

src/BloomTests/Book/BookDataTests.cs

* added a test "SkipOnTeamCity" that will fail if no font
* made existing failing test pass quietly if no font

BL-1257 Fix tests so Andika New Basic isn't required

---

src/BloomExe/ProjectContext.cs

Project Context should be creating just one BloomFileLocator,
but the OptimizedFileLocator property was creating a new one,
not properly initialized, instead of returning it.

BL-2155, 2159 etc: use correct file locator

---

debian/control

If we want to include Linux in beta1, this may need to be part of it.

Remove unneeded build dependency that can cause packaging failure

---

DistFiles/factoryCollections/Templates/Picture Dictionary/meta.json

The missing comma was causing an immediate crash trying to run
Bloom on wasta-12.  I would think other systems would be affected
as well.

Add a missing comma in a meta.json file

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/web/EnhancedImageServer.cs

We recently switched from file-path to URL-based PDF creation. That worked fine for most books, because for those images are just a file name. However for folios, where many books are combined, we need a relative path to the folder where the image resides. So now when a folio is being assembled for running through the PDF engine, an img src attribute might be changed from "lion.png" to "../animals/lion.jpg", which then gets url encoded.

In folios, rewrite the img src attrs so that the image is found

---

src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs

There were 2 problems:
1. The image server would not serve svg files.
2. The basePage.css file was refering to Attention.svg on a relative path that is no longer valid.

Fix serving of Attention.svg file

---

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.js
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookPreview/js/bloomPreview.js

* removed workaround for wkhtmltopdf for centerVertically
* make cog stay in frame on centerVertically when moving
in and out of overflow state and cutting and pasting

Bl 2165 just text cog

---

src/BloomExe/WebLibraryIntegration/BookTransfer.cs
src/BloomTests/WebLibraryIntegration/BookTransferTests.cs

It was a bad idea to URLEncode the book name in the downloadOrder.
But, turns out it was also a bad idea to actually download
the book order: the url we need is already part of the book order.
So just use it.

BL-1239, don't depend on decoding filename for downloadUrl

---

DistFiles/factoryCollections/Sample Shells/Vaccinations/previewMode.css
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.jade
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomBrowserUI/bookPreview/css/previewMode.css
src/BloomBrowserUI/bookPreview/css/previewMode.less

We were ignoring countPageButDoNotShowNumber class.
This class was on one of the pages in in the Traditional xmatter, so that the first page was then page 2. This PR adds it to the factory xmatter too.
The jade xmatter mixins were improved to carry classes like this through to the html.

Fix BL-2187

---

src/BloomExe/MiscUI/ProblemReporterDialog.cs

Unfortunately, Linux/Mono cannot use YouTrackSharp.dll to talk to the
YouTrack server.  YouTrackSharp depends on .Net assemblies that are very Windows
specific, and not implemented at all for Mono.

Prevent YouTrack code from crashing on Linux/Mono

---

src/BloomExe/Collection/BookCollection.cs

Sometimes when a downloaded book had triggered GetBookInfos() (which builds the collection _bookInfos), the file system watcher would discover a file had been added (the downloaded book) and trigger the watcher code which started off by setting _bookInfos = null. Solved the thread crashing by disabling the watcher while in GetBookInfos() and verified that the Watcher does get called again after.
The "sometimes" above, seems to be when the download process coughs up a non-fatal Bloom Problem dialog...

BL-2174 and BL-2173 File Watcher problem

---

src/BloomExe/Book/Book.cs

A couple of 'return's were used where 'continue' should have
been to allow necessary cleanup to happen after a loop.

BL-2204 UpdateBook should not change its orientation

---

src/BloomTests/ProblemReporterDialogTests.cs

This doesn't begin to work since we changed over to YouTrack.

Disable CanSubmitToSILJiraAutomatedTestProject test on Linux

---

src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomTests/ImageProcessing/ImageUtilsTests.cs
src/BloomTests/ImageProcessing/RuntimeImageProcessingTests.cs
src/BloomTests/PageEditingModelTests.cs

Also catch exception thrown while updating books and report it to the
user, with a suggestion to restart the program.  Such exceptions are
usually due to running out of memory somehow, probably by fragmenting
the C level heap and then trying to load a very large image.

Replace Image.FromFile with method that doesn't lock (BL-2214)

---

src/BloomTests/ImageProcessing/ImageUtilsTests.cs
src/BloomTests/PageEditingModelTests.cs

This reverts some changes made earlier today.  It turns out that copying
a Bitmap doesn't preserve all of the characteristics of the original
Bitmap.

Fix failing unit tests to use Image.FromFile again

---

src/BloomExe/web/ServerBase.cs

This looks like it's a similar problem to the one on Windows with
spurious HttpListenerExceptions that were already being caught.

Prevent crash from premature socket shutdown on Linux (BL-2225)

---

src/BloomExe/web/CommandAvailabilityPublisher.cs

The report indicates a failure to set up the web socket we
use to publish command availability to the embedded browser.
Probably because of another instance running.

BL-2205 Improve error reporting when cannot set up socket

---

src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs

If the MRU list has fewer than three items, fill in with any other
most-recently-modified collections in the standard location.
This is especially helpful when the MRU list is lost between
Bloom 3.0 and 3.1.
(Can anyone think of a reasonable way to unit test this?)

BL-2238 Append recent mods to MRU list

---

src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs

Problem was that bloom was giving geckofxhtmltopdf a command line that it couldn't make sense of, e.g. "-R0 -T0 -B0 -L0" instead of "-R 0 -T 0 -B 0 -L 0", so it was using defaults, which are 10mm all around.

Fix 10mm extra margin in PDF

---

src/BloomExe/Publish/PdfViewer.cs
src/BloomExe/Publish/PublishView.cs

Without the fix, the sample settings disappear on Linux as soon as
the print dialog appears, which is somewhat self defeating.

Fix sample print settings display for Linux (BL-2213)

---

src/BloomTests/BloomTests.csproj
src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs

* pull actual upload/download into a class that does it
once for the fixture and then tests various results

[Debt] Make BloomS3Tests more efficient

---

src/BloomExe/CollectionTab/LibraryListView.cs

Setting AutoEllipsis to true is not needed, and causes its own tooltip
if the text takes more than one line to display.

Prevent double tooltip in collection tab (BL-2257)

---

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.css
DistFiles/factoryCollections/Templates/Basic Book/Basic Book.less

The switch from plain .css to .less lost the SplitAcrossPages layout.
Conceivably the users will eventually request that the text side of "SplitAcrossPages" should be centered vertically... That will not be easy, especially in the case of Image in Middle where there are two .bloom-translationGroups to center as a group.

BL-2258 Put Split Across Pages back in Basic Book css

---

build/getDependencies-windows.sh

* only windows version is affected,
the Linux version already doesn't reference the font
* The new Andika New Basic font is in DistFiles

Remove Andika download from getDependencies

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookEdit/js/calledByCSharp.js
src/BloomBrowserUI/bookEdit/js/calledByCSharp.ts
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/PageSelection.cs

Moves the responsibility for saving the page into a new
SelectionChanging event handler, so it all clearly
happens before we change the current page.

BL-2221 Save origami before leaving page

---

src/BloomExe/Book/RuntimeInformationInjector.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Book/RuntimeInformationInjectorTests.cs

Anywhere JS is looking for a (localized) language name
it should now find it.
If it's not a major language it won't be localized, but it will be
a name rather than just an ISO code, assuming it's a language
libpalaso knows about.

BL-1195 Show names for all languages

---

src/BloomBrowserUI/bookEdit/bloomField/bloomField.js
src/BloomBrowserUI/bookEdit/bloomField/bloomField.ts

This extends an existing Mozilla bug workaround for an empty field
to handle deleting everything in a field.  Something was already being
done for paragraph fields, but not for simple text fields.

Keep cursor position sane when deleting all text (BL-2274)

---

src/BloomExe/Browser.cs

* First Alt-F4 doesn't seem to work and the 2nd one crashed.
* Fixed the crash

BL-2313 Crash exiting Bloom while changing folder name

---

build/getDependencies-Linux.sh

Modify the download script to use "wget --no-cache" if wget exists.

Fix caching problem for dependency downloads (BL-2301)

---

src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs

* case of extension was wrong (s/b bloomCollection)
* the change to control.Tag near the end of the method
avoids a "Possible unintended reference comparison"
compiler message

BL-2316 Fix MRU List

---

DistFiles/factoryCollections/Templates/Wall Calendar/wallCalendar.css
DistFiles/factoryCollections/Templates/Wall Calendar/wallCalendar.less
DistFiles/less/common-mixins.less
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less

* only applies to: a)  A4Landscape (on A3 paper)
and b) A5Landscape (on A4 paper)
* the latter only being found (so far) in Wall Calendar,
the calendar bottom page needed an extra tweak.

BL-2310 Make equal left/right margins for calendar fold

---

build/Bloom.proj

Some commands we were passing to Update.exe
were unexpected, presumably obsolete. One arg had
an unexpected space.

Remove obsolete commands to installer builder

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

Testing found that Thumbs.db would be uploaded.
Technically they would be different files on Linux,
but I think it's reasonable to exclude
them all on all platforms.

BL-2246, don't upload any variant of thumbs.db

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/RuntimeInformationInjector.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/ToPalaso/LookupIsoCodeModelExtensions.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/ToPalaso/LookupIsoCodeModelExtensionsTests.cs

Enhances the algorithm for finding default language
names to handle macro languages and possibly other cases
for which the palaso model can find matches but
does not consider it has an 'exact' match.

BL-2334 Find names for some more languages

---

DistFiles/factoryCollections/Templates/Wall Calendar/configure.js
DistFiles/factoryCollections/Templates/Wall Calendar/configure.ts

The problem was that Configurator.ConfigureBookInternal() is calling the javascript function runUpdate() and passing and object, but the javascript was expecting a string. I updated the javascript to expect an object.

BL-2344: Fix bug in calendar configurator

---

src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/PublishModel.cs

The fix here is to have the pdf publisher indicate that it is planning to do a calendar fold. Then the stylesheet keeps the margins left if that class is present.

Fix BL-2348

---

src/BloomExe/web/EnhancedImageServer.cs

I encountered this while trying to chase down BL-2346.  It fixed a problem of two .js files not being found, but didn't fix that particular bug unfortunately.  It parallels a fix made earlier in the following method for .css files.

Remove leading "OriginalImages/" when looking for an actual file

---

DistFiles/factoryCollections/Templates/Wall Calendar/wallCalendar.css
DistFiles/factoryCollections/Templates/Wall Calendar/wallCalendar.less
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less

It remains distressing that we don't know why the PDF looks different than the html/css used to make the PDF. It was also hard to fix because the latest FF looks different than the FF in Bloom
On Windows, both the Bloom 3.1 FF, Bloom 3.1 PDF, the latest FF, and IE11 are happy with the current implementation (Chrome makes it too tall).

Fixes BL-2349, where six-row months didn't fit in the PDF

---

src/BloomExe/Publish/PublishView.Designer.cs

The tooltip claims we use chrome to produce PDFs, but we use Firefox.

Remove obsolete tooltip

---

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/bloom-xmatter-common.css
DistFiles/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less

* Fix BL-1022 in basePage.less was overridden by xmatter css
which have wider relative marginBox margins
* also changed capitalization on @import to match actual
DistFiles folder name (in case we build less->css on linux
someday)
* NB: all 'real' changes are to .less files

BL-2353 Fix image width on xmatter to use full width

---

src/BloomBrowserUI/BloomBrowserUI.csproj
src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js
src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts
src/BloomBrowserUI/bookEdit/js/collectionSettings.d.ts
src/BloomBrowserUI/bookEdit/test/cSharpDependencyInjector.js
src/BloomBrowserUI/bookEdit/test/cSharpDependencyInjector.ts
src/BloomBrowserUI/karma.conf.js
src/BloomBrowserUI/test/specs/SourceBubblesSpec.js
src/BloomBrowserUI/test/specs/SourceBubblesSpec.ts
src/BloomExe/Book/RuntimeInformationInjector.cs

* puts LastViewedSource language first in the list of tabs (if there's translatable material for that language)
* puts the 2nd and 3rd language (from Settings dialog) in 2nd and 3rd position (with above caveat)
* due to the first change, we no longer need to specify which tab is selected or scroll to the selected tab, since the default first tab is always what we want selected.

BL-2357 smart order lgs (v3.3?)

---

src/BloomBrowserUI/bookEdit/js/readerSettings.js
src/BloomBrowserUI/bookEdit/js/readerSettings.ts
src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.htm
src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.jade
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.css
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.js
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.ts
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts

"Bloom 3.0 used word lists as a corpus that it could search through in order to find words that were decodable according to a set of letters. If the user needs the new kind of per-stage authoritative word list, then this feature becomes very confusing. So the first change we will make is to introduce this set of two choices..."
I added the file readerSetup.less also.

Change 1: Let user choose their approach

---

src/BloomBrowserUI/bookEdit/css/editMode.css
src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js
src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts

* Changes long language names to use ellipsis
* Third (last) tab now shows (x), where x is the number of languages in the dropdown
that pops up when you click it.
I decided that the best way to do the rest of this issue involved quite a number of changes, including changing the underlying html and how the dropdown functions. Those changes will be Part 2.

BL-2390 Part 1 of Source Bubble changes

---

src/BloomExe/BloomExe.csproj
src/BloomExe/MiscUI/ProblemReporterDialog.Designer.cs

YouTrackSharp depends on EasyHttp.dll. The compiler
should realize this and 'copy local' both of them, but
doesn't, possibly because EasyHttp.dll is not at the
expected relative location. Adding a direct reference
makes the DLL available when needed.
The other change tweaks control sizes and positions
so the status messages can be fully read.

BL-2399 Repair 'Report a Problem'

---

src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.htm
src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.jade
src/BloomBrowserUI/bookEdit/accordion/LeveledRT/LeveledRT.htm
src/BloomBrowserUI/bookEdit/accordion/LeveledRT/LeveledRT.jade
src/BloomBrowserUI/bookEdit/js/readerTools.js
src/BloomBrowserUI/bookEdit/js/readerTools.ts

The word lists files were being loaded twice if both Decodable and Leveled reader tools were enabled.

Stop loading synphony twice if both Decodable and Leveled enabled

---

src/BloomExe/Book/Book.cs

The fix for selecting a page at startup has
generated crashes when there are no pages.
I don't know how it's possible to get a book
into such a state, since we don't allow deleting
XMatter.

BL-2339 handle case of no pages

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/css/bloomDialog.css
src/BloomBrowserUI/bookEdit/css/bloomDialog.less

* dialog covers source bubbles, not vice versa
* dragging cursor has to move 10 pixels to activate
* dragging is limited to space available in iframe so dragging
the dialog to the side doesn't cause scrolling

BL-2411 Improve FormatDialog dragging

---

src/BloomExe/CollectionTab/LibraryBookView.cs

This addresses BL-2472 "Change Credits Page default license to CC-BY".
The default license is already CC-BY if no information is available.
But the exemplar is set to the most recent license entered if any images
have had a license modified by the user at any time in the past, and that
is used for the next image chosen by the user in any program that uses
the palaso image chooser dialog.

Reset the default image license when creating a new book

---

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js
src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts

This is needed to update that label when the user deletes all of
decodable stage when using word list files to define stages.

Update "Stage X of Y" after reloading wordlists (BL-2464)

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This changes the previous fix from hiding the formatting button to
changing its behavior.

Disable formatting dialog for Reader Templates from Bloompacks (BL-2476)

---

src/BloomExe/Workspace/WorkspaceView.cs

(Linux?) virtual machines may still show menus off the edge, but tests
with xephyr and a real display set to 1024x768 show proper behavior.

Fix remaining glitches in netbook toolbar display (BL-2366)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/Program.cs
src/BloomExe/WebLibraryIntegration/BookTransfer.cs
src/BloomExe/packages.config
src/BloomExe/web/ServerBase.cs

See Palaso/Reporting/ErrorReport.cs for the list of properties.  The machine name and user name
properties are removed to reduce sensitivity concerns.

Add program/system information to analytics exception reports (BL-2418)

---

src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs

This is in addition to the previous error handling, which handled the case where there was no default printer at all.
This is to merged into 3.2

Fix BL-2535, give helpful error if error accessing default printer

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

I think this also fixes BL-2515 and BL-2516, and a minor glitch in sometimes not bringing up the format bar when it should.

Fix bad initial location of ckeditor format bar (BL-2514)

---

src/BloomExe/MiscUI/BloomIntegrityDialog.Designer.cs
src/BloomExe/MiscUI/BloomIntegrityDialog.cs
src/BloomExe/Program.cs

The content of the report was so full of file listings that the edit box wouldn't let the user type in it. I changed it so that
1) it doesn't repeat the root directory for every listing
2) it has a list of directories that it should not go down into
Was 126k characters on my machine, now is 15k.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/662)

Fix BL-2575 by drastically reducing the amount of dir listing text

---

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js
src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts

The solution isn't perfect, but the best we can do without modifying
libsynphony to be much more complicated in dealing with capitalized
words.

Handle capitalized sight words in decodable readers (BL-2550)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

This adds the proper behavior for single language books where the
national language differs from the book's language.

Enable ckeditor in National language text boxes (BL-2515)

---

src/BloomTests/XmlHtmlConverterTests.cs

Also add new test to verify desired result of adding that setting.

Fix tests that fail due to XmlDocument.PreserveWhitespace

---

src/BloomBrowserUI/bookEdit/js/editViewFrame.js
src/BloomBrowserUI/pageChooser/js/page-chooser.js
src/BloomBrowserUI/pageChooser/js/page-chooser.ts
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs

Rather than relying on the modalstate flag, we now always ask javascript to open the dialog. But from there, we check for the existence of any jquery dialog and don't open if we find one.
Also moved  a couple things out of the model that belong in the view.

Fix BL-2561 AddPageDialog was sometimes not opening

---

src/BloomExe/ImageProcessing/ImageUtils.cs

This change aggravates the problem of unused files being left in the book folder, and creates a new problem of duplicating a picture file every time it is used in a book (if it is used more than once).  But it does fix what appears to be the cause of the reported bug.

Fix problem with image files overwriting each other (BL-2627)

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/UpdateVersionTable.cs
src/BloomTests/UpdateVersionTableTests.cs

IsConnectivityError was failing because of an && || precedence problem. Adding parentheses fixed it.

BL-2654 Fix IsConnectivityError

---

src/BloomBrowserUI/bookEdit/js/editViewFrame.js
src/BloomBrowserUI/pageChooser/js/page-chooser.js
src/BloomBrowserUI/pageChooser/js/page-chooser.ts
src/BloomBrowserUI/pageChooser/page-chooser-main.htm
src/BloomBrowserUI/pageChooser/page-chooser-main.jade
src/BloomBrowserUI/pageChooser/page-chooser.css
src/BloomBrowserUI/pageChooser/page-chooser.less
src/BloomExe/Book/Book.cs
src/BloomExe/Browser.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/ServerBase.cs

The template folder may now contain a Caption.png file,
which will be used if Caption.svg is not found. If neither is
found, the system will generate a thumbnail on the fly.
Achieving this involved some tricky changes to our fileserver
so requests for multiple thumbnails don't lock out the server
requests needed to generate a thumbnail.

BL-2629 Generate thumbnails for Add Page dialog

---

DistFiles/less/common-mixins.less
src/BloomBrowserUI/bookLayout/basePage.css
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomExe/Book/SizeAndOrientation.cs

In this commit, I added knowledge of the various American page dimensions to the stylesheets. In SizeAndOrientation, I fixed the case-handling so that we see "HalfLetter" instead of "Halfletter". 
Meanwhile Steve has enabled GeckofxHtmlToPDF to handle "halfletter" and "quaterletter" among other American sizs.
So, next we would need to make "HalfLetter" be an option in various templates (e.g. basicBook.less).  And then do all the same for quarterletter.

Stage 1 of BL-2677, Add HalfLetter to size choices

---

debian/bloom
debian/changelog
debian/control
debian/copyright
debian/install
debian/rules

Linux/debian packages on the master branch should be named with an
unstable suffix.  (debian files should never be merged across branches!)

Reverse package name changes accidently merged to master

---

DistFiles/localization/Bloom.en.tmx
src/BloomExe/Book/Book.cs
src/BloomExe/Collection/BookCollection.cs
src/BloomExe/CollectionCreating/CollectionNameControl.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/ProjectContext.cs

Eliminates context menu for books distributed with Bloom. Allows deletion of books downloaded from BloomLibrary.org. Limits context menu in ways set out in BL-2678.
Also disallows using 'templates' or some case variant as a new collection name.

BL-2678 restrict book cmds

---

src/BloomExe/CollectionChoosing/MostRecentPathsList.cs
src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
src/BloomExe/Program.cs

Try 2: identifies more invalid collections and
prevents more ways of opening them. Hopefully
all of them now!

BL-2626 Prevent opening invalid collection

---

debian/changelog
debian/rules

This is in preparation for building new beta packages for Linux from the Version3.3 branch.

Update the debian package version to 3.3.4 on Version3.3 branch

---

src/BloomExe/Book/BookData.cs

This reverts commit 5e18e058fdc4474714d8da2639024789974b2332 to get tests passing again.

Revert "BL-2425 Enable text in BackCover to be deleteable"

---

src/BloomTests/ImageProcessing/ImageServerTests.cs

I also did by-hand testing. I think we must have fixed this after 3.1 which is the version where we go the error report.

Added a unit test for this, which already passes.

---

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomBrowserUI/BloomBrowserUI.csproj
src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.js
src/BloomBrowserUI/bookEdit/sourceBubbles/bloomSourceBubbles.ts
src/BloomBrowserUI/test/specs/SourceBubblesSpec.js
src/BloomBrowserUI/test/specs/SourceBubblesSpec.ts
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Book/TranslationGroupManager.cs
src/BloomTests/Book/BookStarterTests.cs
src/BloomTests/Book/TranslationGroupManagerTests.cs

Previously, xmatter fields only received those data-book values that were in languages that the project actively uses. That meant that other languages were not there in the bloom-translationGroups, and therefore the source bubbles had nothing to show.
With this change, we make placeholders for all langs, then the get filled by pre-existing code.
This is currently limited to "bookTitle" so as to limit side affects elsewhere. We can broaden it in the future if needed.

Fix bl-120 by making XMatter receive title data-book elms for all langs

---

src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/PageListView.cs

The js needed a chance to run and bring up the dialog window
before we allowed another click to happen. Once the dialog window
is up, the js will catch another attempt to open the dialog while the
first one is up and ignore it.
The important stuff is in PageListView. EditingModel changes are (auto?) refactoring only.

v3.3 BL-2743 Fix AddPage dialog double-click problem

---

src/BloomExe/Book/BookData.cs

Two questions:
1) Is there a better way to strip off the paragraph markers?
2) In BookData.SynchronizeDataItemsFromContentsOfElement() the first line creates a DataSet by GatherDataItemsFromCollectionSettings(), but this has already been done and there's a perfectly good (already migrated) BookData._dataSet member variable set up in the ctor of DataSet. Anybody know why we recreate the DataSet here?

v3.3 BL-2746 migrate topics that had paragraph markers

---

src/BloomExe/Book/BookData.cs
src/BloomTests/Book/BookDataTests.cs

These came in during the beta period, because we didn't realize that ckeditor was being applied to the topic. That problem was fixed earlier, this just cleans up the p elements it introduced. We had a previous commit accepted for this, but it did way more than a constructor should be doing and luckily triggered a bunch of unit tests to fail.

Bl2746 Remove paragraph markers from topics

---

debian/changelog

Len requested using numbers in the 400 range for the third version
number to help differentiate beta from release.

Update Linux package version to 3.3.400

---

DistFiles/localization/Bloom.en.tmx
DistFiles/localization/Bloom.fr.tmx
src/BloomBrowserUI/bookEdit/js/editViewFrame.js
src/BloomBrowserUI/pageChooser/js/page-chooser.js
src/BloomBrowserUI/pageChooser/js/page-chooser.ts

* moved 2 AddPageDialog entries under EditTab
* added French localization for all 3 entries
I hope we don't have to leave the old entries in and say no longer used when we're moving them to a new place in the tree structure...
[Later: actually I see there's a commit from JT that did all this and also accounts for the missing BL-2700 fix that JH just put back. It's 81ce85be133c7 on 1 Sept; but that's on master]

v3.3 Added 3 entries to AddPageDialog localization

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/MiscUI/BloomIntegrityDialog.cs
src/BloomTests/Book/HtmlDomTests.cs
src/BloomTests/Book/PageMigrationTests.cs

Fix BL-2782 Migration to custom pages was dropping the size & layout
I added a couple tests for this and a related future problem, which is that of dropping other classes that are on the page. now, it merges the two classes, but drops the now irrelevant classes like "imageOnTop".

Bl2782 migration dropping size and orientation

---

src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js
src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts

The text box value that correctly marks a field as having no value is '-', not '' in reader setup.

BL-2496 Fix LR rules to stay unselected

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

This should fix some failing tests.  It appears that MonoDevelop doesn't run the failing tests since they don't fail on my build machine, but do fail on the Linux build on TeamCity (as well as the Windows build).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/778)

Check for null ProgressDialog object (fix related to BL-2312)

---

src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs

The program specification changed, which changes how the test itself
should behave.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/782)

Fix a failing test related to BL-2312

---

src/BloomExe/Shell.cs
src/BloomExe/web/EnhancedImageServer.cs

Users would probably never see this particular source of crashes, but
developers certainly can!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/786)

Prevent a SIGSEGV crash on Linux debug builds

---

debian/bloom
debian/changelog
debian/control
debian/copyright
debian/install
debian/rules

Also undo a merge from Version3.4 that renamed the package to
bloom-desktop-beta instead of bloom-desktop-unstable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/785)

Update the version number on the master branch to 3.5

---

src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs

Fix BL-2809 by not allowing booklet option when you choose letter
Limiting this actually helps shape the user's mental model towards how this really works; if they think "I'm going to print a booklet with my letter paper", then really we need them to choose "half letter" anyhow. Unlike with metric sizes which can be easily doubled/halved, double of "letter size" is... unusual. We can always enable this if there is demand for it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/787)

Fix BL-2809 by not allowing booklet option when you choose letter

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/PageEditingModel.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomTests/Book/HtmlDomTests.cs
src/BloomTests/ImageProcessing/ImageUtilsTests.cs

Fix BL-2789, where Tok Pisin and Indonesian would show up in the source bubble for book titles, saying the equivalent of "new book" in each language. BasicBook doesn't have that anymore, but this cleans it up in books made from old shells.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/784)

Fix BL-2789 removing generic names from source bubble for book titles

---

src/BloomExe/Program.cs

For the links to work properly in ProblemReporterDialog we have to
use GeckoFx. This change sets the default browser type for Palaso's
XWebBrowser class so that the links in ProblemReporterDialog open
in an external browser window.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/815)

Fix links in ProblemReporterDialog

---

src/BloomExe/Book/BookStorage.cs
src/BloomTests/Book/BookStorageTests.cs

Previously I didn't expect the cleanup to run at the point where the book didn't yet have its xmatter applied. But I was wrong, and so this fix now also protects from deletion any filename that is mentioned in the datadiv, which is there even when the xmatter is not yet applied and thus not yet referencing the cover image.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/820)

Fix BL-2877 Losing cover page image

---

src/BloomExe/Publish/EpubMaker.cs

It's not clear why the code was previously changing spaces to underscores, but it appeared to be done in the saving of the file, but not in the html, at least in the case reported in BL-2847, which was a cover page and so may have something special going on. As a potential fix for JT to review, I've just removed that conversion as I can't see a reason to do it, it could potentially give us the wrong image (if 2 images differed only by this distinction), and it seems to work fine without it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/813)

Fix BL-2847 epub does not show images that have spaces

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/LibraryBookView.Designer.cs
src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/MiscUI/BloomIntegrityDialog.cs
src/BloomExe/MiscUI/ProblemReporterDialog.cs
src/BloomExe/XmlHtmlConverter.cs
src/BloomTests/ProblemReporterDialogTests.cs

Ended up overhauling a good chunk of the error reporting stuff so that we don't get a bunch of dialogs, just the preview page, which now sports a button the user can click to send us the problem book via the Report A Problem dialog.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/816)

Fix-bl2826 Give helpful message when Bloom is locked out of user files

---

src/BloomTests/Publish/ExportEpubTests.cs

We know that Linux needs more work in this part of the code.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/824)

Ignore tests in the epub area that are failing on Linux

---

src/BloomExe/Edit/EditingView.cs

Basically a refactoring of all the places where we have xCommand.Execute() to wrap them in a try-catch to give a nice Palaso error report.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/830)

BL-2723 Catch toolbar command errors and give nice error message

---

src/BloomExe/SplashScreen.Designer.cs

This was accomplished by removing an unused label.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/839)

Remove an annoying line from the splash screen on Linux

---

build/getDependencies-Linux.sh
build/getDependencies-windows.sh

This is needed for Linux package builds on Jenkins.  (The proper changes
have gone through the BuildUpdate repository pull request process.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/845)

Fix getDependency scripts for broken wget with queries

---

src/BloomExe/BloomExe.csproj
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/ToPalaso/SafeInvoke.cs

This is a timing thing that we can't reproduce, so this is speculative.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/844)

Fix BL-2918 (probably) by skipping refresh if the control isn't ready

---

src/BloomExe/MiscUI/BloomIntegrityDialog.cs

Apparently, Linux/Mono allows even less text in a multiline TextBox than
Windows/.Net, or else its directories have longer names.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/849)

Allow user to type in Integrity Check error report (BL-2895)

---

src/BloomExe/Shell.cs

With the switch to squirrel/nuget, all the file dates are the installed/updated date, not the build date. The one file that has the correct date stamp is the .nupkg, but that would take some work to get at... there may be easier ways to pass this info, e.g. writing out a text file the contains the date during build. In any case, when we revisit this, let's only do it for alpha a beta. It looks odd to have that in release builds, and doesn't add much since there are few of them.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/851)

BL-2852 don't add date to window title, since we don't know it now

---

src/BloomExe/Workspace/WorkspaceView.cs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/852)

Fix BL-2710 Toolbar goes to small mode after minimizing

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.js

Originally, this code had ```find().off()```. This ran ```Window.find()``` which... wait for it.... shows a find dialog box.  We just commented that out. Now I've gone back and corrected it to call the jquery find() that was intended.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/855)

Fix bl-2931 by adding correct $.find().

---

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.htm
src/BloomBrowserUI/bookEdit/js/origami.js

Note that the change to Basic book, though it looks messy in github, really just removes one layer of div around its entire content. Apart from indent changes, only two lines are deleted. Try in reviewable.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/856)

BL-2854 Remove improper split-pane-component-inner layer

---

src/BloomExe/Program.cs
src/BloomExe/Properties/AssemblyInfo.cs

Also fixed AssemblyInformationalVersion to be the same as
AssemblyVersion and AssemblyFileVersion.  This allowed the bug to
happen on developer machines as well as user machines.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/857)

Find Palaso named strings in proper SIL namespace (BL-2923)

---

src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs

1k x 1k is suitable for screens. It will not effect what we get in the PDF. Oddly, on the 6k x 6k "Opposites" book, it actually looks better than the original.
Also, changed the retry code to only wait a short while before giving up. The old code would wait 5 seconds. 5 seconds * 20 pages == "Bloom is dead".
A good follow-on operation would be to limit this transparency operation to only the cover page. Tricky, because the server has no idea, so we'd need to get a query onto the image path to specify that it is on cover stock.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/862)

Help BL-2871 by limiting the transparency operation to 1000x1000

---

DistFiles/factoryCollections/Sample Shells/Vaccinations/Vaccinations.htm
DistFiles/localization/Bloom.en.tmx
DistFiles/localization/Bloom.es.tmx
DistFiles/localization/Bloom.fr.tmx
DistFiles/xMatter/BigBook-XMatter/BigBook-XMatter.htm
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomBrowserUI/bookEdit/css/editOriginalMode.css
src/BloomBrowserUI/bookEdit/js/bloomEditing.js
src/BloomBrowserUI/bookEdit/js/bloomNotices.ts

While I was at it, I changed "ReadOnlyInEditMode", which meant nothing to me (or suggested edit vs. publish, which is incorrect), to "ReadOnlyInAuthorMode".
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/846)

Fix remnant of BL-2598, can no longer type in read-only fields

---

src/BloomBrowserUI/Readium/bloomEpubPreview.css
src/BloomBrowserUI/epub/bloomEpubPreview.less

Ideally we should maybe display on the preview page what size (in pixels) we were showing and update it when they resized the phone image.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/869)

BL-2906 Set Epub phone preview to 400X800px

---

src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/Edit/EditingView.cs

This reverts commit ae1e25746f9595a42d62c1ec99f609cd5ba01a7d.
This was actually BL-2871, not BL-2887!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/870)

[v3.4]Revert "Cherry-pick image metadata work to 3.4"

---

DistFiles/factoryCollections/Sample Shells/Vaccinations/Vaccinations.htm
DistFiles/factoryCollections/Templates/Arithmetic/Arithmetic.htm
DistFiles/factoryCollections/Templates/Picture Dictionary/Picture Dictionary.htm
DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm
DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm
DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm
DistFiles/xMatter/bloom-xmatter-mixins.jade
src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooser.js
src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooser.ts
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Book/XMatterHelper.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomTests/Book/BookDataTests.cs
src/BloomTests/Book/BookStarterTests.cs
src/BloomTests/Book/BookTests.cs

The new algorithm for choosing the language of the topic is Vernacular > National Lang 1 > National Lang 2 > English.
This commit simplifies topic handling.
1) only the english key is now stored in the datadiv, ever.
2) only one html element holds the topic on the page. Its @lang and text are determined only by some c#, no more javascript. By moving to a single html element for which code can select the language, we simplify life by not having the static stylesheets try to impose what language will be shown (and then in many cases not know how to translate the topic into that language).
3) The typescript TopicChooser now does not touch the html. React-style, it instead sends up an event which changes the mode (the bloomDataDiv) and then the UI (the html at the bottom of the cover page) …

Fix BL-2921 by choosing which language to use for topics.

---

src/BloomExe/UrlPathString.cs
src/BloomTests/UrlPathStringTests.cs

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/882)

UrlPathString now handles names with non-encoded plus signs

---

src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/PageMigrationTests.cs

Since September, every non-xmatter page was migrated and the data-page attribute was set to 'extra'. When any such book is used then as a shell those pages disappear forever.
This PR stops it from doing that, but we will require a followup commit to heal all the books that have been broken by this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/858)

Fix BL-2887 migration code should not mess with data-page attribute

---

src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/Program.cs

The fix is to filter out *.BloomPack from the compression process. Also added logging.
The request is to merge into 3.5, then we'll hand-merge into 3.6.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/928)

Fix BL-3015 where saving a Bloompack inside its own collection failed

---

DistFiles/localization/Bloom.en.tmx
src/BloomExe/web/I18NHandler.cs

Adds a number of missing strings to English TMX so they
can hopefully get localized.
Fixes a subtle problem where things saved in the HTML page,
like the page type label in the top left, did not switch BACK to
English after being saved in some other locale.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/930)

BL-3017 Fix some localization problems

---

src/BloomExe/Book/UserPrefs.cs

We have several unexplained cases of NULs in userprefs. Looking at the code, if the serialization failed, perhaps it would cause this.
So now we check to see that at least we have a real string. In case the real problem is shutting down while it's being written, we now do a separate safe write and then do a simple "replace" (using a palaso library class) which should be atomic.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/952)

Prevent book.userprefs getting all NULs

---

src/BloomExe/Edit/AudioRecording.cs
src/BloomExe/web/ServerBase.cs

This fix detects that and makes a new backup. I was tempted to try a simpler approach which would be to record to a randomly named temp file, then copy that to our destination only if we are satisfied. The current approach instead always makes this backup that we can revert to. I left it because if we add undo, this will be useful.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/947)

Fix BL-3160  audio backup file occasionally locks stopping recording

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/UserPrefs.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Book/UserPrefsTests.cs

Added unit test for this case and corrupted file case, and fixed both.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/943)

Fix BL-3150 Empty book.userPrefs kill Bloom.

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.jade
src/BloomBrowserUI/bookEdit/toolbox/toolbox.jade
src/BloomBrowserUI/package.json
src/BloomBrowserUI/typings/axios/axios.d.ts
src/BloomExe/web/RequestInfo.cs

On at least my machine, it was never possible to record something and play it back without switching pages. The reason is that at the end of the recording, the javascript would signal the html audio element that the source had changed. That would immediately hit the server up for the new file, but meanwhile the thread writing that file was still working on it. I tried various approaches but the cleanest ended up just telling the audio element not to preload the audio... just get it when the user clicks on "play".
In the process, I added some error handling around getting files, returning appropriate http codes.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/948)

Fix BL-3153 where browser asked for audio file before it was written

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/BookServer.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/ErrorBook.cs
src/BloomExe/BookThumbNailer.cs
src/BloomExe/Collection/BookCollection.cs
src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/Properties/AssemblyInfo.cs

The proximate problem was saving the book, in the constructor when it lacked a color and was too corrupt to be saved. We no longer save during construction. While I was in there, I made newly created books have the same cover color as the preview the user was shown.
Corrupt meta.json used to use a very different code path to talking to the user; changed that so that they get the same UI, with a button to send us the book.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/949)

Fix BL-3115, and a number of small probs when html or json is corrupt

---

src/BloomBrowserUI/bookEdit/js/bloomImages.js
src/BloomBrowserUI/lib/jquery.myimgscale.js

For inline images with captions, we want the image container to grow as much as needed to fit the image and the caption (which can be multiple lines). But prior to this new class, all images were always centered within the image-container. That made it impractical to have an image-container without a fixed height. With this, we can add this class to turn the centering mechanism off.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/960)

Add new bloom-alignImageTopLeft class for inline images

---

src/BloomExe/Book/BookCopyrightAndLicense.cs
src/BloomExe/Book/UserPrefs.cs
src/BloomExe/BookThumbNailer.cs
src/BloomExe/MiscUI/ToastNotifier.cs
src/BloomExe/NonFatalProblem.cs

The NonFatalProblem.Report problem now uses toast for passive notification.
This will catch the error and put up a toast that the user can click if they want to report it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/964)

BL-3227 Be calm if for some reason the license is in use momentarily.

---

src/BloomBrowserUI/bookEdit/js/bloomImages.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/967)

Fix BL-3238 where imageinfo failed if the name had an "&".

---

src/BloomBrowserUI/bookEdit/js/editViewFrame.js

I didn't see a specific problem with the old method of getting the strings, but I switched it to the more direct method, and it seems fine now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/963)

Bl3081 add page title l10n

---

src/BloomExe/UrlPathString.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomTests/UrlPathStringTests.cs

Fix BL-3259 Can't set cover to an image with a '+' or '%' in the name
Turned out to be two separate problems.
The '+' one: This did not have a satisfying solution... in part because the rules for encoding are just too conflicting (or perhaps I'm missing something). Of course + can mean SPACE, and indeed we use it that way when sending url query string to the server. Howver our image urls have + as... +. But when UrlPathString.CreateFromUrlEncodedString decoded that, it got rid of the +, changed it to space.
So I made the code defeat that bit of HttpUtility.UrlDecode(), so that '+'s stay as '+'s. Added more unit tests, did a bunch of by-hand tests, and all seems good.
The '%' one: The solution for this is on the URL-encoding side. All explained in UrlPathString.UrlEncoded.
---
This change …

Bl 3259 filenames with plus or percent

---

src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/MiscUI/ToastNotifier.cs
src/BloomExe/NonFatalProblem.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/980)

Fix BL-3280 thumbnail failures will not send analytics, but show toast

---

src/BloomExe/Edit/PageEditingModel.cs
src/BloomExe/ImageProcessing/ImageUtils.cs

...leading to error when trying to read metadata. Once fixed, I then discovered that it failed to save the metadata if the format changed, so I fixed that too (removing the else ).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/979)

Fix BL-3214 Bloom changes PNG-->JPG without changing extension

---

src/BloomExe/Book/BookCopyrightAndLicense.cs

The templates installed with Bloom are stored in a read-only
location on Linux.  Updating the license image for a template
book seems rather pointless in any case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/982)

Fix Linux crash due to writing license.png (BL-3284)

---

src/BloomExe/Book/BookData.cs
src/BloomExe/UrlPathString.cs
src/BloomTests/UrlPathStringTests.cs

The thing here is that when we re-visit the book and read in the cover image file name, it will be encoded there as HTML; we immediately re-encode as it is the @src attributes, so that it is the same as when we are pulling from the @src.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/986)

Further fix for BL-3235 with ampersands in image name on cover

---

src/BloomExe/Edit/EditingModel.cs

Note: In my experiments, I could not get any loss of information even when this happened. But I Only tried adding text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/987)

BL-3528 Tell user about the need to upgrade in order to avoid BL2634

---

.gitattributes

A git problem earlier today was probably due to a "new" .less file
being considered a binary file on check-in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/997)

Ensure web source files treated as text

---

DistFiles/IntegrityFailureAdvice-en.md
build/Bloom.proj
src/BloomExe/BloomExe.csproj
src/BloomExe/MiscUI/BloomIntegrityDialog.cs
src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs
src/BloomExe/Publish/PublishView.cs

The idea here is just to make it a bit more likely that a user will say "no" when an antivirus asks to quarantine this file, as AVG likes to do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1003)

Fix BL-3304 by renaming geckofxhtmltopdf.exe to BloomPdfMaker.exe

---

Bloom.sln
src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/InstallerSupport.cs
src/BloomExe/Program.cs
src/BloomExe/WebLibraryIntegration/BookDownloadSupport.cs

Depends on branch allUsersForBloom3.6 of Squirrel, so before merging this, we want to get that branch into our fork and make a TC build of it and make 3.6 use artifacts from that build.
When the installer is run with the new --allUsers command
line argument, it will install Bloom in Program Files (x86).
These changes mean that in this situation Bloom will make
all its registry entries in LocalMachine instead of CurrentUser.
Also, in this (typically classroom) situation we assume an admin
is managing updates, and Bloom will not be able to do its own in
Program Files, so we don't attempt automatic updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1008)

BL-3305, handle installation in Program files (for 3.6)

---

build/Bloom.proj
src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/BloomExe.csproj
src/BloomExe/InstallerSupport.cs
src/BloomExe/Program.cs
src/BloomExe/WebLibraryIntegration/BookDownloadSupport.cs

When the installer is run with the new --allUsers command
line argument, it will install Bloom in Program Files (x86).
These changes mean that in this situation Bloom will make
all its registry entries in LocalMachine instead of CurrentUser.
Also, in this (typically classroom) situation we assume an admin
is managing updates, and Bloom will not be able to do its own in
Program Files, so we don't attempt automatic updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1009)

BL-3305, handle installation in Program files

---

src/BloomBrowserUI/bookEdit/editViewFrame.ts

Kinda looks like there was a merger bug here
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1012)

Fix Bl-3319 with mixed up dialog title names for addpagedialog

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/InstallerSupport.cs

A couple of pieces don't compile on Linux, but aren't needed or
wanted there anyway.  We could just omit the two files from
compiling altogether on Linux, but that would require bigger
changes elsewhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1013)

Fix installer/updater code to not compile on Linux

---

src/BloomExe/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1017)

Prevent Bloom trying to install fonts in allUsers mode

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/BloomExe.csproj
src/BloomExe/InstallerSupport.cs
src/BloomExe/packages.config

These more intrusive changes are needed to build packages for Linux.
Linux won't build packages with Squirrel because it can't resolve all
the assemblies it references.  But Squirrel provides MarkdownSharp, so
we have to provide this explicitly for building on Linux with Mono.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1015)

Remove all references to Squirrel on Linux/Mono

---

debian/bloom.desktop.appdata.xml
debian/rules

This is necessary so that Bloom shows up in Gnome Software app
in Xenial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1027)

Add appdata file to debian package

---

debian/rules
src/BloomExe/ProjectContext.cs

Looking for a window-specific folder at run-time and installing
the wrong folder each led to problems running the program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1031)

Fix file/folder problems running Bloom on Linux (BL-3358)

---

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

(probably messed up by a new version of the accordion code)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1033)

BL-3333 Repair setting current tab in accordion

---

debian/control

fonts-sil-andika-new-basic was renamed on xenial.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1037)

Fix Version3.6 for xenial package dependency

---

src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/ReaderSetup.jade
src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.ui.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.jade
src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
src/BloomBrowserUI/ePUB/bloomEpubPreview.jade
src/BloomExe/HelpLauncher.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/web/ApiRequest.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/RequestInfo.cs
src/BloomTests/PretendRequestInfo.cs

Got rid of BloomHelp altogether; you can now lanch help just by setting the href of an anchor to "/bloom/api/help/.... topic".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1039)

Fix BL-3383 making anchors to help work again, now simplified

---

src/BloomExe/InstallerSupport.cs

To avoid timeouts interfering with shortcut creation,
install the Andika font last.
This is meant to be combined with a change to Squirrel which
increases the timeout and prevents Bloom launching
when installed with --allUsers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1041)

BL-3342 install fonts last

---

DistFiles/localization/Bloom.en.tmx
src/BloomExe/NonFatalProblem.cs
src/BloomExe/web/I18NHandler.cs

I added the (known) missing strings to the base Bloom.en.tmx file
and changed the handling of missing strings to work more quietly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1036)

Don't alarm user with missing i18n strings (BL-3374)

---

src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts

Please try NOT to merge this into 3.7! Resizing works properly
there and should NOT be disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1047)

BL-3386, prevent resize of DR setup dialog in 3.6

---

src/BloomExe/Book/BookCopyrightAndLicense.cs
src/BloomExe/NonFatalProblem.cs

A previous fix prevented the toast in this situation if unable to
CHANGE the icon, but (e.g., Arithmetic template) doesn't have
one at all.
Also took out the confusing 'Alpha' added to toasts which
are modal in Alpha builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1050)

BL-3340 No toast if unable to create license in program files

---

src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Edit/AudioRecording.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/WebLibraryIntegration/BookTransfer.cs
src/BloomExe/web/CurrentBookHandler.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/ReadersApi.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/web/EndpointHandlerTests.cs
src/BloomTests/web/EnhancedImageServerTests.cs
src/BloomTests/web/ReadersApiTests.cs

Although the intended improvement here was just a few lines, I found several things that offered themselves for clean up. Somewhat after-the-fact, I split these into separate commits in case that helps with review.
The biggest thing was removing the dependency of various things on the CurrentBookHandler, which wanted to become a nice independent api controller.
In doing this, I broke the ReadersApi, which was a bunch of statics. That is now, also a normal class that is created by the Project Context and given its dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1056)

BL-2324 BookSettings sensitive to if in shellbook or not

---

src/BloomBrowserUI/bookEdit/test/libsynphony/split_sentences.test.js
src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/bloom_lib.js
src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libsynphony/jquery.text-markup.js
src/BloomExe/web/ReadersHandler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1058)

BL-3406 make synphony handle &nbsp; as white space

---

src/BloomExe/Edit/ToolboxView.cs

This is what we all agreed was the best thing to do for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1069)

Hide the Talking Book Tool on Linux (BL-3430)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/FontFileFinder.cs
src/BloomExe/Publish/FontGroup.cs
src/BloomExe/packages.config

This doesn't get ePUB working on Linux, but does fix a crash due to
Windows specific code.  (Ie, this is necessary, but not sufficient.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1068)

Fix crash from ePUB click (BL-3412) [Linux]

---

lib/dotnet/SharpFont.dll.config
src/BloomExe/BloomExe.csproj

The distributed version causes debian packaging to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1080)

Add SharpFont.dll.config that works for packaging

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts

(includes BL-2284)
When a block is overflowed (text red),
mouse-over produces a tooltip below it.
When a container is overflowed (red bottom border),
hovering over the red border brings up a tooltip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1086)

BL-2283 Give tooltip explaining overflow

---

src/BloomExe/Book/Book.cs
src/BloomTests/Book/BookTests.cs

This is a cherry-pick from master.  I think it was meant for 3.7 first, but accidently submitted onto master instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1089)

Fix tests that were failing on Linux

---

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomExe/Edit/AudioRecording.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/web/BloomWebSocketServer.cs

Previously, the websocket was only used by the audio system. This changes it to be more general, and then makes the page list view show a localized notification when pages are being saved. You won't see the message if it's be saved while leaving this tab or quiting the program, that's ok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1084)

BL-3438 Show toast when saving page

---

src/BloomExe/CollectionTab/LibraryListView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1101)

Fix clicking on down arrow of book icons (Linux, BL-3424)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomExe/BloomExe.csproj
src/BloomExe/ProjectContext.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/controllers/KeybordingConfigAPI.cs

This was working in Chrome, but not FF or Bloom. While trying to figure it out, I just went ahead and refactored into a proper api handler. The problem was somehow related to handling the string result. Changing from "yes/no" to better true/false did the trick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1097)

Fix BL3477 Longpress Broken

---

src/BloomExe/CollectionTab/LibraryModel.cs

See the comment about 9 lines above when looking at the diff!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1103)

Fix an annoying exception that gets swallowed later

---

src/BloomExe/WebLibraryIntegration/BookDownloadSupport.cs

When running bloom as result of a download, channel is lower case and so update check fails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1112)

Fix BL-3515 bad channel case on update if Bloom launched by url

---

src/BloomExe/CollectionTab/LibraryModel.cs

Warning the user to quit and restart is better than crashing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1108)

Catch "Out of memory" viewing "Rescue Missing Images" log

---

src/BloomExe/Publish/EpubMaker.cs
src/BloomExe/web/EnhancedImageServer.cs

We ship a subset of readium, and were getting file not found errors on the bits we don't ship. Also, I redirected a request for jquery to where it is (probably could have just swallowed that, too).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1104)

Fix BL-3497 missing file error in epub preview

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

Previous code was matching on labels, which get localized, so matching failed. Now uses index of selected item.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1116)

Fix BL-3527 When using a non English interface, word space control doesn't work

---

environ-xulrunner
src/BloomBrowserUI/ePUB/baseEPUB.less

1) a directory name capitalization problem in a less @import
2) a setup script worked only for developers, not users
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1117)

Fix a couple of Linux problems for version 3.8 (BL-3541)

---

src/BloomBrowserUI/lib/long-press/jquery.longpress.js

Fix BL-3543 (and possibly BL-3477? couldn't reproduce). The shortcut sensor was staying active after longpress was closed (logic error on my part).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1120)

Fix new shortcut bug in longpress

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomExe/web/ApiRequest.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/ReadersApi.cs

BL-3542 was largely caused by trying to do some 1.4mb write on the UI thread. Possibly this is becuase the client is running on the UI thread too, and the size of the payload was large, so the writer couldn't write because it was waiting for the client to consume, but the client couldn't because the thread was blocked waiting to write some more...
Anyhow so I made it possible when registering a handler to say that it doesn't need to be run on the UI thread.
I then split all the READER api calls into either "io" or "ui", and made separate registrations for the two groups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1118)

Speed up large io calls with Reader Tools

---

debian/control

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1129)

Remove geckofx29 as dependency for Bloom 3.8 (Linux/BL-3592)

---

debian/control

These were previously supplied indirectly by the dependency on
geckofx29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1130)

Add missing dependencies for Linux Bloom 3.8 (BL-3592)

---

debian/bloom

This is needed to handle spaces in folder names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1134)

Fix Linux script to quote directory name

---

build/getDependencies-Linux.sh

This allows Bloom to publish PDF on 64-bit Linux systems, but not on
32-bit Linux systems due to the lack of a suitable TeamCity build agent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1136)

Fix retrieval of GeckofxHtmlToPdf on Linux (BL-3619)

---

src/BloomExe/Edit/EditingModel.cs

These happened every time a page was added or deleted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1142)

Fix bogus missing file reports (BL-3632)

---

src/BloomExe/Publish/EpubMaker.cs

There was a missing format element in a NonFatalProblem string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1150)

Fix crash during epub creation caused by missing wav files (BL-3666)

---

src/BloomExe/Edit/WebThumbNailList.cs

Thumbnail creator was adding "?thumbnail=1" to src="", giving us an empty image request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1149)

Fix BL-3643 error when moving away from Credits Page

---

DistFiles/UnusedTemplates/Template Maker/basePage.css
DistFiles/infoPages/HtmlSamples/Horizontal Centering With Prefix Image/basePage.css
src/BloomBrowserUI/bookLayout/CommonBasePageEPUB.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1152)

Correct typo in Doulos SIL font name (BL-3609)

---

src/BloomBrowserUI/ePUB/bloomEpubPreview.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1153)

Gitden Reader link navigates to help rather than Play Store (BL-3628)

---

src/BloomBrowserUI/bookLayout/languageDisplayTemplate.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1157)

Correct language display order in trilingual book (BL-3555)

---

DistFiles/localization/Bloom.en.tmx

English .TMX file had an incorrect spelling of "arithmetic". Reported by Chris Wilson, SIL Lead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1159)

Correct spelling of "arithmetic

---

src/BloomBrowserUI/bookLayout/languageDisplayTemplate.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1160)

Correct title page language display order in trilingual book (BL-3555)

---

src/BloomExe/Edit/EditingView.Designer.cs

After hours of messing with this (!) narrowed the problem to some interaction between the BitMapButton and BetterToolTip.SetToolTipWhenDisabled. Removing that call makes the problem go away. For more info, check this bug on youtrack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1163)

Fix BL-3657 which showed part of cut icon to the right of the button

---

src/BloomBrowserUI/bookEdit/toolbox/readerTools.less

The first change makes the lettersTable be more assertive.
The second change here is just a bug I noticed. The original "calc(100% - 3px)" was being converted to "calc(97%)". This actually fixes a small visual bug that we had not noticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1164)

Fix BL-3719 Prefer letter list over word list

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

Also, I made it so that if you click the stage buttons rapidly, you can move from that stage you're on to the one you want more quickly. This is done by 
1) delaying start of work for 1/2 second
2) having each load operation check to make sure it is still relevant before executing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1167)

Fix BL-3554 By showing "Loading..."

---

src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
src/BloomExe/web/I18NHandler.cs

This fixes a couple problems in the old code:
1) Tells you exactly what it is you're supposed to do
2) Doesn't throw a false alarm just because the string isn't translated in your current UI language
3) Doesn't mask the problem by adding it to your *local* tmx file if it's not in the *distribution* en.tmx.
For free, this commit includes a small function I ended up not being able to use but which would normally be a good way to safely set HTML to a localized string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1166)

Smarter reminder about adding dynamic string to english tmx

---

src/BloomBrowserUI/lib/long-press/jquery.longpress.js

The shift was being messed with by longpress, which doesn't need the feature that was causing it anymore, now that it has shortcut keys. So I just removed it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1169)

Fix BL-3716 Can't type repeated shifted keys

---

src/BloomBrowserUI/bookLayout/languageDisplayTemplate.css

There is no "content2" when doing a monolingual book, so we need to base the order off of a different class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1170)

Fix BL-3725 Title page language order

---

src/BloomExe/Book/Book.cs

The move operation cleared the page cache, but then didn't rebuild it after the move.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1173)

Fix BL-3739 Error if you move a page and then try to duplicate it

---

src/BloomExe/Browser.cs
src/BloomExe/Collection/CollectionSettings.cs

It works to just always "know" about Andika and always offer it as the default font.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1174)

Deal w/ situation where Andika installer hasn't completed yet BL-3674

---

src/BloomExe/web/ApiRequest.cs
src/BloomExe/web/CurrentBookHandler.cs

The imageInfo api wasn't handling encoded characters in file names.
Added a new method on request to encourage handling encoding properly.
Also, it wasn't reporting the error in a way we would notice it, so now we get a toast in alpha for any such api error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1175)

Properly decode filenames when getting file info (BL-3749)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Edit/EditingModel.cs

Moved the call to UpdateEditableAreasOfELement() out of EditModel into Book.SavePage() method, so that SaveNow() doesn't have to be called twice as before. Result: changing pages is about 50% faster.
HtmlDom: Just clearer names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1180)

Stop saving twice with each page change BL-3772

---

src/BloomBrowserUI/xMatter/bloom-xmatter-common.less

Prevent multi-paragraph titles from showing in columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1181)

Title Page Display editbox should not be "flex" BL-3766

---

src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.cs

I could not reproduce the problem. So this is a bandaid.  Possibly, the error would next show up somewhere else down the line? But this is something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1182)

Maybe help with BL-3774 by filtering titles for null

---

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomExe/web/controllers/ImageApi.cs

Also deleted some dead Typescript code related to the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1187)

Get image info for filenames with spaces (BL-3749)

---

src/BloomBrowserUI/.vscode/launch.json
src/BloomExe/Browser.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/web/EnhancedImageServer.cs

Bloom now understands "CurrenPage"; if you local path contains that, you get the page, which will keep working even if you change the page. That's helpful in normal Firefox work, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1188)

Enable Debugging From Visual Studio Code

---

src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/PageSelection.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1185)

Fix Linux problem of selecting pages too fast (BL-3586)

---

src/BloomExe/Book/Book.cs

This is done by caching the value of Book.FindTemplateBook() when
possible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1192)

Reduce number of (expensive) BookStorage objects created (BL-3782)

---

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomExe/HtmlThumbNailer.cs

This approach creates a dummy "bookmark" node before markup, then after markup, finds the bookmark and sets our selection to that, then removes the bookmark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1193)

Different approach to maintaining cursor during markup BL-3800

---

src/BloomExe/web/RequestInfo.cs
src/BloomTests/web/RequestInfoTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1194)

Fix a regression on handling + signs in url paths (BL-3814)

---

src/BloomTests/web/RequestInfoTests.cs

The fix was suggested by Jason Naylor, our resident threading expert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1197)

Fix fragile test that occasionally fails on TeamCity

---

DistFiles/factoryCollections/Templates/Big Book/BigBook.css
DistFiles/factoryCollections/Templates/Big Book/BigBook.less
src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade

* Change default fontsize for title page to 26pt
* Change vernacular title fontsize to 30pt
* Unlink vern and national title style
(by adding bloom-nodefaultstylerule)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1209)

BL-3827 Fix BigBook title page

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/HtmlDom.cs

* books with BigBook xmatter will be switched
automatically to Factory
* some old Big Books embedded the cover img
tag inside of the background url; handled both
getting and setting image element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1215)

BL-3778 Handle retired xmatter

---

.nuget/NuGet.targets
src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config

Unfortunately, the file MUST be named packages.config, but its exact
location doesn't matter.
I've tested this on both Windows and Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1216)

Provide system specific BloomExe packages.config files

---

src/BloomExe/web/EnhancedImageServer.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/web/EnhancedImageServerTests.cs

For version 3.7, handle spaces (or other characters) that are already
encoded in the HTML file img element src attributes, and then become
encoded a second time when being sent to the Bloom server.  (Note that
this problem was already fixed for 3.8 in BL-3749.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1221)

Handle encoded spaces in image filenames [3.7] (BL-3835)

---

src/BloomBrowserUI/.vscode/launch.json
src/BloomExe/BloomExe.csproj

These changes shouldn't affect Windows developers (similar changes are
already made on the master branch), but will make life easier for Linux
development.  I find myself making these changes repeatedly, and using
git stash (unreliably) to remember them across task branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1222)

Tweak a couple of files to help Linux development

---

src/BloomExe/BookThumbNailer.cs

The fix is almost embarrassingly simple.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1226)

Prevent endless thumbnails for inaccessible books (BL-3841)

---

src/BloomBrowserUI/pageChooser/page-chooser.ts

Without this, pretty yellow dialogs pop up when you opened the
Add Pages dialog for some books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1213)

Prevent invalid images when building Add Page dialog (BL-3819)

---

DistFiles/branding/GRN-REACH/settings.json
src/BloomExe/BloomFileLocator.cs
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookCopyrightAndLicense.cs
src/BloomExe/web/controllers/BrandingApi.cs
src/BloomTests/Book/BookCopyrightAndLicenseTests.cs

Settings.json can contain copyright, license url, and rights statement (license notes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1233)

Allow a settings.json to define some defaults for a brand (BL-3868)

---

build/dependencies.config

This should get master builds working on TeamCity again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1248)

Fix package name for Linux dependency on master

---

build/getDependencies-windows.sh

This is needed only for Version3.7 (and for windows) as far as I know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1250)

Update getDependencies-windows.sh to fully remove Mercurial

---

src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/ServerBase.cs

The fix may also more quietly ignore some other unimportant files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1256)

Ignore missing branding images files (BL-3891)

---

src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/xMatter/Factory-XMatter/Factory-XMatter.less
src/BloomBrowserUI/xMatter/bloom-xmatter-common.less

There was a rule that assumed that only the front matter had multilingual fields. I  generalized that to include back matter also.  that, in turn, required specifying the display for the two back matter pages in other xmatter packs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1257)

Fix BL-3860 Super Paper Saver showing extra lang field for original acks

---

src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/UrlPathString.cs
src/BloomExe/web/CurrentBookHandler.cs

I've tested this fix on both Linux (Wasta 14) and Windows 10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1251)

Handle URL encoded cover image filenames in more places (BL-3901)

---

src/BloomExe/Publish/PublishView.cs

Also eliminate the source of a gratuitous exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1260)

Fix broken loading of MissingLameModule*.html (BL-3906)

---

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts

It's already showing on the title page anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1263)

Don't show regional book title in source bubble (BL-3888)

---

src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs

Very probable linux bloompack install bug
due to capitalization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1269)

Fix Bloompack bug

---

src/BloomExe/web/BloomWebSocketServer.cs
src/BloomExe/web/ServerBase.cs

This doesn't fix the problem, but provides a few details that are
currently unreported.
Also remove an apparently redundant HttpListener prefix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1275)

Log opening a WebSocketServer (BL-3916)

---

src/BloomBrowserUI/lib/ckeditor/config.js

VSCode reformatted a number of lines automatically.  This appears to
be desired by src/BloomBrowserUI/.vscode/settings.json.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1278)

Restrict what can be pasted into text boxes (BL-3899)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomExe/web/ReadersApi.cs

I've tested the updated fix on both Linux and Windows.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1279)

Fix data for counting words in leveled readers (BL-3498)

---

src/BloomBrowserUI/.vscode/launch.json
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts

* changing tabs from Sample Words to Decodable
Stages was not remembering the words in a way
that allowed Synphony to update its data
* since we fixed that pre-registered url issue on our
dev machines I changed the ports in launch.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1283)

Fix BL-3493 DR Setup doesn't find words

---

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js

Actually, we now split words on all Control characters (ZERO WIDTH SPACE
is a Control character) as well as all Separator characters.
This is on the master (3.8) branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1287)

Split words on ZERO WIDTH SPACE (BL-3933)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

* With Typescript 2.0, this is apparently no longer necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1291)

Undo .bind() fix

---

src/BloomExe/Browser.cs

* also in moving to TS v2.0, apparently the
extra .bind(this) in ReaderToolsModel.ts is no longer
necessary (or even legal)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1290)

BL-3658 Fix Cut/Copy buttons

---

src/BloomBrowserUI/lib/ckeditor/config.js

Perhaps the most important addition is u to restore underlining.
I also reordered the list slightly to put content first and inline following.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1293)

Add more inline elements to CKEDITOR filtering (BL-3948)

---

src/BloomBrowserUI/templates/template books/Big Book/Big Book.jade
src/BloomBrowserUI/templates/template books/Big Book/Big Book.less
src/BloomExe/Book/BookStorage.cs
src/BloomTests/Book/BookStorageTests.cs

* fixed algorithm for finding htm/html file if different
than folder name
* renamed BigBook files (.less and .jade) to match
Big Book folder name
* also redid solution for BL-3788 (BB Instructions)
for 3.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1295)

BL-3572 Fix BigBook template

---

src/BloomTests/CLI/HydrateBookCommandTests.cs

Note that the Mono runtime doesn't like combining paths where the
file argument starts with "../".  The combine path still has "/../"
in the middle and at least some methods don't like that at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1298)

Fix unit tests that were failing on Linux

---

src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts

I also tweaked a couple of statements to make debugging easier.  (I don't know why some people have a phobia of temporary variables.)  The critical bugfix to avoid the yellow crash dialog was in the TypeScript file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1301)

Fix crash clicking 'This is a template book' checkbox (BL-3872)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools_libSynphonySpec.ts

We had a workaround in JS which, when the c# was fixed, actually became a bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1304)

Stop double-escaping line feeds (bl-3969 and bl-3970)

---

src/BloomExe/MiscUI/ProblemReporterDialog.cs

If no book is selected, the checkbox for including a
book won't be visible, but it's still checked!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1312)

BL-3987 Fix Report A Problem if no book

---

src/BloomExe/Book/UserPrefs.cs
src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs
src/BloomExe/Publish/PdfMaker.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs
src/BloomTests/PdfMakerTests.cs

This allows low-memory machines (at least for Windows) to create
PDF files that otherwise would require too much memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1311)

Produce PDF files one page at a time if desired (BL-3929)

---

debian/rules

This should have been part of my earlier removal of BloomLinux.sln.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1317)

Fix Linux packaging to build with Bloom.sln

---

src/BloomExe/Edit/EditingModel.cs

until we load a book (ExpensiveInitialization)
This enables Cut -> Paste to remember the
image metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1320)

BL-3717 Cut:Don't cleanup unused images

---

src/BloomExe/Edit/EditingModel.cs

until we load a book (ExpensiveInitialization)
Cherry-pick commit from master to 3.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1321)

BL-3717 Don't cleanup unused images

---

src/BloomBrowserUI/bookLayout/basePage-sharedRules.less
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/ePUB/baseEPUB.less
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-sharedRules.less

A couple of files were labeled EPUB when actually they
were subsets of rules that were used by regular books
AND Epubs.
* renamed files using *-sharedRules.less
* comments in the files explain why they are in
separate files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1325)

BL-3569 Rename files for clarity

---

src/BloomExe/Collection/CollectionSettingsDialog.cs

This bit of code was in the Designer, but got deleted
if the Designer was touched.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1330)

Fix missing xMatter list in Settings

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/ImageProcessing/ImageUtils.cs

This preserves the proper permissions for access over a network
file share.
This is an alternative to https://github.com/BloomBooks/BloomDesktop/pull/1322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1327)

Create temporary files in book folder if needed (BL-3954)

---

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.jade

Credits-Page-style (language agnostic version)
currently affects both label and number, but this
change makes it so the user can modify that
'non-language' version of the style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1334)

BL-4026 Allow ISBN font to follow style

---

src/BloomExe/Edit/EditingModel.cs

This is prevented by not duplicating calls to Browser.Navigate by not
duplicating calls to EditingView.UpdatePageList.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1339)

Prevent bogus message about missing page (BL-3715)

---

src/BloomBrowserUI/templates/template books/Wall Calendar/configuration.jade
src/BloomBrowserUI/templates/template books/Wall Calendar/configure.js

* If after the month of May, use next year
* Otherwise use the current year
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1338)

BL-3549 Make Calendar default to reasonable year

---

src/BloomExe/Collection/CollectionSettings.cs

This works properly with the current way decimal values for line heights
are displayed in CollectionSettingsDialog and stored in the settings file.
If that display should be localized, some adjustment would be needed to
ensure compatible storage and decoding of these decimal values.
Without this fix, line height setting would be forgotten for any locale that
does not use . for "decimal points".  (This fix is a follow-on to BL-4040.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1343)

Handle decimal.TryParse deterministically

---

src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.jade
src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.less
src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/description-en.txt
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.jade

* This includes a change to c# code so that
Credit-Page-style will work on the copyright field
* Add customXMatter folder to templates
* Add jade and less to combine title/credit pages
* Add printer's statement space to inside back cover
* Rearrange some of the parts of the combined page
* Modify a few bits of less, so the rearranged bits fit
* Get Printer's Statement 'bottom aligned'
* Moved both acknowl fields up above funding
* Added Printing Info section just above copyright
* Reduced space below original acknowledgments
and funding sections
* Reduced min-height to one line for funding and
original contributions sections
* Get Credit-Page-style to work on all the combined
title/credits page fields except the titles
* Maintain a separate style for the PrintingInfo
section
---
This …

MXB Pamphlet xmatter

---

debian/install

It's been removed everywhere else already, and packages aren't
building on jenkins.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1344)

Remove Chorus from Linux packaging

---

src/BloomExe/Linux/packages.config

Without this fix, Bloom won't even build on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1351)

Fix Linux packages.config to match Windows

---

src/BloomExe/CollectionCreating/NewCollectionWizard.cs

This is not a proper Form, or it would have a
settable CancelButton property. Instead we have to
rely on the ProcessCmdKey override. Not ideal.
Moving the nullification of the collection variable after the Close() should
prevent the problem in the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1357)

BL-4041 New Collection Wizard error

---

src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/bookLayout/languageDisplayTemplate.css
src/BloomBrowserUI/templates/bloom-foundation-mixins.pug
src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug
src/BloomBrowserUI/templates/template books/Arithmetic/Arithmetic.pug
src/BloomBrowserUI/templates/template books/Big Book/Big Book.pug
src/BloomBrowserUI/templates/template books/sample.pug
src/BloomBrowserUI/templates/template books/standard-page-mixins.pug
src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.pug
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/TranslationGroupManager.cs
src/BloomTests/Book/BookStarterTests.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/PageMigrationTests.cs
src/BloomTests/Book/TranslationGroupManagerTests.cs
src/BloomTests/Publish/ExportEpubTests.cs

http://issues.bloomlibrary.org/youtrack/issue/BL-4065
Goals
Enable user to create text blocks that are for only V, N1, or N2 (BL-4037).
Enable user to be able to hide specific language fields in xmatter (BL-3829).
Unify how we handle fields in XMatter and Content pages
Simplify how we handle field visibility (e.g. neuters languageDisplay.css). Set us up for future removal of bloom-content1, bloom-contentNational1, bloom-contentNaitonal2.
I apologize for the number of files... surprising for such a small change in the code. I've intentionally calved off parts of this project to future PRs so this doesn't get bigger than it needs to be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Switch to new system of controlling language-field visibilitiy BL-4065

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/EpubMaker.cs
src/BloomTests/Publish/ExportEpubTests.cs

Added languagedisplay.css to tests. Had to hold my nose while doing this, it feels like a hack. Every unit test should not have to be updted to whatever the current stylesheet system is; but the system of detecting which fields are visible actually *goes around* the stylesheets of the actual page, so that the only stylesheets it sees are what have been added to the unit test. Very frustrating, but not worth more time now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1371)

Fix epub tests

---

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1277)

Restrict extent of Control-A in source bubbles (BL-3899)

---

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts

There was some logic in there that I removed, related to shellBookEditing. It doesn't make sense to me, and I did manual testing looking for something... so I'm assuming it's something needed in the past that isn't needed now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1368)

Simplify Bubbles using the new bloom-visibility-code-on class (BL-4067)

---

src/BloomExe/Edit/EditingView.cs

With this fix, I haven't been to provoke  a problematic shutdown on my (fast) Windows 10 machine.  On Linux, I can still provoke shutdowns where the program hangs during shutdown and has to be manually killed one way or another.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1377)

Don't crash if no body element (BL-3988)

---

src/BloomExe/ApplicationUpdateSupport.cs

If a squirel update fails, it leaves an empty directory with the name of the Bloom it was trying to create, which then messes up the shortcut so you can no longer run the previous version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1379)

Delete failed updated directory

---

src/BloomExe/Program.cs
src/BloomExe/Shell.cs
src/BloomExe/SplashScreen.cs

We could probably fish out the appropriate nupkg and get its date, but that doesn't feel worth it at the moment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1380)

Remove bogus "build dates" BL-4095

---

src/BloomExe/Linux/packages.config
src/BloomExe/packages.config

Bloom won't build on Linux without this fix.  Well, at least the first file of the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1382)

Fix Linux packages.config to match revised Windows file

---

src/BloomExe/Edit/EditingView.cs

I couldn't figure out any fix for the unreadable text of Publish tab
buttons, but I think they're hard to read only when the buttons are
inactive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1386)

Fix ugly inactive Edit tab button images for Linux (BL-3714)

---

src/BloomExe/Edit/EditingView.cs

With this tweak, the disabled buttons look more like light grey as you would expect, and closely match the color of the associated text.  I have no idea why an identity transformation matrix would have this affect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1387)

Tweak color of disabled buttons on Linux (BL-3714)

---

src/BloomExe/Book/BookCopyrightAndLicense.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1391)

Tell what the failed license URL was when we can't parse it. BL-4108

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
src/BloomBrowserUI/bookEdit/css/origami.less
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
src/BloomBrowserUI/bookEdit/js/origami.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

* un-refactor looking for 'ready' CKEditor instances
* fix overlapping "Picture or Text" links and "Text Box"
* reposition gear to end of "Text Box" identifier
(and put the gear styles in origami.less)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1385)

BL-4037 Further Text Box Properties dialog changes

---

src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1407)

Fix row order of elements in Arithmetic template (BL-4144)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomExe/Edit/AudioRecording.cs
src/BloomExe/Edit/LameEncoder.cs
src/BloomExe/Edit/ToolboxView.cs

This uses the work I did for Linux FieldWorks sound recording,
implementing Bloom tailored forms of SIL.Media.NAudio.AudioRecorder
and related classes.  (without any use of NAudio, of course)
I think this implements everything except trimming the wav file and showing
(and adjusting?) the recording levels.  It even allows switching input devices
inside the program, and detecting when devices are added or removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1397)

Add audio recording for Linux (BL-3935)

---

src/BloomExe/ImageProcessing/ImageUtils.cs

Our process for removing transparency was stripping out metadata too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1413)

BL-4148 Fix lost image metadata

---

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1423)

Correct order of titles for preview and PDFs (BL-4156)

---

src/BloomExe/ApplicationUpdateSupport.cs

This change is intended to be put only in a final 3.7 which we will release
for the purpose of preventing Vista updating to later (3.8) versions
since they require an incompatible version of .NET.
Do NOT merge into master or any later branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1411)

BL-4163 Don't update if running on Vista

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/CLI/GetUsedFontsCommand.cs
src/BloomExe/Publish/EpubMaker.cs
src/BloomTests/Publish/ExportEpubTests.cs

We weren't including fonts for styles
We were embedding extra fonts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1418)

Fix problems with epub embedded fonts (BL-4146)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

* when Decodable Reader setup was incomplete
execution skipped a vital markup pass
NB: This has two commits. The first is just formatting changes from VSCode. The second commit is the actual fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1424)

BL-4184 Fix Leveled Reader counts

---

debian/README
debian/control
debian/rules

This is required by the embedded geckofx45 with firefox binaries.
DO NOT MERGE THESE CHANGES WITH ANY OTHER BRANCH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1429)

Fix Linux packaging for architecture dependency

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/EpubMaker.cs
src/BloomExe/TempFiles.cs
src/BloomExe/ToPalaso/DirectoryUtilities.cs

This fix is only for Version3.7 and should not be merged to other branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1434)

DO NOT MERGE BEYOND 3.7 -- Move fixed DeleteDirectoryRobust from libpalaso to Bloom (BL-4141)

---

src/BloomExe/web/I18NHandler.cs

Added non 3rd-party warning to non-developer code path
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1436)

BL-4135 Warn against localizing 3rd party books

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

* what worked in 3.7 doesn't quite in 3.8
* apparently function(x,y) {} isn't quite the same as
(x,y) => {}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1443)

[3.8]BL-4184 Incomplete DR setup messes w LR counts

---

src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.less
src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.pug

* moved Equation-style from Usermodifiedstyles
(where it couldn't move to a different template)
to ArithmeticTemplate.less (which does go with
the page to another template)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1444)

[3.8]BL-4199 Arithmetic pages equals

---

debian/control

DO NOT MERGE THIS COMMIT TO ANOTHER BRANCH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1454)

Make bloom-desktop-beta depend on lame (BL-4213)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/web/BloomHttpListenerContext.cs
src/BloomExe/web/RequestInfo.cs
src/BloomExe/web/ServerBase.cs
src/BloomTests/web/RequestInfoTests.cs

Requires wrapping some HttpListener classes so we can have Test implementations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1457)

Fix tests which fail on TeamCity by throwing an exception (BL-4137)

---

src/BloomBrowserUI/.vscode/settings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1462)

Turn off formatOnSave in VS Code for 3.7 (BL-4101)

---

src/BloomExe/MiscUI/ProblemReporterDialog.cs

If you decide this should go onto Version3.7, it shouldn't be too hard to rebase this change.  I did notice one omission in the previous enhancement that was made to Version3.7: the previous enhancement didn't do anything if the user had to fall back to email submission instead of being able to submit directly to youtrack.  That has been fixed in this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1478)

Submit collection settings with problem report book (BL-4267)

---

src/BloomExe/Book/BookStarter.cs

For some reason, the fix made last week isn't working today.  Maybe I was hallucinating last week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1487)

Fix the Linux fix for the fix for BL-4160

---

src/BloomExe/MiscUI/ProblemReporterDialog.cs

This also fixes BL-4275.
This is currently on the Version3.7 branch.  If desired, it could be rebased to Version3.8, but that would leave a broken Report Problem on Version3.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1488)

Check for "Sample Texts" and "Allowed Words" folders (BL-4274)

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js
src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js
src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1494)

Fix case-sensitivity of \U vs \u in unicode specifiers (BL-4247)

---

.editorconfig

Line endings should be controlled by the git configuration.
Specifying crlf immediately changes every line of every file on Linux,
which makes VSCode unusable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1502)

Fix .editorconfig to not break VSCode on Linux

---

src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less

The style setting was copied from the Format dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1507)

Fix Text Box Properties dialog tab header font size (BL-4294)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts

* if we ever upgrade our jqueryUI to a newer version
we'll need to undo this change
* there is a comment to that effect in the code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1505)

BL-647 Fix jumping StyleEditor and Text Box Properties dialogs

---

src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts

- fixes old code that was deleting bubble labels
- uses a new strategy to prevent getting source bubbles AND hints
- removes hints from (wrong place in) source bubbles
- hints for auto-language groups show once for whole group
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1508)

BL-4233 Improve template box hints

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts

* includes some renaming and refactoring for code
used by both StyleEditor and TextBoxProperties
* fixes dragging when zoomed or scrolled
* initial placement is better than 3.7, tho' still not
perfect when zoomed for textBoxProperties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1516)

BL-647 Fix jumping StyleEditor for zoom

---

src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/web/EnhancedImageServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1520)

Properly handle lookup of images when using OriginalImages marker (BL-4290)

---

src/BloomBrowserUI/package.json

Version 2.2 has a breaking change that keeps Bloom from building.
Pinning to the 2.0 series apparently pins only to the version 2 series
since this allowed 2.1.* and 2.2.* to be downloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1524)

Pin TypeScript to the version 2.1 series

---

src/BloomExe/BloomExe.csproj

This mimics the batch file I use to build on Windows now.  Perhaps this should be on Version3.8 instead...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1537)

Speed up C# building on Linux

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less
src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less
src/BloomBrowserUI/bookEdit/css/bloomDialog.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1554)

Fix dropdown hiding behind the dialog (BL-4386)

---

src/BloomExe/CollectionCreating/LanguageIdControl.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1566)

Fix somewhat obscure crash when changing UI language in collection chooser (BL-4434)

---

src/BloomTests/Book/XMatterHelperTests.cs

TeamCity seems much more fragile than local developer machines!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1569)

Further fix to failing unit test

---

src/BloomExe/Publish/EpubMaker.cs

This is the only Double.Parse() call in the Bloom source tree.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1573)

Parse timespans invariantly for epubs (BL-4374)

---

src/BloomExe/Publish/EpubMaker.cs

This was done originally on master before we realized it needed to be on Version3.7 and Version3.8.  Getting onto Version3.8 can wait for the next merge from Version3.7 now that that will be a next merge...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1574)

Parse timespans invariantly for epubs (BL-4374) (#1573)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomTests/Book/BookTestsBase.cs

This led to a major cleanup of how books track their
error state. Not sure whether we want to risk this in 3.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1577)

BL-4328 restore backup when book does not validate

---

src/BloomBrowserUI/templates/template books/Big Book/template/NotForAddPage.txt
src/BloomBrowserUI/templates/template books/Decodable Reader/template/NotForAddPage.txt
src/BloomBrowserUI/templates/template books/Leveled Reader/template/NotForAddPage.txt
src/BloomBrowserUI/templates/template books/Picture Dictionary/template/NotForAddPage.txt
src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md
src/BloomBrowserUI/templates/xMatter/TemplateStarter-XMatter/TemplateStarter-XMatter.pug
src/BloomExe/Book/Book.cs
src/BloomExe/web/controllers/PageTemplatesApi.cs

Now instead we look for a subfolder called "template"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1564)

BL-4428 Remove need for Templates to be named Template

---

src/BloomExe/BloomFileLocator.cs
src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs
src/BloomTests/Book/BookTestsBase.cs

Also refactor the code to use a single method for obtaining the execution
folder from the running assembly.  This was involved in all three test
failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1581)

Fix some tests that were failing on Linux

---

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

Might be easiest to review by commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1580)

Protect paragraph-oriented html from backspace and delete BL-4423

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/SplashScreen.cs

Also tweak Linux alpha package channel name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1589)

Don't localize channel name in splash screen (BL-4451)

---

src/BloomExe/Edit/EditingView.cs
src/BloomExe/ImageProcessing/ImageUtils.cs

This is done by copying the image file to pass in to the select/modify
image dialog (ImageToolboxDialog).  Unused duplicates are weeded out by
the normal process of editing the file later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1594)

Prevent image on copied page from changing original (BL-3689)

---

src/BloomExe/MiscUI/ToastNotifier.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1611)

Prevent yellow screen opened by toast from being closed prematurely (BL-4380)

---

DistFiles/localization/Bloom.en.tmx
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/XMatterHelper.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/NonFatalProblem.cs
src/BloomExe/ProjectContext.cs
src/BloomTests/Book/XMatterHelperTests.cs

1) We were handling un-found collections-settings xmatter as if it were book-by-book problem. Now it is handled when collection is open.
2) We had some repeated and seemingly inconsistent handling of xmatter name migration
3) Changed error messages a bit to indicate that the problem may just be due to different versions of Bloom (actually this is by far the likely case)
4) don't load and check xmatter when all we're doing is getting a name. <--- this may be backported to 3.8, we'll see.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1612)

Improve XMatter problem handling BL-4472

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs

For 3.8, we didn't need this tag, so it's safer to just remove knowledge of it altogether since it's about to be released.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1614)

NOT FOR DOWNSTREAM Remove problematic support for <meta xmatter> in 3.8 only

---

src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/ListHeader.cs

Also contains a workaround for a bug
in FlowLayoutPanel that prevents it noticing
changed child widths
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1613)

BL-4470 allow labels in sources to wrap

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
src/BloomExe/Book/RuntimeInformationInjector.cs

Also adds a couple of page labels that really were missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1616)

BL-4355 don't report missing custom hing I10N

---

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/js/bloomNotices.ts
src/BloomBrowserUI/bookEdit/js/bloomQtipUtils.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Edit/EditingModel.cs

This involved moving the transform:scale css from the body element to a
outer div element created especially for holding the scale factor.  With
this fix, the dialogs and dropdowns just positioned themselves nicely,
and the tooltips needed only a minor tweak to continue working as before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1610)

Revise zooming to get dialogs to position correctly (BL-4172)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1622)

Don't honor xmatter tag if it come from a bloom prior to 3.9. BL-4480

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less
src/BloomBrowserUI/bookEdit/css/bloomDialog.less

(cherry picked from commit 97fb569f43e84df0b07784bd897cf30f9169a0c8)
#	src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1629)

VERSION 3.8 ONLY - Fix dropdown hiding behind the dialog (BL-4386)

---

DistFiles/localization/Bloom.en.tmx

* Space Between Paragraphs was missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1631)

BL-4520 Added missing localization

---

src/BloomBrowserUI/pageChooser/page-chooser.ts

The Story Primer used the same guid for custom page. Now only select the first one you find.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1633)

Select the first custom page BL-4500

---

src/BloomExe/Publish/PublishView.cs

I accidentally created the PR on master and it got merged there already.  Here it is again, based on Version3.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1639)

Don't show old PDF while creating new PDF or ePUB (BL-4518)

---

src/BloomExe/Program.cs
src/BloomExe/Workspace/WorkspaceView.cs

Without this, Bloom always thinks it is running for the
first time, which among other things makes it revert
to the system UI language.
(Also made it save new UI lang selection immediately.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1642)

BL-4545 Save setting FirstTimeRun to false

---

DistFiles/localization/Bloom.am.tmx
DistFiles/localization/Bloom.ar.tmx
DistFiles/localization/Bloom.bn.tmx
DistFiles/localization/Bloom.en.tmx
DistFiles/localization/Bloom.es.tmx
DistFiles/localization/Bloom.fr.tmx
DistFiles/localization/Bloom.ha.tmx
DistFiles/localization/Bloom.hi.tmx
DistFiles/localization/Bloom.id.tmx
DistFiles/localization/Bloom.km.tmx
DistFiles/localization/Bloom.lo.tmx
DistFiles/localization/Bloom.ne.tmx
DistFiles/localization/Bloom.ru.tmx
DistFiles/localization/Bloom.rw.tmx
DistFiles/localization/Bloom.sw.tmx
DistFiles/localization/Bloom.ta.tmx
DistFiles/localization/Bloom.te.tmx
DistFiles/localization/Bloom.th.tmx
DistFiles/localization/Bloom.zh-Hans.tmx
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomExe/Book/RuntimeInformationInjector.cs

* Several strings were not under FormatDialog
(and were not used anywhere else)
* Several strings had not yet been put into en.tmx
* Marked a couple of strings as no longer used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1634)

BL-4520 Adjust FormatDialog L10N strings

---

DistFiles/localization/Bloom.es.tmx

Tom Bogle provided help to decide between BloomDesktop and BloomLibrary translations.
Now they are in sync.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1646)

Update Spanish translations for topics (BL-4548)

---

DistFiles/localization/Bloom.en.tmx
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Browser.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/PageListView.cs
src/BloomTests/Book/HtmlDomTests.cs

* 1st commit is minor refactors, including adding a missing
StyleEditor tmx string
* 2nd commit fixes the problem by wrapping merged styles
in CDATA properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1650)

BL-4498 Space Between Paragraphs lost

---

src/BloomExe/Program.cs
src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1667)

Save user's UI language selection (cherry pick from 3.9) (BL-4545)

---

src/BloomExe/Edit/EditingView.cs

Agatha got a "Window does not have a global JSObject" exception from the Geckofx-Core. This prevents that exception crashing Bloom. Comments in the code suggest that a failure here only indicates a timing problem that keeps Bloom from saving the zoom state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1669)

BL-4633 Fix crash in GetPageBody()

---

src/BloomExe/web/UrlLookup.cs

* factor out message string
* limit IssueTrackingSystem to exception Message
* this eliminates long innerExceptions from Amazon
filling up the error reports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1675)

BL-4602 Don't fill error reports with Amazon stuff

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Program.cs
src/BloomTests/Collection/CollectionSettingsTests.cs

zh-CN will be used as default UI language for any variant of zh as system language
zh-CN will be used for license on page if any variant of zh requested. For any other variant, we will try the plain language code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1682)

BL-3691 Use zh-CN for zh-Hans

---

src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
src/BloomBrowserUI/bookEdit/js/bloomQtipUtils.ts
src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
src/BloomExe/web/EnhancedImageServer.cs

A better way to prevent clicks on source bubble hiding it as base field loses focux; and improve reliability of code that determines whether to show it on focus only.
(Also fixed an unrelated crash that was annoying me.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1687)

BL-4568 make source bubble reliably visible

---

DistFiles/localization/Bloom.en.tmx
debian/control
src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs
src/BloomExe/Publish/PdfMaker.cs
src/BloomExe/Publish/ProcessPdfWithGhostscript.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs

What to do about ensuring ghostscript is installed on Windows is yet
to be determined or implemented.  There is a comment about what is
involved in the YouTrack issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1699)

Shrink PDF files with ghostscript before displaying (BL-3721)

---

src/BloomExe/Collection/CollectionSettings.cs

This requires the user to tell the program that the script is RTL, but
we already have a spot for them to do that in the Settings dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1711)

Fix RTL display of license in RTL script (BL-4119)

---

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug

* if vernacular lang is rtl, license image should be on
right side
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1717)

BL-4581 Move license image right on rtl

---

debian/rules

In a pbuilder environment the HOME environment variable is set to
`/nonexistent`. This causes build failures with NuGet and npm.
As a workaround we set HOME to /tmp.
(cherry picked from commit 06c472857d6fff8f9ca0b6ac423ae53eefd2cf9b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1726)

Fix packge build for Version3.8

---

debian/rules

In a pbuilder environment the HOME environment variable is set to
`/nonexistent`. This causes build failures with NuGet and npm.
As a workaround we set HOME to /tmp.
(cherry picked from commit 06c472857d6fff8f9ca0b6ac423ae53eefd2cf9b)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1727)

Fix package build for version 3.9

---

DistFiles/localization/Bloom.en.tmx
artwork/draghandle-grey.svg
src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/bookEdit/editablePage.ts
src/BloomBrowserUI/bookEdit/img/dragHandleGrey.svg
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomBrowserUI/bookEdit/js/origami.ts
src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/bookLayout/textOverPicture.less
src/BloomBrowserUI/templates/common-mixins.less
src/BloomExe/Browser.cs
src/BloomExe/Command.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/ElementProxy.cs
src/BloomTests/ElementProxyTests.cs

* Adds floating text box, drags.
* Switch to using WebSocket
* Added textbox activates properly
* Imported textOverPicture.less to basePage.less
* Textbox background is now transparent, so we only
show the background of the image itself
* Use standard ready function syntax
* Switched websockets to use addEventListener
instead of onmessage
* Fix box border colors
* Get resizable working
* Turn off function for xMatter
* Get dragging to work when scaled (zoomed)
* Add wrapper div
* Hide borders, handles, lang when not hovered
* Add drag handle mostly outside top left corner
* Get left-click working
* Fix bloomImages to not get info Bloom edit-only
images (mostly indent; only real changes are in
SetImageTooltip()
* Only allow add/delete textbox if not "translation"
---
This change is [<img …

 Add draggable text over pictures boxes

---

src/BloomBrowserUI/bookLayout/textOverPicture.less
src/BloomBrowserUI/templates/common-mixins.less

* dragHandle zindex needed to be higher than textbox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1737)

Fix TextOverPicture drag handle

---

src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/WebThumbNailList.cs

This has now become 4 commits:
1- the original commit
2- a cleanup commit in pageThumbnailList.ts (mostly single to double quotes)
3- a small commit in EditingModel/View to simplify creation of the Websocket
4- a commit of CR changes
* improve talkingBook/audioRecording websocket
handling
* improve pageThumbnailList websocket handling
* properly catch "no audio" response
* revert change to talkingBook updateMarkup
* add comment to listenerFunction in
pageThumbnailList
* get "Saving..." toast working again
(WebThumbnailList.cs)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1738)

BL-4737 Connection terminated

---

src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs
src/SquirrelInstaller/Bloom.nuspec

This will be useful for showing page numbers when page is in isolation, computing illustration credits that list the page, and making Table of Contents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1744)

Add HTMLDOM.GetPageNumberOfPage()

---

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomExe/Browser.cs
src/BloomExe/Edit/WebThumbNailList.cs

* tsLint cleanup in pageThumbnailList.ts
* better websocket handling
* block toast notification for websocket connection error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1746)

BL-4737 Websocket cleanup (3 commits)

---

src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Edit/EditingModel.cs

Switch from relying on css counting for left vs. right styling to  using a class maintained by c#. This allows us to show a page in isolation and still show it correctly in this respect.
TODO: how does this impact epub and bloom reader?
TODO: doesn't yet update display of the page when page is reordered
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1748)

Show left vs. right page layout, even in edit mode BL-4797

---

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/templates/common-mixins.less

* pageThumbnailList.less - mostly indent changes
except for A6 and Device16x9 sizes
* main fix is in basePage.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1755)

BL-4820 Fix Device16x9Landscape

---

src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
src/BloomTests/Book/BookDataTests.cs
src/BloomTests/web/EnhancedImageServerTests.cs

This won't fix one failing test (that requires a L10NSharp fix), but will fix the problem with the tests hanging and timing out on TeamCity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1764)

Fix problem with hanging tests due to l10nsharp changes

---

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less
src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/bookPreview/previewMode.less
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomTests/Book/HtmlDomTests.cs
src/BloomTests/Collection/CollectionSettingsTests.cs

Page numbering was done in css, but counting approach that doesn't work if, as in edit mode, we only show one page.
This completely switches responsibility for determining page numbers & their representation in the required script to c#.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1751)

Show page numbers in edit mode BL-4796

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.js
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxSpec.ts

The previous fix for BL-4775 helped at save-page time,
but this helps at actual paste time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1756)

Fix paste from Word (more betterer) (BL-4775)

---

src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/bookLayout/device.less
src/BloomBrowserUI/templates/common-mixins.less

* install DeviceBottomMargin variable and mixin
* add device.less to import into basePage
* center page number on Device layouts
* leave some space at the bottom of Device layouts
for page number, if needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1779)

BL-4819 Device css for margins, pg numb

---

DistFiles/IntegrityFailureAdvice-en.md
DistFiles/infoPages/TrainingVideos-en.md
src/BloomBrowserUI/templates/template books/Big Book/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Decodable Reader/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Leveled Reader/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Picture Dictionary/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Wall Calendar/ReadMe-en.md
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Linux/packages.config
src/BloomExe/MiscUI/MarkDownTextBox.cs
src/BloomExe/Registration/LicenseDialog.cs
src/BloomExe/packages.config

Also remove apparently unused reference to MarkdownDeep.
This is the first step of the new localization approach to markdown files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1793)

Replace MarkdownSharp with Markdig

---

src/BloomBrowserUI/bookLayout/device.less
src/BloomBrowserUI/templates/common-mixins.less

* Device16x9 and PictureStoryLandscape layouts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1780)

BL-4819 Fix margins on Credits page

---

DistFiles/IntegrityFailureAdvice-en.md
DistFiles/leveledRTInfo/leveledReaderInfo-en.pug
DistFiles/localization/en/Big Book/ReadMe.xlf
DistFiles/localization/en/Decodable Reader/ReadMe.xlf
DistFiles/localization/en/IntegrityFailureAdvice.xlf
DistFiles/localization/en/Leveled Reader/Readme.xlf
DistFiles/localization/en/MissingLameModule.xlf
DistFiles/localization/en/Picture Dictionary/ReadMe.xlf
DistFiles/localization/en/Template Starter/ReadMe.xlf
DistFiles/localization/en/TrainingVideos.xlf
DistFiles/localization/en/Wall Calendar/ReadMe.xlf
DistFiles/localization/en/bloomEpubPreview.xlf
DistFiles/localization/en/leveledReaderInfo.xlf
build/Bloom.proj
build/getDependencies-Linux.sh
build/getDependencies-windows.sh
src/BloomBrowserUI/ePUB/MissingLameModule-en.pug
src/BloomBrowserUI/ePUB/bloomEpubPreview-en.pug
src/BloomExe/BloomExe.csproj
src/BloomExe/MiscUI/BloomIntegrityDialog.cs

Add the generated xliff files to source control for crowd-in to find.
As long as the pug and markdown files don't change, and the HtmlXliff
program doesn't change, generating these files afresh shouldn't cause
any differences.
This is the first step of a projected 3-step process.  The second step is
to extract translated xliff files from the translated HTML related file.
The third step is to actually change the program to remove the translated
pug and markdown and create the translated HTML files at build time and
add them to the installer and package.  The program behavior (and maybe
the content of the installer) won't change until the third step.  But we still
might want to consider whether this should be merged even if it looks
okay.
---
This change is [<img …

Extract xliff from pug and markdown files

---

src/BloomExe/ProjectContext.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/Android/UsbPublisher.cs
src/BloomExe/Publish/Android/wifi/WiFiAdvertiser.cs
src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/web/controllers/WiFiPublisher.cs

This moves all the logic of each method out to its own class(es), leaving the API to simply run things and manage the state machine, and hide the whole http request/ web socket layer from the classes that do the publishing. With the new UI, the state system is a lot simpler, so that allowed some simplication too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1805)

Cleanup Android Publishing Classes

---

src/BloomExe/Publish/Android/wifi/BloomReaderUDPListener.cs

It's not clear how BL-4968 happened, but I just made it tolerant of that situation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1819)

Handle listener being null BL-4868

---

src/BloomBrowserUI/react_components/progressBox.tsx

The real error turned out to be a simple change of id. But before I figured that out, I had made the code a bit more robust. Since there I found an instance of this error in the youtrack history, unsolved, it's possible that this will be useful, so I left that in there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1818)

Fix progressDiv null error BL-4929

---

src/BloomBrowserUI/publish/android/androidPublishUI.tsx
src/BloomBrowserUI/react_components/progressBox.tsx
src/BloomBrowserUI/utils/WebSocketManager.ts
src/BloomExe/Publish/Android/AndroidView.cs
src/BloomExe/Publish/Android/wifi/BloomReaderUDPListener.cs
src/BloomExe/web/BloomWebSocketServer.cs

With this commit, users of WebSocketManager have to supply a socket name. The ability to send a message that closes down a named socket is retained, but is not currently used as it did not appear to have any measurable effect, for good or ill. 
On the c# side, we now close sockets instead of just removing them from a list. 
For ease in debugging, on both sides, socket names are now available, by hijacking the "subprotocol" field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1832)

Simplify the WebSocket management system

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/Edit/AudioRecording.cs
src/BloomExe/HelpLauncher.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/ReadersApi.cs
src/BloomExe/web/RequestInfo.cs
src/BloomExe/web/controllers/AddOrChangePageApi.cs
src/BloomExe/web/controllers/ApiRequest.cs
src/BloomExe/web/controllers/BookSettingsApi.cs
src/BloomExe/web/controllers/ExternalLinkController.cs
src/BloomTests/PretendRequestInfo.cs
src/BloomTests/web/controllers/EndpointHandlerTests.cs

The problem was that the c# reply to the POST did not contain any text (not even an "OK"). I don't know why it should, actually. But without that, the JS POST eventually throws the error we were seeing in BL-4901.
In order to prevent this error in the future, I have renamed 2 of the methods so that it will be clear which one to use:
request.SucceededDoNotNavigate() --> request.ExternalLinkSucceeded()
request.Succeeded() --> request.PostSucceeded()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1833)

Fix BL-4901

---

src/BloomExe/Publish/Android/PublishToAndroidApi.cs

It doesn't even compile on Linux without this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1854)

Fix Linux portability problem with clipboards

---

src/BloomExe/web/BloomWebSocketServer.cs

This was happening every time on Linux.  I don't know about the
Windows behavior, but the fix should be safe everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1855)

Fix a green dialog crash on closing after publishing to Android

---

src/BloomExe/Edit/EditingView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1856)

Fix a crash parsing Zoom when opening a book (BL-5045)

---

src/BloomExe/ImageProcessing/ImageServer.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/RequestInfo.cs
src/BloomExe/web/controllers/ApiRequest.cs
src/BloomTests/PretendRequestInfo.cs

Caching of images was not playing well with
resizing of images
* Removed one unused method
* Changed all cache-related paths to use fwd slashes
* When resizing images, used the original path to
decide whether to cache or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1862)

BL-5013 Update CC icon on license change

---

src/BloomExe/UrlPathString.cs
src/BloomExe/web/EnhancedImageServer.cs
src/BloomTests/PretendRequestInfo.cs

Apparently some processing have moved from javascript to C#.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1866)

Fix problem with odd characters in book names (BL-5037)

---

src/BloomExe/Book/Book.cs
src/BloomExe/web/ServerBase.cs

This is a follow-on fix for the fix of BL-5050.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1868)

Fix failing tests and bad program behavior when missing files

---

build/getDependencies-Linux.sh

At least in some circumstances, SIL.Windows.Forms won't load under Mono
without this dependency present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1870)

Add Enchant.Net.dll to download dependencies on Linux (BL-5062)

---

src/BloomExe/CollectionTab/LibraryView.Designer.cs

This should be safe for Windows, but I have no way to test it at the
moment.  Flow style layout engines in Mono are notoriously less capable
than in .Net.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1874)

Fix misplaced buttons on Linux (BL-5043)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/XMatterHelper.cs

These operations fail on Linux and on Windows when installed --allUsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1872)

Prevent copying/deleting files in template books (BL-5061)

---

DistFiles/localization/en/Big Book/ReadMe.xlf
DistFiles/localization/en/Decodable Reader/ReadMe.xlf
DistFiles/localization/en/IntegrityFailureAdvice.xlf
DistFiles/localization/en/Leveled Reader/Readme.xlf
DistFiles/localization/en/MissingLameModule.xlf
DistFiles/localization/en/Picture Dictionary/ReadMe.xlf
DistFiles/localization/en/Template Starter/ReadMe.xlf
DistFiles/localization/en/TrainingVideos.xlf
DistFiles/localization/en/Wall Calendar/ReadMe.xlf
DistFiles/localization/en/bloomEpubPreview.xlf
DistFiles/localization/en/leveledReaderInfo.xlf

This was recommended by the crowdin technical support to ensure that
crowdin produces valid xliff 1.2 files.
This set of files was generated by HtmlXliff during the build process.  A separate checkin will be needed
for the Bloom.xlf and Palaso.xlf files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1879)

Add target elements to xliff files extracted from HTML

---

src/BloomExe/BloomExe.csproj
src/BloomExe/BloomWebClient.cs
src/BloomExe/UpdateVersionTable.cs
src/BloomExe/WebLibraryIntegration/LoginDialog.cs
src/BloomTests/UpdateVersionTableTests.cs

On my developer machine, triggering the captive portal code results in a Yellow screen error that the user can "Continue" from. If I understand the NonFatalProblem.Report() params correctly, on a Beta or higher release it would just "toast".
This only handles the version upgrade case, unfortunately there are several other areas where Bloom accesses the internet that are not handled here.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1869)

BL-5056 Handle captive portal better

---

src/BloomExe/Program.cs
src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1890)

Remove ability for user to launch L10NSharp dialog (BL-5111)

---

.editorconfig
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/BookInfo.cs
src/BloomExe/CLI/UploadCommand.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/PublishView.Designer.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookTransfer.cs

This PR consists of 3 commits:
1 - Andrew's unsubmitted work for uploading Bible Storying Videos
2 - My work to get it creating pdfs and tagging with bookshelf name
3 - Making the process restartable
This is a command line addition to Bloom that I run from a 1 line .bat
file. Bloom needs to be called with "upload" verb, optional flag to
exclude audio files (--excludeAudio or -x), path of directory tree to
upload (e.g. K:\EnablingWriters).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1892)

BL-5087 Add bulk upload capability

---

debian/control
environ

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1901)

Fix Linux Bloom 4.0 to use new libtidy-sil package (BL-4988)

---

.gitignore
DistFiles/localization/README.md
src/BloomExe/BloomFileLocator.cs
src/BloomTests/UpdateVersionTableTests.cs

Also add a couple of (helpful?) comments to tests and tweak the document
describing our localization process to describe corner case of leading or
trailing whitespace changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1906)

Restore proper handling of translated .txt files

---

DistFiles/IntegrityFailureAdvice-es.md
DistFiles/infoPages/TrainingVideos-es.md
DistFiles/leveledRTInfo/leveledReaderInfo-es.pug
src/BloomBrowserUI/ePUB/MissingLameModule-es.pug
src/BloomBrowserUI/ePUB/bloomEpubPreview-es.pug
src/BloomBrowserUI/help/Publish-Android-Troubleshooting-es.md
src/BloomBrowserUI/templates/template books/Big Book/ReadMe-es.md
src/BloomBrowserUI/templates/template books/Decodable Reader/ReadMe-es.md
src/BloomBrowserUI/templates/template books/Leveled Reader/ReadMe-es.md
src/BloomBrowserUI/templates/template books/Picture Dictionary/ReadMe-es.md
src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-es.md
src/BloomBrowserUI/templates/template books/Wall Calendar/ReadMe-es.md

The translations are backported from the crowdin xliff files on the master
branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1908)

Add Spanish translations of md and pug files

---

src/BloomExe/BloomFileLocator.cs

LocalizationManager.UILanguageIdThe UILanguageCode may be something like
"es-ES" when the translated xliff file may use only "es" in its pathname.
This appears to be an artifact of how Crowdin treats some languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1914)

Find xliff files with bare language codes

---

src/BloomExe/web/controllers/BrandingApi.cs

I think this is the proper fix for the Debug messages complaining about books using the branding api.
It ignores the Debug.Fail check for the same set of books that are ignored in CleanupBrandingImages() in Book/XMatterHelper.cs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1922)

Don't complain about branding api for template books (BL-5139)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Collection/CollectionSettingsDialog.cs

* add some missing xmatter items to xlf
* enable l18n of 'branding' names - C#
(but only activate l18n of 'Default') - .xlf
* enable l18n of 'Android' button tooltip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1927)

BL-5128 Localization tweaks

---

build/getDependencies-Linux.sh
build/getDependencies-windows.sh
src/BloomBrowserUI/gulpfile.js
src/BloomExe/BloomExe.csproj
src/BloomExe/BloomFileLocator.cs
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config

This happens after they are created by markdown or pug processing.
This requires that HtmlAgilityPack be pulled from TeamCity as an artifact of XliffForHtml/HtmlXliff
instead of being downloaded as a nuget package so that HtmlXliff.exe can be run before the
nuget packages are downloaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1928)

Translate HTML files during the gulp build process (BL-5189)

---

DistFiles/localization/pt/Bloom.xlf
src/BloomBrowserUI/gulpfile.js
src/BloomExe/Book/BookStarter.cs

Also enhance error message to include filenames and remove duplicate
entry from Portuguese Bloom.xlf.  (duplicate not in English)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1930)

Fix error in translating HTML files

---

src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Workspace/WorkspaceView.cs

1) displaying zh-CN in language menu as Chinese (Simplified) in the
English portion of the display name
2) fix C# typo in string Id specification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1938)

Fix minor L10n problems

---

src/BloomExe/Book/BookStorage.cs

This fix makes an existing situation self healing as far as I can tell.
When a user tries to edit the existing book, a yellow crash dialog
showing REPLACEMENT characters where NBSP existed pops
up, and the page to edit does not display.  If the user then goes
back  to the Collection tab and tries to edit the book again, it
succeeds, and the directory name has been fixed on the disk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1950)

Fix bug with trailing non-breaking space in folder name (BL-5212)

---

src/BloomBrowserUI/gulpfile.js
src/BloomExe/Book/Book.cs

This also ensures that the markdown output is a complete HTML file, not just a
fragment when being displayed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1956)

Mark html from markdown as being in utf-8 encoding (BL-5256)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/react_components/progressBox.tsx
src/BloomExe/Publish/Android/AndroidView.cs
src/BloomExe/Publish/Android/usb/UsbPublisher.cs
src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
src/BloomExe/web/BloomWebSocketServer.cs
src/BloomExe/web/WebSocketProgress.cs

Note that this doesn't affect the "Save Bloom Reader File" option for
publishing to Android.
I also fixed an alphabetization glitch in the Bloom.xlf file.  Note that
changing the order of trans-unit elements does not affect any of the
translations on crowdin except for matching reordering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1962)

Warn user about wrong layout for Android publishing (BL-5274)

---

debian/README
debian/bloom-beta
debian/bloom-beta.appdata.xml
debian/bloom-beta.desktop
debian/changelog
debian/control
debian/copyright
debian/install
debian/rules

This is needed for making Version4.0 the official beta on Linux.
DO NOT MERGE THIS TO master!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1974)

Rename package for Version4.0 to bloom-desktop-beta

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/BloomExe.csproj
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs
src/BloomExe/Program.cs

* Windows Defender update in October 2017 added a
'feature' called Controlled Folder Access that causes problems
when saving CollectionSettings in Documents folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1960)

BL-5243 Detect and inform about Defender

---

src/BloomExe/Collection/CollectionSettings.cs

Moved the Defender protection check to AFTER we've created the directories we're testing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1976)

BL-5243 fix failing tests when creating new collection

---

src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
src/BloomBrowserUI/templates/xMatter/Device-XMatter/description-en.txt

Do not merge until the main part of BL-5312 is merged.
The main part of BL-5312 will delete these if they are empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1980)

Add usually-empty pages back into device xmatter

---

debian/control
environ

THIS SHOULD NOT BE MERGED INTO Version4.0 OR master!
Both files in this change are Linux specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1992)

Backport the Linux fix for private SIL tidy library version

---

src/BloomBrowserUI/publish/android/androidPublishUI.tsx
src/BloomExe/Book/BookCompressor.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/web/controllers/ApiRequest.cs

Now produced the requested thumbnail size
Now centers cover image
Shows actual thumbnail in publish instead of an html simulation
Heuristic to frame line art (actually just pngs) differently than full color (actually just jpgs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2012)

Fix bloomd thumbnails & give wysiwyg preview in publish BL-5346

---

.gitignore
DistFiles/ghostscript/Readme.htm
DistFiles/ghostscript/agpl.txt
src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs

In case we have to stop shipping it, enforce at least version 9.18
before using it in processing.  We know 9.18 works (on Linux) and 9.16
fails (on Windows).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2034)

Use our internal gswin32c.exe (9.21) for ghostscript processing

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Edit/EditingView.cs

* in a locked book, the message now matches
the new page controls for unlocking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2046)

Fix page re-ordering message

---

src/BloomExe/web/BloomWebSocketServer.cs

* sometimes 'socket' is generating an "Object ref
not set to an instance" error even though closed
sockets are supposed to delete themselves
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2054)

BL-5390 fix some socket timing problems

---

src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug
src/BloomExe/Book/Book.cs

* page-cover mixin assumed frontMatter, whereas
we want Inside Front Cover to be backMatter in
Device
* having both front and backMatter classes
messed up the page reordering mechanism
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2089)

Fix ambiguous definition in Device xmatter

---

DistFiles/localization/es/Bloom.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2102)

Fix missing non-breaking space in Spanish ReaderSetup.PoweredBy (BL-5300)

---

src/BloomExe/CollectionTab/LibraryView.Designer.cs

* Some "Make a BloomPack" localizations needed
more room (e.g. Spanish)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2100)

[4.0] BL-5470 Make more room for button

---

DistFiles/localization/ha/Bloom.xlf

One string in one file had already been approved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2105)

Fix an xliff file that I broke when approving everything

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Program.cs
src/BloomExe/Workspace/WorkspaceView.cs

Also prevent displaying languages with no localization at all.
Note that this is on Version4.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2099)

Provide user feedback on localization quality (BL-5472)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/IntegrityFailureAdvice.xlf

Two duplicated trans-unit elements and one &amp; that had become
&amp;amp;.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2109)

Remove unwanted duplication in English xliff files

---

src/BloomBrowserUI/ePUB/baseEPUB.less

This approach shouldn't be as experimental, but seems to work just
as well in the emulator and Gitden readers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2130)

Another fix for ePUB branding with multiple images (BL-5495)

---

DistFiles/localization/es/Bloom.xlf
src/BloomExe/Edit/EditingView.Designer.cs

Also approve a pair of Spanish translations that only changed the inter-word spacing to remove a newline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2131)

Fix button label word wrapping (BL-5506)

---

src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx

This is needed for Bloom to build on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2138)

Fix case problem for Linux in new code

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/web/controllers/ImageApi.cs

Also remove a pair of redundant units in Bloom.xlf while adding a new
unit to that file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2147)

Show page number of images with missing credits (BL-5466)

---

src/BloomExe/CollectionCreating/NewCollectionWizard.cs
src/BloomExe/MiscUI/LanguageFontDetails.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs

I don't know that integer parsing is affected much by the culture
setting for simple integer values (optional sign followed by digits).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2152)

Ensure proper floating point parsing throughout Bloom (BL-5579)

---

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2155)

Display translations first in hint/source bubbles (BL-5420)

---

DistFiles/localization/en/IntegrityFailureAdvice.xlf
DistFiles/localization/en/bloomEpubPreview.xlf
src/BloomBrowserUI/gulpfile.js

It might be worth cherry-picking this at least to Version4.1 to reduce annoyance to programmers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2156)

Preserve generated xliff files better when building Bloom

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/ScriptSettingsDialog.cs

These specifically affect line-height settings from the Collection
Settings dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2163)

More tweaks to floating point/decimal conversions (BL-5579)

---

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug

This was broken back in 3.9, I think.  Let's test it in 4.1 then cherry pick to 4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2169)

BL-5489 Cover credits should be centered.

---

src/BloomExe/WebLibraryIntegration/BookTransfer.cs

* that was pretty easy!
* We download a book as a collection of s3 objects. Cancelling can happen between
any 2 objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2174)

BL-2235 Allows cancelling download

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStarter.cs

* When a shell book has an <img> tag in the data div
(see BL-4586), making a new book will have a
problem without this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2203)

[4.1]BL-5620 Fix Big Book problem

---

src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx

These two filename capitalization problems seem to be behind two
different Linux errors, one of them a strange crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2215)

Fix problems with react on Linux (BL-5640,BL-5648)

---

build/getDependencies-Linux.sh
build/getDependencies-windows.sh

Getting it this way ensures compatibility between libpalaso and Bloom
in using this adapter.  Libpalaso obtains its copy via nuget.  The
adapter is needed now for using the master branch of libpalaso.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2217)

Get DialogAdapters.dll from libpalaso for image file chooser (BL-5541)

---

src/BloomTests/Collection/CollectionSettingsTests.cs

The new language id processing in L10nSharp maps onto the simple language
id without the country code needed for Spanish and Portuguese.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2223)

Fix failing tests caused by BL-5479 fix

---

crowdin.yml

I think I have the right syntax here.
See https://support.crowdin.com/configuration-file/#language-mapping (and examples later in the page).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2229)

Preserve zh-CN in file/folder names of translated xliff

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/templates/template books/Multimedia/Multimedia.pug
src/BloomExe/Browser.cs

* Fixed Talking Book Tool and Comprehension Quiz
so that the contents are not recordable
* fixed TBT so Record is not active on 1st page
display if no recordable divs (part of BL-5457)
* added bloom-userCannotModifyStyles to comp
question translationGroup
* made paste in context of userCannotModStyles
only paste text (no html)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2234)

[4.1]BL-5575 Comprehension Quiz

---

src/BloomExe/Book/BookCopyrightAndLicense.cs

The following fields now handle line breaks better:
* Copyright holder
* Custom license notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2238)

[4.1]BL-5700 line breaks in metadata dialog

---

src/BloomTests/Book/BookCompressorTests.cs

The offending using statement wasn't even used by Windows!
Linux/Mono does not have a System.Windows.Media assembly or namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2240)

Fix a failing build on Linux (20180302)

---

src/BloomTests/Publish/MockUsbPublisher.cs
src/BloomTests/Publish/UsbPublisherTests.cs

USB publishing has not yet been implemented for Linux/Mono.
The UsbPublisher class is totally disabled from even compiling,
so its tests should be as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2267)

Disable UsbPublisherTests for Linux/Mono.

---

src/BloomTests/Publish/MockUsbPublisher.cs
src/BloomTests/Publish/UsbPublisherTests.cs

I believe the TearDown method from one test was running during the other test and messing up the state. I've set the class to STA apartment type (there's only 2 tests).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2268)

Fix (hopefully) failing UsbPublisher tests

---

build/getDependencies-Linux.sh
debian/install

The new libpalaso build system for Linux produces pdb files instead of mdb files.
I regenerated build/getDependencies-windows.sh and it didn't change at all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2277)

Fix Linux packages for handling libpalaso changes

---

src/BloomExe/web/controllers/ImageApi.cs

Version4.2 cleans this up somehow, but Version4.1 throws an error and
fails to display the image file tooltip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2281)

Handle image filenames stored doubly UrlEncoded (BL-5757)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts

* Make sure that "getRecordableDivs()" actually
returns divs with text in them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2265)

BL-5457 Talking Book Tool activation

---

src/BloomExe/Publish/Android/usb/UsbPublisher.cs
src/BloomTests/Publish/MockUsbPublisher.cs
src/BloomTests/Publish/UsbPublisherTests.cs

* Try 4 should do it, since I can now test it!
* The temp .bloomd file was getting deleted before I recorded the size
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2289)

[4.1]BL-5710 Not enough space

---

src/BloomExe/Publish/Android/usb/AndroidDeviceUsbConnection.cs
src/BloomExe/Publish/Android/usb/UsbPublisher.cs
src/BloomTests/Publish/MockUsbPublisher.cs
src/BloomTests/Publish/UsbPublisherTests.cs

* moved new methods down to more logical place
* renamed IsDiskFull -> IsDeviceFullOrHung
* added Win Portable Devices code for Hung device
0x802A0006
* reworked tests to remove test interdependence
(hopefully TC will run them okay now)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2298)

[4.1]BL-5710 Device full error rework

---

src/BloomExe/BloomExe.csproj

It doesn't appear in the windows build process at all.  This is needed
for building on the next version of Linux (bionic), which comes out next
month.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2304)

Remove icu.net.dll from Linux build process

---

ReadMe.md
build/npm-build.sh
debian/rules
src/BloomBrowserUI/.npmrc
src/BloomBrowserUI/package.json

This merge requires the affected TeamCity builds to switch to using node 8.10.0 before it will build on them.  The packaging builds on Jenkins will build okay since the code checked in here changes that behavior for those builds.
The new package-lock.json may or may not need to be checked in.  The discussion about it was not unanimous by any means.
Do not merge this if you aren't will to modify the TeamCity builds.  Of course, if you don't modify those builds first, how will you know it works?  We have a chicken and egg problem in one sense...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2313)

Update node.js to 8.10.0, the latest LTS version (BL-5777)

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs

Also force restart when you change the numbering.
Currently requires a custom font rule to actually see the numbers:
/* Required for Bloom version 4.1 to show page numbers in Chakma */
.numberedPage::after{
font-family: "RibengUni";
}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2323)

BL-5844 Add chakma page numbering

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

* was due to not updating the data-i18n attribute
* another possible solution would be to delete the
attribute when changing the page label on the 
premise that we don't want to try localizing random
template page labels from the user... but we might
want to and they may change it back to something
we already know how to localize.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2331)

[4.1]BL-5855 Prevent forgetting page label change

---

src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx
src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
src/BloomBrowserUI/tslint.json

Suggestion: read one commit at a time
Since this was pointed to as perhaps the cleanest example so far, I spent some hours with it seeing how clean I could get the structure of it, so that it can serve as a model.
Not 100% satisfied, got stymied by some typescript limitations. Also didn't take on the sort of.... unneeded extra layer of the thing that implements ITool. Did minimize it in the case of MusicTool (now MusicToolAdaptor). Tried to clarify that this extra layer is just really, ideally, and "adaptor" becuase some of the complexity I saw in the reader tools was that so much responsibility was spread across the adaptor and the component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

BL-5899 Refactor MusicControls

---

src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx

Why the conventions for filenames and class names are different in js/ts
land is beyond me.
This is needed to get things to build on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2340)

Fix a pair of filename capitalization problems (20180413)

---

src/BloomExe/web/I18NHandler.cs

* I18NHandler already didn't bother with template
page labels and such in "translate" mode
* extend this behavior to "loadStrings" mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2343)

[4.1]BL-5855 Tell handler not to do TemplateBooks

---

src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx

The dimming approach that the code had, it still has, so things aren't *actually* disabled, but I didn't attempt to fix that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2347)

Fix BL-4898 remove extra notice & dim in all disabled situations

---

src/BloomExe/CollectionTab/LibraryView.cs

This may look like a hack, but it works and is the only solution that
I've come up with after 2+ days of looking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2348)

Tweak GTK file chooser usage on Linux to ensure focus (BL-5809)

---

src/BloomBrowserUI/bookEdit/toolbox/panAndZoom/panZoomToolControls.tsx

This refers to dragging the rectangles around when the page is either
zoomed in or zoomed out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2350)

Contain the motion rectangles properly when zoomed (BL-5768)

---

.gitignore
src/BloomExe/Book/BookStorage.cs
src/BloomExe/web/EnhancedImageServer.cs

In BL-5824, we got bit by a design decision we made that allows stylesheets installed via bloompack to override local ones. This was done so that we could send out new custom stylesheets via webpack and have those used in all the books. Fine. But that is indiscriminate; it also was grabbing any "customBookStyles.css" from those sources and using it instead and replacing that of your book.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2332)

Fix BL-5824 which was using bloompack-installed customBookStyles instead

---

src/BloomTests/Publish/ExportEpubTests.cs

The excluded test passes, but strange GTK errors it causes prevent TeamCity from calling it successful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2353)

Exclude test on Linux that causes crash (BL-4867)

---

src/BloomTests/Publish/ExportEpubTests.cs

SIL.BuildTasks has been updated to handle the bogus error messages
this test puts out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2356)

Restore test excluded on Linux yesterday

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/HtmlDomTests.cs

* left over from when the Talking Book tool
allowed recording these pages
* adds 2 classes that are needed
* only preserves div, p, and br tags in quizContents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2357)

[4.1]BL-5910 Repair Quiz pages

---

src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/CollectionCreating/LanguageIdControl.cs

* Bloom side
* update LanguageIdControl and
Collection Settings dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2362)

BL-5736 Enable Variants and Scripts

---

src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/BookStorage.cs

* removes curly braces from filename, but leaves
them in the displayed/printed title
* also removed an unused parameter in BookStarter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2370)

[4.1]BL-5940 Fix curly brace issue

---

src/BloomBrowserUI/bookLayout/bookFeatures.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2374)

Display cover image properly for Motion Books (BL-5770)

---

src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/Publish/Android/file/FilePublisher.cs
src/BloomExe/Publish/PublishModel.cs

This may have been an oversight when we changed to using Gtk file
dialogs on Linux.  Two of six places had this already.  (One of
these changes is in essentially dead code.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2379)

Ensure checking for overwrites on file saves

---

src/BloomBrowserUI/templates/template books/Special/Special.pug

* made it language agnostic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2382)

BL-5886 Fix Translation Instructions page

---

src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxPanel.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

* added a newPageReady() to ITabModel
* commented ITabModel Interface
N.B. This will be a breaking change to 4.2+ when merged upstream because of the addition to ITabModel.
(But easy to fix.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2384)

[4.1]BL-5963 reactivate audio level

---

src/BloomBrowserUI/templates/template books/Picture Dictionary/Picture Dictionary.pug

* only if we created the book with Pict Dict template
* kluge: added an extra copy of template page
(different Guid) that has data-page='extra'
* removed pages from template that are already
in Basic Book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2391)

[4.2]BL-5842 Allow Picture Dict page in AddPage

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

* Awhile back I sorted the word spacing options.
That caused problems selecting options and seems
less of a natural progression in this case.
* Keep localized values, but don't sort them in this
case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2400)

[4.2]BL-5956 Word Spacing fix

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Publish/PublishView.Designer.cs

* there are 2 items that should be localized
** PublishTab.SaveButton
** PublishTab.SaveEpub
* we just make sure the L10NSharpExtender uses
one of these (they actually get set elsewhere)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2402)

[4.2]BL-5931 Fix Publish - SaveButton l18n

---

src/BloomExe/Publish/PublishView.cs

* cause it to be centered in PublishView, instead of
(maybe) on the other screen in case of multiple
monitors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2405)

BL-5015 Fix location of print settings dialog

---

src/BloomExe/Publish/PublishView.cs

* caused by refactor of SetDisplayMode() a few days
ago
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2408)

BL-6001 restore sample print settings

---

src/BloomBrowserUI/ePUB/baseEPUB.less
src/BloomExe/Publish/Epub/EpubMaker.cs

These changes were suggested by looking at the standard Moby Dick
test ePUB.  They do seem to make a big difference in some readers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2438)

Enhance ePUB output for mp3 recordings (BL-6018)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

* Word Find had bloom-userCannotModifyStyles
on a table element several layers above the
bloom-translationGroup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2437)

BL-6023 Fix Story Primer Word Find js errors

---

src/BloomExe/XmlHtmlConverter.cs

* valid html uses < br >, which isn't valid xml
* I had wanted to be able to validate the .htm files with Notepad++ xml validation...
apparently not a good idea here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2443)

Revert "fix" to br tags

---

src/BloomExe/Publish/AudioProcessor.cs
src/BloomTests/Publish/ExportEpubTests.cs

We need to find a way to calculate audio file duration on Linux!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2448)

Fix tests failing on Linux (20180531)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.js

* we were checking for 'b', but not 'strong' tags
* better add 'sup' for superscript
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2460)

BL-6038 Char styling fix for Talking Book

---

src/BloomExe/Publish/Epub/EpubMaker.cs

The title attribute is actually on the parent div, not on the img element itself.  Oops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2461)

Bl 6035 remove title attribute rework

---

debian/rules

When building the debian package we need to install SIL.BuildTasks* first
before setting the assembly version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2474)

Fix package build

---

src/BloomBrowserUI/publish/epub/baseEPUB.less

The file must have moved recently.  This allows the build to succeed and
tests to run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2486)

Fix imports in baseEPUB.less

---

src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.less
src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
src/BloomExe/Book/AccessibilityCheckers.cs
src/BloomExe/web/controllers/AccessibilityCheckApi.cs
src/BloomTests/Book/AccessibilityCheckersTests.cs

* Filter out help bubbles
* Filter based on visibility-on instead of @lang
* Send back the text that was not recorded
* (to enable the above, switch from a simple string to a problem structure)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2493)

BL-6095 Round 2, CheckAudioForAllText

---

src/BloomExe/Publish/Epub/EpubMaker.cs

The new progress reporting may have slowed it down just enough for this
problem to surface on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2502)

Fix broken Linux epub generation (20180615)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Collection/BookCollection.cs
src/BloomExe/CollectionTab/LibraryModel.cs

* fixed a couple of typos
* cached PathToExistingHtml
* books with only .bak file will now show in collection
* when such a book is selected,
ExpensiveInitialization will try to restore the backup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2498)

BL-6099 Use .bak if .htm is missing

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/CollectionTab/LibraryModel.cs

* added an inline style attribute to each editable div
turning display on or off depending on whether
it had bloom-visibility-code-on or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2507)

BL-5998 Fix text visibility in Export to Word

---

src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
src/BloomBrowserUI/publish/accessibilityCheck/accessibilityChecklist.tsx
src/BloomBrowserUI/publish/accessibilityCheck/checkItem.tsx
src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.less
src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
src/BloomBrowserUI/publish/epub/epubPublishUI.tsx
src/BloomBrowserUI/react_components/link.tsx
src/BloomBrowserUI/react_components/progressBox.tsx
src/BloomExe/Publish/Android/usb/UsbPublisher.cs
src/BloomExe/Publish/Android/wifi/WiFiAdvertiser.cs
src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Publish/Epub/PublishEpubApi.cs
src/BloomExe/web/WebSocketProgress.cs
src/BloomExe/web/controllers/AccessibilityCheckApi.cs
src/BloomExe/web/controllers/ApiRequest.cs
src/BloomTests/Book/BookCompressorTests.cs

Also:
Added a manual refresh button
Simplified state down to just the report, since we can use progress for everything else.
Expanded but simplified error reporting when trying to find and run node/npm/ace-by-daisy.
Make web socket message be able to have a simple message  without parameters.
normalized the order of arguments in these websocket messaging.
Changed the localization id parameter from "id" to "idSuffix" to help us remember that in this context, some parent has already set up most of the id.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2505)

BL-6117 Let Ace-by-Daisy checker make its own epub as needed

---

src/BloomExe/app.config

The fix targets .Net 4.7 which we don't use in Bloom.  It doesn't work on
Windows and it crashes the program on Linux.  (See the Remarks section in
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/winforms/.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2513)

Back out dysfunctional high DPI fix

---

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx

Somehow this part of the fix a couple of days ago did not last.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2517)

Fix display of Import Video button. Again. (BL-5871)

---

src/BloomExe/Book/BookStarter.cs

* BookStarter rips out 'extra' pages and xmatter,
leaving nothing from a template to remember the
template's layout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2526)

BL-6108 Make Book remember template layout

---

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less
src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx

* just adding a 'disabled' class doesn't disable mouse
events on an element
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2537)

BL-6137 Import (and others) disable during recording

---

src/BloomExe/CollectionTab/LibraryListView.cs

* I found this condition occurred from time to time
when doing a lot of quick duplicating of pages and
moving from book to book. (testing BL-6100)
* It's not too serious as it only green screen's on
a Debug build, but hey, might as well stop it from
throwing an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2545)

Fix thumbnailer problem

---

src/BloomBrowserUI/react_components/link.tsx

* normal link UI (pointer cursor and underscore)
go away if 'href' is undefined on Link
* but putting in href="dummy" causes an error
when the image server can't find a file "dummy"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2547)

BL-6130 Fix Ally Checker link

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/web/controllers/ImageApi.cs
src/BloomTests/web/controllers/ImageApiTests.cs

* instead of returning a page label, will return a
data-book name (e.g. 'bishmallah')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2546)

BL-6167 Img tag in datadiv kills Paste Credits

---

src/BloomExe/Edit/EditingView.cs

I don't know why the Gecko-based text box was thought to be "needed" by
Linux.  But it is entirely too unreliable on Ubuntu 18.04 with Gnome, the
new default windowing system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2574)

Adjust Image Toolbox dialog for Linux (BL-6126)

---

src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx

* the switch from updateMarkup() to newPageReady() in the ITool
interface was implemented incompletely in Music Tool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2600)

[v4.2]BL-6235 Fix Music tool newPageReady()

---

src/BloomBrowserUI/bookLayout/textOverPicture.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2602)

Fix BL-6267 textOverPicture.less, broken by BL-4972

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/img/importVideoButtonOverlay.svg
src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
src/BloomExe/Edit/EditingView.cs

I also joined up the previously separate "Change Video" and "Import Video" strings, removing the former from the English tsx.
Also changed the name of the icon to help differentiate it from the one on the toolbox.
This will probably need special attention merging into 4.4/master as image files have moved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2619)

Fix BL-6135 Video import button on frame doesn't match Bloom UI

---

src/BloomExe/Edit/EditingView.cs

Saving the page removes any tool's HTML from the book's page.  It needs
to be restored for seamless operation between the main window and the
a11y checking window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2630)

Ensure image description tool stay open for a11y checking (BL-6228)

---

src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
src/BloomBrowserUI/images/ImageDescriptionImageOverlayButton.svg

Since we had something similar for the sign language tool, this also refactors that to use common code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2633)

BL-6232 Adds overlay button to open image description tool

---

src/BloomBrowserUI/publish/accessibilityCheck/accessibilityCheckScreen.tsx
src/BloomExe/Book/Book.cs
src/BloomExe/CLI/ChangeLayoutCommand.cs
src/BloomExe/CLI/HydrateBookCommand.cs
src/BloomExe/Event.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/web/controllers/AccessibilityCheckApi.cs

1) title wasn't updating because the needed websocket event parameter changed (message --> id).
2) the checklist wasn't  auto-refreshing anymore. Created a new BookSaved event to wire to, rather than messing with the use or semantics of the existing BookRefresh event (started down the road, got very odd errors, repented).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2638)

BL-6291 A11y Checker updates

---

src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2682)

Fix metadata editable text fields to show text properly (BL-6350)

---

src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
src/BloomBrowserUI/publish/metadata/SubjectTreeNode.ts
src/BloomExe/Publish/Epub/EpubMaker.cs

This may be Linux-specific behavior.  I haven't tested Windows to see
if these crashes occur there.  The fix should be safe in any case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2694)

Prevent null dereferences in recent metadata code (BL-6178)

---

src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/web/controllers/AccessibilityCheckApi.cs

The real bug is in the ACE code, but this works around it until they
fix their code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2723)

Fix crash in ACE by Daisy checker for bilingual books (BL-6426)

---

src/BloomBrowserUI/bloomUI.less
src/BloomBrowserUI/react_components/l10n.tsx
src/BloomExe/web/controllers/CommonApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2724)

Show untranslated TSX strings in red, not grey (BL-6422)

---

debian/control

THIS SHOULD NOT BE MERGED TO Version4.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2751)

Add gtk-sharp4-sil as dependency for Bloom 4.2

---

debian/control

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2754)

Add gtk-sharp4-sil as dependency for Bloom 4.3

---

src/BloomBrowserUI/bookLayout/basePage.less
src/BloomBrowserUI/bookLayout/device.less
src/BloomBrowserUI/templates/template books/Special/Special.less

* allow scrolling on instructions panel
* reduce padding to give more room on device layouts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2759)

BL-5526 Comprehension Questions css

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2766)

Remove (un)decodable markup when closing tool (BL-6485)

---

src/BloomBrowserUI/bookLayout/device.less

I don't know how to enable PictureStoryLandscape to test still having the white background there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2771)

Remove white background for Device16x9Landscape (BL-6496)

---

src/BloomBrowserUI/themes/bloom-jqueryui-theme/jquery-ui-dialog.custom.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2791)

Fix focus display for jquery dialogs to match React dialogs (BL-6504)

---

src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx

* now user must use OK or Cancel buttons, or hit Esc
to close the dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2799)

[4.4]BL-6561 Don't close ePUB metadata dlg on click

---

src/BloomBrowserUI/pageChooser/page-chooser.ts
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs

* get change layout to count only textboxes that
are not inside of imageContainer divs.
* no longer loses text when text over picture is present
* also won't lose text when image description is added
in 4.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2775)

[4.3]BL-6512 Fix textbox count for change layout

---

src/BloomBrowserUI/react_components/l10n.tsx

This reverts what I thought was an innocuous change last week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2803)

Fix broken Sign Language tool display (BL-6569)

---

src/BloomExe/Book/Book.cs

Note that this fix is originating on Version4.3 as requested.  It looks safe to me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2804)

Fix missing video pages in Bloom Reader (BL-6571)

---

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/react_components/l10n.tsx

The problem was that the newly added tool was looking for the alphabetically correct place to live, but was looking not just at the tool headers, but also their contents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2812)

Fix Bl-6569 Toolbox loads tool contents into header

---

src/BloomTests/UpdateVersionTableTests.cs

These are now failing on TeamCity as well as my local Linux machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2816)

Exclude Windows-specific tests that often fail on Linux

---

debian/rules

Something which used to just report an error now causes a crash.

Fix Linux package build on master (20181022)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts

Fixes a problem where a book has audio recorded in 4.3, and is then loaded it in 4.4 while the collection default was set to TextBox.   The book will now correctly detect the pre-existing mode. Previously the wrong mode was detected and the existing audio would not play
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2829)

Fix Forward compatibility for narration audio (BL-6559)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts

When the talking book tool is closed/switched to a new tool, it previously maintained its state. When it reopened, the state was no longer valid. now we cleanup the state when the tool is closed.
Also, this exposed a problem where it was never looking up the collection default setting, so I fixed that too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2835)

Fix invalid state for Talking Book after changing tools (BL-6655)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

Note that sight words not found in the sample text will now sort at the
end of the frequency list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2837)

Sort sight words found in sample texts by frequency properly (BL-6264)

---

src/BloomBrowserUI/bookEdit/js/bloomFrames.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/utils/WebSocketManager.ts

1) try to ensure .ui-audioCurrent highlight doesn't get overwritten
2) Prevent an easily reproducible case where Talking book navigation can get stuck
3) Reduce visual flash from elements getting disabled/enabled rapidly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2839)

Fix issue where audioCurrent highlight disappears (BL-6654)

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs

Previously, the  model's username was not updated after interaction with the login dialog box. Now it stays up to date.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2847)

Fix Publish to Web - keep username up to date (BL-6275)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/BookStorageTests.cs

Also refer to comments from https://github.com/BloomBooks/BloomDesktop/pull/2851
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2855)

Check for breaking features: Write version requirement to book (BL-6661)

---

DistFiles/localization/en/BloomMediumPriority.xlf

I don't know if this note will show up in crowdin, but it's the best
we can do.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2858)

Add note to BloomMediumPriority.xlf to say it's not yet in use (BL-6539)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/ReadersSynphonyWrapperSpec.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/directoryWatcher.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/jquery.div-columns.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools_libSynphonySpec.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxSpec.ts
src/BloomBrowserUI/tslint.json

This is the final set of files, including the change to tslint.json to
detect places where arrow functions should be used.  Note that tslint
ignores function declarations whose body already uses a this variable
different than the this in the outer scope.  These places may warrant a
second round of fixes, but will require much more thought and care.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2873)

Update TS to use arrow functions, part 3 (BL-6401)

---

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowSpec.ts
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditorSpec.ts
src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts
src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
src/BloomBrowserUI/bookEdit/editablePage.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.ts
src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts
src/BloomBrowserUI/bookPreview/bookPreview.ts
src/BloomBrowserUI/collection/enterpriseSettings.tsx
src/BloomBrowserUI/lib/errorHandler.ts
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
src/BloomBrowserUI/lib/localizationManager/localizationManagerSpec.ts

I'm using the tslint.json setting suggested by Andrew to find the places to fix.  The setting itself will be part of the last PR for this issue.  (I anticipate 2-3 more PRs given the number of affected files.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2870)

Update TS to use arrow functions, part 1 (BL-6401)

---

src/BloomBrowserUI/bookLayout/textOverPicture.less
src/BloomExe/Edit/EditingView.cs
src/BloomExe/ElementProxy.cs

We should review it in e2e tests that it doesn't feel overly jarring for the T.O.P. elements to disappear when you activate the toolbox.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2896)

Disable Text-Over-Picture if Image Description on (BL-6192)

---

src/BloomBrowserUI/publish/metadata/SubjectTreeNode.ts
src/BloomBrowserUI/tsconfig.json

The require function used before is defined by node, which we don't
want to depend on in our TS code.  (we were unaware of this before it
broke yesterday.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2921)

Use import to load JSON data in TypeScript

---

src/BloomBrowserUI/package.json

We don't want this moving forward, but has been implied until recently,
and proving impossible to fix "correctly" with tsc 2.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2922)

Add @types/node to package.json

---

src/BloomBrowserUI/bookEdit/js/origami.ts

Maybe related to updated Typescript. Cleaner now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2928)

Fix  BL-6727, 6730, 6731, problem with ElementQueries module loading

---

src/BloomBrowserUI/utils/measureText.ts

I have not found steps consistent enough to reproduce or test, but I think this defensive change seems innocuous enough from what I can see?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2933)

MeasureText: Try to prevent rare IndexSizeErrror exception

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
src/BloomBrowserUI/bookEdit/editablePage.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Book/TranslationGroupManager.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/web/controllers/CommonApi.cs
src/BloomTests/Book/HtmlDomTests.cs

- Prevent ImageDesc tool activation from messing up text-over-picture elements
- Fix problem where text-over-picture elements often lose focus
- Fix bug where bloom-editable's format all (from gear icon)  e.g. bold all, italic all, underline all were throwing exceptions
- Fix bug in GatherDataBookLanguages where "*" and "z" were not properly removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2930)

Text-over-pic: Prevent ImageDesc tool activation from messing up TOP elements (bl-6721)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts

Follow-on to BL-5996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2950)

Fix audio level meter to use the background of its parent

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

This addresses both a failure to display the image descriptions when the
image description tool is active, and displaying the image descriptions
in the talking book tool when enterprise is disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2954)

Fix display of image descriptions for tools (BL-6270)

---

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
src/BloomBrowserUI/react_components/helpLink.tsx
src/BloomBrowserUI/react_components/requiresBloomEnterprise.less

This simplifies a lot of  code by have a dedicated component for the help. That component positions itself on top of the overlay that disables all of its peers. Also removes some seemingly needless wrappers, classes, and css rules I ran into along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2953)

Fix BL-6740 Overlay and Help link interaction

---

src/BloomBrowserUI/utils/bloomApi.ts
src/BloomExe/web/controllers/CommonApi.cs

This is especially useful on Linux, where we can't get a Debug window
from inside Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2960)

Add common/debugMessage API for Javascript debugging

---

debian/rules

This is the second attempt to do this inside the Bloom build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2969)

Fix Linux package build to install yarn

---

src/BloomTests/Publish/ExportEpubTests.cs

The changes were caused by the fix for BL-6760, and these changes should
have been part of that fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2968)

Fix Publish EPUB tests that are failing on Linux

---

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx

* in the case where we are just now adding the
image description translationGroups, we need to
update our page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2970)

BL-6775 Enable image description controls

---

src/BloomBrowserUI/collection/enterpriseSettings.tsx

For 4.6
I initially got into this because I thought we were losing a class... turned out to be a problem in an xliff. But I think this is clearer pattern for us to follow, so here it is anyways.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2978)

BL-6786 Enterprise Dialog simplification

---

src/BloomBrowserUI/branding/CLB/branding.json
src/BloomBrowserUI/branding/Default/branding.json
src/BloomBrowserUI/branding/GRN-REACH/branding.json
src/BloomBrowserUI/branding/Juarez-Guatemala/branding.json
src/BloomBrowserUI/branding/Local-Community/branding.json
src/BloomBrowserUI/branding/PNG-RISE/branding.json
src/BloomBrowserUI/branding/Papua-Literacy/branding.json
src/BloomBrowserUI/branding/RBI-BookBoost-pilot/branding.json
src/BloomBrowserUI/branding/SIL-International/branding.json
src/BloomBrowserUI/branding/SIL-LEAD/branding.json
src/BloomBrowserUI/branding/SIL-PNG/branding.json
src/BloomBrowserUI/branding/Suluh-INOVASI/branding.json
src/BloomBrowserUI/branding/Test/branding.json
src/BloomBrowserUI/branding/ToMasewalTlahtol/branding.json
src/BloomBrowserUI/branding/UBB-GMIT/branding.json

Add the "branding" class to the images loaded from the presets.  This will cause EpubMaker::HandleImageDescriptions() to set role=presentation which will tell ACE/Daisy to ignore it.  It will also cause empty alt text to be assigned instead of removing the alt text attribute.
Just going with the simpler fix for now, but it is not defensive. We could also add some code to try to ensure that the .branding class is added to images when the BradningSettings presets are loaded from disk.
We could also add non-empty alt text, which was talked about in the card, but for now I leave that off until further discussion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2980)

Suppress ACE/Daisy errors on branding images

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Publish/ExportEpubTests.cs

Also change code such that only allows the alt text to be preserved on branding images
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2987)

Branding alt texts: fix unit tests (BL-6787)

---

src/BloomBrowserUI/collection/enterpriseSettings.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3001)

Don't let uneditable text in Enterprise tab be selected (BL-6788)

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Edit/AudioRecording.cs
src/BloomTests/Collection/CollectionSettingsTests.cs

* add AudioRecordingTrimEndMilliseconds to
CollectionSettings
* bump OneTimeCheckVersionNumber so any
opened collection will save at least a default value
* set AudioRecorder to use value in settings to trim
the end of audio recordings
* default to 40ms
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2999)

[4.5]BL-6790 Add AudioRecordingTrimEndMilliseconds

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomExe/BloomExe.csproj
src/BloomExe/Utils/TextUtils.cs
src/BloomExe/web/controllers/AudioSegmentationApi.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Utils/TextUtilsTests.cs

Related to https://issues.bloomlibrary.org/youtrack/issue/BL-6769
Typing parenthesis into a text box seems to temporarily inject extraneous newline characters.
This causes 2 problems:
1) Aeneas thinks there are more fragments than the bloom code thinks there are.
2) The sentenceToId mapping doesn't work properly because the newline characters get automatically cleaned at a later point in time... and at some points in time we save the version without cleaning, and others we look it up post-cleaning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3012)

AutoSegment: Fix exception if text contains parentheses (BL-6769)

---

src/BloomBrowserUI/gulpfile.js

I don't know why prettier rewrote the string inside ``.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3014)

Fix glitch in HtmlXliff error reporting

---

debian/rules
src/BloomExe/BloomExe.csproj

This mimics a change already made for Version4.5 and master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3023)

Fix Linux build for Version4.4 to use yarn instead of "npm install"

---

src/BloomExe/web/controllers/AudioSegmentationApi.cs

This is a temporary fix until we have time for a proper Linux
implementation.  Without it, annoying yellow crash dialogs always pop
up on Linux when editing a page with the Talking Book tool open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3034)

Fix Linux to not complain about command errors (BL-6769)

---

src/BloomBrowserUI/bloomUI.less
src/BloomBrowserUI/collection/enterpriseSettings.less

* any code that uses bloomUI.less should work now
* if an element is a child of an element with
attribute contenteditable="true" it will be selectable
otherwise not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3031)

BL-6897 Fix selectability

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomTests/Book/BookTests.cs

The warning occurs each time the user loads the book for publishing as
a toast.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3046)

Warn user about damaged (no id) audio elements (BL-6832)

---

src/BloomExe/Edit/AudioRecording.cs

* In case of too short a recording, delete BOTH
.wav and .mp3 versions of the audio.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3054)

[4.5]BL-6881 Fix Talking Book Tool Play button

---

src/BloomExe/Book/Book.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs

This will complain when the epub view opens or when the the user sends/saves a Bloom Reader book.  (The adjusted fix on 4.6 will complain when the Android view opens by tying in to the preview update.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3051)

Fix reporting audio error in book to cover electronic pubs (BL-6832)

---

src/BloomExe/Book/Book.cs

This may deserve to be cherry-picked back to 4.4.
This was not reported in the issue, but happens whenever you open the book uploaded for the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3057)

Fix startup error when user defines coverColor (BL-6923)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.Designer.cs
src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.cs

* checkbox must be checked before enabling Save
button
* linked new Help button to a topic that explains
the difference between the 2 kinds of Bloom Pack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3069)

BL-6202 Add checkbox to Reader Pack dlg

---

src/BloomBrowserUI/publish/metadata/BookMetadataDialog.less

This is a cherry-pick from Version4.5 (requested by John Hatton).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3072)

Make metadata dialog scroll when it should (BL-6948)

---

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3073)

Set right margin in image description toolbox (BL-6893)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/web/controllers/BookMetadataApi.cs

1) rename "Alternative Text" to "Has Image Descriptions" (BL-6946)
2) remove "Sound Hazard" since it's too difficult to explain (BL-6947)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3076)

Two adjustments to epub metadata dialog (BL-6946/6947)

---

src/BloomExe/Publish/PublishView.Designer.cs

The only change is adding "this.tableLayoutPanel1.AutoScroll = true;".
This is a cherry-pick from Version4.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3077)

Allow scrolling of the Publish Options panel (BL-6908)

---

src/BloomTests/Publish/EpubValidAndAccessible.cs
src/BloomTests/Publish/ExportEpubTestsBaseClass.cs

Also beef up the hazard tests a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3078)

Fix tests broken by removing sound hazards (BL-6947)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
src/BloomBrowserUI/bookEdit/toolbox/toolbox.less

This addresses the poor display of the tool option list and missing Sign Language related localizations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3079)

Address localization issues (BL-6975)

---

src/BloomTests/WebLibraryIntegration/BookTransferDupIdTests.cs

1 microsecond worked locally, but not on TeamCity. Try 1 millisecond.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3082)

Increase timespan for failing unit test (20190318)
