src/BloomExe/NavigationIsolator.cs, src/BloomTests/NavigationIsolatorTests.cs
This fixes BL-863 "[Linux] Hard crash adding vaccinations to brand
new collection".
=> Prevent crash due to deleted temporary html file.

src/BloomExe/CollectionTab/LibraryListView.cs
I also fixed an indentation oddity while in the code.
=> Ensure sources header is wide enough for the label (BL-250)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/css/origami.css, src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/bookEdit/js/origami.js
I think it mostly works! The last commit may not be working quite right, but the rest is good for sure.
=> BL-471 Custom Page i18n

build/installNodePackages.sh, src/BloomBrowserUI/test/specs/OverflowSpec.js
Skip overflow tests if user agent is not Firefox.
=> BL-672: Overflow tests are reliable on Firefox only

src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/ServerBase.cs
Also removed redundant setting of ContentType when serving images.
=> BL-999: Fix NotSupportedException when serving jpg files

DistFiles/localization/Palaso.en.tmx, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookData.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/LowResImageProcessing/ImageServerTests.cs, src/BloomTests/LowResImageProcessing/RuntimeImageProcessingTests.cs, src/BloomTests/web/EnhancedImageServerTests.cs
Please ensure that https://github.com/sillsdev/libpalaso/pull/183 is merged first.
=> Use new localizable license descriptions

ReadMe.md
(To see what this change does it's easier to look at the rendered ReadMe.md file (in my branch: ermshiperete:BuildStatus) instead of looking at the diff)
=> Add build status icon to readme

src/BloomBrowserUI/bookEdit/js/bloomEditing.js, src/BloomBrowserUI/bookLayout/basePage.css, src/BloomBrowserUI/bookLayout/basePage.less
* set basePage.css to turn thumb background red
=> BL-1044 tell bloompage it overflows

src/BloomBrowserUI/BloomBrowserUI.csproj, src/BloomBrowserUI/bookLayout/basePage.css, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomExe/Edit/WebThumbNailList.cs
The solution turned out to be more general than I thought. I just limited the width of any image to the width of the margin box.
=> BL-1022 steps to get the Front cover thumbnail right

src/BloomBrowserUI/bookEdit/js/bloomEditing.js
* overflow calculation always says rtl width is too big unless
we include a factor for the border.
=> BL-1070 width is suddenly more important, if lang is rtl

build/Bloom.proj, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
Palaso did this, so we need to do so as well.
=> Update version of NUnit

debian/copyright
Fill out the copyright and license information for all the code
we've used in making Bloom.
=> Give credit where credit is due (BL-1057)

src/BloomBrowserUI/bookEdit/EditViewFrame.htm, src/BloomBrowserUI/bookEdit/EditViewFrame.jade, src/BloomBrowserUI/bookEdit/js/bloomEditing.js, src/BloomExe/Browser.cs
These error messages were found while investigating BL-1030, but they aren't the cause of the issue.
=> BL-1030: Fix causes of calledByCSharp errors reported in Firefox console

DistFiles/localization/Bloom.en.tmx, DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less, DistFiles/xMatter/bloom-xmatter-mixins.jade, src/BloomBrowserUI/bookEdit/js/bloomEditing.js
and revert Topic Chooser button
=> BL-1125 Make topic bubble stay up

src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/BookPagesThumbnailList.htm, src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/TemplatePagesThumbnailList.htm, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.css, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.less, src/BloomBrowserUI/bookEdit/css/TemplatePagesThumbnailList.css, src/BloomBrowserUI/bookEdit/css/TemplatePagesThumbnailList.less
Also refactored both BookPagesThumbnailList.htm and TemplatePagesThumbnailList.htm to use separate .less/.css files.
=> BL-336 Make space for 3 line thumbnail captions

src/BloomExe/Publish/PdfMaker.cs
This requires a new version of PdfDroplet.exe, available via getDependencies-xx.sh.
=> Print A6 booklets 4 to an A4 sheet (BL-1059)

src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts
This is a follow-up to BL-1015 which handled commas in the sight word list
=> Handle commas in list of letters

src/BloomExe/Book/BookData.cs
Someone has somehow marked an email address with bare < and >
characters in one of the shell books.  This causes a program crash
when some tries to instantiate that book.
=> Prevent crash due to bad markup of email address (BL-1117)

src/BloomExe/Publish/PdfViewer.cs
Display and print PDFs using Acrobat if installed.
This avoids various bugs in PDFjs (also BL-1037, 1170, maybe others).
Unfortunately it's not an option on Linux.
=> BL-1170, switch back to using Acrobat

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomExe/Collection/CollectionSettings.cs
=> BL-1187: user-modified css rules were not being applied to children

build/getDependencies-Linux.sh
This finishes the work JohnT did earlier on squirrel, and work that Jason has been doing on chorus.
=> Fix getDependencies-Linux.sh for recent chorus and windows changes

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less
* somehow the min-height made large font sizes overflow
* also removed unnecessary margin-bottoms on TitlePage
(the .less file is the only un-generated one)
=> BL-1200 Remove unnecessary min-height on TitlePage

src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs
BloomPack files created on Windows are storing \ as the directory
separator.  This needs to be converted to / on Linux. ZipFile does
this, but FastZip does not.
=> Fix BloomPack unpacking to handle Windows vs Linux (BL-1213)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Book/Layout.cs, src/BloomExe/Book/SizeAndOrientation.cs, src/BloomExe/Book/StyleSheetLinkSorter.cs, src/BloomExe/Browser.cs, src/BloomExe/Collection/BookCollection.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Edit/DynamicJson.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/TemplatePagesView.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Program.cs, src/BloomExe/Registration/RegistrationDialog.cs, src/BloomExe/SendReceive/SendReceiver.cs, src/BloomExe/SplashScreen.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/web/BloomServer.cs
Changed all C# .ToLower() -> .ToLowerInvariant()
=> [Debt] Change all ToLower() to Invariant version

src/BloomExe/Program.cs
(instead of create collection wizard)
=> BL-1229, first startup should use Open/Create dialog

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/web/EnhancedImageServerTests.cs
Use the server to locate the appropriate css files instead of modifying the dom every time a page is requested
=> BL-854: Use the server to locate the appropriate css files.

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/web/EnhancedImageServerTests.cs
Reverts BloomBooks/BloomDesktop#398 (due to BL-1245)
=> Revert "BL-854: Use the server to locate the appropriate css files."

DistFiles/localization/Bloom.ar.tmx, DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx, DistFiles/localization/Bloom.fr.tmx, DistFiles/localization/Bloom.hi.tmx, DistFiles/localization/Bloom.lo.tmx, DistFiles/localization/Bloom.rw.tmx, DistFiles/localization/Bloom.ta.tmx, DistFiles/localization/Bloom.te.tmx, DistFiles/localization/Bloom.th.tmx, DistFiles/localization/Bloom.zh-Hans.tmx, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
Cleanup some repetitious code;
Made message a bit more friendly;
Added new case about timeouts.
=> BL-1233 Improve reporting of download problems

src/BloomExe/web/EnhancedImageServer.cs
Ampersand in URL causing problems with changes to the way css files are located
=> BL-1245: Ampersand in URL causing problems

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/ImageProcessing/ImageServerTests.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/web/EnhancedImageServerTests.cs
I tried to make this as close as possible to the original pull request for this issue.
**Pull request #430 needs to be merged before this one.**
=> BL-854: Move actual CSS file selection to the server

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.js, src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.css, src/BloomBrowserUI/bookEdit/css/editMode.less
* Don't mark a box as overflowing if typing in it just
made another box overflow marginBox
* On marginBox overflow, mark offending box with
red text and thick red bottom border
=> BL-1261 Change overflow heuristic

src/BloomExe/Program.cs
Changing from the old 3.0 will, unfortunately, cause it once.
=> BL-1225, changing channels should not cause new registration

src/BloomExe/MiscUI/ToastNotifier.cs
It seems disabling a timer is not enough to prevent it ticking
=> BL-1136 Leave update "toast" visible after update ready

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/MiscUI/ToastNotifier.cs
Also report progress (doesn't seem to be very accurate, though)
=> BL-1255 Keep Squirrel Toast up while downloading update

src/BloomExe/ApplicationUpdateSupport.cs
(May contribute to solving BL-1256)
=> Log more details of failed incremental update

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Collection/CollectionSettings.cs, src/BloomTests/Book/BookCollectionTests.cs, src/BloomTests/Book/BookDataTests.cs
* sets up a one time migration any time a collection's settings are loaded
* from default Andika to Andika New Basic
* BookCollectionTests - only moved a method
* tests are in BookDataTests
=> BL-1257 Minimal migration of collection settings

src/BloomExe/Collection/CollectionSettings.cs
* Don't report changes to unset language1 or 2
* Do our best to get an actual language name, just use Ethnologue code as a fallback
=> BL-1257 andika migration fix

src/BloomExe/web/EnhancedImageServer.cs
I had created the Program.OptimizedFileLocator property, but apparently neglected to hook it up.
=> BL-2159: not locating factory xmatter

src/BloomExe/Book/BookStorage.cs
The change around line 724-740 is much simpler than it looks due to removal of one level of indenting.
It was found that Publish now uses a temp html file in the book folder instead of the localhost server method, which bypasses the new smarter file locator. Then we saw that older downloaded books contained support files with brand new dates (date of download) instead of when the file was actually created. This killed the UpdateIfNewer mechanism so books were using older versions of css files, etc. So we are changing UpdateIfNewer() -> Update().
=> BL-2166 Update support files regardless of date

src/BloomExe/Publish/PublishModel.cs, src/BloomExe/web/EnhancedImageServer.cs
BL-932 should be checked perhaps, but this seems like a simpler idea now.
=> BL-2172 Revert to using localhost to create pdf

src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/web/EnhancedImageServer.cs
=> Fix BL-2175 "OriginalImages" preventing proper CSS lookup

src/BloomBrowserUI/bookEdit/js/origami.js
Stop text boxes from overlapping on custom page when one is deleted.
=> BL-2154: Stop text boxes from overlapping on custom page

src/BloomExe/Program.cs
=> BL-2143: Do not show download complete if not completed

DistFiles/factoryCollections/Templates/Wall Calendar/configure.js, DistFiles/factoryCollections/Templates/Wall Calendar/configure.ts, src/BloomBrowserUI/bookEdit/js/directoryWatcher.js, src/BloomBrowserUI/bookEdit/js/directoryWatcher.ts, src/BloomBrowserUI/bookEdit/js/editViewFrame.js, src/BloomBrowserUI/bookEdit/js/synphonyApi.js, src/BloomBrowserUI/bookEdit/js/synphonyApi.ts, src/BloomBrowserUI/bookEdit/js/toolbar/jquery.d.ts
* Make DirectoryWatcher.start() and onChanged() public
* Change all 'bool' to 'boolean' in jquery.d.ts
* 'Fix' MessageEvent problem in synphonyApi.ts
by calling it from accordion.js
=> [Debt]Fix a number of TypeScript errors

src/BloomExe/ApplicationUpdateSupport.cs
The main problems were fixed in Squirrel
(https://github.com/Squirrel/Squirrel.Windows/pull/343);
this one addresses the unpredictability of whether download
or merging deltas is slower.
=> BL-2192 Report install download and apply progress separately

src/BloomBrowserUI/bookEdit/css/qtipOverrides.css, src/BloomBrowserUI/bookEdit/css/qtipOverrides.less, src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts
This is a replacement for PR #469
=> BL-878: Prevent bubbles from overlapping

src/BloomExe/XmlHtmlConverter.cs
Stack trace in BL-2174 indicates that somewhere deep in libtidy
it fails to write a byte because a stream is mysteriously closed.
Could not figure out why, but there may be some issue with writing
the same file twice in close succession. It's better anyway not to
hit the disk with the intermediate result, and the change seems to
fix the problem.
=> BL-2174 Make HtmlConverter save intermediate result in RAM

src/BloomExe/Book/BookData.cs
(It is a duplicate of licenseNotes.)
=> BL-2198, don't create Description for custom license

src/BloomBrowserUI/BloomBrowserUI.csproj
* deleted some obsolete things
* localizationManager.ts ref was in the wrong place
=> Update csproj for BloomBrowserUI

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/BloomExe.csproj, src/BloomExe/InstallerSupport.cs
Removes some params and references no longer needed
(some of the latter unrelated to squirrel).
https://github.com/BloomBooks/Squirrel.Windows/pull/7 should be merged (immediately) before this.
=> BL-2228 Update to current Squirrel

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Collection/BloomPackInstallerTests.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs, src/BloomTests/CollectionTab/TestLibraryModel.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
* Created 1st bloompack creation test
* Made test for upload too
=> BL-2246 Don't include thumbs.db in packs or uploads

src/BloomBrowserUI/test/fixtures/OverflowAncestorTestPage.htm, src/BloomBrowserUI/test/fixtures/OverflowAncestorTestPage.jade, src/BloomBrowserUI/test/fixtures/OverflowMarginTestPage.htm, src/BloomBrowserUI/test/fixtures/OverflowMarginTestPage.jade, src/BloomBrowserUI/test/fixtures/OverflowTestPage.htm, src/BloomBrowserUI/test/fixtures/OverflowTestPage.jade
After removing the old Andika font, there were some test failures.
=> Update tests to use Andika New Basic.

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/XmlHtmlConverter.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/web/EnhancedImageServerTests.cs
Fixed problem where & in book title made it unusable.
Also removed bloom-ui elements when saving so they don't get into data-book elements
=> BL-2223 ampersand in title

src/BloomExe/Program.cs
(Depends on a libpalaso change; do not merge until after https://github.com/sillsdev/libpalaso/pull/226)
=> BL-2247 Update green/yellow-box privacy notice

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
* remove unused usings and methods in BloomS3Client
* minor edits to tests
=> Simplify some S3 stuff

src/BloomExe/XmlHtmlConverter.cs
Phil has unit tests and maybe a different fix coming
=> Initial fix for BL-2250

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs, src/BloomTests/CollectionTab/TestLibraryModel.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
* Tests will also confirm that pdfs WILL be uploaded
to BloomLibrary.
=> BL-2246 Don't put pdf files in bloompacks

src/BloomBrowserUI/bookLayout/collection styles override template.css
A new version of "collection styles override template.css" that is the template for "customCollectionStyles.css".
=> BL-2260 update collection styles override template

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/BloomLibraryPublishControl.Designer.cs, src/BloomExe/Publish/BloomLibraryPublishControl.cs, src/BloomExe/Publish/BloomLibraryPublishControl.resx, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomTests/Book/BookTests.cs
specifically, which languages are advertised in the library
=> BL-2017 Allow user to control which languages when uploading

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
Prevents wasting space and bandwidth on any
obsolete previews or other PDF junk that has crept
into the book folder
=> BL-2246 Don't publish PDF files except main preview

src/BloomBrowserUI/bookEdit/js/readerSettings.js, src/BloomBrowserUI/bookEdit/js/readerSettings.ts, src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.htm, src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.jade, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.css, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts, src/BloomExe/web/ReadersHandler.cs
"If in 'allowed words' mode, then in each stage, allow user to select a file containing words allowed for that stage."
=> Change 2: Allow user to select a file of words allowed for a stage

src/BloomBrowserUI/bookEdit/js/readerTools.ts, src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/js/synphonyApi.js, src/BloomBrowserUI/bookEdit/js/synphonyApi.ts
This pull request contains no functionality changes, just clean-up of typescript files.
=> Clean up reader tools typescript before adding features

src/BloomBrowserUI/bookEdit/css/editMode.css, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts, src/BloomBrowserUI/karma.conf.js, src/BloomBrowserUI/test/specs/SourceBubblesSpec.js, src/BloomBrowserUI/test/specs/SourceBubblesSpec.ts
* fixed a bug in SmartOrderSourceTabs()
* used a pure css method of dropdown box that is simpler than trying to cover
a select arrow with my own arrow
* made better use of @variables in editMode.less so colors are easier to change
* made the source tabs look more like tabs
=> BL-2390 Source tabs part2

src/BloomBrowserUI/karma.conf.js
Need Firefox to run Overflow tests.
Need Chrome to debug tests.
=> Fix karma config

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
=> BL-2386 Put style name back in status/reminder message

src/BloomBrowserUI/bookEdit/js/readerSettings.js, src/BloomBrowserUI/bookEdit/js/readerSettings.ts, src/BloomBrowserUI/bookEdit/js/readerTools.js, src/BloomBrowserUI/bookEdit/js/readerTools.ts, src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts, src/BloomExe/web/ReadersHandler.cs
Gets the list of available words for each stage and displays them in the reader setup stages dialog.
=> Word list in stage setup dialog

src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.htm, src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.jade, src/BloomBrowserUI/bookEdit/js/readerTools.js, src/BloomBrowserUI/bookEdit/js/readerTools.ts, src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts
This just displays the word list, it doesn't do any markup of the editable text.
=> Word list in decodable reader tool

src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.css, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.less, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts
Show delete button only when mouse is on the same row as the file name
=> BL-2401: show delete button only when mouse is on the same row

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/js/synphonyApi.js, src/BloomBrowserUI/bookEdit/js/synphonyApi.ts
This should be the last commit for this BL-2363
=> Implement decodable reader markup with allowed words list

src/BloomBrowserUI/bookEdit/css/editMode.css, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/css/editPaneGlobal.css, src/BloomBrowserUI/bookEdit/css/qtipOverrides.css, src/BloomBrowserUI/bookEdit/css/qtipOverrides.less, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts, src/BloomBrowserUI/test/specs/SourceBubblesSpec.js, src/BloomBrowserUI/test/specs/SourceBubblesSpec.ts
* Bloom remembers which language user looked at last
* round qtip (only for source bubbles)
* multiple style changes to tabs
=> BL-2142 Source bubble work; take three

src/BloomBrowserUI/BloomBrowserUI.csproj, src/BloomBrowserUI/bookEdit/css/editMode.css, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/css/qtipOverrides.css, src/BloomBrowserUI/bookEdit/css/qtipOverrides.less, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.js, src/BloomBrowserUI/bookEdit/js/bloomSourceBubbles.ts
* update csproj file with correct test file location
* make qtipOverrides not override too much
* change min-height of a bubble to fit a one line text
even when the textbox was shorter than a bubble
* strip out CustomPage style changes before making bubbles
* still having trouble with Len's "problem 2", but wanted to get this in
=> BL-2142 Fix some source bubble glitches

src/BloomExe/CollectionTab/LibraryListView.cs
Needed to handle the button Paint event.
=> BL-2450: Make dropdown triangle scroll with the button

src/BloomBrowserUI/bookEdit/css/editMode.css, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/css/origami.css, src/BloomBrowserUI/bookEdit/css/origami.less
* actually needed to hide scrollbars in Custom Pages anyway
* also hid scrollbars in source text
=> BL-2439 fix interaction between Bubbles and Overflow

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.htm, src/BloomBrowserUI/bookEdit/readerSetup/ReaderSetup.jade, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts
* for Delete Word List File control
=> BL-2449 Add tooltip to red x

src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts, src/BloomExe/web/ReadersHandler.cs
Reverts BloomBooks/BloomDesktop#605
=> Revert "BL-2446: Remove word list from cache when no longer being used."

src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.js, src/BloomBrowserUI/bookEdit/readerSetup/readerSetup.ui.ts, src/BloomExe/web/ReadersHandler.cs
BL-2446: Remove word list from cache when no longer being used.
=> BL-2446: Remove word list from cache when no longer being used.

src/BloomExe/MiscUI/ProblemReporterDialog.cs
* made the link show the zip file instead of opening it
=> BL-2398 Report a Problem zip link

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts
Also clear the letter display if the stage count goes to zero.
=> Update stage number when stages have been removed (BL-2464)

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.htm, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.htm, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.htm, DistFiles/xMatter/bloom-xmatter-mixins.jade, src/BloomExe/Book/BookSelection.cs, src/BloomExe/CollectionTab/LibraryBookView.cs
My previous fix was mistaken in thinking about image licenses instead of book licenses.
=> Change default book license to CC-BY (BL-2472)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.js, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
Using alert(msg) crashes on Linux.  This works on both platforms.
=> Use the format dialog for a 'No format change' message (BL-2476)

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/MiscUI/ProblemReporterDialog.cs, src/BloomExe/packages.config
The fix was to fork the YouTrackSharp repository and create a branch with the Windows-specific code removed. The offending code was referencing WMI, which we don't need.
=> BL-2399: Fix 'Report a Problem' for Linux.

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, debian/rules
Also update getDependencies-*.sh to work with wget.
=> Fix packaging to use BloomLinux.sln

src/BloomExe/app.config
The implementation of this change is in libpalaso
=> BL-2415: Use ProductName setting from config file, if present

debian/bloom, debian/changelog, debian/control, debian/copyright, debian/rules
Change package name to bloom-desktop and version to 3.2.1.
Also change package maintainer from Eberhard to Steve.
=> Update Linux packaging for version 3.2

src/BloomBrowserUI/bookEdit/js/bloomEditing.js
This works on both custom pages and old statically defined pages.
=> Get ckeditor format bar to position correctly (BL-2580)

src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.htm, src/BloomBrowserUI/bookEdit/accordion/DecodableRT/DecodableRT.jade, src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts
Also limit the number of words read from files in general.  The program
was still hanging if the wordlist was used for sample words instead of
allowable words.  (I didn't try to show the truncation message for that
case, however.)
=> Fix color and wording of maximum allowed words message (BL-2463)

src/BloomBrowserUI/bookEdit/js/jquery.div-columns.js, src/BloomBrowserUI/bookEdit/js/jquery.div-columns.ts
A new TypeScript compiler has changed comment indentation, and made a couple of other minor formatting changes.
=> Ensure valid column number in displaying words (BL-2588)

src/BloomExe/Edit/EditingModel.cs
=> used existing JSON library to greatly simplify things

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.jade, DistFiles/factoryCollections/Templates/Decodable Reader/Decodable Reader.htm, DistFiles/factoryCollections/Templates/Decodable Reader/Decodable Reader.jade, DistFiles/factoryCollections/Templates/Leveled Reader/Leveled Reader.htm, DistFiles/factoryCollections/Templates/Leveled Reader/Leveled Reader.jade, DistFiles/jade/StandardPages.jade, src/BloomExe/Book/Book.cs, src/BloomTests/Book/PageMigrationTests.cs
I think review can safely ignore the merge commit (which trivially brought master stuff into the feature branch) and focus on the second one.
=> Bl 2562 migrate to customizable

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.htm, DistFiles/factoryCollections/Templates/Big Book/BigBook.htm, DistFiles/factoryCollections/Templates/Decodable Reader/Decodable Reader.htm, DistFiles/factoryCollections/Templates/Leveled Reader/Leveled Reader.htm, DistFiles/factoryCollections/Templates/Picture Dictionary/Picture Dictionary.htm, DistFiles/jade/StandardPages.jade
* Big Book's JustText page needed updating
* StandardPage Picture in Middle's 2nd textbox needed updating in all templates
=> BL-2632 finish updating templates to be custom pages

src/BloomExe/Browser.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageListView.cs, src/BloomExe/Edit/WebThumbNailList.cs
I also cleaned out a lot of dead code from WebThumbNailList.cs (blocks of code that were commented
out and unused member variables).
=> Handle Ctrl-N (for creating a new page) on Linux/Mono (BL-2642)

src/BloomBrowserUI/pageChooser/js/page-chooser.js, src/BloomBrowserUI/pageChooser/js/page-chooser.ts
This works around a bug deep in javascript somewhere.
=> Ensure proper page selection in Add Page dialog (BL-2623)

DistFiles/localization/Bloom.es.tmx
I've never done a major update to a tmx before. (a few strings here and there that I was working on, yes) I'm assuming all I need to do is drop the new tmx into its place in the file structure. I did do a diff to see if anything looked suspicious... Let me know if I'm missing a step or something.
=> V3.3 BL-2665 Update Spanish tmx

debian/bloom, debian/changelog, debian/control, debian/copyright, debian/install, debian/rules
Also rename the Linux package to bloom-desktop-beta.
=> Update version information on the Bloom Version3.3 branch

src/BloomExe/Edit/EditingModel.cs
Just a desperate attempt to learn more about how this
can happen. Not sure it's worth doing.
=> BL-2634 gather more information

build/dependencies.config
This should fix a failing test on Linux build agents
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/711)
=> Add dependency for Andika New Basic

src/BloomBrowserUI/bookEdit/js/readerToolsModel.js, src/BloomBrowserUI/bookEdit/js/readerToolsModel.ts
(cherry picked from commit ca4d71b2c483b099064689f52f7d51b6a25acd13)
=> Fix interpretation of sight words separated by newlines (BL-2683)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/js/editViewFrame.js, src/BloomBrowserUI/pageChooser/js/page-chooser.js, src/BloomBrowserUI/pageChooser/js/page-chooser.ts, src/BloomExe/Edit/PageListView.Designer.cs
Also adds a couple of missing dynamic IDs and moves them to
their proper places. I doubt anyone has translated them,
since they had not previously been added at all.
=> BL-2700, Fix localization ID for Add Page

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/BloomBrowserUI.csproj, src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/BookPagesThumbnailList.htm, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.css, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.less, src/BloomBrowserUI/bookEdit/js/editViewFrame.js, src/BloomBrowserUI/pageChooser/js/page-chooser.js, src/BloomBrowserUI/pageChooser/js/page-chooser.ts, src/BloomBrowserUI/pageChooser/page-chooser-main.htm, src/BloomBrowserUI/pageChooser/page-chooser-main.jade, src/BloomBrowserUI/pageChooser/page-chooser.css, src/BloomBrowserUI/pageChooser/page-chooser.less, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.Designer.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageListView.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Book/PageMigrationTests.cs
Enhances the Add Page dialog so it can also be used
to change the layout of an existing page.
=> BL-2565 Change Page Layout

DistFiles/factoryCollections/Templates/Basic Book/Basic Book.css, DistFiles/factoryCollections/Templates/Basic Book/Basic Book.less, DistFiles/less/common-mixins.less, DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.css, src/BloomBrowserUI/bookEdit/css/BookPagesThumbnailList.less, src/BloomBrowserUI/bookLayout/basePage.css, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomExe/Publish/PdfMaker.cs
This handles QuarterLetter similarly to A6 when printing booklets.
=> Add HalfLetter and QuarterLetter size choices (BL-2677)

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less
This may only be a partial solution to the problem(s)
in this issue, but it seems to help somewhat.
=> BL-2681 contentEditable divs in title should not be flex

src/BloomExe/web/EnhancedImageServer.cs
This will need to cherry picked to the 3.3. branch.
=> Fix Add Page dialog to work without network (BL-2713)

DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less
Note that some of the commits being merged were cherry-picks from master, so  they effectively disappear in the actual set of file changes.
=> Merge version3.3 to master 20150904

build/Bloom.proj
Bloom uses this icon for the desktop shortcut
=> BL-2714 Create Bloom<channel>.ico for installer

src/BloomExe/Book/BookData.cs, src/BloomExe/Edit/EditingModel.cs
The first commit is actually a refactoring I've been wanting to do in EditingModel. _bookSelection.CurrentSelection in that file is the definition of CurrentBook property, so it simplifies things to just use CurrentBook.
The actual change for this issue is the one in BookData.
=> BL-2425 inside back cover

src/SquirrelInstaller/Bloom.nuspec
Also removes other PDBs except Bloom.pdb
and BloomTests.*
=> BL-2727 Do not ship 28 meg AWSSDK.pdb

debian/changelog, debian/rules
This was used to build the packages yesterday.
=> Update the Linux package version to 3.2.3 on the Version3.2 branch

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.fr.tmx, src/BloomBrowserUI/pageChooser/js/page-chooser.js, src/BloomBrowserUI/pageChooser/js/page-chooser.ts
=> Merge v3.3 into master

src/BloomExe/ApplicationUpdateSupport.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/776)
=> Ignore flaky internet in update checks (BL-2783)

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
Also avoid downloading thumbs.db files if they exist.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/767)
=> Avoid downloading PDF files from the library (BL-2312)

src/BloomExe/CollectionTab/LibraryListView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/779)
=> BL-2778 Stop always redoing thumbs for Sources

src/BloomExe/Browser.cs
Note: the git hub diff here is worthless.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/781)
=> BL-2787 Give nicer message when we get the mystery paste failure

src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/769)
=> Prevent needless copying of image files (BL-2776)

DistFiles/factoryCollections/Sample Shells/Vaccinations/Vaccinations.htm, DistFiles/factoryCollections/Templates/Picture Dictionary/PictureDictionary.css, DistFiles/xMatter/Factory-XMatter/Factory-XMatter.css, DistFiles/xMatter/SIL-Cameroon-XMatter/SIL-Cameroon-XMatter.css, DistFiles/xMatter/Traditional-XMatter/Traditional-XMatter.css, DistFiles/xMatter/bloom-xmatter-common.css, DistFiles/xMatter/bloom-xmatter-common.less
For A6 and Quarter Letter, we reduce the spacing.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/788)
=> BL-2794 Fix spacing in picture dictionary

src/BloomExe/web/EnhancedImageServer.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/789)
=> Fix a but where the AddPageDialog choked if template on my 'x' drive

src/BloomExe/Edit/EditingModel.cs
* It's a strange case. I can't figure out how it can happen
It's actually the second of the lines that I protected that appears to have had the problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/783)
=> v3.4 BL-2780 ContentLanguages had an exception

src/BloomExe/Book/HtmlDom.cs, src/BloomExe/HtmlThumbNailer.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/751)
=> BL-2673 Retry thumbnail generation if image failed to load

src/BloomExe/Book/HtmlDom.cs, src/BloomExe/HtmlThumbNailer.cs
This reversion fixes BL-2824.
This reverts commit 43946e37f2d79f190b8f9138da439f6333a5a30f.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/796)
=> Revert "BL-2673 Retry thumbnail generation if image failed to load"

src/BloomExe/AboutMemory.Designer.cs, src/BloomExe/AboutMemory.cs, src/BloomExe/AboutMemory.resx, src/BloomExe/BloomExe.csproj, src/BloomExe/Browser.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/web/ServerBase.cs
This doesn't fix anything, but provides access to information that
may help lead to a fix.  The new class may be useful as a way to
provide other debugging information as well.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/793)
=> Add memory check features for debugging leaks (BL-2786 related)

src/BloomExe/Edit/EditingView.cs
* when translating a shell, show a summary of existing metadata
* if a shell image has no metadata, still don't allow it to be edited
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/797)
=> BL-2821 Fix editMetadataButton operation

src/BloomBrowserUI/bookEdit/js/bloomImages.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/799)
=> Add DPI calculation to image tooltip

src/BloomExe/ApplicationContainer.cs, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/ErrorBook.cs, src/BloomExe/BookThumbnailer.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Publish/EpubMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/Book/BookCollectionTests.cs, src/BloomTests/Book/BookStarterTests.cs, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Book/ExportEpubTests.cs, src/BloomTests/CollectionTab/TestLibraryModel.cs, src/BloomTests/ProblemReporterDialogTests.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs, src/BloomTests/web/BloomServerTests.cs
Previously we were depending on a thumbnail
that gets created during upload
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/800)
=> BL-2833 make cover thumbnail for epub

src/BloomBrowserUI/BloomBrowserUI.csproj, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ElementProxy.cs
Commits in order:
*remove annoying minification
*fix changeImage button (EditingView.cs)
*fix editMetadata button (ElementProxy.cs)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/806)
=> Fix image buttons

src/BloomBrowserUI/bookEdit/js/bloomImages.js, src/BloomExe/web/EnhancedImageServer.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/803)
=> Fix tooltip on cover image and add BitDepth to image tooltips

src/BloomBrowserUI/bookEdit/BookPagesThumbnailList/BookPagesThumbnailList.htm, src/BloomBrowserUI/bookEdit/js/bloomImages.js
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/805)
=> Fix BL-2801 where the cover thumbnail lacked an image

src/BloomExe/Edit/EditingView.cs, src/BloomExe/Workspace/BloomClipboard.cs
Here I take care of leaking PalasoImages. Along the way it started working reliably for me, ta' boot.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/808)
=> More work on BL-2342 Cut/copy images

src/BloomBrowserUI/audio/audioRecording.js, src/BloomBrowserUI/audio/audioRecording.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/811)
=> Improve audio position

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Publish/EpubMaker.cs, src/BloomExe/UrlPathString.cs, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/UrlPathStringTests.cs
fix bl-2351 by deleting unused images when book is loaded or image is added.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/814)
=> fix bl-2351 by deleting unused images when book is loaded or img added

src/BloomExe/Edit/WebThumbNailList.cs
Previously, the initial load of  page thumbnails added a ?thumbnail=1 to each src, but then when we leave the page, the thumbnail was being regenerated without that query string, taking up as much ram as the uncompressed version of the image.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/818)
=> Use less RAM by using small versions of imgs when updating page thumbs

src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Edit/EditingModel.cs
Naudio hasn't been supported on Linux to this point.  Something needs
to be done to get audio to work on Linux.
See https://silbloom.myjetbrains.com/youtrack/issue/BL-2878.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/819)
=> Use #if _MonoCS__/#else on new Naudio references

src/BloomExe/Edit/EditingView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/821)
=> BL-2821 Extend shell locking of images to Change Image button

src/BloomExe/XmlHtmlConverter.cs, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/XmlHtmlConverterTests.cs
LibTidy strikes again!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/823)
=> Fix BL-2881 Blank lines between paragraphs disappear

build/getDependencies-windows.sh
It had been downloading an old zip file from bitbucket.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/825)
=> Change source of GeckoFx for windows to TeamCity build artifacts

src/BloomExe/Publish/EpubMaker.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/827)
=> Reinstate underline removal in epubs and make it work for covers

debian/control, debian/rules
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/829)
=> Fixes for failing Linux packaging

src/BloomExe/MiscUI/BloomIntegrityDialog.cs
It is provided in a separate package that the Bloom packages depend on.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/832)
=> AndikaNewBasic is not shipped as part of Bloom for Linux (BL-2894)

src/BloomExe/Edit/EditingView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/833)
=> BL-2338 only invalidate button if state changed

src/BloomBrowserUI/pageChooser/js/page-chooser.js, src/BloomBrowserUI/pageChooser/js/page-chooser.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/835)
=> BL-2565 Hide Custom page in Choose Layout

src/BloomExe/Book/BookStorage.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/834)
=> When a folder is denied, give same experience as we do with a file

src/BloomExe/MiscUI/ProblemReporterDialog.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/831)
=> BL-2800 Handle upload attachment too large

src/BloomExe/BloomExe.csproj, src/BloomExe/CollectionCreating/LanguageIdControl.cs, src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/ToPalaso/LanguageLookupModelExtensionsTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/840)
=> Fix after ws

build/getDependencies-Linux.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/841)
=> New getDependencies-Linux.sh for recent Palaso sea change

src/BloomExe/Workspace/WorkspaceView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/842)
=> Fix comment to use proper assembly name (SIL.Windows.Forms)

src/BloomBrowserUI/bookEdit/js/bloomEditing.js, src/BloomBrowserUI/bookEdit/js/calledByCSharp.js, src/BloomBrowserUI/bookEdit/js/calledByCSharp.ts, src/BloomExe/Browser.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/HtmlThumbNailer.cs
Added a few more settings, and more debug window menu items.
Remove event handlers/listeners better when done with an html document.
Dispose images and gecko html objects that are no longer needed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/826)
=> Try to reduce memory leakage and use (BL-2786)

src/BloomExe/CollectionCreating/LanguageIdControl.cs
(Depends on a libpalaso fix also.)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/843)
=> BL-2919 Fix a null ref crash in New Collection

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, debian/install, src/BloomExe/BloomExe.csproj
Part of this is due to the Palaso library renaming and revising, but
probably not all of this.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/848)
=> Get Linux package building to work after recent upheavals

DistFiles/factoryCollections/Templates/Big Book/ReadMe_en.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/847)
=> Changed reference from Bloom 2 to Bloom 3 (BL-2646)

src/BloomExe/Book/BookStorage.cs
* add "license" to the list of images not deleted
* add Distinct() to speed things a bit
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/850)
=> BL-2883 Fix Story Primer refresh problem

src/BloomExe/Workspace/WorkspaceView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/853)
=> Fix Linux crash caused by fix for BL-2710

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/860)
=> BL-2790 Prevent custom license from being discarded

src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/861)
=> [v3.4]Cherry-pick image metadata work to 3.4

src/BloomExe/web/ServerBase.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/web/BloomServerTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/865)
=> Enhance fix for Url.LocalPath losing network path slashes (BL-2932)

src/Bloom-ChorusPlugin/BloomHtmlFileTypeHandler.cs, src/Bloom-ChorusTests/HtmlHandlerTests.cs
See https://github.com/sillsdev/chorus/pull/77.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/866)
=> Adjust to renamed Chorus namespace

src/BloomTests/PretendRequestInfo.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/867)
=> Fix test failing due to work on BL-2932

DistFiles/factoryCollections/Templates/Arithmetic/Arithmetic.css, DistFiles/factoryCollections/Templates/Arithmetic/Arithmetic.less
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/859)
=> Fix BL-2884 with multilingual header texts on arithmetic pages

src/BloomBrowserUI/bookEdit/js/bloomNotices.js
Earlier commit changed the .ts file, but didn't include the change to the .js file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/871)
=> File change left out of earlier commit d352a7a

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/Shell.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/872)
=> Add (non-Release) channel name to Bloom window banner (BL-2940)

src/BloomExe/Properties/Settings.settings
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/875)
=> Update the Settings file to use the renamed Palaso library classes

src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs
DO NOT MERGE UNTIL 3.5 HAS ITS OWN BRANCH!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/881)
=> Report a corrupt Bloom Pack nicely instead of crashing (BL-2485) [Bloom 3.6]

src/BloomExe/BloomExe.csproj, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/MiscUI/LanguageFontDetails.Designer.cs, src/BloomExe/MiscUI/LanguageFontDetails.cs, src/BloomExe/MiscUI/LanguageFontDetails.resx
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/879)
=> Add Language and Script page to the create collection wizard (BL-2912) [Bloom 3.6]

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/889)
=> Fix BL-2962 meta.json no longer getting topic tags

src/BloomTests/BloomTests.csproj, src/BloomTests/MiscellaneousTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/892)
=> BL-2974 Build should fail if naudio is missing or wrong version

src/BloomBrowserUI/lib/pure-drawer.css
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/893)
=> BL-2968 prevent toolbox visibility control white background

src/BloomExe/Collection/CollectionSettings.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/894)
=> If collection settings can't be read, include the contents in the log

src/BloomExe/web/EnhancedImageServer.cs, src/BloomTests/MiscellaneousTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/901)
=> Two minor fixes needed to compile on Linux/Mono

src/BloomBrowserUI/bookEdit/EditViewFrame.htm, src/BloomBrowserUI/bookEdit/bloomField/bloomField.js, src/BloomBrowserUI/bookEdit/bloomField/bloomField.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.js, src/BloomBrowserUI/typings/ckeditor/ckeditor.d.ts, src/BloomExe/Browser.cs
This was caused by adding ckeditor. Part of this commit is removing some of the filtering we were doing, since ckeditor can do a better job of it anyhow.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/914)
=> Fix BL-3010, where pasting text into SHRP books pasted twice

src/BloomBrowserUI/bookEdit/bloomField/bloomField.js, src/BloomBrowserUI/bookEdit/bloomField/bloomField.ts, src/BloomBrowserUI/bookEdit/ckeditor.d.ts, src/BloomBrowserUI/lib/ckeditor/config.js
We lost this feature when we added ckeditor.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/913)
=> BL-3009 Fix shift-enter to get linebreak span

src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/ToolboxView.cs
Also fix BL-3050 while we're at it.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/924)
=> Fix BloomBrowserUI to build on Linux using npm

build/dependencies.config, debian/control
I have no idea if that actually helps for the current problem, but at least it seems a step in the right direction.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/925)
=> Add npm to dependencies

src/BloomBrowserUI/bookEdit/js/bloomEditing.js
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/934)
=> Fix BL-3125 Inline images broken by ckeditor

src/BloomExe/Program.cs
THis part can go in 3.5. The second part will have to wait for a new palaso with 3.6 (don't want to upgrade palaso at this point in 3.5's life).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/944)
=> Bl3113 corrupt palaso user.config handling (part 1)

src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Publish/EpubMaker.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/950)
=> Fix BL-3159 where we tried to encode mp3 without seeing if we had LAME

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/946)
=> Fix BL-3161 where audio player was occasionally not getting new file

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/951)
=> Fix BL-3167 Clear button is often not disabled when it should be

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/953)
=> Fix BL-3078 Bubbles in simple front/back matter lost after 1st use

src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
This PR will merge into the RELEASE, 3.5
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/956)
=> Wasn't looking in the right place, at least for windows 10

DistFiles/infoPages/aboutBox-fr.htm, DistFiles/infoPages/aboutBox.htm, src/BloomExe/Program.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/957)
=> Bl3192 registration behind warning

src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js, src/BloomBrowserUI/bookEdit/js/bloomEditing.js, src/BloomBrowserUI/bookEdit/js/origami.js, src/BloomBrowserUI/package.json
Key thing is the addition of the css-element-queries library, which makes it possible to write selectors that declare a minimum width or height.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/961)
=> Making origami look better when boxes get small. BL-3210

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.jade, src/BloomBrowserUI/gulpfile.js, src/BloomBrowserUI/lib/toastr.css, src/BloomBrowserUI/lib/toastr.less, src/BloomBrowserUI/typings/toastr/toastr.d.ts, src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/packages.config, src/BloomExe/web/BloomWebSocketServer.cs, src/BloomExe/web/CommandAvailabilityPublisher.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/IRequestInfo.cs, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/SimpleHandler.cs, src/BloomTests/PretendRequestInfo.cs
This requries https://github.com/sillsdev/libpalaso/pull/363 first
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/959)
=> Bl3179 trim click noise

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/UserPrefs.cs, src/BloomExe/BookThumbNailer.cs, src/BloomExe/NonFatalProblem.cs
In a libpalaso PR, I'll fix the actual problem.
This introduces a way to report non fatal problems like this in different way depending on the channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/962)
=> (3.5) BL-3222 prevent crash if we can't save prefs

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/966)
=> Fix BL-3246 Talking Book Tool presents an error when it shouldn't

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/965)
=> Fix BL-3241 Dispose Web Socket

src/BloomBrowserUI/fixNodejsForLinux.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/NonFatalProblem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/972)
=> Fix Version 3.6 to compile on Linux

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/969)
=> Get Bloom V3.5 to build and run on Linux

src/BloomExe/NonFatalProblem.cs
This includes problems coming from the server handlers. Also made this report the exception to analytics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/976)
=> Allow NonFatalProblems that want to show toast work from non-ui thread

debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/978)
=> Update linux package to version 3.6 for Version3.6 branch

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/975)
=> Fix BL-3263 by closing the splash screen before showing dialogs

src/BloomExe/Book/BookData.cs, src/BloomExe/UrlPathString.cs, src/BloomTests/UrlPathStringTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/971)
=> Fix BL-3235 by re-encoding url encoded var before writing to xml

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/977)
=> Handle tag lib sharpt exceptions

src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/lib/split-pane/split-pane.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/989)
=> BL-3288 Show percentages on splitters

src/BloomExe/MiscUI/ToastNotifier.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/993)
=> Fix ToastNotifier crash on Linux (BL-3285)

src/BloomExe/ProjectContext.cs, src/BloomExe/web/ServerBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/992)
=> BL-3290 is mystery scenario; this is an experiment in fixing it

src/BloomExe/Properties/Resources.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/998)
=> Fix resource file for filename capitalization.

.gitignore, DistFiles/xMatter/bloom-xmatter-common.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/ePUB/baseEPUB.less
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1000)
=> Fix some filename case issues in .less files

debian/changelog, debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1005)
=> Update the Linux package version to 3.7 on master branch

src/BloomExe/BloomExe.csproj
I tested this on both Linux and Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1006)
=> Fix build to copy/rename BloomPdfMaker and related files

src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts, src/BloomBrowserUI/bookEdit/toolbox/leveledReader/leveledReader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1011)
=> BL-3320 Restore DR level and stage reliably

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomBrowserUI/webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1014)
=> Fix BL-3071 by putting all page-chooser dialog stuff together. Sheesh

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/Browser.cs, src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Extensions.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/Publish/PdfViewer.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/CommandAvailabilityPublisher.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/ServerBase.cs, src/BloomExe/web/WebLibraryView.cs, src/BloomTests/ImageProcessing/ImageServerTests.cs, src/BloomTests/PretendRequestInfo.cs, src/BloomTests/UpdateVersionTableTests.cs, src/BloomTests/web/BloomServerTests.cs, src/BloomTests/web/EnhancedImageServerTests.cs, src/BloomTests/web/RequestInfoTests.cs
BL-3313 Make Bloom look for open ports it can use
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1010)
=> Bl3313 adaptive port

src/BloomExe/Book/BookInfo.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1018)
=> Two little tweaks based on incoming bug reports today

src/BloomExe/InstallerSupport.cs, src/BloomExe/Program.cs, src/BloomExe/ToPalaso/FontInstaller.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1019)
=> Automatic font install shared

src/BloomExe/ProjectContext.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1022)
=> Fix port number selection (BL-3337)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1021)
=> BL-3314 broken usage of toastr hides More options

build/getDependencies-Linux.sh, debian/rules
Xenial uses ICU 55, so we have to include that dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1025)
=> Update dependencies for Ubuntu 16.04 Xenial

DistFiles/ReleaseNotes.md, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/css/bloomDialog.less, src/BloomBrowserUI/bookEdit/img/LineSpacing.svg, src/BloomBrowserUI/bookEdit/img/WordSpacing.svg, src/BloomBrowserUI/bookEdit/js/bloomBootstrap.js, src/BloomBrowserUI/package.json, src/BloomBrowserUI/tsd.json, src/BloomBrowserUI/typings/bundledFromTSC.d.ts, src/BloomBrowserUI/typings/jquery/jquery.d.ts, src/BloomBrowserUI/typings/select2/select2.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1026)
=> BL-3346 Allow arbitrary font sizes

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/ImageProcessing/ImageServer.cs, src/BloomExe/web/EnhancedImageServer.cs
- after book renamed, trying to update page thumbnails
- images referred to in templates not found in pageChooser folder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1032)
=> BL-3345 some problems with images not found

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/ToolboxView.cs
(One part of a disabled method was still needed.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1034)
=> BL-3354 Need to remember toolbox is open

debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1038)
=> Fix for renamed andika package on xenial

src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.d.ts, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/bloom_lib.js, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/libSynphony/synphony_lib.js, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerTools.ts, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1029)
=> BL-3330, update display when sample words change

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/bookEdit/js/bloomFrames.ts, src/BloomBrowserUI/bookEdit/toolbox/decodableReader/decodableReader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1040)
=> BL-3331 Re-enable draggable and resizable for reader setup

src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1042)
=> BL-3387 Don't choke if image is to big to save as jpeg

src/BloomBrowserUI/bookEdit/toolbox/decodableReader/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1044)
=> Fix BL-3390 where leveled reader panel would be 11 pixels heigh

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1046)
=> BL-3360 Don't try to show format gear until CkEditor finishes loading

src/BloomExe/InstallerSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1048)
=> BL-3342 Fix installing Andika last for allUsers

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/Workspace/WorkspaceView.cs
Also, BL-3363, allUsers install just says admin manages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1049)
=> BL-3052 Notify if no updates available if user requested check

DistFiles/factoryCollections/Sample Shells/Vaccinations/previewMode.css, src/BloomBrowserUI/bookEdit/js/bloomFrames.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.jade, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxSettings/toolboxSettingsToolboxPanel.jade, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Edit/ToolboxView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1052)
=> Fix BL-3393 and various cleanups around panels

src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxPanel.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools_libSynphonySpec.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1053)
=> BL-3335 Make ReaderToolsModel fully global

src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomExe/BloomExe.csproj, src/BloomExe/ProjectContext.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/controllers/ExternalLinkController.cs
Now there is a proper api controller for exeternal links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1051)
=> Fix BL-3332 so Leveled reader external links work. Remove need for JS

src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1059)
=> BL-3398 Allow user to specify max for average wds in sentence

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/DecodableReaderTool.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/InstallerSupport.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/web/ApiRequest.cs, src/BloomExe/web/ReadersApi.cs, src/BloomExe/web/ServerBase.cs, src/BloomTests/web/ApiTest.cs, src/BloomTests/web/EndpointHandlerTests.cs, src/BloomTests/web/ReadersApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1061)
=> Leftovers from PR# 1020

src/BloomBrowserUI/ePUB/baseEPUB.less
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1062)
=> Fix a filename capitalization error (needed for Linux)

src/BloomBrowserUI/npm-shrinkwrap.json, src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1065)
=> shrink-wrap npm dependencies

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1067)
=> BL-2749 handle sight words separated by newlines

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1071)
=> Fix tests that were failing on Linux

debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1082)
=> Update version number to 3.8 for Linux packages on master

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1092)
=> BL-2795 Report-a-problem should include book by default

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1100)
=> merge spanish fix

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/BloomExe.csproj, src/BloomExe/ProjectContext.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/controllers/KeybordingConfigAPI.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1099)
=> Fix BL3457 Longpress Shortcuts

src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1102)
=> Fix BL-3499 don't complain about missing favicon.ico and .map files

src/BloomBrowserUI/pageChooser/page-chooser.ts
While diagnosing, I ended up switching to axios, thought that didn't end up being part of the problem. Pro Tip: in FF debugger, need to inspec "_this" instead of "this" to see the object of the outerscope in a lamda.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1094)
=> Fix PageChooser bugs Bl-3473 and BL-3476

src/BloomExe/Publish/BloomLibraryPublishControl.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/Workspace/WorkspaceView.cs
(And disable various controls during upload.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1093)
=> BL-3085 Allow Cancelling upload

src/BloomExe/Browser.cs
This fixes the initial problem report.  I'm not sure whether it fixes
the later two reports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1114)
=> Ensure proper initialization of Geckofx45 (BL-3523)

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1115)
=> Add build/AWSSDK.dll to .gitignore

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettingsToolboxPanel.jade, src/BloomExe/BloomExe.csproj, src/BloomExe/ProjectContext.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/BookSettingsApi.cs, src/BloomExe/web/controllers/CurrentBookHandler.cs, src/BloomExe/web/controllers/ImageApi.cs
BL-3529
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1106)
=> Template book UI+API

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, src/SquirrelInstaller/Bloom.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1119)
=> Remove GeckoFx 29 and xulrunner from installer and getDependencies

src/BloomExe/BloomFileLocator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1124)
=> Fix check for installed files on Linux (BL-3047)

build/getDependencies-Linux.sh, build/getDependencies-windows.sh
This is needed especially for jenkins package building.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1126)
=> Fix the get dependency scripts for wget

src/BloomExe/BloomExe.csproj, src/BloomExe/packages.Linux, src/BloomExe/web/EnhancedImageServer.cs
Also a small fix needed for developer machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1127)
=> Fixes for memory leak on Linux (BL-2786)

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1128)
=> Correct some more lookups for processing source language tabs (BL-3538)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/CLI/HydrateBookCommand.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Program.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/CLI/HydrateBookCommandTests.cs
Initial ability to say "Bloom hydrate --preset app --bookpath..."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1132)
=> Add Hydrate Command Verb

src/BloomExe/web/I18NHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1139)
=> Don't annoy users with untranslated strings (BL-3598)

src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.jade, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/DataSet.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/CLI/HydrateBookCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1138)
=> Add background audio attributes to title page

build/getDependencies-Linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1140)
=> Add BloomPlayer to downloaded dependencies for Linux

src/BloomExe/BloomExe.csproj, src/BloomExe/CLI/DownloadBookCommand.cs, src/BloomExe/Program.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/WebLibraryIntegration/IProgressDialog.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1137)
=> BL-3560 Command-line download of books

src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1143)
=> Fix Linux build for not having Naudio

src/BloomExe/CLI/HydrateBookCommand.cs, src/BloomTests/CLI/HydrateBookCommandTests.cs
Also implemented national languages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1148)
=> Follow up on clean up of some hydrate code

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/CLI/GetUsedFontsCommand.cs, src/BloomExe/Program.cs, src/BloomExe/Publish/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1147)
=> Implement getfonts Command

src/BloomBrowserUI/xMatter/bloom-xmatter-mixins.jade, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1151)
=> Correctly update the language name when the user changes it in settings (BL-3599)

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1155)
=> Fix BL361 by filtering userPrefs. Also filter bloompacks from upload

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1158)
=> Enable 'Listen to the whole page' only if there is audio (BL-3655)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.less, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1161)
=> Remove extraneous vertical scrollbars from Reader Setup Dialog (BL-3701)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1162)
=> Fix broken text vs picture selection caused by BL-3555 (BL-3711)

src/BloomExe/web/I18NHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1172)
=> Improve notification of missing TMX string

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This could use another round of work someday. See comments in BL-3663 for future work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1168)
=> Fix BL-3663 Longpress positioning (mostly)

src/BloomExe/BloomExe.csproj, src/BloomExe/MiscUI/ProblemReporterDialog.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/WebLibraryIntegration/AccessKeys.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/WebLibraryIntegration/ProblemBookUploader.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs, src/BloomTests/WebLibraryIntegration/ProblemBookUploaderTests.cs
Large books were failing to attach to youtrack issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1176)
=> Submit problem books to S3 instead of youtrack (BL-3729)

src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/ServerBase.cs, src/BloomTests/web/RequestInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1178)
=> Properly decode special characters in URLs (BL-3750)

src/BloomExe/Book/BookData.cs, src/BloomExe/Browser.cs, src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1179)
=> Don't bother user if something is looking for a page we just left (BL-3769)

src/BloomExe/web/EnhancedImageServer.cs
From the stacktrace, I saw that the contention was in the Clone(). This image is cached by the thumbnailer, so it appears that multiple server threads were asking for the same image and being cloned at the same time. But the Clone() itself appeared to be a previous attempt at preventing this kind of error, probably in the Save(). A better solution, it seems to me, is to lock() on the image  while we save it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1183)
=> "Object is currently in use elsewhere" making thumbnails

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Browser.cs, src/BloomExe/web/I18NHandler.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1186)
=> Add strings for L10N and improve reporting of missing strings (BL-3795)

src/BloomExe/Edit/Configurator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1190)
=> Fix initialization of Wall Calendar "books" (BL-3573)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.less, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettingsToolboxPanel.jade, src/BloomBrowserUI/bookEdit/toolbox/toolbox.jade, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1189)
=> Add "Reset Zoom" link (fix BL-3805)

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Palaso.en.tmx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/origami.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxPanel.jade, src/BloomBrowserUI/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1191)
=> More improvements for L10N after reviewing Nepali (BL-3795)

src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1195)
=> Fix a Linux crash introduced by an earlier fix for BL-3782.

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1196)
=> Prevent an illegal cast seen by a user (BL-3796)

src/BloomExe/web/controllers/PageTemplatesApi.cs
Also remove some now redundant locking.  (The lock(SyncObj) in
EnhancedImageServer.ProcessRequest() handles the thread safety at
a much coarser granularity.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1200)
=> Fix a deadlock situation on Linux/Mono (BL-3818)

DistFiles/factoryCollections/Templates/Big Book/BigBook.css, DistFiles/factoryCollections/Templates/Big Book/BigBook.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1207)
=> BL-3788 Fix Big Book Instructions

DistFiles/IntegrityFailureAdvice-id.md, DistFiles/factoryCollections/Templates/Decodable Reader/ReadMe-id.md, DistFiles/factoryCollections/Templates/Leveled Reader/ReadMe-id.md, DistFiles/infoPages/TrainingVideos-id.md, DistFiles/leveledRTInfo/leveledReaderInfo-id.jade, DistFiles/localization/Bloom.id.tmx, DistFiles/localization/Palaso.id.tmx, src/BloomBrowserUI/xMatter/Factory-XMatter/description-id.txt, src/BloomBrowserUI/xMatter/Traditional-XMatter/description-id.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1212)
=> Indonesian UI strings from TransGlobal for URC

src/BloomTests/Book/BookTestsBase.cs
Added IBookStorage method needed moq'ing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1219)
=> BL-3778 Fix broken xmatter tests

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1223)
=> Check for internet before accessing it and hanging (BL-3840)

src/BloomExe/web/ServerBase.cs, src/BloomTests/web/RequestInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1224)
=> BL-3808 fix Network problem

src/BloomExe/web/UrlLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1225)
=> Fix broken unit tests by hard-coding the url for unit tests (BL-3853)

src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/web/UrlLookup.cs
This should more robustly handle missing or intermittent internet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1227)
=> Move check for internet to UrlLookup.TryLookupUrl (BL-3840)

src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1230)
=> Hide ePUB radio button on Linux for Bloom 3.7 (BL-3858)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1231)
=> BL-3861 Add 0.7 and 0.8 line spacing

DistFiles/localization/Palaso.en.tmx, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1228)
=> Allow newlines in license descriptions and notes (BL-3832)

src/BloomExe/web/BloomWebSocketServer.cs
We had only one report of this, and can't reproduce it. The addition here is a conservative action that could maybe help, since it's very likely we were sending on the socket on one thread while another was closing it down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1234)
=> Maybe help with websocketserver not closing (BL-3850)

src/BloomExe/RobustIO.cs, src/BloomTests/Book/BookTestsBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1238)
=> Update Bloom to reflect changed namespace of RetryUtility

src/BloomExe/Book/BookInfo.cs, src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1237)
=> Fix BL-3774 by converting null titles to empty strings

build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1239)
=> Leave pdb file name as Bloom.pdb (BL-3879)

src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1240)
=> Update book before publishing to get latest collection settings (BL-3881)

src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1242)
=> BL-3828 untruncate source bubbles

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/web/I18NHandler.cs
* Integer keys swallowed
* 'none' swallowed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1241)
=> BL-3821 Swallow bad L10N keys

.gitignore, build/makeWindowsInstaller.bat, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config, src/SquirrelInstaller/Bloom.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1245)
=> Remove moq.dll from installer and cleanup other dependencies

src/BloomExe/ResolveShortcut.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1246)
=> Fix Linux build for Bloom master branch

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1218)
=> Stop new Bloom after downloading if called from Bloom (BL-3822)

src/BloomExe/ResolveShortcut.cs
This is a cherry-pick from the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1247)
=> Fix Linux build for Bloom 3.7 branch

src/BloomExe/Publish/EpubMaker.cs
Also hoping this helps with locked files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1249)
=> Properly dispose of WafeFileReader

src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1252)
=> Merge Version3.7 into master

src/BloomExe/NonFatalProblem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1262)
=> Add stacktrace to non-exception NonFatalProblem reports BL-3911

src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1264)
=> Fix reporting bug (related to BL-3905)

build/Bloom.proj, src/BloomTests/packages.config
- use new NUnit3 task (https://github.com/sillsdev/libpalaso/pull/405)
- add NUnit.ConsoleRunner nuget package as dependency of test project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1259)
=> Use NUnit 3 for running tests when building from command line

.gitignore, build/install-deps
We want to install any Ubuntu packages in non-interactive mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1258)
=> Improve install-deps

build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1267)
=> Attempt to fix NUnit3 test runner on TC

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1270)
=> Deobfuscate a log message from BookStorage.Update() (BL-3910)

src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/SuperPaperSaver-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1271)
=> Correct SuperPaperSaver to Super Paper Saver (BL-3915)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1273)
=> Fix BL-3900 where markup and longpress were interfering to delete text

src/BloomBrowserUI/bookEdit/toolbox/readers/jquery.div-columns.ts, src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1274)
=> Upgrade to typescript 2.0 and fix resulting compile error (BL-3885)

src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1276)
=> Slightly different image transparency removal which works on Linux

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomExe/web/UrlLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1280)
=> Point parse-server unit tests at new azure unit-test app.

src/BloomExe/Workspace/WorkspaceView.cs
Note that this is only the master branch (version 3.8).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1282)
=> Ensure menu hidden for Report A Problem screenshot (BL-3792)

src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1281)
=> Show only toast for missing image files (BL-3938)

src/BloomExe/Workspace/WorkspaceView.cs
to sending the offending book
* this was merged to master in June, now to put it in
3.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1284)
=> BL-2795 Make 'Report a Problem' default

DistFiles/IntegrityFailureAdvice-ha.md, DistFiles/factoryCollections/Templates/Decodable Reader/ReadMe-ha.md, DistFiles/factoryCollections/Templates/Leveled Reader/ReadMe-ha.md, DistFiles/infoPages/TrainingVideos-ha.md, DistFiles/leveledRTInfo/leveledReaderInfo-ha.jade, DistFiles/localization/Bloom.ha.tmx, DistFiles/localization/Palaso.ha.tmx, src/BloomBrowserUI/xMatter/Factory-XMatter/description-ha.txt, src/BloomBrowserUI/xMatter/Traditional-XMatter/description-ha.txt
Cleaned up pull request with only 1 commit. Thank you Steve!!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1286)
=> Add Hausa localiation files from TransGlobal work

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1289)
=> Fix failing js unit test

src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1292)
=> Reload sample word lists after dialog OK (BL-3496)

DistFiles/factoryCollections/Templates/Decodable Reader/ReadMe-ha.md, DistFiles/leveledRTInfo/leveledReaderInfo-ha.jade
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1294)
=> Updates to Hausa translations

src/BloomExe/Resources/current-service-urls.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1296)
=> Update URL for development parse server

src/BloomExe/Publish/BloomLibraryPublishControl.Designer.cs, src/BloomExe/Publish/BloomLibraryPublishControl.cs, src/BloomExe/Publish/BloomLibraryPublishControl.resx
* if signed in for upload, display email address (user Id)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1297)
=> BL-3896 Display Id if signed in

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1300)
=> BL-3871 Fix Js error causing CKEditor popup

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1305)
=> Allow Add Page dialog after setting up reader (BL-3962)

src/BloomBrowserUI/lib/ckeditor/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1308)
=> Prevent losing recorded audio while maintaining paste filter in ckeditor (BL-3976) - NEEDS 3.7 RISK ANALYSIS

src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/controllers/BrandingApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1307)
=> Prevent validation warning 'Image /bloom/api/branding/image is missing' (BL-3975) - DO NOT MERGE WITHOUT 3.7 RISK ANALYSIS

src/BloomExe/Book/Page.cs, src/BloomExe/Edit/WebThumbNailList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1303)
=> Fix L10N scenario when page does not have a caption

DistFiles/localization/Bloom.en.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1309)
=> Add missing localizations for toolbox settings (BL-3958)

src/BloomExe/Resources/current-service-urls.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1315)
=> Update fallback url for parse server

src/BloomExe/BloomExe.csproj
This cleans up the csproj file a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1316)
=> Remove premature references to Mercurial on Linux

src/BloomExe/Publish/PublishView.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1313)
=> Allow room for localized "Save PDF..." (BL-3995)

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.cs
This will allow us to actually count unique books created vs. published in some form (epub, print, save as pdf), per country, if any of those events happen while online.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1319)
=> Add country and bookid to key analytics events

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/CollectionSettingsDialog.resx, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookCollectionTests.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
* in Settings dialog BookMaking tab
* the combo label and the combo contents are
localizable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1323)
=> BL-3960 Add Page Number style selector

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1326)
=> BL-3983 Message on Copy failed

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Palaso.en.tmx
This is first step. Simply sort the .TMX files based on @tuid to better track future changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1329)
=> Sort on English @tuid elements

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Palaso.en.tmx, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade, src/BloomExe/Book/Book.cs, src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Collection/BloomPack/BloomPackInstallDialog.cs, src/BloomExe/CollectionCreating/KindOfCollectionControl.resx, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/MakeReaderTemplateBloomPackDlg.resx, src/BloomExe/Edit/EditingView.Designer.cs, src/BloomExe/Edit/JpegWarningDialog.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/Publish/BloomLibraryPublishControl.Designer.cs, src/BloomExe/Publish/BloomLibraryPublishControl.cs, src/BloomExe/Publish/PublishView.Designer.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/WebLibraryIntegration/LoginDialog.cs, src/BloomExe/Workspace/WorkspaceView.Designer.cs
Sync source strings with TMX strings as appropriate.
This pull request completes English string updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1332)
=> Update English TMX files with missing strings.

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1333)
=> BL-4025 Fix ISBN label and number alignment

DistFiles/ReleaseNotes.md, DistFiles/factoryCollections/Templates/Wall Calendar/Wall Calendar.htm, DistFiles/factoryCollections/Templates/Wall Calendar/Wall Calendar.jade, src/BloomExe/Book/XMatterHelper.cs, src/BloomTests/Book/XMatterHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1341)
=> Insert flyleaf when needed for page spread BL-3040

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1337)
=> Save formatting changes even if page deleted BL-40535

DistFiles/IntegrityFailureAdvice-fr.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Decodable Reader/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Leveled Reader/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-fr.md, DistFiles/infoPages/TrainingVideos-fr.md, DistFiles/leveledRTInfo/leveledReaderInfo-fr.jade, DistFiles/localization/Bloom.fr.tmx, DistFiles/localization/Palaso.fr.tmx, src/BloomBrowserUI/ePUB/MissingLameModule-fr.jade, src/BloomBrowserUI/ePUB/bloomEpubPreview-fr.jade, src/BloomBrowserUI/xMatter/Factory-XMatter/description-fr.txt, src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-fr.txt, src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/description-fr.txt, src/BloomBrowserUI/xMatter/Traditional-XMatter/description-fr.txt
1. Align to English source XLF files
2. Add missing French localization files
3. Correct previous errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1336)
=> Update French localization:

DistFiles/IntegrityFailureAdvice-id.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-id.md, DistFiles/factoryCollections/Templates/Leveled Reader/ReadMe-id.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-id.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-id.md, DistFiles/leveledRTInfo/leveledReaderInfo-id.jade, DistFiles/localization/Bloom.id.tmx, DistFiles/localization/Palaso.id.tmx, src/BloomBrowserUI/ePUB/MissingLameModule-id.jade, src/BloomBrowserUI/ePUB/bloomEpubPreview-id.jade, src/BloomBrowserUI/xMatter/Factory-XMatter/description-id.txt, src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-id.txt, src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/description-id.txt
Add previously unlocalized files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1342)
=> Update Indonesian strings.

src/BloomExe/Collection/CollectionSettings.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
* bug left a zero in the upper left corner of every page
in Edit mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1346)
=> Fix small bug introduced with BL-3960

src/BloomExe/HtmlThumbNailer.cs, src/BloomExe/Publish/EpubMaker.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/ServerBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1345)
=> Fix ePUB on Linux (BL-3412)

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Palaso.en.tmx
This is needed as a precursor to merging 3.7 into master as this sorting has taken place on 3.7 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1347)
=> Sort English Tmx files by tuid

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1348)
=> Fix xenial (Linux) package building for new icu.net.dll

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Palaso.en.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1349)
=> Revert changes to English tmx file indentation size

.editorconfig
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1350)
=> Add basic .editorconfig file

src/BloomExe/web/ServerBase.cs
BL-3561, BL-4032,  BL-4033, BL-4034
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1352)
=> Catch errors we get when checking for Zone Alarm BL-4055

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1353)
=> Fix Help button in Leveled and Decodable Reader setup dialogs (BL-4046)

src/BloomExe/BookThumbNailer.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1358)
=> Ensure main thumbnail image is created/updated before upload (BL-3469)

src/BloomBrowserUI/pageChooser/page-chooser.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1361)
=> Allow user to restore original page layout (BL-3482)

src/BloomExe/web/UrlLookup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1362)
=> Correct unit test url for parse server to be https

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
* made sure all text is localizable
* moved Local Language radio button to top of group
* reworded Normal label
=> BL-4081 Tweak Text Box Properties dialog

src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1367)
=> Fix and unignore tests broken by BL4065 (BL-4062)

src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, src/BloomBrowserUI/bookEdit/js/origami.ts
to all text boxes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1369)
=> BL-4037 Add TextBox Properties dialog

src/BloomBrowserUI/bookEdit/pageThumbnailList/TemplatePagesThumbnailList.less, src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/templates/common-mixins.less, src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, src/BloomBrowserUI/templates/template books/Big Book/Big Book.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less, src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1374)
=> BL-4079 Add A3 and A5 Landscape sizes

src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, src/BloomBrowserUI/bookEdit/js/origami.ts
* always visible/active for each text box
whether old or newly created
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1375)
=> BL-4037 TextBox Properties cog changes

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1381)
=> Ensure help button stays visible on Linux (BL-3444)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
* to files I'm about to edit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1384)
=> Editor Config Changes

src/BloomExe/Publish/MakePdfUsingGeckofxHtmlToPdfProgram.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1390)
=> Catch exception when creating LocalPrintServer (BL-4060)

src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1392)
=> Fix Add Page for Arithmetic Template (BL-4112)

src/BloomBrowserUI/templates/bloom-foundation-mixins.pug, src/BloomBrowserUI/templates/template books/Big Book/Big Book.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1393)
=> Fix Big Book instructions (BL-4094)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1401)
=> Fix BL-4130 Title Page languages are reversed

DistFiles/factoryCollections/Templates/Big Book/ReadMe-ar.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-bn.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-en.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-id.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-ar.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-bn.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-en.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-id.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-ar.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-bn.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-en.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-fr.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-id.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1400)
=> Correct storing of issues email address and replace old bloom.palaso.org web address

DistFiles/IntegrityFailureAdvice-sw.md, DistFiles/factoryCollections/Templates/Big Book/ReadMe-sw.md, DistFiles/factoryCollections/Templates/Decodable Reader/ReadMe-sw.md, DistFiles/factoryCollections/Templates/Leveled Reader/ReadMe-sw.md, DistFiles/factoryCollections/Templates/Picture Dictionary/ReadMe-sw.md, DistFiles/factoryCollections/Templates/Wall Calendar/ReadMe-sw.md, DistFiles/infoPages/TrainingVideos-sw.md, DistFiles/leveledRTInfo/leveledReaderInfo-sw.jade, DistFiles/localization/Bloom.sw.tmx, DistFiles/localization/Palaso.sw.tmx, src/BloomBrowserUI/ePUB/MissingLameModule-sw.jade, src/BloomBrowserUI/ePUB/bloomEpubPreview-sw.jade, src/BloomBrowserUI/xMatter/Factory-XMatter/description-sw.txt, src/BloomBrowserUI/xMatter/SIL-Cameroon-XMatter/description-sw.txt, src/BloomBrowserUI/xMatter/SuperPaperSaver-XMatter/description-sw.txt, src/BloomBrowserUI/xMatter/Traditional-XMatter/description-sw.txt
Additional language for REACH project.
Text translated by TransGlobal and reviewed by SIL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1399)
=> Add Kiswahili localized resources.

src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/BookSettingsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1403)
=> Fix "allow changes to this shellbook"  BL-3621

DistFiles/localization/Bloom.ar.tmx, DistFiles/localization/Bloom.bn.tmx, DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx, DistFiles/localization/Bloom.fr.tmx, DistFiles/localization/Bloom.ha.tmx, DistFiles/localization/Bloom.id.tmx, DistFiles/localization/Bloom.ne.tmx, DistFiles/localization/Bloom.ru.tmx, DistFiles/localization/Bloom.sw.tmx, DistFiles/localization/Bloom.zh-Hans.tmx, src/BloomExe/Publish/BloomLibraryPublishControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1396)
=> BL-4018 Add (partial) to Chinese Localization

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1404)
=> Fix build for latest Linux Geckofx45 package

src/BloomExe/BloomExe.csproj
This fix is Linux specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1405)
=> Fix for Geckofx45 45.0.23.0 changing the name of the Firefox folder

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1409)
=> Remove extraneous ISBN fields (BL-4180)

src/BloomExe/web/BloomWebSocketServer.cs, src/BloomExe/web/CommandAvailabilityPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1410)
=> Treat failure to open WebSocketServer as a fatal error (BL-4113)

src/BloomBrowserUI/ePUB/MissingLameModule-en.pug, src/BloomBrowserUI/ePUB/MissingLameModule-fr.pug, src/BloomBrowserUI/ePUB/MissingLameModule-id.pug, src/BloomBrowserUI/ePUB/bloomEpubPreview-en.pug, src/BloomBrowserUI/ePUB/bloomEpubPreview-fr.pug, src/BloomBrowserUI/ePUB/bloomEpubPreview-id.pug, src/BloomBrowserUI/templates/bloom-foundation-mixins.pug
* made mixin for hyperlinks to handle spacing
(and periods after)
* fixed several minor problems with the indonesian
layout
* also updated ShareIt link (BL-4139). Oops, sorry about that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1395)
=> BL-4089/4139 Pug link and whitespace repairs

src/BloomExe/web/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1415)
=> Don't lose stacktrace in api-related exceptions (BL-4192)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1422)
=> Fix content type of "currentRecordingDevice" post in talking book

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/RobustIO.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1426)
=> BL-4148 Follow-up move robust image save to palaso

src/BloomExe/Book/BookStarter.cs
* When creating a book from a template, don't copy
the template's markdown files into the new
book folder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1427)
=> BL-4167 Filter out markdown files

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1431)
=> Fix display and function of device list (BL-4206)

src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1432)
=> BL-4160 Fix htm file search pattern

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1435)
=> Trim off extra 'Microphone (...)' wrapper around audio device names

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1437)
=> Handle older books which have CC urls with no version number (BL-4108)

src/BloomExe/CollectionTab/LibraryListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1440)
=> BL-4176 Fix InDesign menu visibility issue

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1439)
=> Ignore "conflict" files created by file sharing services (BL-4218)

build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1441)
=> Update getDependencies-windows.sh to use special libpalaso build

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookStarter.cs
Also fix build issue on Linux caused by new Geckofx45 nuget packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1450)
=> Fix problem creating book on Linux (tweak BL-4160 fix)

src/BloomExe/CLI/HydrateBookCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1456)
=> Enhance hydrate command to allow the creation of shell books (BL-4221)

debian/control
DO NOT MERGE THIS COMMIT ONTO ANOTHER BRANCH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1455)
=> Make bloom-desktop-alpha install lame (BL-4213)

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1460)
=> Add diagnostic messaging to evaluate random unit test failure (BL-4099)

src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.less, src/BloomBrowserUI/templates/template books/Arithmetic Template/ArithmeticTemplate.pug, src/BloomBrowserUI/templates/template books/standard-page-mixins.pug, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Command.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/web/controllers/AddOrChangePageApi.cs, src/BloomTests/Book/HtmlDomTests.cs
* revert initial solution (which moved .Equation-style to .less file)
* make sure User Modified styles used on the new page
get pulled into the new book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1448)
=> BL-4199 Make sure user-defined styles in a template page are copied to the destination book

src/BloomExe/Publish/BloomLibraryPublishControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1463)
=> Report to user when we cannot validate version for upload or lookup prior existence of book (BL-4171)

src/BloomBrowserUI/npm-shrinkwrap.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1470)
=> DO NOT MERGE WITH OTHER BRANCHES - NPM shrinkwrap for Version3.8 (BL-4257)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomExe/web/controllers/ImageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1465)
=> Add link label to collect and insert image credits (BL-4222)

src/BloomExe/MiscUI/ProblemReporterDialog.cs
If this looks safe enough, it might be backported to Version3.7.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1469)
=> Add reader info to user error reports if applicable (BL-4240)

src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1474)
=> Disable booklet printing for large pages (BL-4155)

src/BloomBrowserUI/bookEdit/js/origami.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1476)
=> Prevent deleting a box from losing page space (BL-4168)

src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1475)
=> Refactor TextBoxProperties to use pug (BL-4264)

src/BloomExe/BloomExe.csproj, src/BloomExe/Publish/AudioProcessor.cs, src/BloomExe/Publish/ElectronicPublishView.cs, src/BloomExe/Publish/EpubMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.cs, src/BloomTests/Publish/ExportEpubTests.cs
Factor out audio processing from Epubmaker so BloomReaderMaking can use. Factors out some of the epub stuff too. Also fixes BL-4182. Maybe not ideal or complete, but it's been languishing on my machine for too long, getting dangerous.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1480)
=> More separating of  some epub stuff from pdf

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1481)
=> Refactor StyleEditor to use pug (BL-4264)

src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1483)
=> Cancel displaying replaced simulated files (BL-4268)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomExe/Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1482)
=> BL-4256 Add 'Reset Style' link to StyleEditor

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1489)
=> Fix reader panel collapsing (BL-4272)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
* factored out a GetBaseStyleNameForElement that
strips off '-style'
* font-size select wasn't picking up the stored value
* factored out code to set dialog values to current
style and used it for resetStyle:
UpdateControlsToReflectAppliedStyle()
* added paragraph spacing control to above method
* StyleEditor wasn't being updated to reflect style reset
after the reset link was clicked
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1486)
=> BL-4256 Fix several StyleEditor bugs

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1491)
=> Add test for sentence-breaking on space (BL-4247)

debian/rules
I don't why it suddenly quit working, but it was failing consistently
the same way on both jenkins and my local machine.
DO NOT MERGE WITH OTHER BRANCHES.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1492)
=> Fix Bloom 3.7 Linux package building

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.jade, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.less, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1497)
=> Remove sentence-ending punctuation control from Decodable Reader (BL-4247)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1498)
=> Direct the help button on the Punctuation tab to the correct topic (BL-4247)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/PageMigrationTests.cs
* First commit is tslint stuff in StyleEditor.ts
* Second commit is c# fix for userModifiedStyles in the case where
the book didn't have that style element, or that element was
corrupted by data from the coverColor element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1496)
=> BL-4266 Fix bug in userModifiedStyles

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
* some type adjustments
* make tslint happier (line length, braces, parseInt radix, etc.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1499)
=> StyleEditor tslint adjustments

DistFiles/localization/Bloom.en.tmx
This file is current with all strings in Version 3.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1503)
=> Correct English .TMX sort and add missing strings.

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1506)
=> Fix filename case problem introduced last week

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1509)
=> Add Superscript for localization (BL-4096)

DistFiles/localization/Bloom.fr.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1511)
=> Add French for Superscript (BL-4096)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1510)
=> Fix broken talking book tool (BL-4298)

src/BloomExe/Publish/EpubMaker.cs, src/BloomExe/Publish/FontFileFinder.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1513)
=> BL-4202 Don't ever embed bold or italic fonts

src/BloomExe/Shell.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1514)
=> Prevent endless restarting on Linux (BL-4304)

DistFiles/localization/Bloom.ar.tmx, DistFiles/localization/Bloom.bn.tmx, DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx, DistFiles/localization/Bloom.fr.tmx, DistFiles/localization/Bloom.ha.tmx, DistFiles/localization/Bloom.id.tmx, DistFiles/localization/Bloom.lo.tmx, DistFiles/localization/Bloom.ne.tmx, DistFiles/localization/Bloom.ru.tmx, DistFiles/localization/Bloom.sw.tmx, DistFiles/localization/Bloom.th.tmx, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxPropertiesSpec.ts, src/BloomBrowserUI/bookEdit/css/bloomDialog.less, src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1504)
=> Add Borders and Background tab to TextBoxProperties (BL-4238,BL-4239)

src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1519)
=> Remove blank pages from ePUB books (BL-4288)

src/BloomBrowserUI/ePUB/baseEPUB.less, src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1521)
=> Stop ePUB paragraphs from showing in columns (BL-4320)

src/BloomExe/Publish/EpubMaker.cs
This looks safe to me for 3.7, but the rest of the team needs to agree
with that assessment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1525)
=> Display branding images in ePUBs (BL-4323)

src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1529)
=> Fix ePUB check for blank pages to handle branding images (BL-4323)

src/BloomExe/Publish/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1530)
=> Add svg image handling to ePUBs (BL-4323)

src/BloomExe/Publish/EpubMaker.cs
This cleans up and reorganizes the code a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1536)
=> Check background image for non-blank ePUB page (BL-4347)

src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookInfo.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1541)
=> Allow for multiple meta tags (BL-4283)

src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomExe/Browser.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/web/EnhancedImageServer.cs
Also fixes a couple of the more commonly occurring ones
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1543)
=> BL-4301 report JavaScript errors

DistFiles/localization/Bloom.en.tmx, src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1547)
=> Fix a couple of toast localizations (BL-4151)

src/BloomBrowserUI/templates/template books/Template Starter/Template Starter.pug, src/BloomBrowserUI/templates/xMatter/TemplateStarter-XMatter/TemplateStarter-XMatter.less, src/BloomBrowserUI/templates/xMatter/TemplateStarter-XMatter/TemplateStarter-XMatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/TranslationGroupManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1546)
=> Custom XMatter for Template Starter

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1545)
=> Add some missing localization strings (BL-4115,4116,4120)

src/BloomExe/Book/BookStarter.cs, src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1548)
=> Clear out old page description when adding page

DistFiles/localization/Bloom.en.tmx, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.designer.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.resx, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1542)
=> Change UI language in Collection Chooser (BL-4307)

src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md, src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1552)
=> Don't get stuck with out of date template thumbnails

src/BloomExe/web/controllers/PageTemplatesApi.cs, src/BloomTests/web/controllers/PageTemplatesApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1549)
=> Dont list same template twice if found in two ways BL-4383

DistFiles/ReleaseNotes.md, DistFiles/localization/Bloom.en.tmx, src/BloomExe/Command.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PageListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1555)
=> Copy/Paste Pages BL-4327

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1553)
=> Disallow page labels that would make for problematic file names BL-4392

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomTests/Book/XMatterHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1544)
=> Allow books to specify XMatter (BL-4363)

DistFiles/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1562)
=> Correct two lines in the Release Notes

src/BloomExe/Program.cs, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1558)
=> Set the UI language from the system if possible (BL-4393)

src/BloomTests/Book/XMatterHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1565)
=> Fix failing unit test that somehow didn't fail on Linux

DistFiles/localization/Bloom.en.tmx, src/BloomExe/CollectionCreating/NewCollectionWizard.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1567)
=> Correct L10N ID for the finish page content so it isn't a duplicate (BL-4395)

src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/Wizard/WinForms/WizardPage.cs, src/BloomExe/Wizard/WizardAdapterControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1568)
=> Dispose of WizardPages when NewCollectionWizard is disposed (BL-4434)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1571)
=> Focus the New Style input element when enabled (BL-4411)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1572)
=> Hide hanging indent option (BL-4435)

src/BloomExe/CollectionChoosing/OpenAndCreateCollectionDialog.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/Wizard/WinForms/WizardControl.cs, src/BloomExe/Wizard/WinForms/WizardPage.cs, src/BloomExe/Wizard/WizardAdapterControl.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1563)
=> Add UI language picker to the New Collection Wizard (BL-4391)

DistFiles/localization/Bloom.en.tmx, src/BloomExe/web/controllers/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1575)
=> Display file error in ApiRequest as toast (BL-4425)

DistFiles/localization/Bloom.en.tmx, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts, src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1561)
=> BL-4344 Allow hint bubbles per field

src/BloomExe/Book/BookStorage.cs
Please don't merge into master, we have a better way there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1579)
=> BL-4340 Detect null file and try to restore backup

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1582)
=> BL-4340 Allow template starter books to have no pages

DistFiles/localization/Bloom.en.tmx, src/BloomExe/CollectionTab/LibraryListView.Designer.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomTests/CollectionTab/TestLibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1588)
=> Add book level Make Bloom Pack menu command (BL-4442)

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1591)
=> Rename key, add string to TMX (BL-4455)

DistFiles/localization/Bloom.ar.tmx, DistFiles/localization/Bloom.bn.tmx, DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx, DistFiles/localization/Bloom.fr.tmx, DistFiles/localization/Bloom.ha.tmx, DistFiles/localization/Bloom.id.tmx, DistFiles/localization/Bloom.ne.tmx, DistFiles/localization/Bloom.ru.tmx, DistFiles/localization/Bloom.sw.tmx, DistFiles/localization/Bloom.zh-Hans.tmx, src/BloomExe/CollectionTab/LibraryListView.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1595)
=> Change "Copy Book" to "Duplicate Book" (BL-4458)

src/BloomExe/BloomExe.csproj, src/BloomExe/MiscUI/InstallationFailedDialog.Designer.cs, src/BloomExe/MiscUI/InstallationFailedDialog.cs, src/BloomExe/MiscUI/InstallationFailedDialog.resx, src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1593)
=> If installation fails, user receives a link to the installation troubleshooter (BL-4052)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1585)
=> Remember user-defined styles while editing (BL-4438)

src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.pug, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1598)
=> BL-4344 Show hint bubbles tab only in template

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/BookCopyrightAndLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1600)
=> Base credits page original language phrases on national lang 1

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1602)
=> localization of separators between country, province, district BL-3446

src/BloomExe/MiscUI/ToastNotifier.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1603)
=> BL-4380 Close toast windows when done with

src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomExe/BookThumbNailer.cs, src/BloomExe/HtmlThumbNailer.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1607)
=> BL-4461 Fix redoing current template thumbs on AddPage

src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1599)
=> BL-4344 hint bubbles handle missing data-default-languages

src/BloomBrowserUI/templates/template books/Template Starter/Template Starter.pug, src/BloomExe/Book/BookStarter.cs, src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1608)
=> Don't pass on <meta> for xmatter to child books BL-4467

DistFiles/localization/Bloom.en.tmx, src/BloomExe/web/controllers/ApiRequest.cs
This is a cherry-pick from the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1615)
=> Display file error in ApiRequest as toast (BL-4425) (#1575)

src/BloomExe/Collection/BookCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1621)
=> BL-4477 Don't allow xmatter folders as sources for books

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1618)
=> BL-4471 Direct user to help with file permissions

src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1623)
=> Found another spot in 3.8 reading meta.xmatter

DistFiles/localization/Bloom.en.tmx, src/BloomExe/Book/BookStorage.cs
Idea is to make it potentially useful in other contexts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1625)
=> BL-4471 generalize "See url" message

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1626)
=> Fix Linux layout problem with Choose Collection dialog (BL-4409)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/BookStarter.cs, src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1624)
=> BL-4483 Books made from templates should use default license

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/ePUB/baseEPUB.less, src/BloomBrowserUI/ePUB/epubVisibility.less, src/BloomExe/Publish/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1617)
=> Remove (rather than only display:none) certain elements before creating ePub (BL-4348)

src/BloomExe/Book/BookStarter.cs, src/BloomExe/Publish/BloomLibraryPublishControl.cs
also a tweak to finish BL-4372 allowing CC0 books
to be uploaded without copyright
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1632)
=> BL-4527 Fix books from Template Starter should be CC0

src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1628)
=> Retain TemplateStarter betweeen 3.9 to 3.8 and back (BL-4491)

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1637)
=> Ensure "Copy Page" copies recent changes (BL-4512)

src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1638)
=> Don't show old PDF while creating new PDF or ePUB (BL-4518)

DistFiles/localization/Bloom.es.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1647)
=> Add and correct several Spanish translations (BL-4530)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1630)
=> Fix undefined language in xMatter and group bubbles (BL-4487)

src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1648)
=> Don't treat book added to source collection as a derivative BL-4497

src/BloomBrowserUI/templates/xMatter/TemplateStarter-XMatter/TemplateStarter-XMatter.pug, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomTests/Book/TranslationGroupManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1645)
=> Rethink what langs to give fields for when making template BL-4522

src/BloomBrowserUI/templates/common-mixins.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1652)
=> A stylesheet-only approach to separating items BL-4515

src/BloomExe/web/EnhancedImageServer.cs
* if the user installs a collection in a non-standard
location, more work was needed to handle
thumbnail updates and AddPage dialog thumbs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1654)
=> BL-4543 Server could not find image

src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1657)
=> Allow nodejs version 6.10.2+ as well as 6.10.1

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1655)
=> BL-4556 Get Original Contributors copied

src/BloomExe/InstallerSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1660)
=> Fix new windows installer code to compile on Linux

src/BloomExe/Book/BookData.cs
Catch null object introduced by fix for
originalContributions (BL-4556)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1659)
=> Fix UpdateDomFromDataSet

DistFiles/localization/Bloom.fr.tmx, src/BloomExe/InstallerSupport.cs
This has a null merge from Version3.8 for the Linux packaging changes plus a cherry-pick of the fix for Linux of the new Windows installer/updater code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1661)
=> Merge from3.8

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/BloomExe.csproj, src/BloomExe/ProjectContext.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/KeyboardingConfigApi.cs
* 1st commit is just cleanup
misspelled class
case problem in api call between cs and ts
* 2nd commit changes alert to console.log
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1664)
=> BL-4583 Fix locking useLongPress query message

DistFiles/IntegrityFailureAdvice-pt.md, DistFiles/infoPages/TrainingVideos-pt.md, DistFiles/localization/Bloom.pt.tmx, DistFiles/localization/Palaso.pt.tmx, src/BloomBrowserUI/ePUB/bloomEpubPreview-pt.pug, src/BloomBrowserUI/templates/template books/Big Book/ReadMe-pt.md, src/BloomBrowserUI/templates/template books/Decodable Reader/ReadMe-pt.md, src/BloomBrowserUI/templates/template books/Leveled Reader/ReadMe-pt.md, src/BloomBrowserUI/templates/template books/Picture Dictionary/ReadMe-pt.md, src/BloomBrowserUI/templates/template books/Wall Calendar/ReadMe-pt.md, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1665)
=> Add Portuguese localization based on work in crowdin

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1656)
=> Ensure & in copyright notice is handled for shell books (BL-4585)

DistFiles/localization/Bloom.zh-CN.tmx, DistFiles/localization/Palaso.zh-CN.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1668)
=> Improvements for Chinese L10N (BL-3691, BL-4091)

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1670)
=> Add Spanish localization of newer page layouts (BL-4637)

DistFiles/infoPages/aboutBox-fr.htm, DistFiles/infoPages/aboutBox.htm, src/BloomExe/SplashScreen.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1671)
=> [3.8]Update end Copyright date in AboutBox and Splash screen

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1672)
=> Add Spanish localization of A3Landscape layout (BL-4637)

src/BloomExe/web/BloomWebSocketServer.cs, src/BloomExe/web/CommandAvailabilityPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1673)
=> [3.8]BL-4605 Change message for websocket port problem

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
consists of 2 commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1676)
=> [3.8]BL-4556 Cherrypick fix from 3.9

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
Some old books had an XML img tag embedded in
the html-encoded background-image url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1663)
=> BL-4586 Handle oddly encoded background image

src/BloomBrowserUI/templates/bloom-foundation-mixins.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1678)
=> Fix loss of front cover credits going to Bloom 3.8 (BL-4591)

DistFiles/localization/Bloom.ru.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1680)
=> BL-4603 Add Russian localizations for new Credits page

src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1681)
=> BL-4643 Handle special characters in user name

src/BloomTests/Book/BookInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1684)
=> ReflectionHelper moved from SIL.Windows.Forms assembly to SIL.Core

src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1685)
=> Handle null Language3Iso639Code in LicenseDescriptionLanguagePriorities (BL-3691)

DistFiles/infoPages/aboutBox.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1686)
=> BL-4662 Fix AboutBox to work with Palaso

src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1688)
=> Fix unwanted multilingual display in MXB xmatter (BL-4614)

DistFiles/localization/Bloom.zh-CN.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1690)
=> Add zh-CN localizations for TextBoxProperties (BL-4587)

DistFiles/infoPages/aboutBox-fr.htm
* added same tags to french html file as the english
* translated 'Thanks'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1691)
=> Update french aboutbox file

src/BloomExe/Publish/BloomLibraryPublishControl.Designer.cs, src/BloomExe/Publish/PublishView.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1692)
=> Tweak upload controls to not scare users (BL-4661)

src/BloomBrowserUI/templates/customXMatter/ReleaseProcess.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1693)
=> Add Custom XMatter pack release documentation

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Publish/AudioProcessor.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs, src/BloomTests/CollectionTab/TestLibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1677)
=> Add BookCompressor (BL-4647)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1689)
=> Bl 4587original credits update

DistFiles/localization/Bloom.es.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1702)
=> Add Spanish localizations for new credits page text (BL-4589)

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1703)
=> Fix problem in building Linux packages on master

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/checkStorySpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1705)
=> Handle edge case in which last remaining unknown letter was part of digraph (BL-4720)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditorSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
* Also ignore failing and obsolete test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1712)
=> BL-4727 Remember for this Level fix

src/BloomExe/Workspace/ZoomControl.Designer.cs, src/BloomExe/Workspace/ZoomControl.cs
* Also used En-dash instead of hyphen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1715)
=> BL-4733 Enlarge Zoom Buttons

Bloom.sln, debian/bloom-alpha, src/BloomExe/Program.cs, src/LinuxBloomLauncher/BloomLauncher.c, src/LinuxBloomLauncher/BloomLauncher.gresource.xml, src/LinuxBloomLauncher/LinuxBloomLauncher.cproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1709)
=> Create Linux launcher to show instant splash screen (BL-4666)

src/LinuxBloomLauncher/LinuxBloomLauncher.cproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1718)
=> Fix build problems introduced by LinuxBloomLauncher

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1719)
=> Fix Linux package build for executable BloomLauncher

.gitignore, .nuget/NuGet.targets
These changes resulted from debugging the package build, but turned out to be not necessary to get the package build going again. Might still be an improvement if so desired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1728)
=> Two small improvements

build/getDependencies-Linux.sh, build/getDependencies-windows.sh
The Linux one is definitely needed.  I'm not so sure about the Windows one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1730)
=> Update the (TeamCity) dependency download scripts

Bloom.sln, debian/rules, src/LinuxBloomLauncher/LinuxBloomLauncher.cproj
Also adjust packaging to build it independently
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1732)
=> Remove LinuxBloomLauncher from solution

DistFiles/infoPages/aboutBox-fr.htm, DistFiles/infoPages/aboutBox.htm, build/getDependencies-windows.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Communication/AndroidDeviceConnection.cs, src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, src/BloomExe/Publish/ReaderBookPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1729)
=> Add ability to push books via USB/MTP to Android (BL-4648)

src/BloomBrowserUI/lib/ckeditor/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1733)
=> Paste only plain text (BL-4775)

src/BloomBrowserUI/lib/ckeditor/config.js, src/BloomExe/XmlHtmlConverter.cs
Extra Spans: BL-4701 BL-3490 BL-4704 BL-4775
Extra ckeditor comments: BL-4621
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1736)
=> Fix problems related to pasting from MS Word

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
There was a problem where resizing a box messed
up its draggable containment, so now after we resize,
we go back through making it draggable and
clickable again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1742)
=> BL-4694 Fix TextOverPicture resizing

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1745)
=> Fix silly error in TextOverPicture

src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/bloomButton.tsx, src/BloomBrowserUI/react_components/l10n.tsx, src/BloomBrowserUI/react_components/progressBox.tsx, src/BloomBrowserUI/webpack.config.js, src/BloomExe/BloomExe.csproj, src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Publish/AndroidView.cs, src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/Publish/PublishView.Designer.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/Publish/ReaderBookPublisher.cs, src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/controllers/PublishToAndroidAPI.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1747)
=> Hook up push-to-Android-device code to the UI (BL-4770)

DistFiles/localization/Palaso.ar.tmx, DistFiles/localization/Palaso.bn.tmx, DistFiles/localization/Palaso.en.tmx, DistFiles/localization/Palaso.es.tmx, DistFiles/localization/Palaso.fr.tmx, DistFiles/localization/Palaso.ha.tmx, DistFiles/localization/Palaso.hi.tmx, DistFiles/localization/Palaso.id.tmx, DistFiles/localization/Palaso.ne.tmx, DistFiles/localization/Palaso.pt.tmx, DistFiles/localization/Palaso.ru.tmx, DistFiles/localization/Palaso.sw.tmx, DistFiles/localization/Palaso.ta.tmx, DistFiles/localization/Palaso.te.tmx, DistFiles/localization/Palaso.zh-CN.tmx
N.B. This requires the latest version of libpalaso (update dependencies)
* I believe I was able to find the appropriate place in
each shipping .tmx file to put the {2}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1752)
=> BL-4227 Don't translate "factory password"

debian/install
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1761)
=> Fix Linux packaging for new TeamCity dependencies

src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs
* moved image manipulation stuff from EditingView
to ImageUpdater static class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1762)
=> BL-4578 Prevent "copy license to all" from AOR

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1767)
=> BL-4788 Don't garbage-collect (twice!) on every page switch

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs
Advice on how to write a test for this is welcome. I couldn't figure out how to do it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1759)
=> BL-4197 Catch HRESULT E_FAIL

src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/Publish/WiFiAdvertiser.cs, src/BloomExe/web/controllers/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1769)
=> More logging during wifi advertise

src/BloomBrowserUI/publish/android/androidPublishUI.less, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/bloomButton.tsx, src/BloomBrowserUI/react_components/l10n.tsx, src/BloomExe/Publish/AndroidView.cs, src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1775)
=> Enable WiFi transfer for Linux (BL-4848)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
* removed "Skipping markup on paste..." check
this  fixes the problem when TalkingBook tool is
active
* moved exclusion of markup on keypress to still
remove inserted comments from editable html
* rename method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1783)
=> BL-4837/BL-3490 Reenable markup on paste

src/BloomExe/Book/BookCompressor.cs, src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/Publish/PublishView.cs, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1784)
=> Clean up CompressBookForDevice (BL-4809)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowFixture.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1788)
=> Fix a JS test that was failing on Linux (BL-4842)

src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, src/BloomExe/Communication/IAndroidDeviceUsbConnection.cs, src/BloomExe/Communication/UnimplementedAndroidDeviceUsbConnection.cs, src/BloomExe/Publish/BloomReaderPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1786)
=> Enhance USB/MTP transfer with better logging (BL-4770)

src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/web/controllers/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1794)
=> Make SendBook a background operation (BL-4812)

src/BloomExe/MiscUI/BloomIntegrityDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1799)
=> BL-4853 Add 'icons' directory to integrity check

src/BloomBrowserUI/publish/android/androidPublishUI.less, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/Publish/WiFiAdvertiser.cs, src/BloomExe/web/controllers/PublishToAndroidApi.cs
This really calls for yet more refactoring; the wifi vs. usb is still overly mixed togeter, but I did start changing names to at least make it clear what is what. I avoided splitting out files in orer to make reviewing easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1801)
=> Initial work on new Publish to Android UI

src/BloomBrowserUI/images/publish-android-file.svg, src/BloomBrowserUI/images/publish-android-usb.svg, src/BloomBrowserUI/images/publish-android-wifi.svg, src/BloomBrowserUI/publish/android/androidPublishUI.less, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomExe/Communication/AndroidDeviceUsbConnection.cs, src/BloomExe/Publish/BloomReaderPublisher.cs, src/BloomExe/Publish/WiFiAdvertiser.cs, src/BloomExe/web/controllers/PublishToAndroidApi.cs
Depends on: https://github.com/BloomBooks/BloomDesktop/pull/1801
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1802)
=> BL-43897 Add images to publish android method combo

src/BloomExe/Book/BookCompressor.cs, src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1806)
=> BL-4891 fix branding images blocked by ?optional

src/BloomBrowserUI/publish/android/androidPublishUI.less, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/progressBox.tsx, src/BloomExe/BloomExe.csproj, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/Publish/Android/FilePublisher.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/app.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1808)
=> Add Publish-Android-Save File (BL-4898)

src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1810)
=> BL-4889 make images have transparent background

src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/app.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1811)
=> REmember Android Publishing Method BL-4899

src/BloomExe/web/BloomWebSocketServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1820)
=> Toughen websocket send loop bl-4920

src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/option.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1827)
=> Make remaining publish:android UI elements localizable BL-4808

src/BloomBrowserUI/publish/android/androidPublishUI.less, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/helpLink.tsx, src/BloomBrowserUI/react_components/link.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1826)
=> Add link to get bloom reader to the Publish:Android screen BL-4930

src/BloomExe/Publish/Android/usb/UsbPublisher.cs, src/BloomExe/Publish/Android/wifi/WiFiAdvertiser.cs, src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs, src/BloomExe/web/WebSocketProgress.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1834)
=> Make publish-android progress messages localizable

DistFiles/localization/Bloom.en.tmx, DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1838)
=> Change labels on the rgb and cmyk pdf choices BL-4774

DistFiles/localization/en/Bloom.xlf
PublishTab.Android.GetBloomReader -> "Get Bloom Reader App"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1847)
=> Add missing localization string (BL-4976)

DistFiles/localization/en/Big Book/ReadMe.xlf, src/BloomBrowserUI/templates/template books/Big Book/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1848)
=> Correct zooming instructions for Big Book template (BL-4978)

src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1849)
=> Remove top and left border from compressed images (BL-4962)

src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1852)
=> Improve and update gulpfile.js

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1851)
=> BL-4995 Make sure we suggest legal filename

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/android/androidPublishUI.tsx, src/BloomBrowserUI/react_components/link.tsx, src/BloomBrowserUI/react_components/progressBox.tsx, src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1853)
=> Add link to copy text from the progress box (BL-4903)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1857)
=> Fix a Linux-specific crash caused by Windows specific operation

src/BloomExe/Collection/CollectionSettings.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1860)
=> BL-5054 Fix rub -> Russian license error

src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1861)
=> Fix PDF page numbers all being zero (BL-5017)

src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1863)
=> Fix page numbering bug more simply (BL-5017)

src/BloomExe/Edit/WebThumbNailList.cs
Stops reporting:
"COM object has been separated from...."
thumbnailing error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1865)
=> Cherrypick fix for BL-4690 to 3.9

src/BloomTests/Book/BookDataTests.cs
The solution was to change the tests in this instance because the
program behavior change was intentional.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1867)
=> Fix tests that failed due to change in fixing BL-5017

src/BloomExe/web/EnhancedImageServer.cs, src/BloomExe/web/ServerBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1864)
=> BL-5050 Remove log spam from optional branding images

DistFiles/infoPages/aboutBox-fr.htm, DistFiles/infoPages/aboutBox.htm
* jquery.alphanum was in twice in the English
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1871)
=> Update French aboutBox

src/BloomExe/web/controllers/ImageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1873)
=> BL-4998 Don't report missing credits for branding

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/BookTestsBase.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1876)
=> Renumber pages when duplicating or removing (BL-5044)

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1877)
=> Obtain MarkdownDeep like libpalaso for its use (BL-5005)

DistFiles/infoPages/aboutBox-fr.htm, DistFiles/infoPages/aboutBox.htm
* with stuff found on BL.org aboutBox
* in French too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1875)
=> BL-4640 update desktop aboutBox

src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1881)
=> Fix tests failing due to markdown removal

src/BloomExe/Edit/PageListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1882)
=> BL-5014 Disable "Paste Page" when book is locked.

src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.less, src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/BloomBrowserUI/templates/xMatter/Device-XMatter/description-en.txt, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1883)
=> Add Device-specific xmatter BL-4885

src/BloomExe/WebLibraryIntegration/LoginDialog.cs
* toast instead of throwing exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1885)
=> BL-4824 Exception in Login dialog

src/BloomBrowserUI/templates/Sample Shells/The Moon and the Cap/The Moon and the Cap.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1886)
=> Remove extraneous audio spans from sample shell (BL-5069)

DistFiles/localization/en/IntegrityFailureAdvice.xlf, DistFiles/localization/en/TrainingVideos.xlf, crowdin.yml
This is the best we can do via github to fix things I think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1891)
=> Restore older English xliff files and add update_option for crowdin

src/BloomExe/WebLibraryIntegration/LoginDialog.cs
* we don't want to trigger a problem report
* just show a MessageBox, log the error and close
the dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1893)
=> BL-4824 Handle signup link w/no internet better

src/BloomExe/Book/BookInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1897)
=> Upload leveledReaderLevel to parse server (BL-5118)

src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, src/BloomExe/WebLibraryIntegration/LoginDialog.cs
* plugging a hole earlier in the chain
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1898)
=> BL-4824 Login Exception

src/BloomExe/Book/BookInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1900)
=> BL-5087 Fix bug in BookInfo

build/Bloom.proj, src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1905)
=> Some minor tweaks for localization support

DistFiles/localization/DistFiles/localization/Big Book/ReadMe-es.xlf, DistFiles/localization/DistFiles/localization/Decodable Reader/ReadMe-es.xlf, DistFiles/localization/DistFiles/localization/Leveled Reader/ReadMe-es.xlf, DistFiles/localization/DistFiles/localization/Picture Dictionary/ReadMe-es.xlf, DistFiles/localization/DistFiles/localization/Template Starter/ReadMe-es.xlf, DistFiles/localization/DistFiles/localization/Wall Calendar/ReadMe-es.xlf, DistFiles/localization/es/Bloom.xlf, DistFiles/localization/es/IntegrityFailureAdvice.xlf, DistFiles/localization/es/Palaso.xlf, DistFiles/localization/es/Publish-Android-Troubleshooting.xlf, DistFiles/localization/es/TrainingVideos.xlf, DistFiles/localization/es/bloomEpubPreview.xlf, DistFiles/localization/fr/IntegrityFailureAdvice.xlf, DistFiles/localization/pt/IntegrityFailureAdvice.xlf, DistFiles/localization/pt/TrainingVideos.xlf
This should bring us up to date with the state on crowdin.  But there's more cleanup needed before we can allow crowdin to continue syncing with our github repository.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1909)
=> Merge recent translations from crowdin

src/BloomExe/BloomExe.csproj, src/BloomExe/BookThumbNailer.cs, src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishControl.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/WebLibraryIntegration/OverwriteWarningDialog.cs
2 commits:
- 1st is simple refactoring and cleanup
- 2nd extracts business logic to a model class and reuses it
for the bulk upload process
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1907)
=> BL-5087 follow-up

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/controllers/ImageApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/web/controllers/ImageApiTests.cs, src/BloomTests/web/controllers/PageTemplatesApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1899)
=> [4.1]BL-4692 Paste Image Credits page nums

src/BloomExe/BloomFileLocator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1918)
=> Ensure runtime created localized HTML files are in UTF-8

DistFiles/localization/README.md
Add a couple more paragraphs and make some things more consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1919)
=> Tweak the readme for the integrated Crowdin translation workflow

src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1921)
=> BL-5087 Better uploader messaging

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1924)
=> Simplify the language picker menu display (BL-5188)

src/BloomExe/BloomFileLocator.cs, src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1923)
=> Handle more complexities in locating translated xliff files

DistFiles/localization/en/IntegrityFailureAdvice.xlf, DistFiles/localization/en/TrainingVideos.xlf, build/Bloom.proj, src/BloomBrowserUI/gulpfile.js
Also update a pair of xliff files that had the BOM stripped somehow
so that future runs won't create differing files that are really the
same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1931)
=> Move regenerating English xliff to gulpfile.js

src/BloomExe/HelpLauncher.cs
Another case of case (in)sensitivity depending on the system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1942)
=> Fix launching help through API on Linux (BL-4577)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1940)
=> Display native name of language if nothing better (BL-5128)

DistFiles/localization/Template Starter/ReadMe-en.xlf, src/BloomBrowserUI/templates/template books/Template Starter/ReadMe-en.md
The xlf file will need to be merged into master to have any effect on crowdin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1948)
=> Fix typos in Template Starter ReadMe file (BL-5124,BL-5125)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/Program.cs
May want to cherry pick this to 3.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1949)
=> BL-5201 Record the language with each analytics event

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1947)
=> Ensure all quote marks recognized at sentence end (BL-5063)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This is a less-than-satisfactory fix as it doesn't address the root issue,
but it does seem to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1951)
=> Prevent markup routine from interfering with longpress (BL-5215)

src/BloomExe/Publish/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
* deleting elements inside of a foreach had unwanted
side-effects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1954)
=> [3.8]BL-5234 Repair Epub RemoveUnwantedContent

src/BloomExe/Publish/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
* fold xpath expression back into select
* delete test that doesn't function correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1955)
=> [3.9]Small mods to my BL-5234 fix

DistFiles/localization/Template Starter/ReadMe-es.xlf, DistFiles/localization/Template Starter/ReadMe-fr.xlf, DistFiles/localization/Template Starter/ReadMe-pt.xlf, DistFiles/localization/es/Bloom.xlf, DistFiles/localization/es/MissingLameModule.xlf, DistFiles/localization/es/TrainingVideos.xlf, DistFiles/localization/es/bloomEpubPreview.xlf, DistFiles/localization/es/leveledReaderInfo.xlf, DistFiles/localization/fr/Bloom.xlf, DistFiles/localization/fr/MissingLameModule.xlf, DistFiles/localization/fr/TrainingVideos.xlf, DistFiles/localization/fr/bloomEpubPreview.xlf, DistFiles/localization/fr/leveledReaderInfo.xlf, DistFiles/localization/pt/Bloom.xlf, DistFiles/localization/pt/MissingLameModule.xlf, DistFiles/localization/pt/TrainingVideos.xlf, DistFiles/localization/pt/bloomEpubPreview.xlf, DistFiles/localization/pt/leveledReaderInfo.xlf
This is a cherry-pick from the master branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1967)
=> Merge new/updated translations from crowdin

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1968)
=> USB transfer on Linux logs message instead of throwing error (BL-5289)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/EnhancedImageServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1952)
=> Handle complexities of language naming (BL-5223 / BL-5244)

debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1975)
=> Change Linux package version to 4.1 on master branch

src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1977)
=> Fix test failure introduced by earlier pull request

debian/README, debian/bloom-alpha, debian/bloom-alpha.appdata.xml, debian/bloom-alpha.desktop, debian/changelog, debian/control, debian/copyright, debian/install, debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1982)
=> Reverse accidental merge of Linux packaging files

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1981)
=> BL-5296 Control page changing direction for rtl epubs

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1986)
=> BL-5151 Composed characters in longpress

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/NonFatalProblem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1991)
=> Change channel numbers on Linux to match Windows (BL-5320)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomTests/Book/BookCompressorTests.cs
There will be a Bloom Reader PR to make use of these. But either can land first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1995)
=> BL-5325 Larger BR thumbnails with smaller borders

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/1998)
=> Handle composed chars using mouse with longpress BL-5151 part 2

DistFiles/localization/pbu/Bloom.xlf, DistFiles/localization/pbu/Palaso.xlf, DistFiles/localization/prs/Bloom.xlf, DistFiles/localization/prs/Palaso.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2000)
=> Fix glitch in pbu and prs Bloom.xlf and Palaso.xlf files

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
* for Guatemala workshop
* x + dieresis upper/lower
* saltillo upper/lower
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2003)
=> BL-5333 Add new longpress characters

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2002)
=> Reliably match UI language against localizations (BL-5298)

DistFiles/localization/Big Book/ReadMe-en.xlf, DistFiles/localization/Picture Dictionary/ReadMe-en.xlf, DistFiles/localization/Template Starter/ReadMe-en.xlf, DistFiles/localization/Wall Calendar/ReadMe-en.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2009)
=> Update xliff files for markdown changes

DistFiles/localization/en/Bloom.xlf, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Collection/BrandingProject.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/web/controllers/BrandingApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2007)
=> BL-5329 Move and relable the Branding combobox

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2016)
=> Fix Linux build due to page control button move

src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2022)
=> BL-5012 Reposition qtips after Paste Image Credits

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2023)
=> Make Windows-specific bugfix Windows-specific

src/BloomExe/web/controllers/ImageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2026)
=> BL-5347 Improve Image Credit punctuation

src/BloomBrowserUI/bookEdit/EditViewFrame.pug, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/bookEdit/css/origamiEditing.less, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/origami.ts, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/bookLayout/device.less, src/BloomBrowserUI/bookPreview/previewMode.less, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PageControlsApi.cs
* created space above page (but not in thumbnail)
* moved the page label and origami toggle into space
There is a small problem when zooming in. Greater than 170% starts to scroll these off the screen. Anybody have any ideas how to fix that?
We weren't thinking of doing React here, were we?!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/2008)
=> BL-5075 Move page label and layout toggle
