BloomBooks/BloomDesktop

src/BloomExe/Book/Page.cs
This was tested on "The Moon and the Cap" and "Vaccinations" (which are
the official sample shell books) and on *"My Fish! "No, it's my fish!"*
downloaded from bloomlibrary.org.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3083)
=> Fix changing multiple page layouts in shell books (BL-6991)

src/BloomBrowserUI/bloomWebFonts.less, src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less, src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less
* still doesn't allow active Chinese tab to be bold
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3085)
=> BL-6918 Tweak to do webfonts right

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Pre-existing books that have no IDs marked up yet (and which you don't type into, which would trigger updateMarkup to fix the state) are missing IDs and current highlights and stuff. Now this fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3084)
=> Talking Book: Fix initialization problems (BL-6994)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomTests/Book/TranslationGroupManagerTests.cs
This repairs damaged books, but doesn't address the cause.  I have been
unable to reproduce the original bug that resulted in the duplicate divs.
Even if we want to press on to try to find out what caused the duplication,
this is useful for repairing books that have gotten into a bad state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3059)
=> Fix books with duplicated language divs in translation groups (BL-6923)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
When Split is done, add a special 3-way alternating highlight to visually indicate that Split has finished.
Clear the split when the user starts a new recording, clears (deletes) the recordings for the text box, or changes the recording mode.
Don't clear if the user types, nor on book close/save.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3088)
=> AutoSplit 4.5: Special Highlight after finish (BL-7000)

src/BloomExe/Browser.cs
* only seems to occur with Release builds
* only seems to occur when doing a bulk upload
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3108)
=> Keep InvalidCastException from crashing bulk upload

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
Note this fix is for Version4.4 as requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3117)
=> Fix display of top "optional" in web upload page (BL-7022)

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is on Version4.4 as requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3118)
=> Fix cover image descriptions to use ImageDescriptionEdit-style (BL-7039)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
FYI, since these are error messages, these can be rather difficult to test..
Discussed with John hatton. The 2 strings are now expected to have the same generic error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3115)
=> Localize some error messages for talking book tool

src/BloomBrowserUI/lib/errorHandler.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3127)
=> Fix javascript error handler to not swallow errors (BL-7085)

src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
* existing regexp was too greedy about splitting
words on certain Control characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3128)
=> [4.5]BL-7081 Fix Nepali word count

src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/Android/usb/UsbPublisher.cs, src/BloomExe/Publish/Android/wifi/WiFiAdvertiser.cs, src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/web/WebSocketProgress.cs, src/BloomExe/web/controllers/AccessibilityCheckApi.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
This fixes tests which are failing due to receiving a null WebSocketProgress object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3142)
=> Fully define IWebSocketProgress (BL-6896)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
Introduced by BL-6912
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3145)
=> Fix regression preventing Split button from being hidden (BL-6912)

src/BloomBrowserUI/.storybook/config.js, src/BloomBrowserUI/.storybook/webpack.config.js, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, src/BloomBrowserUI/package.json, src/BloomBrowserUI/react_components/l10n.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/webpack.common.js, src/BloomBrowserUI/webpack.core.js, src/BloomBrowserUI/yarn.lock
Storybook did not add babel, for some reason it is already in our package.json. But it does *use* babel, unlike our normal build. This exposed a couple typescript checking errors for some reason, which have been fixed in this commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3138)
=> add storybook

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, src/BloomExe/web/BloomServer.cs
* page list thumbnail images will use the
video-placeholder image instead of capturing
an image from the video
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3148)
=> BL-7074 Use CSS instead of DOM manipulation

src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
* Device 16 x 9 Landscape was producing odd buttons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3139)
=> BL-7130 Resize some thumbs to fit buttons

src/BloomExe/Book/BloomReaderFileMaker.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/Book/HtmlDomTests.cs
After a text box audio gets (hard) split, the audio is no longer currently referenced and so therefore arguably eligible for cleanup. This change will make it no longer eligible for cleanup except during publishing (because at that point we know we no longer need it)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3165)
=> Preserve maybe-referenced text box audio until publishing.

src/BloomBrowserUI/bookLayout/basePage.less
* make sure editable div displays "fake" text image
in auto-generated thumbnails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3174)
=> BL-6582 SL Template page fix

src/BloomBrowserUI/publish/metadata/SubjectChooser.tsx
The removed code is not needed (if it ever was) with the mobx observer
in the parent dialog.  Having it there causes a loop in change property /
render / change property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3176)
=> Fix crash in opening metadata dialog for epub publishing (BL-7152)

src/BloomBrowserUI/lib/ckeditor/config.js, src/BloomBrowserUI/lib/ckeditor/plugins/autolink/plugin.js
I used the version of the autolink plugin for ckeditor 4.10.x because it introduced email links.  I didn't use the version from 4.11.x because it changed the way it interacted with the rest of the program.
The changes in ckeditor/config.js are mostly due to VSCode prettification.  The last few lines are the only real change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3177)
=> Add autolink plugin to ckeditor (BL-6845)

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This applies to Bloom Library uploads at this point.  The languages chosen for content in the book
have their checkboxes locked in the checked position in the UI.  They should always be uploaded.
(This always includes the primary/vernacular language.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3179)
=> Disable deselecting languages used for content (BL-7166)

src/BloomExe/Book/Book.cs
This includes allowing the book title in the 3rd language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3182)
=> Display proper names for multilingual books (BL-6830)

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3188)
=> Fix source bubbles that have text in many languages (BL-6940)

src/BloomExe/Book/Book.cs
The previous change copied only the reference inside the HTML file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3197)
=> Copy template's stylesheet file(s) when changing layout (BL-7170)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3192)
=> Prevent double paste when text contains standard format verse marker (BL-7052)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
This works better on Windows than on Linux, but prevents unneeded conversion of images that are
already opaque on both Windows and Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3203)
=> Don't convert 1-bit format images to 32-bit unnecessarily (BL-7202)

DistFiles/localization/Template Starter/ReadMe-en.xlf, DistFiles/localization/en/Publish-Android-Troubleshooting.xlf
These files are automatically generated.  I don't know how they got
merged with the unwanted newlines and spaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3216)
=> Update xliff files to remove unwanted whitespace (20190529)

src/BloomBrowserUI/yarn.lock
This happens automatically on the master branch, so may as well merge it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3217)
=> Update yarn.lock @types/react to ^16.8.19 (20190529)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Fixes backward compatibility issues with playing a book in 4.6 that was created using 4.5 and Hard Split.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3219)
=> Narration highlight backward compatibility fix  (BL-7182)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/SignLanguageApi.cs
This is needed if we ever want to add query markup to image URLs for
transparency (or other effects).  Doing so would make books incompatible
with earlier versions of Bloom.  This fix prepares for a possible future
enhancement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3236)
=> Fix uses of UrlPathString.NotEncoded for filepaths (BL-4816)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3239)
=> New and improved fix for the Story Primer Wordfind grid bug (BL-7061)

src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, src/BloomBrowserUI/publish/commonPublish/ProgressDialog.less, src/BloomBrowserUI/publish/commonPublish/ProgressDialog.tsx, src/BloomBrowserUI/publish/ePUBPublish/ePUBPublish.less, src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
Also, in Progress Dialog, don't show spinner if you're not working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3243)
=> Improve some layout things in the epub/android screens

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3247)
=> Clean-up after publish screen refactor: move hack lower to avoid unexpected changes

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/es/Bloom.xlf, src/BloomExe/Program.cs, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/app.config
This is on the Version4.5 branch as requested by the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3253)
=> Allow users to optionally see unapproved localizations (BL-7281)

debian/control, environ, src/BloomExe/HelpLauncher.cs
Also remove an unneeded Linux dependency.  mono4-sil and libgdiplus4-sil
provide everything mono related needed by Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3279)
=> Improve xchm use for viewing help on Linux (BL-7244)

src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3284)
=> Fix yellow crash caused by publishing with no cover image (BL-7329)

src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
An update to one of the packages in Windows broke the Linux build since
it wasn't copied to the Linux specific file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3296)
=> Fix packages.config and Linux/packages.config to agree (20190703)

src/BloomExe/Publish/Epub/EpubMaker.cs
Ok, so this is obviously less than ideal.
(I think) the real solution is to have the unit tests actually call MakeDeviceXmatterTempBook, but someone in the past decided this was too hard at that time.
But we have broken tests now... (my fault for not checking before making the previous PR).
So we probably need to merge this and make a card which I will pick up to get the tests running MakeDeviceXmatterTempBook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3315)
=> Fix unit tests with a hack (BL-7300)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This covers both error conditions and no relevant hardware available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3325)
=> Show error icon if no microphone found (BL-7272)

src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
The default value is "bloom" to indicate the .bloomd was built by the
Bloom desktop app.  BloomHarvester will set the value as "harvester". (in
a separate bloom-harvester commit, of course)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3328)
=> Add meta[@name="creator"] for use by harvester in bloomd files (BL-7409)

src/BloomExe/WebLibraryIntegration/OverwriteWarningDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3329)
=> Fix a dialog display glitch on Linux (20190725)

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs
This applies to uploading to BloomLibrary and to creating BloomPacks, and
is needed for backward compatibility with Bloom 4.5 and earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3324)
=> Redo handling lang attributes and css for collection settings (BL-7343)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomTests/Book/BookTests.cs
This relieves bloom-player of slow checks for nonexistent audio files.
Note that this markup is added just by opening the Talking Book tool even
when no sound is ever recorded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3330)
=> Remove obsolete talking book tags when making bloomd (BL-7434)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Fix problem where the class responsible for enabling the highlights is removed when playing the audio happens (and never added back on either).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3346)
=> Talking Book: Fix bug where blue split highlight removed (BL-7548)

src/BloomExe/Book/Book.cs
This was crashing on Linux and Windows --allUsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3351)
=> Prevent trying to create css files in distributed folders (BL-7550)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
I suggest we do a different version for 4.6+ that uses ES6 Promise instead of JQueryPromise. 4.5 is still on ES5, where Promise isn't available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3375)
=> [4.5 only]BL-7588 Fix audio initialization

src/BloomExe/web/BloomServer.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3377)
=> Prevent some javascript errors which cause TeamCity test failures when using Geckofx60

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
* When switching to the TalkingBook tool from another
tool, the Speak button was not activated even if there
was text on the page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3379)
=> [4.5]BL-7588 Fix Speak button second problem

src/BloomExe/Edit/Configurator.cs, src/BloomExe/Publish/PublishView.cs
I also renamed an event handler method that didn't match the event name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3389)
=> Fix a couple of spots disposing of GeckoWebBrowser objects (20190916)

debian/control
For some reason, the xenial package was being built with unobtainable
dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3397)
=> Fix Linux package dependencies (20190927)

build/dependencies.config, debian/control
This dependency update fixes 311 test failures on TeamCity if nothing else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3398)
=> Update Linux dependencies for Geckofx60 (20190927)

src/BloomTests/BloomFileLocatorTests.cs
The current (possibly temporary) setup apparently handles the problem of
false positives for test failure.  This (extremely temporary) hack tests
whether that setup correctly handles true test failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3399)
=> Test TeamCity setup for detecting test failures on Linux (20190930)

src/BloomExe/Browser.cs
This requires setting an environment variable DEBUGBLOOM to something
other than "false" or "no" (or "").  This may help in debugging memory
leaks in Geckofx without requiring a debug build of Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3401)
=> Conditionally allow the about:memory window in release builds

src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
The new Geckofx60 package fixes the worst of the Gecko window/memory leaks
that I've observed.  Memory consumption is now on a par with Geckofx45 in
initial testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3406)
=> Update Geckofx60 and add some explicit garbage collection (20191018)

src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
Fix some cases where the 1st argument to console.assert was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3412)
=> Fix bad asserts

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/BookThumbNailer.cs
* use a better preexisting method to get image path
* add image for web to .bloomd production
(and by extension to Harvester)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3432)
=> BL-7674 Publish front cover image take two

src/BloomExe/BookThumbNailer.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
Very large and very small front cover images could lead to failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3443)
=> Fix two causes of thumbnail creation to fail (BL-7792)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/LanguageSpec.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/CollectionCreating/LanguageIdControl.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/MiscUI/LanguageFontDetails.cs, src/BloomExe/MiscUI/ProblemReporterDialog.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebLibraryIntegration/BookDownloadSupport.cs, src/BloomExe/web/ReadersApi.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Collection/CollectionSettingsTests.cs, src/BloomTests/Publish/ExportEpubTests.cs
Factor out Language info to LanguageSpec, leading to a huge reduction in duplication and other unneeded code in CollectionSettings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3445)
=> Factor out LanguageSpec from CollectionSettings

debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3464)
=> Fix Bloom Linux package dependencies for Geckofx60 (20191119)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3465)
=> Comic tool: Ctrl+drag allows drag through text box (BL-7841)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
2 questions: 1) Should this target Version4.5 instead? and 2) This provides 5px margin for Firefox70 on Linux: is this sufficient leeway? (ie, it still fully displays for "@labelButtonMaxHeight: 125px;" in Linux Firefox70)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3471)
=> Fix missing Music checkbox in Motion tool (BL-7826)

src/BloomExe/Book/Book.cs
This doesn't really address the issue in BL-7800 but is a needed fix.
Without, if the first div.bloom-translationGroup encountered had all
languages in it, it would be the only one checked in the whole book.  The
previous code only saved the parent div for the first div.bloom-editable
that had content for a given language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3477)
=> Fix minimal coverage of book in Book.AllLanguages (BL-7800)

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
I think this should be safe for 4.6 as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3480)
=> Fix unwanted Motion Book stickiness in Bloom Reader output (BL-7680)

src/BloomBrowserUI/bookEdit/js/point.ts, src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
1) Determine the border width accurately when scaled
2) Work around an off-by-1 error when you set the position, then read it back out again.
3) Fix accumulation of rounding errors by using the unrounded values in calculation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3485)
=> Comic Tool: Improve accuracy of resize calculations (BL-7894)

src/BloomBrowserUI/problemDialog/ProblemDialog.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx
* not sure why the padding-bottom is no longer
needed... but it isn't
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3502)
=> BL-7666 Add close X to title bar

src/BloomExe/web/controllers/SignLanguageApi.cs
I haven't seen the ffmpeg failure since making this change in 70+ video recordings in two books.  I had
seen it twice today before making this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3505)
=> Tweak code to reduce likelihood of unreadable file (BL-7076)

src/BloomExe/web/controllers/ProblemReportApi.cs
* there will be a comma only if both first and last name
contain something
* the parentheses around the email address will only
appear if there is an email address
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3507)
=> BL-7666 fix comma in user information

src/BloomExe/web/controllers/ProblemReportApi.cs
* adding "(UTC)" confused the YT code to find the
reporter's email address in our user info string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3513)
=> BL-7666 restore Reporter email functionality

src/BloomExe/Program.cs
Previously, if the Harvester ran and then launched a Bloom subprocess which encountered an error during setup, it would erroneously complain that two Bloom processes were running. It was mistakenly counting the BloomHarvester processes as a bloom process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3508)
=> Count Bloom processes more accurately

src/BloomBrowserUI/webpack.common.js
This probably should be cherry-picked back to 4.6 as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3509)
=> Don't publish storybook to users (BL-7882)

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3519)
=> Avoid showing script markers in language tags during lookup (BL-7641)

src/BloomExe/CollectionTab/LibraryBookView.cs, src/BloomExe/FatalExceptionHandler.cs, src/BloomExe/InstallerSupport.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* uses SIL.ExceptionHelper to get the same exception
information we got with the old dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3520)
=> BL-7666 Get stack trace working

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/EPubMakerTests.cs
Should this be considered for cherry-picking to 4.6?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3515)
=> Prevent cover image description audio when unwanted (BL-7839)

src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3544)
=> Allow a book to specify the xmatter to use in derived books (BL-7921)

src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
These spots both had problems with failed screenshots.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3551)
=> Fix sources of recursive problem report dialogs (20191218)

src/BloomBrowserUI/templates/Sample Shells/The Moon and the Cap/The Moon and the Cap.htm, src/BloomBrowserUI/templates/customXMatter/Dari-XMatter/Dari-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/Pashti-XMatter/Pashti-XMatter.pug, src/BloomBrowserUI/templates/xMatter/Video-XMatter/Video-XMatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/BookData.cs, src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3555)
=> Fix CSS font selection for language names on cover (BL-7968)

src/BloomBrowserUI/bookLayout/langVisibility.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3562)
=> Allow vertical arrow keys when textbox is center or bottom aligned

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Edit/EditingModel.cs
Reverts BloomBooks/BloomDesktop#3557
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3565)
=> Revert "Use custom language names consistently (BL-7832)"

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Edit/EditingModel.cs
A customized name will always be used, in the UI and published material.
A non-customized name will depend (in theory) on the context, the UI
language, and the national language for the collection.  In practice at
the moment, we have only possibly custom names, English names, and the
name of the language in itself (autonym).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3566)
=> Handle customized language names more consistently (BL-7832)

src/BloomExe/Collection/WritingSystem.cs
IsCustomName should default to false like IsLanguageRTL if the language
is essentially undefined in the .bloomCollection file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3570)
=> Fix initialization error in WritingSystem (BL-7832)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3581)
=> Fix bug where resize handles and format gear get blown away (BL-8035)

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomTests/Publish/PublishModelTests.cs
This is needed to keep unwanted fonts from being embedded in bloomd
books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3572)
=> Remove unwanted xmatter language data for bloomd books (BL-7998)

src/BloomExe/XmlHtmlConverter.cs
Previously code emitted <Iframe..../> which isn't valid html5 and which kills the rest of the book. Change  to emit
`<iframe...>Must have a closing tag in HTM</iframe>`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3587)
=> Fix BL-8051 don't let iframes break book

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
Targeting master... Don't think it's necessary for this to be in 4.7 IMO since it's only addressing a Harvester issue right now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3591)
=> Fix Harvester bug could not find part of path (BL-8055)

src/BloomExe/FatalExceptionHandler.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* if problem reporter produces an error, we fallback
to the old WinForms handler
* **Dependent on libpalaso PR#890**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3602)
=> BL-8041 Close "holes" in problem reporter

src/BloomExe/Book/BookInfo.cs
This is needed for RoseGarden output to help users trace the origin of
converted books.  An entry needs to be made in the book table in Parse.com
for production eventually, and maybe for the sandbox/next.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3611)
=> Add original-book-source-url to the book metadata json (BL-6981)

src/BloomBrowserUI/bookLayout/bubble.less
Even though the old code says it's (100% + 1px) away, the preprocessor actually calculates this as 101% away (this isn't a unit conversion it can handle at compile time). So the amount we positioned them away from the left edge was actually based on percentages of the width, not the fixed number! :(
We want to change that to a fixed number instead (so that the tip does not move as the bubble size changes), but keep them at the same initial position *handwave*. But when determining where the old behavior's position is thorny because it's based on a percentage of the width. So we need to assume a certain width of the text box.
The most reasonable assumption seems to be to use the default text box width, which is 140.
That means that for text boxes which are of the default width, there will …
=> Fix language tip 1) in wrong position & 2) moves unexpectedly (BL-8151)

src/BloomBrowserUI/bloomMaterialUITheme.js, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx, src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, src/BloomBrowserUI/publish/stories.tsx
* if PublishLanguagesGroup changes
* currently Feature and thumbnail color changes refresh
automatically and Language checkbox changes don't
* this change just highlights the refresh button and label
if a Language checkbox has changed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3628)
=> BL-8009 set state to highlight refresh icon

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
* our code linters keep the .htm files in our code base from
using capital letters for html tags like DIV, so they won't
work on Moon & Cap, e.g.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3631)
=> BL-8115 fix cover color changing regex to be general

debian/control, debian/rules, environ, src/BloomExe/BloomExe.csproj, src/BloomTests/BloomTests.csproj
This is needed for the upcoming Ubuntu LTS release (20.04 / focal).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3648)
=> Minimally fix Bloom to compile/run with mono5-sil

src/LinuxBloomLauncher/BloomLauncher.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3649)
=> Fix LinuxBloomLauncher to use mono5-sil instead of mono4-sil (BL-8253)

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, environ, src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This enables Bloom to run on mono5-sil on Linux with the Gtk file chooser
dialogs.  It also prepares for Geckofx60 on Linux in allowing a Gtk3 specific
package to be installed for Bloom.  (although that's not part of this particular
change)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3650)
=> Get DialogAdapters from nuget instead of libpalaso

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
Fix bug where non-HTML files match FindBookHtml()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3655)
=> Fix bug where non-HTML files match FindBookHtml()

src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs
Replacing a SIL.WF.BetterLabel with a SIL.WF.HtmlLabel works to prevent
the wizard dialog from getting stuck during initialization.  (I think
having translators continue to deal with newlines in the string is okay
compared to having them try to deal with <br/> elements.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3656)
=> Fix a hanging bug for mono5-sil in NewCollectionWizard (BL-8253)

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/problemDialog/EmailField.tsx, src/BloomBrowserUI/problemDialog/ProblemDialog.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx, src/BloomBrowserUI/react_components/UseDrawAttention.ts
* shake the BR preview refresh icon when it changes
color (indicating something changed that affects the
preview)
* move the draw attention hook to React_components
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3660)
=> BL-8009 use draw attention hook for Refresh

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomTests/Book/BookTests.cs
This gives the user control over what is seen on the the screen and what
is published in the book without any surprising changes in some places.
This breaks the fix for BL-7382 until the libpalaso language chooser
dialog is changed to offer autonyms instead of (or in addition to?)
English names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3669)
=> Use language.Name for the (up to) three chosen languages (BL-8302)

debian/control, debian/rules, environ, src/BloomBrowserUI/gulpfile.js, src/BloomExe/BloomExe.csproj, src/BloomExe/Collection/ScriptSettingsDialog.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/LinuxBloomLauncher/BloomLauncher.c
This is needed for the upcoming Ubuntu LTS release (20.04 / focal).  I've tested this by opening every dialog and menu that I could access and by creating a book (with multiple content pages) for every standard template except Template Maker.  I also tried all of the tools in editing at least one book.  Everything I tried seemed to work okay, or at least as well as under mono4-sil.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3665)
=> Fix Bloom 4.7 to compile/run with mono5-sil (cherry-picks from master)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bloomMaterialUITheme.js, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug, src/BloomBrowserUI/react_components/expandable.tsx, src/BloomBrowserUI/react_components/option.tsx, src/BloomBrowserUI/react_components/playbackOrderControls.tsx, src/BloomBrowserUI/react_components/progressBox.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/react_components/stringListCheckbox.tsx, src/BloomExe/web/controllers/TalkingBookApi.cs
* 1st commit is mostly cleanup and Toolbox checkbox
* 2nd commit adds playback order UI and sets tabindex
* still need to get audio recording mechanism to respect tabindex order
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3674)
=> BL-7883 Talking Book playback order

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
I guess we can test it in 4.8 first, then merge into 4.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3678)
=> Fix image pos and bubble resize after overflow (BL-8239, BL-8240)

src/BloomExe/Book/Book.cs
Handles books where the data-page-number uses another script's numbering system.
e.g.:
data-page-number="၁"
Instead of:
data-page-number="1"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3681)
=> PHash handles pages whose page numbers are not Arabic numerals (BL-8346)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/PhashHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3685)
=> Fix phash functions to handle 1-bit colormap images on Windows

src/BloomExe/web/controllers/ProblemReportApi.cs
I tested this on both Windows and Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3689)
=> Get proper screenshots for error reports (BL-8348)

src/BloomExe/Workspace/ZoomControl.cs
The bug is apparently in the mono 5 runtime library.  We just work around
it in Bloom code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3695)
=> Fix bug in displaying zoom control on Linux (BL-8360)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomTests/Book/BookStorageTests.cs
* deactivate image container handles while P.O. controls up
* standardize on lowercase attribute for audio recording
mode
* fix .filter() bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3697)
=> BL-7883 more Playback order changes

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
* Refactor to use constants consistently
* Bundle up add/remove playback order UI better
* Get new page to highlight correctly on un-checking box
* Add new comic bubbles at end of container, instead of
beginning
* Sort divs with no tabindex to the bottom of their
container
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3705)
=> BL-7883 more changes

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
The problem seems to be that we re-added duplicate drag handles. I think only the first one gets the event listener, but probably the last one is the one that gets the mouse events. So the listener isn't fired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3707)
=> Drag icon works after resize (BL-8066)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/karma.conf.js
* There were cases where data-audioRecordingMode was
present, but the audio-sentence classes weren't properly
setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3711)
=> [4.7] BL-8425 Fix Next button problem

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
Previously, it would throw nasty exceptions that crashed the program without saving the book if the book contained "invalid xml" (not properly encoded)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3712)
=> Fix originalTitle to handle HTML special chars in title (BL-8221)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, src/BloomTests/Book/BookStarterTests.cs
Previously, it was re-escaping the originalTitle every time the book was saved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3713)
=> Prevent originalCopyright from being escaped multiple times (BL-8221)

src/BloomBrowserUI/branding/BARMM/branding.json, src/BloomBrowserUI/package.json, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-Xmatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
Only the change to bloom-xmatter-mixins.pug has the potential to change the rest of Bloom, but it should be safe.
* hide Stage letters on "normal" books
* fix license logo
* adjust spacing in branding credits and add paragraph
* adjust license details
* add originalContributions field for image credits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3715)
=> [4.7] ABC-BARMM - the easy stuff

src/BloomBrowserUI/branding/BARMM/branding.json, src/BloomBrowserUI/templates/bloom-foundation-mixins.pug, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-Xmatter.pug
* Refactor .less into more logical structure
* Add non-standardized vernacular Topic field (right-
justified, on the same line as Reader Description)
* Make Front Cover Title smaller and left-justified
* Make Reader Description left-justified
* Really fix license logo problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3723)
=> ABC-BARMM changes

src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less
* because of scoped CSS in Swiper, we can't just put the
body classes on the body in BP
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3730)
=> [4.8] Tweak ABC XMatter rules to work in BP

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
* after unchecking playback order box, sometimes
next and previous were left in a bad state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3736)
=> BL-7883 Fix state of Next/Previous

build/dependencies.config
Perhaps most important is mono5-sil instead of mono4-sil since Version4.8
does not build with the older mono's compiler.
This file is used in TeamCity builds.  Theoretically new developers on
Linux might use it at well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3739)
=> Bring dependencies.config up to date with debian/control (20200514)

src/BloomExe/Edit/WebThumbNailList.cs
Just added back some code that was in 4.7 that got deleted during a rewrite of a class in 4.8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3747)
=> Fix bug that causes exception after title changed (BL-8472, BL-8487)

src/BloomTests/Publish/BloomReaderPublishTests.cs
It's the español that somehow got entered as ISO-8859-1 aka Latin-1, and
maybe also the same as Windows 1252 for this character.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3764)
=> Change test file to use UTF-8 instead of ISO-8859-1 encoding (20200602)

src/BloomBrowserUI/branding/Afghan-Children-Read/branding.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3766)
=> Don't allow the default of a gray Bloom logo on the back cover (BL-8372, BL-8549)

debian/rules
The package build, which runs inside of a chroot environment, didn't have access to the environment variable that we tried to set before we started the package build. The result was that the patch version was always 0.
This change depends on a change in [ci-builder-scripts](https://gerrit.lsdev.sil.org/c/ci-builder-scripts/+/7516) that stores the build number in `build_number.env`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3768)
=> Properly set version number during package build

debian/rules
For local builds, the version stays at 4.7.0.0.
For jenkins builds, the build number and git sha are used for the last two numbers instead of 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3771)
=> Fix Bloom packaging to have the full version number in the assembly

.gitignore, build/getDependencies-windows.sh, debian/control, src/BloomExe/BloomExe.csproj, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
This allows much larger PNG files to be handled by shrinking them in an
external program to a more manageable size.  This shrinkage takes place
either when the picture is first imported into Bloom using the Image Chooser
dialog or when the user clicks on the "Bring Book Up to Date" menu item.
In the latter case, no effort is made to convert the PNG to JPEG to achieve
even more disk space savings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3767)
=> Use GraphicsMagick to process incoming image files (BL-8512)

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config
A new version of DialogAdapters.Gtk2 is needed to fix observed problems
on Linux.  The old version of DialogAdapters works fine on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3774)
=> Get file dialogs to work properly on Linux (BL-8518)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
If you paste in enough text that it overflows out the bottom, the scroll amount will be set and will mess up calculations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3791)
=> Fix bubble jump upon paste (BL-8559)

src/BloomExe/web/controllers/ProblemReportApi.cs
* so far unsuccessful getting problem dialog to be
draggable, but this should keep the splash screen from
being a problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3792)
=> BL-8249 Close splash screen before problem dialog

src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomExe/MiscUI/BrowserDialog.cs
Make the winforms host have a draggable title bar, then remove the "X" from the html part of the dialog because it is already there in the title bar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3794)
=> BL-8249 Make Problem dialog draggable

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomTests/Book/BookTests.cs
* to decide whether or not something is fully translated or not
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3793)
=> [4.7] BL-8527 XMatter should not be part of measure

src/BloomBrowserUI/react_components/colorPickerDialog.less, src/BloomBrowserUI/react_components/colorPickerDialog.tsx, src/BloomBrowserUI/react_components/customColorPicker.less
* remove inner shadow
* change to material-ui buttons
* use Bloom theme
* temporarily remove alpha slider
* hide "HEX" label
* hide control to switch to RGB or HSL input
* regularize padding around dialog contents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3799)
=> BL-8195 Color picker UI mods

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/react_components/colorPickerDialog.tsx
* turn alpha slider off in comic tool, not in dialog
(makes other things easier)
* fix deletion mechanism
* skip swatches in calculating "full" swatch panel that will
not be shown anyway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3806)
=> BL-8195 fixes

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageSelection.cs
Also improve chances of getting a stack trace and error report when an
access violation hard crash occurs.
This fix is needed only for Version 4.8 using Geckofx45.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3804)
=> Fix hard crash from clicking a page before loading complete (BL-8619)

src/BloomExe/Edit/WebThumbNailList.cs
I found this in the course of fixing BL-8619.  I don't know if it helps
that issue directly, but it seems an obvious fix that is needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3809)
=> Fix an event handler to fire only the one time it is needed (BL-8619)

src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.less, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
* include Script/Region/Variant codes to distinguish from
defaults
* this actually solves BL-8175 too, with a bit of an update
for the layout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3811)
=> BL-8174 Web Upload Text

src/BloomExe/Publish/Epub/EpubMaker.cs
Also set the correct direction on the body elements of the .xhtml files
in the generated ePUB.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3814)
=> Remove direction setting from CSS files for publishing ePUBs (BL-8662)

src/BloomExe/Publish/Epub/EpubMaker.cs
This fixes one error found in SVG files and one warning found in the
generated nav.xhtml file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3815)
=> Fix ePUB output to validate for ePUB version 3.2 (BL-8639)

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3823)
=> Fix wifi sharing of books with invalid filename chars in title (BL-8674)

src/BloomExe/Edit/EditingView.cs
Looking at the code again, this seems like an obvious fix.  The current
implementation of the the dialog makes the current code work okay, but
what if the implementation changes to always instantiate a new ImageInfo
when the image changes in any way, not just a new Image in the ImageInfo?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3824)
=> Tweak fix for cropping only second time bug (BL-8638)

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, src/BloomExe/web/controllers/SignLanguageApi.cs
This change should probably be copied to the Version4.8CS branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3829)
=> Set recorded videos from Geckofx60 to be 30 frames per second (BL-7934)

src/BloomExe/Program.cs
This fix increases the chance of getting a stack trace and error report
for access violation crashes which otherwise cause the program to simply
disappear.  It's still not foolproof since the action of bringing up the
text editor with the stack trace can still cause another access violation
which is unhandled.  But it improves the odds considerably.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3810)
=> Fix to improve handling of hard crashes (BL_8619)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/TempFiles.cs
Filenames with characters outside the user's default codepage cannot be
handled when running a GraphicsMagick process from inside Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3818)
=> Run GraphicsMagick with ASCII-only filenames (BL-8512)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/LibraryModel.cs
This can greatly speed up loading a collection with large, complex books
such as nontrivial picture dictionaries.  This is most noticeable when
starting Bloom with the Splash screen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3827)
=> Speed up processing book buttons at idle time (BL-8376)

src/BloomExe/Book/Book.cs
This merely removes something I added yesterday without thinking it
through carefully enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3834)
=> Fix failing unit test (BL-8376)

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
* the secret was to use the information about whether this
is a custom name or not that we store in the collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3828)
=> BL-8174 Sync up C# lang name with BP version

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Publish/Epub/EpubMaker.cs
This can either be a carefully crafted file placed in the original
book folder for permanent use, or it can be generated on the fly from
the cover image for one-time use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3835)
=> Use special epub-thumbnail.png file for publishing ePUBs (BL-8682)

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/EpubValidAndAccessible.cs
Also tweak check for existing epub thumbnail to not require read-only
status: I'm not sure this can be preserved, it isn't logically needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3839)
=> Fix failing unit test due to fix for BL-8682

src/BloomExe/Workspace/WorkspaceView.cs
This seems to be the source of observed GUI strangeness when the dialog
pops up but is hidden behind another window (usually Bloom itself).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3843)
=> Prevent nonstandard DPI warning on auto-restart (BL-8687)

src/BloomExe/Publish/Epub/EpubMaker.cs
Bloom won't create an ePUB for comics, but there's no need to crash!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3848)
=> Make Bloom more robust for harvesting comics (20200721)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
Microsoft Word still uses the old markup.  Other sources probably do as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3850)
=> Convert <b> to <strong> and <i> to <em> when pasting (BL-8711)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs
Also clean up the L10NSharp calls to not be "dynamic" since they aren't.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3856)
=> Add missing PDF related error messages to xliff (BL-8775)

src/BloomBrowserUI/bookEdit/test/testUtil.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/md5Util.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/md5UtilSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordable.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomExe/Edit/AudioRecording.cs
Recently, it was added that if recordings already existed, the sentence splits would be locked. Now, typing will cause the splits to be re-calculated, even if recordings exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3846)
=> TalkingBook also updates sentence splits after text modified (BL-8649)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
Move logic which is about dealing with the newly ready page from showTool to newPageReady.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3871)
=> TalkingBook: Refactor showTool and newPageReady. (BL-8649)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloom_xregexp_categories.js, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3874)
=> Fix bug where context prevents "|" from delimiting phrases (BL-8649)

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/HtmlDomTests.cs
* depends on updated comicaljs
* assumes Comical only inserts svgs that aren't transparent
* migrates old comical books by deleting transparent svgs
inserted for 'none' style bubbles
* add migration tests
* handle case where old book goes directly to Publish
* refactor some stuff around BookStorage's
PerformNecessaryMaintenanceOnBook()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3870)
=> BL-8648 new comical detection algorithm

src/BloomExe/Browser.cs
This is needed for reliably embedding fonts and removing inactive
language data when publishing Bloom Reader and ePUB books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3879)
=> Ensure Browser.NavigateAndWaitTillDone waits long enough (BL-8741)

src/BloomExe/BloomExe.csproj
A previous fix for Mono 5 worked for enabling #if \_\_MonoCS__, but lost the
DEBUG setting so that Debug.WriteLine, Debug.Assert, etc. didn't work on
Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3880)
=> Fix DEBUG settings for Linux (20200813)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/branding/Juarez-USDA-PCI-Guatemala/branding.css, src/BloomBrowserUI/branding/branding-base.less, src/BloomBrowserUI/templates/common-mixins.less, src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less, src/BloomExe/Book/SizeAndOrientation.cs, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, src/BloomExe/Publish/PDF/PdfMaker.cs
This creates a new page size/layout called "Comic Portrait" that is 10.5" high by 6.75" wide.
This PR does nothing to implement the bleed margin of .125" at the top, bottom and outside edges.
The booklet PDF printing assumes A3 paper in the printer.  (Ledger would work as well, fwiw.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3884)
=> Add "Comic Portrait" page size (BL-8832)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts
It is possible for the audio current to get set to the qtip version of it instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3894)
=> Fix audio current getting set to wrong element sometimes (BL-8849)

src/BloomExe/Publish/PublishView.cs
The "Full Bleed" setting was already working properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3915)
=> Remake PDF when changing CMYK setting (BL-8925)

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3931)
=> Fix credits page layout by removing license/copyright min-height (BL-8951)

src/BloomBrowserUI/publish/metadata/BookMetadataTable.less, src/BloomBrowserUI/publish/metadata/SubjectChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3948)
=> Fix subject chooser usability in metadata dialog (BL-9022)

src/BloomExe/Book/XMatterHelper.cs
Don't change to Device xmatter if current xmatter's css handles Device16x9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3959)
=> BL-9085 Simpler Device XMatter handling

src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.less, src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/description-en.txt, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.less, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/description-en.txt
Had to "remanufacture" changes to MXB custom xmatter bloompacks that were
already "on the field", so we have a record in our repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3963)
=> BL-6972 Save MXB xmatter changes

src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx, src/BloomBrowserUI/react_components/bloomSelect.tsx, src/BloomBrowserUI/react_components/stringListCheckbox.tsx
Also remove an unneeded @mobxReact.observer flag from a component.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3970)
=> Fix BookMetadataTable to tab between textboxes (BL-9022)

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomExe/Extensions.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/ExtensionsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3969)
=> Fix URL encoding of books with punctuation in title (BL-9041)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/XMatterHelper.cs
If we know we're going to a device, automatically put all pages that aren't the cover to the back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3971)
=> BL-9091 Auto Order Xmatter

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
Creating bloomd books through harvester were setting signLanguage as a
feature whenever a video exists in the book.  This was then getting set
in the parse table, and showing in next.blorg.  Blind and sign language
should be set only by the user when uploading.  (Talking book is still
being set automatically as a feature: it will be controlled by the user
allowing narration audio to be uploaded.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)
=> Have Android depend on user settings for blind and sign language (BL-8995)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/lib/localizationManager/localizationManager.ts, src/BloomExe/Browser.cs, src/BloomExe/Program.cs, src/BloomExe/Workspace/WorkspaceView.cs
This is needed for Geckofx60 to use anything except English.  Firefox 60
no longer picks up the OS locale (which was a poor substitute anyway for
the current UI language).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3982)
=> Give the browser the UI language for toLocaleString() calls (BL-8275)

src/BloomExe/Extensions.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/PDF/PdfViewer.cs, src/BloomExe/web/controllers/AccessibilityCheckApi.cs, src/BloomTests/ExtensionsTests.cs, src/BloomTests/PretendRequestInfo.cs
Encodes more special characters now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3986)
=> Cleanup ToLocalhost references to use updated implementation (BL-9093)

src/BloomExe/BloomExe.csproj
Previously, I couldn't get the code to build if the directory was named "srcCode #2".
FYI, our typescript code doesn't compile right now if the directory has a "!" in it, but I didn't bother fixing that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3995)
=> Fix .csproj to work even if SolutionDir has spaces or punctuation.

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
If you tab into an Equation-style editable, then type into it, the selection is before the first child (aka the <p> tag). However, we would like the selection to be at the start of the <p> tag, not before.  For bloom-editables, this is normally taken care of by CK Editor, but .Equation-style editables were previously not handled by CK Editor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3998)
=> Fix arithmetic templates overflowing (BL-9102).

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
* hide canvas and bubble text while Image Desc tool is active
* fix talking book tool so it doesn't show image descriptions if that
tool is not active
* fix getRecordableDivs() to include/not include image descriptions
based on whether the tool is active
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4008)
=> [4.9] BL-8515 Comic bubbles interfere with Image Desc.

src/BloomExe/Book/Book.cs, src/BloomExe/Book/SizeAndOrientation.cs
Also ignore being unable to find another file that is optionally copied
only when needed (BL-9129).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4029)
=> Ignore being unable to find an obsolete file (BL-9128)

src/BloomTests/BloomTests.csproj, src/BloomTests/Collection/CollectionSettingsTests.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs, src/BloomTests/PdfMakerTests.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
The reasons for disabling them appear to no longer apply.  They all run
okay on the local machine.
I added a "SkipOnTeamCityLinux" category for the one test that runs okay
locally but would produce an error from a warning message on TeamCity.
It is possible that one or more of the reactivated tests may fall into
that category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4030)
=> Reenable a number of tests on Linux (20201020)

src/BloomBrowserUI/bookLayout/bubble.less
In the first PR for this issue, extra space would be inserted between items if the bubble was much bigger than what was required to fix the text. Now, the stretching of the flex items has been disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4049)
=> Remove extra space between paragraphs in flexboxes (BL-8247)

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.ts
* avoids new Typescript syntax error because of
redeclaration when > 1 quiz page in a book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4056)
=> BL-9185 move const inside functions

src/BloomExe/Publish/SHRP_TeachersGuideExtension.cs
* affects any collection with "Guide" or "TG" contained in the collection name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4061)
=> [4.9] BL-9210 Fix non-SHRP PDF generation

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4066)
=> Fix placement of logo to not be language-setting dependent (BL-8545)

src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, src/BloomBrowserUI/react_components/CopyContentButton.tsx
* switched transition from zoom to fade
* fixed overflow problems
* hide copy button when text box not focused
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4079)
=> BL-9198 Copy text from source bubbles

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
Duplication could also happen after typing the same sentence a second
time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4080)
=> Minimal fix to not duplicate audio ids after text copy/paste (BL-9221)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomBrowserUI/react_components/CopyContentButton.tsx, src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx
Cherry-picked from 5.0
* allows copy to clipboard from any source bubble
* convert BloomSourceBubbles to .tsx
* works with onclick
* got "Copied" transition working
* fix js test failure
* UI review chgs
* switched transition from zoom to fade
* fixed overflow problems
* hide copy button when text box not focused
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4092)
=> [4.9] BL-9198 Copy from text source bubbles

src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less, src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less
* remove horizontal scroll bar
* revert to "normal" bottom padding if not in focus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4105)
=> BL-9294 source bubble focus/scroll problems

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
* box-header-off was causing the wrong text box
to get focus
* Don't have Talking Book Tool hide source bubbles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)
=> [4.9] BL-8073 regularize focus code

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
Needed by Kyrgyz project, but I also make this the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4109)
=> Make Credits page bottom branding text use credits-page-style

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomExe/Edit/EditingView.cs
Holding SHIFT down while changing pages causes a different navigation that doesn't leak as much but is slower.
Holding ALT down while changing pages causes garbage collection to occur in the background without waiting for finalizers.
(This should make page changing appear faster, but may not minimize memory use quite as much.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4112)
=> Trace memory leaks changing pages (BL-9261)

src/BloomExe/Browser.cs
This includes things like opening the "about:memory" window.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4114)
=> Show debug menu items for alpha test builds (BL-9261)

src/BloomBrowserUI/bookEdit/js/bloomWidgets.ts, src/BloomBrowserUI/bookEdit/js/origami.ts, src/BloomExe/Book/Book.cs
* existing widget works when not in Enterprise mode
* if NOT in Enterprise or not in Advanced Features,
- cannot import .wdgt file where there is a placeholder
- cannot change layout of page to add/delete widget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4119)
=> [4.9] BL-9319 Make custom widgets Enterprise-only

src/BloomExe/BloomExe.csproj, src/BloomTests/BloomTests.csproj
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4121)
=> Fix Windows builds for SIL.Media having both 32- and 64-bit dlls

src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/bookEdit/js/origami.ts
I've thought of a possible simpler CSS-only solution, so hold off on reviewing/approving this change.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4124)
=> Show adder buttons as much as possible (BL-9176)

src/BloomBrowserUI/bookEdit/css/origami.less, src/BloomBrowserUI/bookEdit/js/origami.ts
Note that origami.ts has been restored to its state before the previous fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4130)
=> Fix visibility problem in "change layout" in CSS only (BL-9176)

src/BloomBrowserUI/bookPreview/previewMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4131)
=> Fix the fix to hide content overflowing page in preview (BL-9352)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
This warrants some discussion before merging. For one thing, it targets 4.9. So I've made it a draft even though the code change is complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4125)
=> Stop removing transparency from all incoming images (BL-9349)

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4132)
=> Remove problematic max-width on imgs (BL-9350)

src/BloomExe/Publish/Epub/EpubMaker.cs
Note that this fix is on the Version4.9 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4136)
=> Fix ePUB publishing with unsplit textbox audio recording (BL-9370)

src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4139)
=> Fix another glitch caused by unsplit TextBox-mode audio (BL-9370)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4142)
=> Remove rule which caused landscape back cover to not allow full text box to be used (BL-9356)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
* some comment and other minor refactoring
* Caption tails are straight lines, but previous versions
won't display them correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4143)
=> BL-9057 Require Desktop 5.0+ for Caption tails

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/comic/comicToolColorHelper.ts, src/BloomBrowserUI/react_components/colorPickerDialog.tsx, src/BloomBrowserUI/react_components/colorSwatch.tsx, src/BloomBrowserUI/react_components/customColorPicker.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomExe/Book/HtmlDom.cs
* set bubble background including opacity and update
spec
* rework getSwatchFromHex and rename to
getSwatchFromBubbleSpecColor
* simplify setBackgroundColor
* adjust api getColors to not do opacity, since it is now
part of the color string
* move more logic to getSwatchFromBubbleSpecColor
so it handles all expressions of color that can be found
in a bubbleSpec
* fix generation of rgba() string for bubblespec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4152)
=> BL-8537 Handle partly transparent bubbles

src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4157)
=> Skip "empty" durations in generating ePUB audio overlays (BL-9428)

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
This provides a minimum of 6 lines of progress report instead of a minimum of 1 line in my testing.
Visual Studio Designer insisted on changing another layout setting that doesn't seem to materially affect things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4162)
=> Increase minimum size of progress report area for uploads (BL-8429)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomTests/Book/BookStarterTests.cs
2 commits
* 1st is just refactoring
* 2nd uses a new i18n id for the complete version of copyright/license
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4173)
=> BL-9217 i18n issues in Copyright and License

src/BloomBrowserUI/problemDialog/ProblemDialog.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomExe/web/controllers/ProblemReportApi.cs
This fix is based on the 5.0 code, but is much simpler in the C# part.
It should *not* be merged into 5.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4185)
=> Show the description in the Problem Dialog in 4.9 (BL-9520)

src/BloomBrowserUI/bookPreview/previewMode.less, src/BloomBrowserUI/package.json, src/BloomExe/Book/Book.cs, src/BloomExe/BookThumbNailer.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/PublishHelper.cs
Currently templates lose placeholder flowers and  can lose their pages. This makes it hard to view them on blorg2.
Fix up some indentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4189)
=> BL-9346 Don't mess with Bloom Player versions of templates

src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
Writing PNG files turns out to be very slow, whether inside C# code
or with GraphicsMagick.  Setting the quality to 0 for GraphicsMagick
causes PNG saving to use Huffman encoding which is much faster, and
usually okay for image data compression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)
=> Avoid saving PNG files from Image objects if possible (BL-9377)

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/PublishHelper.cs
Also fix a formatting (indentation) error that made code harder to read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4211)
=> Fix for Harvester handling template book pages (BL-9501)

src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/statusPanelCommon.less, src/BloomBrowserUI/teamCollection/stories.tsx
* panel is shorter
* panel color is full-width of screen
* panel contents are limited to 560px width (roughly A5)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4222)
=> BL-9577 Improve TC Status Panel

src/BloomExe/TeamCollection/FolderTeamCollection.cs
I don't know how this stray "using NuGet" got added: it's not used even
on Windows.  And it's totally invalid on Linux/Mono.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4233)
=> Fix a broken build on Linux (20210223)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/Utils/MiscUtils.cs
Also fix a couple of image related bugs along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4240)
=> Generalize error handling when creating/copying PNG files (BL-9533)

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
Also fine-tune the message displayed for fixing duplicate audio ids.  In
many (most?) cases, this results in no message being displayed. (BL-9503)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)
=> Fix missing audio ids (BL-9599)

src/BloomBrowserUI/templates/template books/Wall Calendar/wallCalendar.less
* allow up to 6 rows in a month
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4247)
=> [4.9] BL-9470 Wall Calendar template

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4255)
=> Include L1 by default in Bloom Reader even if incomplete (BL-9587)

src/BloomExe/Book/BookStorage.cs
Compiler complained about needing version 7.2 of C#: not sure if Mono 5
offers that level, and the fix seems clearer anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4264)
=> Fix Linux package build error (20210309)

src/BloomExe/TeamCollection/TeamCollectionApi.cs
It should do so only when the user is in a team collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4281)
=> Fix problem with TeamCollection method disabling Edit tab (20210311)

src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/Browser.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs
Old DOM manipulation approach appeared to contribute to memory leaks, so getting the page content a different way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4288)
=> Save page using RunJavaScript to get content

src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Utils/MemoryUtils.cs
This is a partial cure for memory leaks.
Code is present, but disabled, to only do it when short of memory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)
=> Always reload the top page in the edit view when switching

build/dependencies.config, debian/control
It is used by some unit tests related to image processing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4324)
=> Add graphicsmagick to Linux dependencies (20210331)

src/BloomBrowserUI/collection/enterpriseSettings.less, src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.less, src/BloomExe/Collection/CollectionSettingsDialog.cs
* enterprise tab top/left/right margins now match
previous tabs
* TC collection tab margins are same as enterprise
* TC font type and size now match other tabs
* removed a few unused usings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4340)
=> BL-9746 UI tweaks to Settings dialog

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/Epub/FontFileFinder.cs
Discovered that IntializeFontData() is a bottleneck in ExportEpubTests.  Making that function only happen once instead of every time reduced the time for me to run the entire test suite from 11 minutes to 8.2 minutes, a reduction of 2.8 minutes or 25% speedup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4363)
=> Reduce time taken by ExportEpubTests

src/BloomExe/Program.cs
The user can manually restart Bloom fine after the scary green crash
dialog, but this keeps things going smoother.  This could be applied
to 4.9 if we think it worthwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4362)
=> Fix a Linux crash when restarting Bloom (20210414)

src/BloomBrowserUI/bookEdit/toolbox/comic/colorBar.tsx, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/comic/comicToolColorHelper.ts, src/BloomBrowserUI/react_components/colorPickerDialog.tsx, src/BloomBrowserUI/react_components/colorSwatch.tsx, src/BloomBrowserUI/react_components/customColorPicker.tsx, src/BloomBrowserUI/react_components/stories.tsx
* for background color in Text Blocks and elsewhere
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4391)
=> BL-9815 and 9819 Better 'transparent' handling

src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings
The standard Settings implementation in Mono has known issues which result
in very weird (and crashing) behavior.  I'm not sure why this hasn't hurt
us before the most recent change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4395)
=> Ensure using cross platform settings provides for all settings (BL-9842)

src/BloomBrowserUI/branding/PNG-RISE/branding.json
This does nothing to remove it from existing books, but at least it will
stop introducing it automatically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4397)
=> Remove PNG-RISE contact information boilerplate as requested (BL-9546)

src/BloomBrowserUI/publish/ePUBPublish/epubVisibility.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
* reversing part of my previous change that was not
needed and was more "dangerous"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4402)
=> BL-9844 Kyrgyzstan ePub

src/BloomExe/Publish/PublishView.cs
This helps especially on Linux, which seemed to go through some strange
stages between modes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4408)
=> Make Publish view mode transitions smoother (BL-9798)

src/BloomBrowserUI/package.json, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/HtmlDomTests.cs
The thought is to reduce unnecessary memory allocation/garbage collection required by the book preview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4409)
=> Disable videos in preview mode (BL-9845)

src/BloomExe/web/ReadersApi.cs, src/BloomTests/web/controllers/ReadersApiTests.cs
They also skip pages that don't have any places to put vernacular text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)
=> Readers skip pages that don't print or have nonvernacular text (BL-9876)

src/BloomTests/Book/BookDataTests.cs
The C# compiler on jenkins was reporting Book/BookDataTests.cs(1031,94):
error CS1738: Named argument specifications must appear after all fixed
arguments have been specified. Please use language version 7.2 or
greater to allow non-trailing named arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4427)
=> Fix package build failure on Jenkins (20210504)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
* due to including Kyrg xmatter css in ePubs now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4434)
=> [4.9] BL-9844 Fix ePub xmatter issues

src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, src/BloomBrowserUI/performance/PerformanceLogPage.tsx, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/PublishProgressDialog.tsx, src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx, src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/utils/WebSocketManager.ts
The point of the refactoring was to introduce an automatic disconnect from listening when components are dismounted. That code is still there, and we do want it, but I commented it out because it breaks Bloom Reader Publish preview. Will make a 5.1 card to revisit this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4437)
=> WebsocketManager refactor

DistFiles/localization/en/Bloom.xlf
For now, this is only used in a special REACH upgrade build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4445)
=> Add "Get a better Bloom message" for L10n (BL-9799)

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.less, src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/pageChooser/page-chooser.less, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomBrowserUI/react_components/checkbox.tsx, src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx, src/BloomBrowserUI/utils/WireUpReact.ts, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs
Also:
- fix a bug where our Checkbox class could not handle localization params
- Improve the way the Checkbox aligns the checkbox and label
- Make Checkbox class handle emotion css properly.
- Fix various other uses of Checkbox that this broke.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4449)
=> Don't allow Team Collections to be renamed (BL-9810)

src/BloomExe/Program.cs, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/app.config
* an inadvertent change of setting default led to discovery
of a most bizarre behavior.
* most of the designer changes are just whitespace
* Somehow 'AutoUpdate' behaves differently than any
other Setting in Bloom. To get things working correctly
we've had to migrate to 'BloomAutoUpdate' which works
fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4450)
=> BL-9044 Fix strange AutoUpdate behavior

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4464)
=> Fix misfiring source/hint bubble mouse click (BL-9901)

src/BloomBrowserUI/problemDialog/ReportDialog.tsx
... it's too easy to accidentally close the whole thing when you just wanted to "go back".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4470)
=> BL-9914 don't show the close/quit button if in "Learn More" mode

src/BloomExe/Book/Book.cs, src/BloomExe/CollectionTab/LibraryListView.cs
Turns out there were three places where this was set, and I only had covered one of them. This PR factors out the setting of the tooltip so that all 3 places share the same code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4471)
=> Better BL-9948 fix

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs
If a save to tool state comes in after we're already back on the collection tab, it's not going to get saved anyways. And it seem to not matter, since important tool state gets saved as it happens (e.g. reader level). A better fix JohnT and I decided is way too expensive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4474)
=> BL-9912 saving tool state too late

src/BloomBrowserUI/publish/commonPublish/ProgressDialog.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4495)
=> Fix progress messages padding (BL-9951)

src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, src/BloomBrowserUI/bookLayout/basePage.less
* Works great on EKitabu and Lithium, whether or not the
user chooses to honor the publisher's defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4496)
=> [5.0] BL-9960 Move line-break rule so ePubs get it

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4497)
=> Allow choosing background color when initially transparent (BL-9922)

src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, src/BloomExe/Publish/Epub/EpubMaker.cs
* simplifies Kyrgyzstan xmatter and allows brandings and
other parts of xmatter to layout better when xmatter css
is included in ePub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)
=> [5.0] BL-9844 Fix ePub xmatter

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4500)
=> Display & in language name properly in settings dialog (BL-9919)

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
... also moves it a bit closer to the image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4503)
=> BL-9946 Move image description below front cover image

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4507)
=> Fix check for quiz pages disabling overflow marking (BL-9952)

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.pug
Removing these stylesheet references had no apparent effect on the
program.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4508)
=> Remove references to node_modules from generated html file (BL-9921)

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/ScriptSettingsDialog.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4515)
=> More fixes for ampersands in language names (BL-9919)

src/BloomExe/ApplicationContainer.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/Program.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* Add the "Report" button to the Ui dialog opened
* Re-factoring of fallback reporting
* Add mechanism to submit reports including the problematic .bloomCollection file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)
=> Allow error reporting if opening collection fails (BL-9916)

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4553)
=> Prevent bookshelf getting cleared when other settings saved (BL-10093)

debian/rules
Avoid using the environ script to set the PATH.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4558)
=> Fix broken Linux package building (20210617)

src/BloomBrowserUI/bookEdit/css/editMode.less
Deleting one empty paragraph would delete all contiguous empty paragraphs. Arrow navigating over one would navigate over all contiguous empty paragraphs. Now this is fixed (by not using display:none on the br elements)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4565)
=> Fix bug where empty paragraphs skipped over (BL-10058)

src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
Also fix a minor typo in a progress message that I missed earlier.
The CLI invocation uses no GUI, so it doesn't need to initialize
XulRunner (Geckofx), which was crashing on Linux anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4574)
=> Get bulk upload link working on Linux (BL-9997)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comic.less, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
This is 3 commits:
* 1st adds the comicTool shapes to drag (still need updated icons)
* 2nd just refactors/renames mostly from 'text over picture' to 'over picture 
element' wording
* 3rd a lot of refactoring and the guts of getting video and pics over pics to work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4586)
=> BL-9976 Add pics and video as options for comic "bubbles" over pictures

src/BloomBrowserUI/branding/Kyrgyzstan2020/branding.json, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, src/BloomExe/Book/BookCompressor.cs
The Kyrgyzstan branding files were modified to apply the new class to back-cover images.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4600)
=> Preserve original images when desired for BloomPub books (BL-10162)

src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4608)
=> Handle nonstandard image formats better (BH-5812, BH-5813, BH-5817)

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx
ThemeProvider is already applied to BloomDialog.  Applying it in more
places had no effect.  The expanded list is the same as that given in
bloomMaterialUITheme.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4619)
=> Expand list for font-family in DialogTitle (BL-10208)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookLayout/bubble.less
* handle pic over pic editing
* make comic bubbles not draggable when the book is
locked
* remove Image Description overlay button
* make pic/vid placeholders square
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4607)
=> BL-9976 Video and image comics

src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs
With React asynchronously asking for HTML which can trigger a preview
update, creating a new book from an existing one often updates the
preview DOM and the real DOM simultaneously.  This seems harmless to
me as the code is operating on different input data.  The master branch
has also added more calls to BringBookUpToDate, such as from SelectBook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4628)
=> Nag user about concurrent updates only when problematic (BL-10227)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookLayout/bubble.less
* fix hiding of image buttons for nested imageContainers
* use video container constant
* take off video .bloom-selected when entering comicTool
* add hover background color for video container
* give picture and video over picture elements the blue
border when selected that Just Text bubbles have
* keep video placeholders from automatically jumping to
the sign language tool when clicked
* match size on duplicate picture/video on picture
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)
=> BL-9976 Third section of tweaks, one UI bit to go

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj
These improve the situation on Linux with regard to using SQLite, but don't totally solve it.
In theory, these changes should have been sufficient as well as necessary.  I'm looking for
a new theory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4634)
=> Tweak SQLite related packages for Linux

src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettingsToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This should finish the renaming task after splitting into bundle
specific exports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4635)
=> Finish using toolboxBundle inside the toolbox (BL-10235)

src/BloomExe/Book/Book.cs
Without this fix, computing the book's hash throws an exception when it
encounters a read-only file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4638)
=> Allow read-only image files (20210805)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4656)
=> Add non-edit mode border to images for better WYSIWYG (BL-10268)

src/BloomExe/BloomExe.csproj
This will fix a recurring source of package build failures that I've
previously changed code to fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4662)
=> Ensure Linux package builds use C# 7.3 (20210817)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comic.less, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
* figured out "hooks" problem
* replaced 'bubbleActive' state with 'bubbleType', which
allows the UI to distinguish text/video/image bubbles
* added a "Show Sign Language Tool" button to go to that
tool when a video is selected in comic tool
* added a message "Image selected" when a picture over
picture element is selected in comic tool
* fix image metadata problem question mark that was
showing twice on picture over picture
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4630)
=> BL-9976 tool UI changes

src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx, src/BloomBrowserUI/react_components/ContentEditable.tsx, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs
Also add asserts to check for the invalid color string issue that Koen claims
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4673)
=> Fix Color Chooser getting reset on enter. (BL-10190)

src/BloomTests/TeamCollection/TeamCollectionTests.cs
* there is now an extra book-selection event in this case that occurs "last"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4674)
=> Fix failing test

src/BloomExe/CLI/CreateArtifactsCommand.cs
This allows harvester to produce books with the same settings as the user sees on the local machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4676)
=> Set AndroidPublishSettings from metadata in CLI commands (BL-10300)

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This also required moving the 5.0 tag on PdfDroplet to match.
If these changes do not merge cleanly to master, there will be a separate PR for master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4688)
=> Update libpalaso to fix crash in ImageToolboxDialog (BL-10314)

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/bookLayout/bubble.less
* removed a rule that fixed BL-7929 2 years ago
* more recent rules in bubble.less seem to have fixed the
older problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4689)
=> BL-9976 Fix Over Picture sizing

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/checkStorySpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
Fixing the regular expression appears to fix the cursor jumping problem
as well since javascript exceptions are no longer interfering with typing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4696)
=> Fix regular expressions for letters involving hyphens (BL-10324)

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
Code says gray, but was actually showing up as purple (CSS selectivity favored the Material UI rule...)
Now made it the same color as the Edit text color.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4710)
=> Change "Make a book using this source" button to black (BL-10358)

src/BloomExe/CollectionTab/LibraryListView.Designer.cs
* Initially tried commenting out the whole section,
but it left a gap in the menu!
Making the menu items not visible allowed it to adjust
things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4712)
=> BL-10381 Hide Spreadsheet menu commands

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
Old: The Make a book using this source button was purple
1st change: Always made the button black. However, if the book button was disabled, it was black instead of gray.
This change: If the button is enabled, it is black. If disabled, it is gray.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4713)
=> Rework change "Make a book using this source" button to black (BL-10358)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/CollectionTab/LibraryListView.Designer.cs, src/BloomExe/CollectionTab/LibraryListView.cs
* Delete a few unused 'usings'
* Update L10n keys, so they will work when we need them
* Remove unused event handler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4717)
=> BL-10381 Hide Spreadsheet commands

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookServer.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomTests/Book/BookStarterTests.cs, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Edit/ConfiguratorTest.cs, src/BloomTests/TestDoubles/Book/FakeBookServer.cs
This ensures that the proper support files are included in the uploaded
books.
I also renamed a method to reduce confusion moving forward.
The forSelectedBook parameter to ExpensiveInitialization has also been
renamed to fullyUpdateBookFiles to express usage instead of one caller's
intention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4727)
=> Fix BulkUploader to call ExpensiveInitialization(true) (BL-10347)

src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.cs
* Extend the existing DisplayMode to include
NotPublishable
* Save a couple of initial strings in ctor, so a second book
will update the error message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4737)
=> BL-10418 Fix persistent error mode

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/BloomServer.cs
Also ensure branding images are found when changing collection settings
without changing the book selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4735)
=> Eliminate unnecessary missing file reports when previewing templates (BL-10409)

DistFiles/localization/README.md
This will reduce confusion for merging Crowdin commits in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4742)
=> Update some details in DistFiles/localization/README.md (20210923)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs
This includes setting bookshelf to "None" not displaying a bogus missing
image message and updating the book preview more promptly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4744)
=> Handle branding bookshelf settings better (BL-10451)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
The problem is that the "Words" message handler in readerTools.ts tries to call the "Words" message handler in readerSetup.ui.ts. However, because now the readerTools handler is somehow attached too (an import which indirectly imports ReaderTools causes this somehow, see commit 6edf699819f39df3073e1b8a3710337a3afb34fc's jquery.text-markup.ts), now both handlers respond to the "Words" message. Note that Words is now invoking itself (along with its desired target) which means this is an infinite recursion. It invokes itself repeatedly (with the wrong parameters after the 1st time) and the matching words are overwritten after the 1st iteration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Fix no  matching words in Decodable Reader setup dialog (BL-10439)

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4758)
=> Disable turning off image descriptions in xmatter pages (BL-10472)

src/BloomExe/CollectionTab/LibraryListView.cs
The setting could be present in the userprefs file but listed as <value>\r\n        </value>, in which case the Null Coalescing Operator failed to detect that it was uninitialized.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4770)
=> Fix wrong default spreadsheet export folder (BL-10259)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4813)
=> Fix vertical alignment of toolbox item when enterprise-only (BL-10622)

src/BloomExe/Edit/EditingView.cs
This effects A4 Landscape (Side By Side) and A4 Landscape (Split Across Pages) page orientation. They are from the early days and were an attempt to provide layout-like capability through the page orientation system. At some point when we switched to actual layouts, we broke these and no one noticed.
For 5.0 & 5.1, we're hiding them.
For 5.2, we remove them from the code entirely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4814)
=> BL-9636 Hide two unsupported page orientations

src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomExe/Spreadsheet/SpreadsheetRow.cs, src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs, src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, src/BloomTests/Spreadsheet/SpreadsheetTests.cs, src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs
- Remove image and text index columns
- Color-band every other page
- Hide metadata columns & make gray background
- Push most metadata rows to the end & hide & make gray background. This doesn't include the 1st row (labels) or title
- Bold the first row
TODO: combining text and image rows
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4806)
=> Clean up spreadsheet (BL-10368)

src/BloomExe/web/BloomServer.cs
This fix is for Version5.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4817)
=> Make cover images transparent in book preview (BL-10625)

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less
This fix is simple enough that it might be cherry-picked to 5.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4819)
=> Fix Comprehension Quiz answer alignment for long answers (BL-10581)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js
This fix is for Version5.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4818)
=> Fix bug in marking phrases for audio splitting (BL-10569)

src/BloomExe/CommonMessages.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4830)
=> Fix TCol sync dialog report button when there is a book error (BL-10624)

src/BloomExe/TeamCollection/BookHistory.cs
Trying to create a SQLiteConnection always throws an exception on Linux.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4852)
=> Disable book history on Linux since it is not working

src/BloomBrowserUI/publish/stories.tsx, src/BloomBrowserUI/react_components/bookInfoCard.tsx, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
* In the Upload ID Collision dialog, uploading now lists
the languages actually checked to upload, not just the
currently "active" ones or even all the languages that have
some text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4854)
=> BL-10734 Better upload language handling

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/web/controllers/SignLanguageApi.cs, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/Utils/MiscUtilsTests.cs
* whitelists file extensions for book level and audio and video folders
* whitelists an activities folder (Widgets) and any contents
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)
=> BL-8956 switch BookCompressor from black to whitelist

src/BloomExe/Book/BookCompressor.cs
* we hadn't handled collection-level files
* or simpleComprehensionQuiz.js
* or .distribution
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4857)
=> Fix for BL-8956 for BloomPacks

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/lib/json.js, src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, src/BloomExe/Book/SizeAndOrientation.cs, src/BloomExe/Edit/EditingView.cs, src/BloomTests/Book/SizeAndOrientationTests.cs
These were used before we had page layouts. Nowadays, we keep "layouts" separate from "page size/orientation".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815)
=> Remove SideBySide and SplitAcrossPages

src/BloomBrowserUI/bookLayout/basePage.less
* problem was an accidental conflation of rules when
removing side-by-side
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4895)
=> BL-10805 A4Landscape regression

src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomTests/Book/BookStorageTests.cs
* initial refactor
* delete all .htm/.html files in book folder other than the
one we need for the book and configuration.htm and any
readme files.
* Was initially concerned that this PR doesn't apply to bulk upload, but
bulk upload only uploads books with only one .htm file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868)
=> BL-10679 Don't publish multiple .htm files

src/BloomBrowserUI/bookEdit/css/origami.less
* also refactored so all the .origami-layout-mode code was
in one place
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4908)
=> BL-9953 Defeat toolbox markup in origami mode

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Publish/Android/AndroidPublishSettings.cs
* When Harvester is creating bloomPUB artifacts (which
will be used to READ the book online), it should use the
language selections that the user chose in the BL upload
control.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4915)
=> BL-10840 Fix L1 not showing on bloom library

src/BloomBrowserUI/react_components/bloomButton.tsx, src/BloomBrowserUI/utils/BloomMessageBox.tsx
* allow BloomButton to take normal button props
* add disable ripple to all the buttons
* use the BloomDialog's innards instead of Materials, which was giving us gray text
* add an empty title element so that things are still spaced well
* add some space between the icon and the text
* push the text down a wee bit w.r.t. the icon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4917)
=> BL-10849 Fix message box

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
That's the last framework supported by mono5-sil (mono 5.16)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4971)
=> Fix Linux build to use .net framework 4.7.1 (20220216)

src/BloomExe/BloomExe.csproj
Bloom 5.1 builds with node 12 while bloom-player builds with node 16.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4981)
=> Fix Bloom 5.1 Linux yarn install for new bloom-player (20220217)

src/BloomExe/Properties/AssemblyInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4997)
=> Fix font scaling when two monitors are scaled differently (BL-10981)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bloomMaterialUITheme.ts, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx, src/BloomBrowserUI/bookEdit/StyleEditor/stories.tsx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/react_components/fontDisplayBar.tsx, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomExe/FontProcessing/FontFileFinder.cs, src/BloomExe/FontProcessing/FontMetadata.cs
* finally talk getPageFrame() into not complaining
in VS Code
* wire up new React panel for Format dialog
* add story to Storybook
* get select menu items from fontdata
* get font list to overlay main dialog
* get current font to show correctly
* show font in that font face
* show colored badge to right
* get font change to actually propagate to text
* get popover working
* get a more complete font list, but marked for suitability
* add stories
* add FontDisplayBar as a separate component
* differentiate between fonts in dropdown and selected
* turn input red if unsuitable
* feed hovered font into popover (FontInformationPane)
* don't use disabled on MenuItems; still gray out not-OK
* get info pane formatted correctly
* close popover on any click instead of mouse leave
* add info button …
=> BL-10388 Improved font UI for Format dialog

src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
...as opposed to making all of the white pixels transparent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5000)
=> Preserve image if it already has transparency (BL-10972)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx, src/BloomBrowserUI/react_components/fontDisplayBar.tsx, src/BloomBrowserUI/react_components/fontInformationPane.tsx
* remove extra "Version"
* include drop down arrow
* match sizes of font and font-size selects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5009)
=> BL-10388 Font UI tweaks

src/BloomExe/Collection/CollectionSettingsDialog.cs
Try to ensure that controls don't stand out against the background of the current tab page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5010)
=> Try to keep controls from sticking out in settings dialog (BL-10973)

src/BloomExe/Publish/Android/BloomPubMaker.cs, src/BloomExe/Publish/PublishModel.cs
Also remove redundant (and slightly deficient) SanitizeFileName method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5015)
=> Fix a Harvester crash for trailing periods in title (BH-6097)

src/BloomExe/Browser.cs
I've satisfied myself that not disconnecting the GeckoBrowser event
handlers in Browser.Dispose does not cause any memory leakage or
delays in garbage collection.  But I added a comment and one event
disconnection to the Dispose method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5019)
=> Minor dispose/disconnect tweaks to Browser (BL-9835)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/Android/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
ePUBs were crashing and bloomPubs weren't warning users that these fonts
can't be published.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5017)
=> Prevent crashes and warn users about .ttc font files (BH-6108)

src/BloomExe/Browser.cs
The Control.ModifierKeys property does not work on Linux when a Gecko
based browser is active.  This implements a simple state machine (on
Linux only) to enable the debugging menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5048)
=> Enable generic browser debugging on Linux (20220321)

src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/statusPanelCommon.less, src/BloomBrowserUI/teamCollection/statusPanelCommon.tsx, src/BloomBrowserUI/teamCollection/stories.tsx
* redid the flexbox arrangement some
* bottom margin is now consistent with all "occupants"
* changes Input is same height as button so it's easier
to align correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5055)
=> BL-10862 Align checkin button properly

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx, src/BloomBrowserUI/bookEdit/StyleEditor/stories.tsx, src/BloomBrowserUI/collection/fontScriptSettingsControl.tsx, src/BloomBrowserUI/react_components/AutoUpdateSoftwareDialog.tsx, src/BloomBrowserUI/react_components/fontDisplayBar.tsx, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, src/BloomBrowserUI/react_components/singleFontSection.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/webpack.common.js, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/FontProcessing/FontsApi.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs
* move font test data to a separate file
* add control to storybook
* remove old controls from Collection Settings Dialog
* refactor to pull out SingleFontSection that groups the
controls for each language
* get script settings link working
* remove more old stuff in C#
* only display font control when it has a font
* use FontsApi to get font data to new control
* correct a localization Id in requiresBloomEnterprise
* allow font script control to display before font metadata
"arrives"
* update some api endpoints
* add close icon to font information pane
* finish up dialog updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5042)
=> BL-10974 new font control in Collection Settings

src/BloomExe/Book/HtmlDom.cs
* remove some more legacy preview code
* add script tag to regex list in CleanupHtml5()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5059)
=> BL-11056 fix Calendar preview

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, src/BloomBrowserUI/webpack.common.js, src/BloomExe/Book/Book.cs, src/BloomExe/web/BloomServer.cs
* removed more obsolete preview stuff
(including 3 webpack bundles)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)
=> Minor refactoring

src/BloomBrowserUI/react_components/localizableMenuItem.tsx
I also cleaned up a couple of warning from React parsing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5071)
=> Use Segoe UI for menus when available (BL-11039)

src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightPanel.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5073)
=> Hide the up/down control on the year field (BL-6259)

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx
* a couple of minor places in the overlay tool were updating themselves,
but not the overall spec that governed the UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5100)
=> BL-9936/11104 Make sure overlay UI is up-to-date

src/BloomExe/Publish/Android/BloomPubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
Getting fonts for embedding is working okay already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5106)
=> Clean CSS of unwanted language rules in BloomPub publishing (BL-11108)

src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, src/BloomExe/web/ReactControl.cs
* Bookshelf dropdown hover fixed
* better css for ReactControl
(we might be able to do w/o either or both of App.less
and TeamCollection.less, but I wanted to get this working)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5120)
=> BL-10974 Tweaks

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx, src/BloomBrowserUI/bookEdit/StyleEditor/stories.tsx, src/BloomBrowserUI/react_components/singleFontSection.tsx, src/BloomBrowserUI/react_components/winFormsStyleSelect.tsx
* redo select id to require a language number
* repaired popup detection mechanism to be more general
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5123)
=> BL-11139 fix font select

src/BloomExe/Publish/PublishView.Designer.cs, src/BloomExe/Publish/PublishView.cs
* and trick winforms into not doing horizontal scrolling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5127)
=> BL-11143 widen Publish sidebar

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
Prevents a message box popping up for BL-3166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5148)
=> Prevent extraneous call to get book preview html

src/BloomExe/Book/Book.cs, src/BloomExe/UrlPathString.cs
I thought we killed this bug years ago, but apparently not quite.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5116)
=> Fix URL encoded filename stored for cover image (BL-11145)

src/BloomBrowserUI/app/selectedBook.ts, src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, src/BloomExe/Workspace/WorkspaceView.Designer.cs, src/BloomExe/Workspace/WorkspaceView.cs
The only remaining regression is no adjustable split between the book preview and information panes.  This would require more knowledge of how splitters work in React, and probably be much more complicated in implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5161)
=> Restore book information panes for template previews (BL-11190)

src/BloomBrowserUI/react_components/winFormsStyleSelect.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5190)
=> Prevent scrolled font menu from jumping (BL-11258)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookCopyrightAndLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5199)
=> Fix BL-11280 [5.2] Tweak boilerplate text in adaptation credits

src/BloomExe/Publish/PublishView.Designer.cs
Without this, the ePUB button is shoved all the way to the bottom on
Linux, possibly offscreen if the the window is resized to be smaller.
This has no apparent effect on Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5208)
=> Fix the ePUB button display location on Linux (20220607)

src/BloomBrowserUI/utils/BloomMessageBox.tsx, src/BloomBrowserUI/utils/bloomMessageBoxSupport.ts
* added function for Typescript-land to open the dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5210)
=> BL-11150 Fix BloomMessageBox

src/BloomExe/ErrorReporter/ErrorReportUtils.cs
All this does is give slightly more realistic behavior in the fake error report dialogs used for development/testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5209)
=> Populate stack trace in fake error report dialogs

src/BloomExe/Book/BookData.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5225)
=> Fix BL-11290, remove full-bleed if branding no longer requests it

src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx, src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs, src/BloomExe/Publish/Video/RecordVideoWindow.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5227)
=> Change FB video target to 2:3 aspect ratio (BL-10992)

src/BloomBrowserUI/lib/ckeditor/config.js
It's sad what missing a silly semicolon can do...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5237)
=> Restore pasting of formatted text (BL-11325)

DistFiles/localization/en/TrainingVideos.xlf, src/BloomBrowserUI/infoPages/TrainingVideos-en.md
* The tiny.cc links were also updated to point to the
"All videos" link.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5184)
=> BL-10833 Fix broken links in Training Videos

src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs, src/BloomExe/Publish/Video/RecordVideoWindow.cs
This was because it was observed that videos uploaded to a business/organization page were only allocated a 4:5 box.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5248)
=> Change FB portrait target size to 4:5

src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx
This applies to Version5.2.  These were inadvertently left out earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5249)
=> Apply publishing license restrictions to USB and Wifi (BL-11328)

src/BloomExe/Publish/Video/RecordVideoWindow.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5250)
=> Fix bookUrl encoding for RecordVideoWindow (BL-11319)

src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomExe/web/controllers/CollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5251)
=> Prevent spurious missing l10n messages for collection names

src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5253)
=> Fix BloomPUB preview when book file name has parentheses (BL-11352)

src/BloomExe/Collection/BookCollection.cs, src/BloomExe/CollectionTab/CollectionTabView.Designer.cs, src/BloomExe/CollectionTab/CollectionTabView.cs
The problem occurs after switching collections. There are 2 CollectionTabView instances and 2 BookCollection instances attempting to watch the same directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5257)
=> Fix book download not opening (BL-11326)

src/BloomBrowserUI/.eslintrc.js, src/BloomBrowserUI/bookEdit/copyrightAndLicense/LicensePanel.tsx, src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManager.ts, src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx, src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomBrowserUI/lib/localizationManager/localizationManagerSpec.ts, src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx, src/BloomBrowserUI/publish/commonPublish/PublishProgressDialog.tsx, src/BloomBrowserUI/publish/commonPublish/PublishProgressDialogInner.tsx, src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx, src/BloomBrowserUI/publish/stories.tsx, src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomBrowserUI/react_components/helpLink.tsx, src/BloomBrowserUI/react_components/htmlHelpLink.tsx, src/BloomBrowserUI/react_components/muiRadio.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/teamCollection/ForceUnlockDialog.tsx, src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx, src/BloomBrowserUI/teamCollection/stories.tsx, src/BloomBrowserUI/utils/bloomApi.ts
This warning is in eslint's recommended list.
eslint doesn't like it supposedly because:
1. Hard to tell if it was intentional or mistake
2. Hard to tell if it's an empty function or returning an empty object.
Solutions:
1. eslint recommends adding a comment in the body explicitly explaining that you want to "do nothing", etc.
2. () => undefined technically also works, although idk that it's any more clear
3. disabling the rule (temporarily or globally) also works...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5265)
=> Fix "no-empty-function" eslint  warnings

src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5315)
=> Restore missing SIL.Windows.Forms.GeckoBrowserAdapter to Linux build

src/BloomBrowserUI/package.json, src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx
For the Philippines ABC project, the blorg label  doesn't give enough context to make the choice.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5318)
=> Use UrlKey for selecting upload bookshelf

src/BloomExe/Book/SizeAndOrientation.cs, src/content/branding/MXB-Book-Literacy/branding.json, src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/MXBLiteracy-Device-XMatter.less, src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/MXBLiteracy-Device-XMatter.pug, src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/description-en.txt, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.pug, src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/MXBScripture-Device-XMatter.less, src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/MXBScripture-Device-XMatter.pug, src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/description-en.txt, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug
* Set default HalfLetterPortrait page size
* fix "Funding Agency" line breaks
* add Device xmatters for Literacy and Scripture
* close up space under license block
* add custom spanish hint bubbles for various
Scripture fields
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5323)
=> [5.3] BL-11273 MXB tweaks

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/lib/ckeditor/plugins/colorbutton/plugin.js, src/BloomBrowserUI/react_components/bloomPalette.ts, src/BloomBrowserUI/react_components/colorChooser.tsx, src/BloomBrowserUI/react_components/colorPickerDialog.tsx, src/BloomBrowserUI/react_components/stories.tsx
Could have done more, but I chose to scope this to what I can do this afternoon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5357)
=> Refactor Palette stuff, give ckeditor accesses to our colors

src/BloomBrowserUI/react_components/colorPickerDialog.tsx
* A lot of the original color picker dialog has now been built into BloomDialog,
so using it simplifies the color picker greatly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5358)
=> BL-11406 change Color picker to use BloomDialog

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx
* fixes overlay text color and Android cover color
* will fix overlay background color in webview2
(this is broken since at least 5.2 in Geckofx)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5363)
=> Fix hex color selection (BL-11406)

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx
* ESC -> treated like Cancel
* clicking out of dialog -> treated like OK
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5365)
=> BL-11406 standardize color picker

src/BloomExe/Publish/AudioProcessor.cs, src/BloomExe/web/controllers/MusicApi.cs
But allow existing .wav background audio files in existing books to hang around.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5381)
=> Don't allow importing .wav music (background) audio files (BL-11481)

src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/HtmlThumbNailer.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/web/controllers/CommonApi.cs, src/BloomTests/Book/BookTests.cs
* fix Android cover color detection regex to handle
lowercase 'div' rules from templates
* keep black color for templates with preserveCoverColor
(Comics and Video)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)
=> BL-11406 color picker fixes

src/BloomExe/ImageProcessing/ImageUtils.cs
After extensive testing and discussion, we decided to speed up processing PNG files by a factor of 4 while increasing file sizes by maybe 4%.  (This applies to reducing image dimensions on importing image files.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5401)
=> Adjust PNG compression from 100 to 75 for GraphicsMagick (BL-11441)

src/content/branding/MXB-Book-Scripture/branding.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.pug, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.pug, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug
* Both Literacy and Scripture: add L1-Name-style to front
cover language name
* shrink LigaBiblica logo
* add Reference-Default-style to Scripture reference field
and style as requested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5411)
=> BL-11273 MXB xmatter tweaks

src/BloomExe/Program.cs
The bug report in BL-10333 is not this, but its example book showed this bug, which I added as a comment while testing fix for the original problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5430)
=> Fix spurious path length errors from downloading books (BL-10333)

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.pug, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug
* added default rules for L1-Name-Cover and
L1-Name-TitlePage styles, which allows them to show up
in the styles dialog
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5433)
=> BL-11273 more MXB tweaks

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/EPubMakerTests.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/Publish/ExportFixedLayoutEpubTests.cs, src/BloomTests/Publish/UsbPublisherTests.cs, src/BloomTests/Publish/Video/ResolutionTests.cs, src/BloomTests/Spreadsheet/SpreadsheetAudioImportTests.cs, src/BloomTests/Spreadsheet/SpreadsheetAudioTests.cs
* Tests now run in Region: English (Sweden)
* fixed a few places where being in the wrong region might
have messed up the user's data!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5440)
=> BL-10042 Fix failing unit tests if in different region

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5468)
=> Hide format gear icon when its text box is not focused (BL-11603)

src/content/branding/MXB-Book-Scripture/branding.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less
* they want all xmatter pages to have the same bottom margin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5469)
=> [5.3] BL-11273 MXB Enterprise bottom margin fix

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This fixes the side-effect of setting text background to transparent. It also extracts a method from some repeated code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5480)
=> Tweak the fix for dropping images from overlay tool (BL-11620)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
* by clearing .bloom-editable bubble colors in 5.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5489)
=> [5.3] BL-11621 Prepare for Style text color changes

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
I don't think it actually causes any errors at this current commit (because Jquery), but if you were to start doing vanilla JS assuming that containerDiv is not undefined as the types state, you'd be sorry :(
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5494)
=> Handle if overlay contains a non-overlay-image bubble

src/BloomExe/Publish/PDF/PdfMaker.cs
This looks safe for cherry-picking to 5.3.  The bug has been around since at least 5.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5501)
=> Fix PDF generation on Linux for full bleed books (BL-11685)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5502)
=> Ctrl or Alt key causes image editing buttons to hide (BL-11638)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/overlay/colorBar.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx, src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx, src/BloomBrowserUI/react_components/color-picking/colorSwatch.tsx, src/BloomBrowserUI/react_components/color-picking/stories.tsx
* introduces the concept of a default style text color
* setting the style of a bubble w/StyleEditor can be overridden
by setting the Overlay tool text color.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5500)
=> [5.4] BL-11621 Move Overlay text color to editable

DistFiles/InstallAce.sh
This should be cherry-picked to 5.3 as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5507)
=> Update ACE by Daisy Linux install script to use node 16 (20221031)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5525)
=> Safely remove inserted BOM after span.bloom-linebreak (BL-11717)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/css/qtipOverrides.less, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5535)
=> Ensure the tooltip for the active field shows on top (BL-11745)

src/BloomExe/Collection/CollectionSettings.cs
* loading CollectionSettings was inadvertently "migrating"
SignLanguageName to an invalid SignLanguage1Name
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5539)
=> [5.3] BL-11754 fix Custom Sign Language Name problem

src/BloomExe/Book/BookData.cs
* this fixes the language name on parse.com which affects
the language name on the Book Detail page online
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5548)
=> BL-11754 Fix upload of custom Sign Language name

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookInfo.cs, src/BloomTests/Book/BookTests.cs
Addresses the failing unit test BloomTests.Book.BookInfoTests.TitleSetter_FixesTitleWithXml. The \r\n is handled different by XmlDocument vs XElement. (Also, that path was previously not trimmed)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5522)
=> Re-do fix for titles with linebreaks (BL-11717)

src/BloomExe/Publish/PublishModel.cs
Exception.Message is usually far too brief to be informative enough. This change will allow the exception stack trace and other information to show up in the problem report.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5552)
=> Allow problem report dialog to capture exception info (BL-11788)

src/BloomBrowserUI/.eslintrc.js, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
Currently, VSCode does not complain if you fail to add something to the dependencies array of something like useEffect, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5557)
=> Add react-hooks/exhaustive-deps linting rule

src/BloomBrowserUI/bookEdit/css/editMode.less
This essentially redoes the fix for BL-11603 in a better way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5559)
=> Fix loss of style button in ISBN field (BL-11803)

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less, src/BloomBrowserUI/bookEdit/TextBoxProperties/TextBoxProperties.less, src/BloomBrowserUI/bookEdit/css/bloomDialog.less
* modify colors to use bloom palette
* fixes BOTH the StyleEditor (format dialog) AND the
TextBox Properties dialog
* overrides colors from 3rd party select2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5565)
=> BL-11676 Make Format dialog conform

src/BloomBrowserUI/package.json
In theory, old files should be removed when copying bloom-player to the output folder to avoid some subtle bug possibilities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5577)
=> Clean bloom-player directory

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5599)
=> Fix bloom-player pages/buttons misaligned (BL-11497)

src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
This fix applies to Version5.4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5636)
=> Fix padding for PublishAudioVideo screen (BL-11820)

src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
This is not a cherry-pick because the commit that included this line did not apply cleanly and included other changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5644)
=> Prevent recording video when display is actively scaled (BL-11880)

src/BloomExe/CollectionTab/CollectionTabView.cs
* another change for the disappearance of Source/Vernacular collections
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5646)
=> BL-11921 update Help URL in Collections tab

src/BloomExe/Linux/packages.config
This is for Bloom 5.4, the last version supported by Linux (for now).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5668)
=> Fix the Linux packages.config for new libpalaso version (20230227)

DistFiles/localization/az/BloomLowPriority.xlf, DistFiles/localization/en/BloomLowPriority.xlf, DistFiles/localization/es/BloomLowPriority.xlf, DistFiles/localization/fr/BloomLowPriority.xlf, DistFiles/localization/pt/BloomLowPriority.xlf, DistFiles/localization/sw/BloomLowPriority.xlf, src/BloomExe/CLI/ChangeLayoutCommand.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/CLI/DownloadBookCommand.cs, src/BloomExe/CLI/SendFontAnalyticsCommand.cs, src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Spreadsheet/SpreadsheetExportCommand.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs, src/BloomExe/Spreadsheet/SpreadsheetImportCommand.cs, src/WebView2PdfMaker/Program.cs
Exception.ToString() provides more information than the combination of Exception.Message and Exception.StackTrace.  (It includes both of those plus more, at least in some circumstances.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5674)
=> Enhance console messages for caught exceptions

src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx, src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightAndLicenseDialog.tsx, src/BloomBrowserUI/bookEdit/css/bloomDialog.less, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx
* No dialog should drag from anywhere but the title
* If we want to disable dragging, only tell the Dialog, not the Title too
* Restore dragging on 3 dialogs that had disabled it for a problem that I cannot reproduce (assuming it was a geckofx-specific thing).
* Allow dragging to the bottom of the screen even if the page is shorter
* Allow dragging to the very edge of body
* On the jquery-based dialogs a) change title to be white b) show drag cursor on title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5682)
=> Improve various dialog dragging things

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5684)
=> [5.4] BL-11992 Fix L1 name wrapping on MXB Cover

src/BloomExe/Book/BookCompressor.cs, src/BloomExe/Book/PublishSettings.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/CLI/SendFontAnalyticsCommand.cs, src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/Publish/Android/AndroidPublishSettings.cs, src/BloomExe/Publish/Android/BloomPubMaker.cs, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomExe/web/controllers/AccessibilityCheckApi.cs, src/BloomExe/web/controllers/BookSettingsApi.cs, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/ExportEpubTests.cs
* Make constructors for all classes which create all children
* For various language arrays, instead of checking for null, check for empty array
* In method arguments, stop making provision of settings optional
* When deserializing from json, do that on top of a fully constructed object
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5677)
=> Remove reliance on null for all Publish Settings

src/BloomBrowserUI/utils/BloomMessageBox.tsx, src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/MiscUI/BloomMessageBox.cs, src/BloomExe/Program.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, src/BloomExe/Publish/PDF/PdfViewer.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/Workspace/WorkspaceView.cs
* instead of NotifyUserOfProblem, use BloomMessageBox
which doesn't claim that Bloom had a problem when it
didn't
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)
=> BL-11303 better dialog solution

src/BloomExe/SourceCollectionsList.cs
* If the template that a book is based on doesn't exist on this machine,
this keeps the add page dialog from crashing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5698)
=> Fix missing template crash

src/BloomExe/Book/BookStarter.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookStarterTests.cs, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.pug, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug
* added .bloom-removeWhenMakingDerivative class to the
translation group
* added code in BookStarter that looks for this class and an
associated 'data-book' key and removes the bloom-editable
contents from the book and the datadiv.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697)
=> BL-11993 Make MXB Printing History a non-derived field

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
I think this finally works with the async/Promise stuff properly to get the deshrouding to happen at the right time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5718)
=> Another attempt to get hiding/revealing phrase markers to work (BL-11632)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx, src/BloomBrowserUI/react_components/stories.tsx
* add a tooltip explaining why the item is disabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)
=> [5.4] BL-12005 keep disabled menu items

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/Publish/Android/file/FilePublisher.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/Video/RecordVideoWindow.cs, src/BloomExe/Utils/OutputFilenames.cs, src/BloomExe/web/controllers/BookCommandsApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Publish/Video/RecordVideoWindowTests.cs, src/BloomTests/Utils/OutputFilenamesTests.cs
This changeset does not deal with spreadsheets, which look for folder paths instead of file paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5724)
=> Use common code for creating/remembering output filenames (BL-11996)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts
* The old code was actually adding the right span,
but AFTER the paragraph element it was supposed to be
inserting INTO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)
=> BL-12053 Fix Shift+Enter

src/BloomExe/Book/Book.cs, src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomTests/Book/BookInfoTests.cs
* pull out code that creates runtime injector dictionary
to make it testable
* use the 'language-display-names' field of meta.json to
fill in the Display names of languages "known" to the
collection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5737)
=> BL-12064 DisplayName problem

src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs
* make unique copies of image files, if the image is re-used
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5742)
=> BL-10772 On SS import, image re-use generates new image

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx, src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx, src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx, src/BloomBrowserUI/react_components/BloomToolTip.tsx
Also use BloomTooltip to provide nicer looking tooltips (with a somewhat better message) for disabled PDF booklet buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5755)
=> Add BloomTooltip placement capabilities and default L10n use (BL-12096)

src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx
* No Topic means 'currentTopic' is undefined
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5758)
=> [5.4] BL-12106 Correct "No Topic" dialog load

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx, src/BloomBrowserUI/react_components/BloomDialog/BloomDialogPlumbing.tsx, src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx, src/BloomBrowserUI/utils/bloomApi.ts
Commit 1: Refactor ProgressDialog to be easier to consume
Since ProgressDialog doesn't expose the event args to its consumers, they might as well take it in via a simple scalar prop which is easier to comprehend than having to useRef functions which generate functions and invoke them at the right time
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5741)
=> Show progress dialog for long-running MakeSelectedBook ops (BL-12033)

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5762)
=> Stop multiplying languagesOfBook fields in bloomDataDiv (BL-12112)

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomLowPriority.xlf, src/BloomBrowserUI/collection/useGetEnterpriseBookshelves.tsx, src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx, src/BloomBrowserUI/react_components/BloomToolTip.tsx, src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx, src/BloomExe/ApplicationContainer.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs
* ApplicationContainer.cs and CollectionSettings.cs
changes are just white-space.
* If Enterprise code changes, clear out Bookshelf unless
the branding is still the same
* pull out custom hook to get current project and any
associated bookshelves.
* put a progress warning in book upload, if there is not a
valid subscription code, but a bookshelf is in the settings.
* disable menu items if they only apply to an expired code
* add a tooltip to BloomSplitButton that works when it is
disabled
* disable the Upload button and put up an explanatory
tooltip if the calls to the api error out or if the collection
settings specify a bookshelf that isn't a valid one for the
current (active) subscription (should be very rare)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> BL-10638 Clear Bookshelf if Enterp. code has changed

src/BloomExe/IBrowser.cs, src/BloomExe/WebView2Browser.Designer.cs, src/BloomExe/WebView2Browser.cs
Maybe not part of the issue exactly, but seems like an obvious leftover from removing Geckofx which was.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5774)
=> Remove the bright red WV2 label from the browser windows (BL-12085)

src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, src/BloomExe/web/controllers/CollectionSettingsApi.cs
* handles the case of down-grading to Local Community or
None Enterprise status
* disable bookshelf control if the only option is "none"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5777)
=> BL-10638 Reset bookshelf when switching status

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5783)
=> Fix bug in "deshrouding" phrase markers for talking book tool (BL-11632)

src/BloomExe/Book/BookData.cs
These shouldn't happen in the normal course of events, but bugginess in the past has allowed some books to be infected with this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5797)
=> Fix sticky ui-audioCurrent class in dataDiv values (BL-12094)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx, src/BloomBrowserUI/publish/commonPublish/DeviceFrame.less, src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx, src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx, src/BloomBrowserUI/publish/stories.tsx
* Don't auto start preview; wait for button click
* Fix up layout of preview and orientation buttons
* Move some basic CSS to Emotion
* Leave BPlayer preview blank until Preview button is
pressed (it actually doesn't even load BPlayer)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791)
=> BL-12116 More Polite Preview pane

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx
* Don't auto preview on changing Motion book checkbox
* Don't auto preview on changing cover color
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5803)
=> BL-12116 More Polite Preview tweaks

src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
Clicking the button does POST cancel and mark the worker as cancelled, but the SS code was never written to check for cancellation or to cancel itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5814)
=> Remove unintentional cancel button which does almost nothing (BL-12167)

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5824)
=> Fix PDF print screen height to be 100% (BL-12156)

src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx, src/BloomExe/TeamCollection/TeamCollection.cs
https://github.com/BloomBooks/BloomDesktop/pull/5820/commits/9674c7d7770acb6076473e31732f18d1247b6221 fixes it for the one existing current reference.
This commit will fix it for any future references to work as originally intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5826)
=> Fix WinForms Progress Dialog not opening (BL-12171)

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
Using an "updated function" instead of an object allows us to remove bookStatus from the dependencies array and remove the condition that causes the loop
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5829)
=> Fix useEffect loop eating lots of CPU cycles (BL-12180, BL-12154)

src/BloomExe/BookThumbNailer.cs, src/BloomExe/web/IRequestInfo.cs, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs, src/BloomTests/PretendRequestInfo.cs
This isn't the original issue, but came up when testing the fix for the original problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5823)
=> Fix persistent blank images for generated template thumbnails (BL-11855)

src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx
* if no Enterprise, disable checkbox and throw up an
Enterprise Required tooltip
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5831)
=> BL-11582 Publish -> bloomPUB Activity chkbox

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5852)
=> Add the missing tooltip for ePUB publishing mode selection (BL-12097)

src/BloomBrowserUI/lib/ckeditor/config.js, src/BloomExe/WebView2Browser.cs
* Someday hopefully WV2 will improve their spell checking
api, so we can check text based on the `lang` attribute
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5858)
=> BL-12205 disable spell checking in WV2

src/BloomExe/XmlHtmlConverter.cs
This fix targets Version5.5, but looks safe enough for Version5.4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5874)
=> Don't automatically insert space before links (BL-12248)

src/BloomBrowserUI/publish/commonPublish/PublishProgressDialog.tsx
[5.5 Regression] Publish BloomPUB - When updating preview, Publish Progress Dialog appears done prematurely 
Repro Steps:
[5.5.3006 BetaInternal](https://bloomlibrary.org/installersBetaInternal/BloomInstaller.5.5.3006.BetaInternal.exe) or similar version
Select a book
Publish -> BloomPUB
Click "Preview"
Observed:
The Publish Progress Dialog pops up. A "Close button" appears immediately. Clicking it will close the Publish Progress Dialog, but it will not cancel the updatePreview operation. (If you debug behind the scenes, you can see that the component has ProgressState = Done even while the updatePreview is in progress.
Expected:
In 5.4, the Publish Progress Dialog looks like it's in a working state [No "Close" button"] while the updatePreview operation is ongoing. After the update …
=> BL-12256 fix preview dialog from being done/closeable too early

src/BloomExe/Book/BookStorage.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomTests/Book/BookStorageTests.cs
A new method TruncateFileBasename is used for image and sound files, which are assumed to already be valid filenames.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5896)
=> Revert SanitizeNameForFileSystem to allow multiple spaces (BL-12300)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowFixture.pug, src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowMarginFixture.pug, src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5913)
=> Replace Andika with Arial in typescript unit tests (BL-12321)

src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx, src/BloomExe/Book/PublishSettings.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs
Fixes Publish epub throws NullReferenceException unless you first preview
Corrects progress modal behavior
Makes epub not regenerate if settings have not changed
Fixes progress messages that were not displaying in the progress modal
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)
=> BL-12286 save epub without preview first fix

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
This change targets Version5.4 as requested in the issue.  I tried to ensure that it's safe enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5927)
=> Try to ensure that color is preserved in copy/paste in Bloom (BL-12357)

src/BloomExe/BookThumbNailer.cs, src/BloomExe/Extensions.cs
Multiple Bloom threads may be trying to build thumbnail.png simultaneously. Just a small workaround to retry it in that case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5933)
=> Fix thumbnail.png locked intermittent errors

src/BloomExe/BloomExe.csproj, src/BloomExe/WindowsMonitorScaling.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* adjusts size of screenshot if Windows display resolution
has been set > 100%
* putting this in 5.5 because it's Windows-specific, if we decide to cherry-pick it
back to 5.4, we'll need to add Windows only gating.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5934)
=> [5.5] BL-12318 Scaling for Problem Report screenshots

src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
* in a user collection, the delete cmd is visible, but disabled
if the book isn't checked out
* refactored code that determines whether a item is
shown and whether an item that is shown is disabled
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5936)
=> [5.4] BL-12372 Delete book cmd should not be hidden

src/BloomBrowserUI/react_components/bloomAvatar.tsx, src/BloomExe/TeamCollection/TeamCollectionApi.cs
By default react-avatar caches which gravatar urls failed (whether because the user was offline or did not have a gravatar) in local storage and then doesn’t retry the cached failed urls for a week. This PR turns off this undesireable failed url caching. It also fixes the default avatars when the user is offline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5950)
=> BL-12379 disable unhelpful react-avatar caching and fix offline avatar default initials

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx
* Making them appear above instead of below keeps them
from causing scrolling issues
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5943)
=> [5.5] BL-12366 Fix Talking Book tooltips

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.less
On a device, we show a scrollbar instead of overflowing. This commit detect that we're in a device layout, enabled a simple scrollbar (not the fancy one we get in Bloom Player), and removes overflow indicators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5951)
=> BL-11949 Scroll In Device Layout

src/BloomBrowserUI/bloomMaterialUITheme.ts, src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bloomWebFonts.less, src/BloomBrowserUI/themes/bloom-jqueryui-theme/jquery-ui-1.8.16.custom.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5973)
=> Set UI font to Roboto with NotoSans fallback (BL-12439)

src/BloomBrowserUI/spreadsheet/spreadsheetBundleRoot.ts, src/BloomExe/Spreadsheet/MarkedUpText.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs, src/BloomTests/Spreadsheet/SpreadsheetAudioTests.cs
Spreadsheet export should not remove segment markers. We make audio segment markers become pipes in spreadsheet so that they can survive roundtrip. 
- also fixes a bug which extraneously marked some text as black on import from spreadsheet, leading to more instances of https://issues.bloomlibrary.org/youtrack/issue/BL-12435/Spreadsheet-import-with-both-audio-and-formatting-messes-up.
- Improves a bug where consecutive audio segment breaks with only whitespace in between (e.g. | at the end of a sentence or multiple | | would break roundtrip)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5980)
=> BL-12429 export audio segment markers

src/BloomBrowserUI/collectionsTab/BookButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5988)
=> Fix Javascript null reference when renaming a book (BL-12384)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Program.cs, src/BloomExe/web/UrlLookup.cs
Webview2 isn't being updated for Windows < 10, so let's get them to just stay at 5.4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5990)
=> BL-12367 Check for Windows < 10

src/BloomExe/web/controllers/LibraryPublishApi.cs
* should not give message about PDF generation failing if we didn't try to
create a PDF because we have SL video!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5995)
=> BL-12479 Fix message when SL uploading fails

src/BloomBrowserUI/.eslintrc.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
This seems to help with the empty paragraph generation bug as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5996)
=> Don't mark empty "words" in decodable reader (BL-12460)

src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs
If you export to spreadsheet and it fails because e.g. you have that spreadsheet still open in excel, you get an error message but that spreadsheet comes to the foreground anyway, so it seems like it succeeded until you navigate back to bloom and see the error message. 
We should not open/foreground the spreadsheet path if export failed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5984)
=> BL-12436 failed spreadsheet shouldnt open

src/content/branding/Guatemala-RTI-DIGEBI/branding.json, src/content/branding/Guatemala-RTI-GBEQT/branding.json
* using 'always' and the entire copyright, including year,
enables us to update the copyright in existing books.
* using either one by itself is insufficient
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6000)
=> BL-12401 BL-12396 Update Guatemala copyright

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug, src/BloomExe/Edit/AudioRecording.cs
Show an popup message but not the error dialog if we can't access microphone.
This PR depends on Palaso changes: https://github.com/sillsdev/libpalaso/pull/1280
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6017)
=> Bl 12406 Don't show error Dialog if mic access is off 

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
* prevents a wrapAxios unexpected promise failure that, in turn, keeps the
Style dialog from showing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6025)
=> [5.5] BL-12584 Gear icon sometimes unresponsive

src/BloomExe/web/I18NApi.cs
Fix UI string fallback to English when it's not translated and the source code itself does not duplicated the English.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6038)
=> Fix BL-12566 UI strings fallback

src/BloomExe/web/RequestInfo.cs
* WV2 is more picky than FF about the need for an
Accept-Ranges header entry
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6040)
=> [5.5] BL-12593 Fix Sign Language Trimming problem

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomTests/Book/BookStorageTests.cs
Probably can/should go on 5.4 eventually?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6042)
=> BL-12587 Broken file names with surrogate pairs

src/content/bookLayout/basePage.less
fixes bug where title breaks differently in editor vs. bloom reader due to different font size
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6055)
=> BL-12621 title wysiwyg in bloom reader

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
Upload would work for these books, but not download since the book's .BloomBookOrder file would not be uploaded.  This resulted in a null bookOrder field in the book's Parse data, preventing download.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6073)
=> Fix upload whitelist for books with periods in title (BL-12649)

src/BloomExe/web/controllers/LibraryPublishApi.cs
* Ensure that any changes in publish settings for the
current book are saved, before initiating a bulk upload
* Especially applies to "Accessible to the Visually Impaired"
and "Draft" visibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6087)
=> BL-12553 Fix Bulk Upload

src/BloomExe/Book/Book.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs, src/BloomExe/web/controllers/PublishApi.cs
* also reverts an earlier 'hammer' change that was mostly not needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6093)
=> BL-12553 Save Draft status immediately on change

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
This is 1 of 2 PRs. The second does the same thing, but in bloom-player.less
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6106)
=> [5.5] BL-12675 Keep white space in Title during audio

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6110)
=> Fix hiding copyright button for placeholder images (BL-12700)

src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx, src/BloomExe/web/controllers/CollectionSettingsApi.cs
* 1st commit- Use sign language, if present
* 2nd commit- Shorten language name w/ellipsis, if necessary
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6114)
=> BL-12403 Books on Blorg updates

src/BloomBrowserUI/bookEdit/js/showInvisibles.ts
move tooltips to other side, make them fade out after 2 seconds
Note that if you move your mouse onto one during those two seconds, it will restart the two second countdown for that tooltip
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6117)
=> BL-12495 improve show invisibles again - tooltips

src/BloomExe/Edit/ConfigurationDialog.cs, src/BloomExe/Edit/Configurator.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/HtmlThumbNailer.cs, src/BloomExe/IBrowser.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomExe/WebView2Browser.cs
Makes the CanUndo() use the async call to javascript, removing the looping of Application.DoEvents()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6096)
=> Fix BL-12614

src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs, src/BloomExe/web/controllers/PublishApi.cs
It has been suggested that this might go on 5.5, but it isn't a new problem with 5.5 as far as I can tell looking at the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6119)
=> Remove initial redundant BloomPub creating for saving books (BL-12694)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/Utils/BloomArchiveFile.cs, src/BloomExe/Utils/RobustZip.cs
* this error is bad news and is liable to leave a zip file in a
bad state.
* we catch the error and log it at least
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6113)
=> [5.5] BL-12689 Team Coll Zip CRC failed

src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx, src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx, src/BloomBrowserUI/react_components/BloomCheckBox.tsx, src/BloomBrowserUI/react_components/BloomToolTip.tsx
Here I redid just one instance of checkbox (Sign Language) to use this system. Anything that already uses BloomTooltip `showDisabled` prop will get it for free.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6122)
=> Make disabled status available to components wrapped by tooltip

src/BloomBrowserUI/pageChooser/page-chooser.ts
This fixes the problem in the release (Version5.4) in the old dialog code.  Apparently, the code used a Javascript construct that Firefox 60 didn't understand.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6124)
=> Fix i18n for old Add Page Dialog in Version5.4 (BL-12572)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx
This was mistakenly introduced by BL-12269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6129)
=> Remove xmatter restriction for Recording Mode (BL-12740)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/HtmlThumbNailer.cs, src/BloomExe/WebView2Browser.cs
Either switch to RunJavascriptAsync where feasible, or merge multiple consecutive calls to a single call to at least minimize exposure to problems with the synchronization code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6111)
=> Reduce number of synchronous calls to RunJavascript (BL-12691)

src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6140)
=> Fix l10n of page description in Add Page dialog for 5.4 (BL-12572)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/pageThumbnailList/PageThumbnail.tsx, src/content/bookLayout/basePage.less
Also
* fixes two "false-alarm" overflow warnings when we have scrolling available
* works around a language-label problem when scrolling
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6144)
=> Fix BL-1275 paragraph collision in overflowing vertically-aligned boxes

src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderToolSwitch.tsx, src/BloomBrowserUI/react_components/BloomSwitch.tsx
* removed unused children call
* center switch labels vertically
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6143)
=> BL-12444 Alignment of Reader switches

src/BloomExe/CollectionTab/CollectionTabView.Designer.cs, src/BloomExe/CollectionTab/CollectionTabView.cs
The new button and dialog are merely hidden.  The partial work on that dialog is still there, but inaccessible to the user interface.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6153)
=> Restore the old settings dialog (BL-12777)

src/BloomBrowserUI/bloomMaterialUITheme.ts, src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx, src/BloomExe/web/controllers/CollectionApi.cs
This fixes a display anomaly revealed by the screenshots in BL-12587. The effect of the fix may have nothing to do with surrogate pairs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)
=> Use the assigned font for BookButton labels (BL-12587)

src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderToolSwitch.tsx, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomTests/Book/HtmlDomTests.cs
* added a x-reader-off class on the html body to record
the user turning off the toggle
* added a check for this class in the BBUD code so it won't
revert the toggle wrongly
* fixed the 2 Toolbox tools so they redo the markup if the
toggle is updated and sets to no markup if the toggle is
off
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6155)
=> BL-12444 DR LR toggle function

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
This provides the leveled reader sentence ending punctuation setting without having to first open one of the reader tools.  We also add a pair of Khmer characters to the standard sentence ending punctuation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6159)
=> Load reader settings for talking book (BL-12784)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
The bound is larger than Ultra HD on the smaller dimension to accommodate paper printing which can have less elongated images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6167)
=> Change maximum image size to 3840x2800 to allow Ultra HD (BL-12130)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs
* replaced "so text might not fit" with "which may cause text to scroll"
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6177)
=> [5.6] BL-12811 Fix out-of-date bloomPUB message

src/BloomExe/Book/Book.cs
This doesn't directly address the question of why the file was locked for the user, but it sidesteps the problem by not writing the file if its content hasn't changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6189)
=> Don't write unchanged defaultLangStyles.css file (BL-12767)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6192)
=> Fix a crash checking for unchanged defaultLangStyles.css file (BL-12767)

src/BloomExe/Edit/EditingView.cs
No, I don't understand why this works or why it is needed in Version5.5 and later, but not earlier.  But it's the only thing I've found which affects the display of the check mark.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6202)
=> Get checkbox to display in middle for content language menu (BL-12839)

src/BloomExe/Book/BookCompressor.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/web/controllers/PublishApi.cs
This seems to reliably result in smaller file sizes for smaller image dimensions.
I've added the fix for shrinking images for previewing BloomPUBs, and changed the code to use GraphicsMagick for the image manipulations whenever possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175)
=> Use input quality for output quality in jpeg size reduction (BL-12808)

src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/EditingView.cs, src/BloomTests/BloomTests.csproj, src/WebView2PdfMaker/WebView2PdfMaker.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6215)
=> Handle TagLibSharp exceptions better for some images (BL-11933)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
If an image problem is symptomatic of something serious enough to get reported, something will be in the log file for post mortem analysis. We can't really help users with all the possible quirky images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6217)
=> Log image problems instead of reporting them (BL-11911)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/web/controllers/CollectionApi.cs
Hide Parse behind API: Book Status
Part of the larger project to replace direct calls to Parse with calls to azure fns, so that we reduce our lockin to Parse.
**Depends on https://github.com/BloomBooks/bloom-azure-functions/pull/68**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6226)
=> Bl-12758 book status to api

src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx, src/BloomExe/Collection/BookCollection.cs
And unnecessary api calls after refresh``
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6229)
=> BL-12879 fix badges disappearing after duplicate book,

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
This might be simple enough to cherry-pick back to 5.5 if we think it's robust enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6224)
=> Fix pasting (from Word) to remove useless spans (BL-12861)

src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx, src/BloomExe/Collection/BookCollection.cs
Cherrypicking to 5.6: Fix badge disappearing after duplication and uneccesary api calls after refresh (https://github.com/BloomBooks/BloomDesktop/pull/6229)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6239)
=> Cherrypick BL-12879 fix badges disappearing after duplicate book,

src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
The music tool displays the .mp3's filename, but if it has multiple periods in the filename, the name is truncated at the first period instead of the last (extension) period.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6272)
=> BL-12888  fix music file name display

src/BloomExe/Collection/CollectionSettings.cs
This fix could be simple enough to backport to 5.6.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6273)
=> Keep language display names more consistent (BL-12992)

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomLowPriority.xlf, src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomBrowserUI/problemDialog/ReportDialog.tsx, src/BloomBrowserUI/problemDialog/theme.ts, src/BloomBrowserUI/utils/linkHandler.ts, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/CollectionTab/CollectionTabView.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/MiscUI/StartupScreenManager.cs, src/BloomExe/Program.cs, src/BloomExe/Utils/FileException.cs, src/BloomExe/Utils/OneDriveUtils.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomExe/web/controllers/BookCommandsApi.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
Catch OneDrive exceptions and give a clear notice with no report button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)
=> BL-12977 OneDrive error dialog

src/content/appearanceMigrations/purpleRounded/appearance.json
The checksum calculation now trims the CSS string before checksumming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6288)
=> Fix checksum for purpleRounded appearance migration (BL-13021)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
Tweaked labels and L10n names
Move warning about legacy to top
Make legacy warning work as soon as the dialog is open (previously only worked when you changed the theme)
Stuff like that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6312)
=> BookSettings UI work

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6325)
=> Fix editing vertically-centered text for overflow condition (BL-13081)

src/BloomExe/Book/AppearanceSettings.cs, src/BloomTests/Book/AppearanceSettingsTests.cs, src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css, src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css, src/content/bookLayout/basePage.less, src/content/bookLayout/pageNumbers.less
This is currently only used in  a rare case where we a) have little to no bottom margin and b) are not able to place the page number on top of something (an image)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6327)
=> BL-13122 Extra space for page number in rare circumstance

src/content/bookLayout/pageNumbers.less
This does not affect Device16x9... pages which center the page numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6331)
=> Default theme right-side page has page number on right (BL-13132)

src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6332)
=> Use a stable text-wrap in overlays (BL-13135)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6341)
=> Allow more space for the resolution slider tooltips (BL-13067)

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6356)
=> Prevent page selection crash when tab changes too quickly (BL-13184)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Utils/LocalizationHelper.cs
Also BL-13167 and BL-13168.  We have no idea what is happening, but this check might provide at least a clue on fixing it on the user's computer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)
=> Check for unreadable localization file for license (BL-13115)

src/content/bookLayout/basePage-sharedRules.less
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6362)
=> Use more popularly implemented value for text-wrap in overlays (BL-13135)

src/BloomExe/Book/Book.cs, src/BloomExe/Utils/ColorUtils.cs, src/content/branding/Bible-for-Children/branding.less
The final page used to have a white background in comics before we merged the final two backmatter pages back together for comics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337)
=> Fix Bible for Children branding comic to show white back page (BL-13138)

src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/CommonApi.cs
Also, mark the common/channel API as not needing to be synchronized since it uses only read-only data and is called only once by the javascript code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6383)
=> Prevent collection change while enumerating (BL-13209)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
The previous fix for BL-13098 was causing problems and is no longer needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6385)
=> Ensure image buttons hide when mouse leaves image container (BL-13221)

src/BloomExe/Book/BookCopyrightAndLicense.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6390)
=> Fix the check for license l10n to ignore Custom "und" (BL-13228)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6396)
=> Add transition delay for hiding hint bubbles on focus loss (BL-13224)

src/content/bookLayout/basePage-legacy-5-6.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6400)
=> Restore 3px margin between split panes for legacy theme (BL-13259)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css
This covers the standard "Picture in Middle" page layout and the "Rounded Border Ebook" theme.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6395)
=> Format cog adjustment to avoid hiding behind page number (BL-13206)

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less, src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/Book.cs, src/BloomExe/web/controllers/IndicatorInfoApi.cs, src/BloomTests/Book/AppearanceSettingsTests.cs, src/content/appearanceThemes/appearance-theme-default.css, src/content/bookLayout/basePage.less, src/content/templates/xMatter/bloom-xmatter-common.less, src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less, src/content/templates/xMatter/project-specific/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-Xmatter-common.less, src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-Xmatter-common.less, src/content/templates/xMatter/standard-template-preview.less
Also adjust the margin settings in appearance-theme-default.css to match the Default Margins table in docs.bloomlibrary.org better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6415)
=> Fix 5.7 default front covers to match 5.6 better (BL-13264)

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Edit/EditingModel.cs
1) View asked to invoke before being fully initialized.
2) Validating team collection administrators when not a team collection.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6432)
=> Fix a pair of blocking bugs (20240422)

src/BloomBrowserUI/bookEdit/css/editMode.less
The border of the translationGroup was pushing the editable box over. We can live with out it if we add an `outline` to the editable box.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6426)
=> Fix BL-13288 where edit mode was 1px off from publish

src/BloomExe/WebView2Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6434)
=> Fix broken external links in template help frames (BL-13316)

src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6436)
=> BL-13215 disable mui ripple on collection tab menu button

src/content/templates/xMatter/bloom-xmatter-common.less, src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-XMatter.less
With these changes, the front cover closely approximates what is seen in Bloom 5.6 for both HalfLetterPortrait and Device16x9Portrait.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6433)
=> Fix line-height and other settings in ABC branding (BL-13281)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6441)
=> BL-13326 move custom css messages to Content Pages tab in book settings

src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/web/controllers/EditingViewApi.cs
The minimal fix here is just the one in bloomImages.ts.
However, looking at the rest of the code, it seems we were needlessly doing dangerous things to simulate synchronous behavior when it wasn't needed, so I removed that too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6469)
=> Fix BL-13387 Prevent double clicking image buttons

src/BloomBrowserUI/bookEdit/css/editMode.less
cherry-picked from master
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6477)
=> Fix overflow for Device16x9Landscape books, and maybe others (BL-13374)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs
This replaces the previous fix by accurately determining if the marginBox is empty rather than skipping the check for calendar pages.
And handles flyleaf pages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6475)
=> More accurate check for a messed up margin box (BL-13423)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomExe/Book/AppearanceSettings.cs, src/content/bookLayout/basePage-sharedRules.less, src/content/bookLayout/basePage.less
Fixes:
* padding on bottom in picture on top
* padding all around on text-only
* disable "smart padding" (which takes page margins into account) for grey boxes
* remove unneeded appearance property
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6497)
=> BL-13475 padding update

src/BloomExe/NonFatalProblem.cs, src/BloomExe/web/BloomServer.cs
These exist in developer builds, but not in installed builds.  (We don't want to pay the 11MB price of including files that might be useful for debugging, but not that helpful for user machines when expanded to 52MB.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6514)
=> Allow missing .map files in BloomServer (BL-13526)

src/content/appearanceThemes/appearance-theme-default.css, src/content/bookLayout/pageNumbers.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6529)
=> Center page numbers on non-device layouts in bloom-player (BL-13311)

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6505)
=> BL-13496 #2: Fix transparency when you initially add a line drawing to cover page

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/content/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6552)
=> Fix padding for overlay bubbles (BL-13585 and BL-13604)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6563)
=> Fix resizing bubbles after duplicating an overlay bubble (BL-13617)

src/content/bookLayout/bubble.less
border steals from the box's content size, outline does not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6583)
=> Use outline instead of border to highlight focused textbox (BL-13668)

src/BloomExe/Program.cs
Note that this fix is on the Version5.6 branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6594)
=> Allow system language not to be localized on first run (BL-13708)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/ImageUpdater.cs
This is for Bloom 5.6 as a followup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6598)
=> Report better when copying metadata to all images fails (BL-13723)

src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/HtmlDomTests.cs
This targets Version6.0 to get into harvester sooner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6596)
=> Prevent getfonts from returning fonts for unused styles (BL-13655)

src/BloomExe/WebLibraryIntegration/S3Extensions.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
Books with more than 1000 S3 objects would silently fail, crashing with an out of memory error due to an infinite (nonterminating) loop.  The symptom was a harvesterState of "Failed" and an empty harvesterLog array.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6609)
=> Fix crash when downloading books with >1000 S3 objects (20240822)

src/content/templates/template books/Activity/simpleComprehensionQuiz.less
This is really a one-line change.  I don't know why the reformatting happened.   (commit hook?)
The last changed line is the only actual change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6621)
=> Fix spacing weirdness on quiz pages when not focused (BL-13807)

src/BloomExe/Book/BookFileFilter.cs, src/BloomTests/Book/BookFileFilterTests.cs
This is a minimal fix for Bloom 5.6.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6633)
=> Fix template folder name for book filtering (BL-13825)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6638)
=> Fix javascript crash when duplicating an overlay bubbble (BL-13829)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Spreadsheet/SpreadsheetApi.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs, src/BloomExe/web/controllers/StylesAndFontsApi.cs, src/BloomTests/Collection/WritingSystemDialogTests.cs, src/BloomTests/Publish/BloomLibraryPublishModelTests.cs
This change does not address any GUI changes for setting or changing this information within Bloom itself.  More information than the language tag and name can be stored but currently would not be used anywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6627)
=> Store all language names from spreadsheet import (BL-13551)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6667)
=> Hide reposition dot when moving cropped image overlay (BL-13876)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6670)
=> Disable alt-drag for overlay elements (BL-13899)

src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6692)
=> Do not round image overlay corners for rounded page theme (BL-13960)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
This is implemented by reordering the overlay elements in the DOM.  There is no indication
of the playing order other than DOM position.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6693)
=> Add "Play Earlier" and "Play Later" to video overlay menu (BL-13930)

src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomTests/Book/TranslationGroupManagerTests.cs
The repair takes two forms: fix a broken book as best we can, and prevent breakage when changing the page format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6712)
=> Repair loss of style with resulting loss of format cog (BL-13953)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
I don't understand how, but in some circumstance, this.kTransformPropName could be undefined. Making it absolutely a constant should make this impossible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6721)
=> Fix problem where kTransformPropName could be undefined (

src/BloomBrowserUI/bookEdit/js/niceScrollBars.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6738)
=> Cleanup more after nicescroll to keep backward compatibility (BL-14052)

src/BloomExe/FontProcessing/FontFileFinder.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6723)
=> Embed bold and italic variants of fonts needed in ebooks (BL-13811)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6754)
=> Move the background image crop handles inward (BL-13965)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6756)
=> Use outline instead of border to mark overflow (BL-14059)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6763)
=> Fix initial game picture space to fit placeholder properly (BL-14063)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6772)
=> Fix positioning of overlay control box for older books (BL-14106)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6773)
=> Restore automatically showing source bubbles (BL-14109)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/narration.ts, src/BloomExe/Book/Book.cs
Also add cleanup to remove message inserted by narration.ts for invalid videos when testing games.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6771)
=> Get narration.ts and dragActivityRuntime.ts more up-to-date (20241202)

src/BloomBrowserUI/bookEdit/js/niceScrollBars.ts
This could be a candidate for cherry-picking to 6.1.  A similar fix is needed in bloom-player.  (The contexts are just different enough to not to be able to share code.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6781)
=> Fix scroll position for zoomed "Just text" pages (BL-14112)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/TeamCollection/DisconnectedTeamCollection.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6779)
=> Store color palettes apart from other collection settings (BL-14129)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/Book.cs, src/BloomExe/Book/Page.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Book/XMatterPackFinder.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PlaceHolderPage.cs, src/BloomExe/web/controllers/BookSettingsApi.cs, src/content/bookLayout/basePage.less, src/content/templates/xMatter/CoverIsImage-XMatter/CoverIsImage-XMatter.pug, src/content/templates/xMatter/bloom-xmatter-common.less, src/content/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6602)
=> Allow cover to be full-bleed image (BL-13271)

src/BloomExe/Registration/Registration.cs
The previous check didn't work at all and resulted in empty registration in installed builds.  This showed up especially in Team Collections which require registration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6795)
=> Fix check for dynamic registration settings properties (BL-14101)

src/BloomExe/web/controllers/FileIOApi.cs, src/BloomExe/web/controllers/MusicApi.cs
This undoes a change made by JT in https://github.com/BloomBooks/BloomDesktop/pull/6571/files#diff-fda3f19b08588223b7b2ec9253a08eb8a388139f08bbf0023c025233bab01174R105. I talked to him about it and he thought this change would be okay.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6790)
=> BL-14167 import recording should reopen to last location

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescriptionUtils.ts, src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/basePage.less, src/content/bookLayout/bubble.less
Overlay on the image can now be shown in the shrunk image. Shrink is always 50% even if larger would fit. Commands that would change the image container size are disabled or hidden while in this mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6798)
=> Make image descriptions work again

src/BloomBrowserUI/bookEdit/css/editMode.less
This restores the behavior of version 6.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6817)
=> Restore source bubbles when page is still focused (BL-14256)

src/BloomExe/Publish/PublishModel.cs
All images are now stored as overlay background images, even those that are not used to host overlays.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6818)
=> Fix enterprise check for overlays with new overlay pictures (BL-14245)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.less
- don't let the overflow border take up space
- if we decide the page has too many boxes for overflow checking, remove any previously set overflow classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6824)
=> More overflow fixes (BL-14088)

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs
The four standard faces of Andika ship with Bloom Reader already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6825)
=> Never embed variant faces of Andika and Andika New Basic (BL-14259)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6826)
=> Allow focus on overlays if no standard text box (BL-14265)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bloomQtipUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6831)
=> BL-14166 fix missing language name in hovered textboxes

src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/bookLayout/bubble.less
Also:
- extra white border to help make text-block overlays visible is better aligned
- it is not shown for other kinds of text overlays
- it is never shown when the bubble is selected, even if it is not focused
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6833)
=> Prevent spurious overflow after adding overlay (BL-14276)

src/BloomExe/CLI/CreateArtifactsCommand.cs
This is on Version6.1 since the harvester is based on the beta.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6856)
=> Fix Bloom Harvester crash from uninitialized Sldr (BH-7454)

src/BloomBrowserUI/bookEdit/css/editMode.less
This also means ones that are hidden when focus is elsewhere won't make an exception when the mouse is over them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6862)
=> Stop bubbles going away when mouse leaves (BL-14337)

src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6864)
=> Fix BloomBrowserUI bp-to-src script to not delete README file

src/BloomExe/web/controllers/StylesAndFontsApi.cs
There was a problem where a book has differing default fonts for different languages and use a style (like ImageDescription) that has no definition (or possibly one that specifies no font info).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6865)
=> Handle a corner case in reporting Font info (BL-14357)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx
Duplicate audio ids and extra letters in target area could happen if a word in a second language was longer than a word in the first language.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6871)
=> Handle multiple languages in Drag Letters pages better (BL-14348)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6875)
=> Work harder at getting the prompt dialog focused (BL-14347)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
I can't build master locally without this update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6900)
=> Update bloom-player to ^2.9.5

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6905)
=> Fix bug when there is no default name in language chooser (BL-14426)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs
Makes it work even if later migrations have happened that don't need to be reversed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6907)
=> Generalize back migration

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/content/templates/template books/Activity/simple-dom-choice-activities.less
- moved the crop handles in a pixel on background images for less chance handle gets cropped
- fixed issues with border on images in simple-dom-choice activities
- improved alignment of overlay control rect (was sometimes a pixel off)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6920)
=> Fix various layout issues in simple-dom-choice (BL-14398)

src/content/appearanceThemes/appearance-theme-default.css
User reported that their desktop printer was cutting off the bottom of the page number.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6932)
=> BL-14456 Nudge up page numbers

src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6955)
=> Fix a crash that leaves a blank enterprise tab in the dialog

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.less
Don't limit bloom-show-en-when-blank to drag-activity-start. It could be useful elsewhere, and we get flicker because some code that depends on it runs before drag-activity-start gets set.
But there are other sources of flicker from checking overflow too soon. And we had two separate sources initiating overflow checks and two different ways of delaying the checks and making them incremental. So I removed the old one that was happening too soon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6952)
=> Fix overflow sizing glitches while loading page (BL-14489)

src/content/bookLayout/basePage.less
Somehow this makes flex-grow/shrink work when the parent is height:auto and the child is content-fit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6956)
=> Make cover sizing of bloom-canvas work again

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
Actually, it gets independently resized, but the area it used to occupy doesn't need to stay visible or be used as the basis for the resize.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6957)
=> Ignore hidden BG image on page resize (BL-14484)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bloomWidgets.ts, src/BloomBrowserUI/bookEdit/js/origami.ts
Moves the buttons up to be relative to the bloom-canvas.
Fixes a glitch in the calc() expression for the position of the license button in full-bleed pages.
In the process, got rid of hoverUp and the code that still manipulated it and various other redundant code and CSS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6966)
=> Fix positioning of large image editing buttons

src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderToolSwitch.tsx, src/BloomBrowserUI/react_components/BloomSwitch.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6978)
=> Use defaultChecked of BloomSwitch when not controlled (BL-14538)

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6980)
=> Make BloomDialog set a default font, not force it everywhere (BL-14556)

src/BloomBrowserUI/bookEdit/toolbox/games/DragActivityTabControl.tsx, src/content/templates/template books/Games/Games.less
Also try to prevent other items from being deleted or moved except in an appropriate tab.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6976)
=> Hide unwanted items in Game editing tabs (BL-14532)

DistFiles/localization/en/Bloom.xlf
Too many users may not have things set up for the mailto: link to work, so we now expose the actual email address in the message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6994)
=> Reword the expiring subscription message (BL-14588)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6998)
=> Allow svg to follow theme foreground color, too (BL-14595)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7013)
=> Items from Correct/Wrong always go in front (BL-14627)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/content/templates/template books/Games/Games.less
Part of the fix was in bloom-player.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7024)
=> Ensure images and shadows show properly when playing games (BL-14664)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
Reverts BloomBooks/BloomDesktop#7031
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7032)
=> Revert "Prevent overflow marking on empty Word draggable in games (BL-14643)"

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7035)
=> Prevent text box outlines from showing when playing a game (BL-14678)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7039)
=> Remove bloom-canvas wrapper around book grid images (BL-14698, BL-14700)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/content/templates/template books/Games/Games.html
The background image may not fill the screen initially despite my attempt to make it happen.  There is a button you can click to make it expand (which already existed).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7038)
=> Reduce clutter for background images in games (BL-14703)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
Also display "Background Image" in context control popup only when appropriate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7053)
=> Restore default background image display outside drag games (BL-14734)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/content/bookLayout/canvasElement.less
Stops checking (and hence reporting) overflow on targets
Fixes a crash on deleting canvas element
Prevents targets clipping bloom-editable descenders
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7065)
=> fix various problems with draggable text

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
Also with their initial sizing and spurious overflow reporting when empty.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7071)
=> Fix problems with sizing new canvas elements (BL-14749)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7090)
=> Restore adjusting target when text draggable size changed (BL-14786)

src/content/templates/template books/Games/Games.html
Some blocks still had "word" in English as content. Some still had audio ID attributes, which could have become duplicates. Some had spurious font and min-height styles, which should be controlled by stylesheet and code. Some had English and/or French empty content instead of just "z".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7103)
=> Fix various problems in Games.html (BL-14781)

src/BloomExe/Book/Book.cs
This could be cherry-picked to 6.1 safely I think.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7133)
=> Fix print DOM for full bleed only if FullBleed set for printing (BL-14863)

src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx, src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx, src/BloomBrowserUI/react_components/requiresSubscription.tsx
Also improve the wrapper to cover only its child elements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7135)
=> Add subscription wrapper overlays for epub and video/audio (BL-14793)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
...when launched from context controls
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7138)
=> Fix problem with format dialog not closing (BL-14857)

src/BloomExe/BloomFileLocator.cs, src/BloomExe/Collection/BrandingProject.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/web/controllers/BrandingSettings.cs
Any subscription with BloomProgram as its main name will have Enterprise permissions but with Default appearance whereever branding is applied.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7142)
=> Add BloomProgram branding that mimics default branding (BL-14872)

src/content/templates/template books/Games/Games.html
It would be considerable work to make any possible style settings here propagate properly to the word fragments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7190)
=> Prevent mysterious scroll bars in game tool when disabled (BL-14905)

src/BloomTests/Publish/PublishHelperTests.cs
...since the Widget feature no longer behaves differently in derivatives
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7200)
=> Fix PublishHelper page removal tests to use Game not Widget (BL-14917)

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx
Choosing languages without a default region will not crash Bloom
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7198)
=> BL-14544 Language Chooser Country Error

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7204)
=> Don't ensureCanvasElementsIntersectParent in shrunk image (BL-14896)

src/BloomExe/Spreadsheet/SpreadsheetIO.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7205)
=> Handle ampersands in image file names in spreadsheet import (BL-14374)

src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/basePage-sharedRules.less, src/content/bookLayout/basePage.less
Also corrected obsolete CSS property word-wrap to overflow-wrap and removed a redundant copy of a rule.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7215)
=> Fix horizontal overflow of narrow overlays (BL-14920)

src/BloomTests/Publish/PublishHelperTests.cs, src/BloomTests/web/controllers/SubscriptionTests.cs
A few will expire in September 2026.  We need a longer term decision on what to do about subscription codes embedded in source code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7238)
=> Update expired subscriptions used in unit tests (20250701)

src/content/templates/template books/Games/Games.html
It's unclear how this would be used, and the display during recording is messed up by the lines being so close together when the text stretches over more than one line.  At the moment, when playing the game, there's no way to play the audio.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7241)
=> Disable audio recording of text in order words game (BL-14967)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomTests/CLI/CreateArtifactsCommandTests.cs
Browsers are still created on demand when processing books for creating bloompub and epub artifacts.  The WebThumbNailList and EditingView browsers are never used in creating artifacts, so they don't need to be created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7245)
=> Prevent creating unused browsers in harvester mode (BL-14975)

src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
Also prevent audio recording of the sentence in portrait layout (BL-14967)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7250)
=> Display the sentence in the Order Words game page for PDF (BL-14978)

src/BloomExe/Program.cs, src/BloomExe/WebView2Browser.Designer.cs
This prevents the silent accumulation of gigabytes in the Temp folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7247)
=> [6.2] Remove WebView2 user folders when Bloom exits (BL-14984)

src/BloomExe/Program.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/WebView2Browser.Designer.cs, src/BloomExe/WebView2Browser.cs
This can be needed for unit tests in some environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7254)
=> Fix WebView2 folder cleanup to handle reused process ids (BL-14984)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7256)
=> Safer way to fix paste to <input> (BL-14989)

src/BloomExe/Book/TranslationGroupManager.cs
The language control is also enabled when the text box is set to "V" for the language.  This is by design.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7293)
=> Enable language control when text box goes back to "Normal" (BL-14011)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/content/templates/template books/Activity/simple-dom-choice-activities.pug
Simple comprehensions quizzes and simple dom choice games export and import okay: the other games, not so much.  Warning the user that these pages are being skipped is better than unintelligible error messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7291)
=> Skip over game pages for spreadsheet export (BL-15055)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Program.cs
This affects bloom-harvester operations, so it targets 6.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7299)
=> Remove WebView2 folders after command line operations (BL-15091)

src/content/bookLayout/pageBoxesSizing.less
Should be null-merged, if we take the full fix for 6.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7305)
=> Temporary patch for unsupported full bleed page sizes (BL-14442)

src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/PublishHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7315)
=> Fix reallyCropImage to handle duplicate names and spaces (BL-15121)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7319)
=> Restores old clipboard behavior for bloom-editable (BL-15123)

src/BloomExe/Workspace/WorkspaceView.Designer.cs, src/BloomExe/Workspace/ZoomControl.Designer.cs
Make vertical alignments match what they looked like before the .net 8 upgrade
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7352)
=> BL-15233 fix menubar display sizing/shape regressiosn

src/BloomExe/Publish/PublishHelper.cs
Trying to do so is worthless since they won't be visible, and the attempt can fail, leading to being unable to publish the BloomPub.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7368)
=> Don't try to crop placeHolder.png image files (BL-15229)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7385)
=> BL-15277 fix for hidden image toolbox language option

src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7392)
=> bloom-player was updated on Version6.2 without updating yarn.lock

src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This can happen if the .bloomCollection file is readonly or hidden.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7407)
=> Add help link for file permissions to hard crash report (BL-15282)
