BloomBooks/BloomDesktop

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3424)
=> Properly handle font file names with spaces and parentheses (BL-7779)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3423)
=> Change Callout Tool name back to Comic Tool

src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3427)
=> Comic Tool: Hide from toolbox unless experimental features on

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookEdit/toolbox/callout/callout.less, src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/Book.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Edit/ToolboxView.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3430)
=> Merge from master to Geckfx60 - 20191031

src/BloomExe/Book/Book.cs, src/BloomExe/BookThumbNailer.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3429)
=> BL-7674 Emit front cover picture for web

src/BloomBrowserUI/publish/commonPublish/BasePublishScreen.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3436)
=> Merge from beta to master (20191104)

src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3439)
=> Increase padding around controls (BL-7788)

src/BloomExe/BookThumbNailer.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3433)
=> Use a reduced cover image for book thumbnails (BL-7792)

src/BloomExe/BookThumbNailer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3440)
=> Fix failing unit tests for epub thumbnail images (BL-7792)

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, src/BloomBrowserUI/yarn.lock
* Desktop side (maybe temporary)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3441)
=> BL-7758 Keep quiz parts from swiper buttons

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less, src/BloomBrowserUI/yarn.lock
Requires this PR to be merged first: https://github.com/BloomBooks/comical-js/pull/35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3442)
=> Comic tool: Make bubbles directly draggable (BL-7821)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less, src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less, src/BloomBrowserUI/yarn.lock, src/BloomExe/BookThumbNailer.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.Designer.cs, src/BloomExe/Publish/PublishView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3444)
=> Merge master into Geckfx60 (20191111)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3447)
=> Comic Tool: Fix issue where height/width was getting reset (BL-7821)

src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3446)
=> Comic Tool: Remove text box borders for bubbles (BL-7836)

src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3448)
=> Comic Tool: Make format gear and language tip appear in sync (BL-7837)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3452)
=> Comic tool: Fix a bug where the wrong bubble can get dragged (BL-7821)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.less, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.pug, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/ScriptSettingsDialog.Designer.cs, src/BloomExe/Collection/ScriptSettingsDialog.cs, src/BloomExe/Collection/ScriptSettingsDialog.resx, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/ReadersApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3454)
=> BL-7737 Allow user to set font size for language text in Reader Tools

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3455)
=> Update Geckofx60 to version 60.0.43 (20191115)

build/getDependencies-Linux.sh
This is temporary to check what jenkins is doing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3457)
=> List folder content for getDependencies-Linux.sh (20191119)

build/getDependencies-Linux.sh
This is still temporary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3459)
=> More testing of fetching Linux dependencies (20191119)

build/getDependencies-Linux.sh, debian/control
This still has some temporary test code in the shell script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3460)
=> Test using curl for Linux palaso dependency downloads (20191119)

build/getDependencies-Linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3462)
=> Test using https instead of http for getDependencies (20191119)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3466)
=> Enable resize handles on all 4 sides

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3469)
=> Update Geckofx60 to 60.0.44 on the Geckfx60 branch (20191121)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3467)
=> Fix bug where resize and drag happening simultaneously (BL-7880)

.nuget/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3478)
=> Use default NuGet package sources

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3479)
=> BL-7586 Do not auto-delete Activity pages

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3481)
=> Fix unwanted Motion Book stickiness in Bloom Reader output (BL-7680)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookLayout/textOverPicture.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3470)
=> Comic Tool: Alt+Drag resizes bubbles (BL-7881)

src/BloomBrowserUI/bookEdit/js/point.ts, src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3482)
=> Comic Tool: Fix moving bubbles when zoom is not 100% (BL-7841)

src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/MiscUI/TroubleShooterDialog.cs, src/BloomExe/web/SimulatedPageFile.cs
* clean up usings in TroubleShooterDialog and
SimulatedPageFile
* refactor to save reloading html file from disk for
each change to page list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3491)
=> BL-7704 Thumbnail efficiency

src/BloomBrowserUI/publish/metadata/BookMetadataTable.less, src/BloomBrowserUI/publish/metadata/BookMetadataTable.tsx, src/BloomBrowserUI/utils/bloomApi.ts, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/web/controllers/BookMetadataApi.cs
This will need a UI review as well as a code review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3490)
=> Add summary/description to epub metadata (BL-7831)

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3489)
=> Restore cover page image descriptions to epubs (BL-7804)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3493)
=> Corrected logic for when we get an "Adapted from" statement (BL-7898)

src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3495)
=> Fix unit test failure (BL-7898)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3496)
=> Rename "CalloutTool" to "ComicTool" in localization keys

src/BloomExe/FatalExceptionHandler.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* this change requires a palaso PR first
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3497)
=> BL-7666 Fix issues with null Control

src/BloomExe/Edit/WebThumbNailList.cs
* fix so front cover is on the right again
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3498)
=> BL-7704 fix WebThumbnailList

src/BloomExe/Collection/CollectionSettings.cs
Note that this change is on Version4.6 as requested by the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3501)
=> Remove migration from Andika to Andika New Basic (BL-7868)

src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3504)
=> Remove obsolete test of no longer existing Andika migration (BL-7868)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/problemDialog/PrivacyNotice.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3506)
=> Fix duplicate Common.LearnMore entries in Bloom.xlf

src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3510)
=> Tweak code to reduce likelihood of unreadable file (BL-7076)

src/BloomExe/Edit/PageListView.cs, src/BloomExe/Edit/WebThumbNailList.cs
* This commit is just clean up of unused props and
moving some member vars and some renaming
* some refactoring (lots of extracted static methods)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3512)
=> BL-7704 webThumbnailList efficiency

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3511)
=> Improve check for complete translations (BL-7800)

src/BloomBrowserUI/webpack.common.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3518)
=> Don't publish storybook to users (BL-7882)

src/BloomExe/Publish/Epub/EpubMaker.cs
Should this be considered for cherry-picking to 4.6?
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3514)
=> Fix image description TextBox recordings for ePUB publishing (BL-7805)

src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3521)
=> BL-7666 Make sure we can't get a stale screenshot

src/BloomExe/CollectionCreating/LanguageIdControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3525)
=> Finish removing scripts from language lookup codes (BL-7641)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3529)
=> Fix possible crash with missing problem report screenshot (20191213)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/textOverPicture.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3522)
=> Default Text-over-picture items to style "bubble" instead of "normal" (BL-7914)

src/BloomExe/Book/BookInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3533)
=> Allow bulk upload to have no bookshelf

src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less, src/BloomBrowserUI/bookEdit/toolbox/toolbox.less, src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3536)
=> Disable Comic tool for xmatter (BL-7919)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/BookStorageTests.cs
* bloom-player needs a few more characters
added to the list of bad ones
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3531)
=> BL-7816 Improve name sanitization

src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3537)
=> Fix timing of Motion preview for record-by-text-box mode (BL-7824)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3539)
=> BL-7925 Hide page label

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3541)
=> Prevent improper removal of data-duration attributes (BL-7825)

src/BloomBrowserUI/bookEdit/js/textOverPicture.ts, src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx, src/BloomBrowserUI/utils/isLinux.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3540)
=> Get inserting comic bubbles to work on Linux (BL-7958)

src/BloomBrowserUI/bookEdit/toolbox/callout/calloutControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3546)
=> BL-7908 Make bubble outline control handle "none" correctly

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3545)
=> Require language selection for upload if language data possible (BL-7799)

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3550)
=> Re-render if xmatter state changes (BL-7919)

src/BloomExe/web/controllers/AudioSegmentationApi.cs
The user may see only a brief red background warning about the failure.
Whether that happens or a full error dialog pops up, the information is
saved in the log file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3548)
=> Log aeneas error information when error occurs (BL-7947)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3549)
=> Prevent recursive Problem Report Dialogs (20191218)

debian/control, src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3552)
=> Get aeneas sound file splitting working on Linux (20191218)

src/BloomExe/web/RequestInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3559)
=> Prevent bogus Javascript "no element found" error (BL-7900)

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/Android/AndroidPublishSettings.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomTests/Book/BookTests.cs
* when the pages have L2 text, we want them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3558)
=> BL-7967 Keep .bloomd from losing Xmatter

src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3561)
=> Fix test for updating languages of book (BL-7968)

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3557)
=> Use custom language names consistently (BL-7832)

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3564)
=> Use browser display to determine fonts to embed (BL-7998)

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3567)
=> Make comic tool available even without experimental (BL-8016)

src/BloomExe/Book/BookData.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/CollectionCreating/LanguageIdControl.cs, src/BloomExe/WebLibraryIntegration/BookDownloadSupport.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Publish/PublishModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3569)
=> Unit test fixes - BL-7832, BL-7968

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/bookLayout/bubble.less
1st commit: Jeffrey Su
2nd commit: joint effort Gordon and Jeffrey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3568)
=> (depends on comicaljs PR)BL-7907 Fix misleading dragHandle situation

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/yarn.lock, src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3571)
=> Add error message if publishing ePUB for comic book (BL-8006)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3574)
=> BL-7907 and test failure fix

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3575)
=> Fix Linux package building to use node 12.14.0 (20200115)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3576)
=> Cleanup Comic Tool UI elements (BL-8007)

src/BloomExe/Publish/Android/PublishToAndroidApi.cs
Without this, I've been seeing initial bloomd book previews without any
content except a couple of xmatter pages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3573)
=> Ensure languages are setup before initial book preview update

src/BloomExe/Book/LicenseChecker.cs, src/BloomTests/Book/LicenseCheckerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3577)
=> Make content license parsing more robust (BL-8013)

src/BloomBrowserUI/bookLayout/langVisibility.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3580)
=> Revert fix for BL-8000 in order to fix BL-8017

src/BloomExe/FatalExceptionHandler.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
* just while BloomServer is offline
* requires libpalaso PR#889 (merged)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3579)
=> BL-8019 Use old error reporting

src/BloomExe/web/controllers/ProblemReportApi.cs
* Make ProblemReportApi log error  before trying
to do anything (take screenshot or open dialog)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3584)
=> BL-8041 Close "holes" in error reporting-step 1

src/BloomTests/Publish/PublishModelTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3585)
=> Bl 7998 add unit tests

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3578)
=> Ensure focus and translation bubbles as much as possible (BL-7994)

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3586)
=> Only publish L1 of books with comics (BL-7912)

src/BloomBrowserUI/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3588)
=> Fix Comic shift problem on hover (BL-8033)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3590)
=> BL-8048 Fix multiplying image names11111

src/BloomExe/ImageProcessing/ImageUtils.cs
* should not have a zero counter on a filename
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3592)
=> BL-8048 fix tests

debian/bloom-alpha.appdata.xml, debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3596)
=> Update Linux packages for master to 4.8 (20200127)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3601)
=> Quick fix to problem reporter

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3603)
=> Fix book download if book contains nested folders (BL-8071)

src/BloomExe/Collection/WritingSystem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3605)
=> Handle custom name determination when there is no default language name (BL-8072)

src/BloomBrowserUI/yarn.lock, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs, src/BloomTests/ToPalaso/LanguageLookupModelExtensionsTests.cs
* when Script/Region/Variant tags are used
* w/ a test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3607)
=> BL-8081 Remove pre-pended garbage from name

src/BloomExe/InstallerSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3608)
=> Fix failing Linux build (20200205)

src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/CollectionTab/LibraryBookView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3610)
=> Prevent LibraryBookView from crashing during bulk upload (20200205)

src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs, src/BloomTests/ToPalaso/LanguageLookupModelExtensionsTests.cs
* Use updated StandardSubtags method and do a better
job of handling exceptions to the rule
* More/better testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3609)
=> BL-8081/8096 GetBestName update

src/BloomExe/WebLibraryIntegration/BookTransfer.cs
Seeing error messages scroll by rapidly in the popup window isn't really
good enough in my opinion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3612)
=> Add error messages to BloomBulkUploadLog.txt (BL-6981)

src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3613)
=> Add upload options for user and shelf restriction (BL-6981)

src/BloomExe/ProjectContext.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3615)
=> [4.7]BL-8112 Fix error handling on bad collection

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/react_components/l10nComponents.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3616)
=> Internationalize Comic Tool's "Text Block" (BL-8108)

src/BloomExe/Book/BookInfo.cs, src/BloomExe/CLI/UploadCommand.cs
Also fix a repeated word typo in a command help string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3617)
=> Rename originalBookSourceUrl to importedBookSourceUrl (BL-6981)

src/BloomExe/BookThumbNailer.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3614)
=> Add createThumbnailArtifact option (BL-8054)

src/BloomExe/Book/TranslationGroupManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3618)
=> Add/fix comments about shouldNormallyShowEditable(). Related to BL-8093

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookLayout/langVisibility.less, src/BloomBrowserUI/react_components/l10nComponents.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3619)
=> Fix bubble position drift (BL-8077)

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3621)
=> Localize "Caption" too (BL-8108)

src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3623)
=> Update package numbers

src/BloomExe/web/YouTrackIssueSubmission.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3624)
=> [4.7]BL-8142 Get problem reporter to name zip after issue

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug, src/BloomExe/Edit/AudioRecording.cs
Probably we want to wait for UI Review before merging...
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3626)
=> BL-7568 Microphone problem message

src/BloomBrowserUI/react_components/colorChooser.less
* simple z-index collision
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3627)
=> BL-8115 Fix Color Chooser hex color option

src/BloomExe/Book/BookStorage.cs, src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3630)
=> Add upload --preserveThumbnails command line option (BL-6981)

src/BloomExe/Book/SizeAndOrientation.cs, src/BloomExe/NonFatalProblem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3633)
=> Ignore customCollectionStyles.css when looking for layout choices

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3632)
=> Language-specific features (BL-8158)

src/BloomExe/Browser.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3634)
=> Properly handle non-fatal errors from the command line

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3636)
=> Add comic feature string (4.7) (BL-8167)

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3638)
=> Save motion feature change immediately (BL-8049)

src/BloomExe/Book/BookInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3639)
=> Add Publisher to the book metadata (BL-6981)

src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3640)
=> Fix features array set wrongly if enterprise settings is off (BL-8200)

src/BloomExe/Book/TranslationGroupManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3641)
=> Properly copy talking books upon lang switch (BL-8215)

src/BloomBrowserUI/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3643)
=> Make bubbles vertically aligned center (BL-8247)

src/BloomBrowserUI/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3645)
=> Don't vertically center "Just Text" bubbles (BL-8247)

src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.less, src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, src/BloomBrowserUI/publish/commonPublish/PublishProgressDialog.tsx, src/BloomBrowserUI/utils/bloomApi.ts, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3642)
=> Fix Problem Report Dialog (BL-8222)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3647)
=> Fix leveled reader warnings if unset (BL-7895)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
The second commit adds the computation to the Book.BringBookInfoUpToDate method.  This
is called by Book.BringBookUpToDate, which is called by the upload function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3644)
=> Add phashOfFirstContentImage to BookMetaData (BL-8233)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3651)
=> Show problem report dialog before fatal errors terminate (BL-8222)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3652)
=> Use SafeInvoke.InvokeIfPossible instead (BL-8222)

src/BloomExe/Program.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3653)
=> Verify before blindly using most recent collection during command line upload

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/CLI/GetUsedFontsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3654)
=> Return exit code to Harvester if the original HTM file cannot be found

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3657)
=> Fix empty paragraph height (BL-8213)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomTests/CLI/CreateArtifactsCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3659)
=> CreatedArtifactsCommand: exit code description notifies if unknown flags

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3661)
=> BL-8134 Adjust comic resizing to work when scaled

src/BloomExe/Book/BookInfo.cs, src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs, src/BloomTests/packages.config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3662)
=> Send lastUploaded and updateSource to parse (BL-8295)

src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3663)
=> Make the Bloom build compatible with mono5-sil msbuild

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3664)
=> Always show the book language names approved by the user (BL-8302)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
* handle left side position changes too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3666)
=> BL-8134 fix Comic scaled resizing

src/BloomExe/CLI/CreateArtifactsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3670)
=> CreateArtifactsCommand supports calculating perceptual hash  (BL-8234)

src/Bloom-ChorusPlugin/BloomChorusPlugin.csproj, src/BloomExe/BloomExe.csproj, src/BloomTests/BloomTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3671)
=> Upgrade compiler to C# 7.3

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3672)
=> URL-decode src paths before computing perceptual hash (BL-8234)

src/BloomBrowserUI/gulpfile.js, src/BloomBrowserUI/templates/template books/Decodable Reader/Decodable Reader.pug, src/BloomBrowserUI/templates/template books/Leveled Reader/Leveled Reader.pug, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3673)
=> Merge from version4.7 to master 20200408

debian/control, debian/rules, environ, src/BloomBrowserUI/gulpfile.js, src/BloomBrowserUI/templates/template books/Decodable Reader/Decodable Reader.pug, src/BloomBrowserUI/templates/template books/Leveled Reader/Leveled Reader.pug, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Collection/ScriptSettingsDialog.Designer.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookTests.cs, src/LinuxBloomLauncher/BloomLauncher.c
This merges the changes for running Bloom with mono5-sil.
=> Merge 4.7 to 4.7_CS - 20200408

src/BloomExe/Book/Book.cs
* pre-origami books were not being migrated unless
the page was edited, now they are.
* removed a now useless
UpdatePageFromFactoryTemplates() method,
which only updated pages based on Basic Book pages
that were NOT customPage (there aren't any anymore)!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3677)
=> BL-8280 Make BringBookUpToData migrate

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
* based on whether playback order controls are active
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3680)
=> BL-7883 Get TalkingBook tool to disable/enable

src/BloomExe/Book/Book.cs
This supports the ABC+ xmatter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3682)
=> Add reader tags to body if reader is missing them

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3684)
=> Fix a bug that causes pHashes for the placeholder image to be generated

debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3688)
=> Add python3-aeneas dependency for Linux 4.7 package (20200420)

src/BloomExe/Book/PhashHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3686)
=> Tweak handling of 1-bit colormap images in phash calculations (20200421)

src/BloomBrowserUI/bloomMaterialUITheme.js, src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/react_components/playbackOrderControls.less, src/BloomBrowserUI/react_components/playbackOrderControls.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/yarn.lock, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
* separate .less file for playbackOrderControls
* hover makes the controls opaque
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3683)
=> BL-7883 more PlaybackOrder work

src/Bloom-ChorusPlugin/app.config, src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/app.config, src/BloomExe/packages.config, src/BloomExe/web/YouTrackIssueSubmission.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config, src/BloomTests/web/YouTrackIssueSubmitterTests.cs
This has the side-effect of updating Newtonsoft.Json to version 12.0.3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3694)
=> Update YouTrackSharp to version 2020.1.0 (BL-8329)

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3693)
=> PHash works on books using background-image instead of img src

src/BloomExe/BloomExe.csproj, src/BloomExe/web/YouTrackIssueSubmission.cs, src/BloomTests/web/YouTrackIssueSubmitterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3698)
=> Update youtrack interaction to its REST API version 2020.1 (BL-8329)

src/BloomBrowserUI/bloomUI.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3699)
=> Fix BL-8353 which prevented clicking in Problem Dialog

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3700)
=> Update DialogAdapters to 0.1.9 for Geckfx60 branch (BL-8281)

src/BloomBrowserUI/gulpfile.js, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3704)
=> Bump bloom-player to 1.1.65 (BL-8283)

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3701)
=> Set S3 cache-control headers on uploaded files (BL-8199)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3709)
=> BL-7883 fix test instability

src/BloomBrowserUI/templates/Sample Shells/The Moon and the Cap/meta.json, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStarter.cs, src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3710)
=> [4.7] BL-8381 Move Publisher to OriginalPublisher

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3706)
=> Handle internet problems during error report upload (BL-8403)

src/BloomBrowserUI/branding/BARMM/branding.json, src/BloomBrowserUI/package.json, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less, src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-Xmatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3721)
=> Merge from 4.7 to 4.8 (20200508)

src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3717)
=> [4.7] ABC-BARMM clean up non-reader display

Bloom.sln.DotSettings, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/XMatterHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3716)
=> Allow for Device-specific xmatter override per xmatter pack (BL-8372)

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
* when publishing to BR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3724)
=> [4.7]Fix bug in case of duplicate Title in a collection

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3725)
=> Strip surrounding markup out of original title (BL-8221)

build/dependencies.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3741)
=> Merge4.8into master again 20200514

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3744)
=> Set node memory allocation for Linux packaging (20200518)

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3746)
=> Set node memory in linux packaging 20200518

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/comic/comic.less, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
* Caption tail is a straight line
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3743)
=> BL-8192 Allow comic Caption to show tail

src/BloomExe/BookThumbNailer.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/BookThumbnailerTests.cs, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3745)
=> Generate social media sharing thumbnail (BL-8406)

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3749)
=> Change epub filename fix to encode only problematic characters (BL-8505)

src/BloomExe/Publish/Epub/EpubMaker.cs
Jeffrey's eagle eyes spotted this one...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3751)
=> Fix comparison for nonASCII characters (BL-8505)

src/BloomExe/Book/XMatterHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3752)
=> Use a special device xmatter if already selected (BL-8372)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageListView.cs, src/BloomExe/Edit/WebThumbNailList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3756)
=> Update page thumbs after page size or content langs changed (BL-8501)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3755)
=> BL-8192 New method of dealing with optional tails

src/BloomExe/BookThumbNailer.cs, src/BloomTests/BookThumbnailerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3758)
=> Generate social media thumbnail even if placeholder cover img (BL-8406)

src/BloomBrowserUI/templates/customXMatter/Pashti-Device-XMatter/Pashti-Device-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3761)
=> Fix file pathname capitalization error in pug file (20200601)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3762)
=> Fix Talking Book highlight not moved when activeElement change (BL-8538)

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3770)
=> Fix Linux packaging to also run locally (20200604)

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3772)
=> Merge from version4.7to version4.8 20200604

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3778)
=> Merge from4.8to master 20200605

src/BloomBrowserUI/templates/customXMatter/Dari-Device-XMatter/Dari-Device-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/Pashti-Device-XMatter/Pashti-Device-XMatter.pug, src/BloomBrowserUI/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3781)
=> Add End Extra and The End pages to Afghan device xmatters (BL-8372)

src/BloomExe/web/YouTrackIssueSubmission.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3783)
=> Fix file attachments in YouTrack issues (BL-8573)

src/BloomBrowserUI/templates/customXMatter/Afghanistan-XMatter.less, src/BloomBrowserUI/templates/customXMatter/ReleaseProcess.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3788)
=> Tweak Afghan xmatter copyright spacing again (BL-8372)

src/BloomBrowserUI/react_components/colorPickerDialog.tsx, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/web/controllers/EditingViewApi.cs, src/BloomTests/Book/HtmlDomTests.cs
* feeds into color picker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3790)
=> BL-8604 Add api call to get book's colors

src/BloomBrowserUI/bookEdit/toolbox/bookSettings/bookSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloom_xregexp_categories.js, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordable.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3789)
=> Disable updateMarkup if recordings present (BL-8529)

src/BloomExe/Publish/Epub/PublishEpubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3796)
=> Enhance error report when epub preview (and screenshot) fails (BL-8348)

src/BloomExe/NonFatalProblem.cs
Note that this is on the Version4.7 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3798)
=> Use the Bloom.Shell for problem screenshot if at all possible (BL-8348)

src/BloomExe/web/RequestInfo.cs
The "problem" is trying to send a non-ASCII file path through a purely
ASCII-only HTTP channel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3800)
=> Prevent a useless problem dialog for missing image files (BL-8643)

src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3801)
=> BL-8527 fix test to reflect situation more accurately

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3802)
=> Show URL decoded filenames for missing images (BL-8643)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/ToPalaso/BackgroundWorkerProgressAdapter.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomExe/web/WebProgressAdapter.cs
This adds a "maintenanceLevel" meta element in the HTML head element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3784)
=> Ensure large images in existing books are always handled (BL-8512)

src/BloomExe/Workspace/WorkspaceView.cs
This is on the Version4.7 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3805)
=> Prevent crash from repeated clicking on same tab (BL-8382)

src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, src/BloomTests/Publish/ExportEpubWithVideoTests.cs
All 62 failing tests are fixed by this set of changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3808)
=> Fix ePUB unit tests broken by EpubMaker calling BringBookUpToDate

src/BloomExe/BloomZipFile.cs, src/BloomExe/Publish/Epub/EpubMaker.cs
Also ensure that it's the first item stored in the .epub file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3813)
=> Don't compress the ePUB mimetype file (BL-8661)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
* text color and background color should be consistent
for a parent bubble and all its child bubbles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3807)
=> BL-8195 Make color changes to whole 'family'

src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3817)
=> Add epub 2.0 metadata for cover image for WorldReader (BL-8639)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3819)
=> Remove modal dialog during unit tests that causes errors on TeamCity

src/BloomBrowserUI/bookEdit/js/origami.ts
* video and widget containers weren't being detected
where they needed to be in a couple of places
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3816)
=> [4.8] BL-8547 Fix incomplete implementation of origami

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3822)
=> Fix cropping an image with GraphicsMagick processing afterward (BL-8638)

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3826)
=> BL-8458 Center BR preview vertically

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3830)
=> Add non-breaking space to longpress (BL-8683)

src/BloomBrowserUI/lib/long-press/jquery.longpress.js, src/BloomBrowserUI/lib/long-press/longpress.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3833)
=> Change display for non-breaking space in longpress (BL-8683)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3795)
=> Instead prevent imageContainer from scrolling down (BL-8559)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3803)
=> Fix regression in switch from Sentence -> TextBox mode (BL-8649)

environ
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3837)
=> Fix Linux environ to make debugging with monodevelop easier (20200717)

environ
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3838)
=> Merge from version4.8 to master 20200717

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3845)
=> Bl 8687 merge from release to beta

src/BloomExe/CollectionCreating/LanguageIdControl.cs
* Now detects if the language name is custom or not
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3847)
=> BL-8174 New collection language name fix

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3849)
=> Use narrow no-break space (BL-8683)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3852)
=> [4.8] BL-8726 Fix translation bubble regression

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3853)
=> Scroll thumbnail of current page into view automatically (BL-8701)

src/BloomExe/Book/Book.cs, src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3855)
=> Stop adding simpleComprehensionQuiz.js to books (BL-8480)

src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3862)
=> Fix occasional weird appearance of thumbnails (BL-8700)

DistFiles/ReleaseNotes.md, DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/branding/Juarez-USDA-PCI-Guatemala/branding.css, src/BloomBrowserUI/branding/branding-base.less, src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomBrowserUI/templates/common-mixins.less, src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less, src/BloomExe/Book/Layout.cs, src/BloomExe/Book/SizeAndOrientation.cs, src/BloomExe/BookThumbNailer.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs, src/BloomExe/Publish/PDF/PdfMaker.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs
This does not implement booklet making using this new size: if that is
wanted, another issue is needed to modify PdfDroplet as well as Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3842)
=> Add "13cm Square" page size (BL-8685)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3867)
=> Fix async unit test

src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3868)
=> Fix exception when closing a decodable reader book 

src/BloomExe/web/controllers/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3869)
=> Fix exception in APIRequest.

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3863)
=> Add language info to <body> so that a single branding can vary things by lang

src/BloomExe/Book/Book.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3872)
=> Don't remove transparency from images on cover page (BL-8819)

src/BloomExe/Shell.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3877)
=> Limit window sizes context menu to top tab strip (BL-8668)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3878)
=> Talking Book: Improve timing splits of 1st sentence (BL-8844)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3881)
=> Ensure style links always ordered properly in HTML head (BL-8845)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3882)
=> Preserve transparency in all images (BL-8846)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/lib/errorHandler.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3886)
=> Add error if duplicate ID encountered (BL-8852)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3889)
=> Add error if duplicate ID encountered, even if on another page (BL-8852)

src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/WebLibraryIntegration/BookDownloadedEventArgs.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/Publish/ExportEpubTestsBaseClass.cs
* with an older format book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3888)
=> BL-8648 fix case of going directly to Publish

Bloom.sln.DotSettings, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3896)
=> Add .distribution file to bloomds (BL-8875)

src/BloomBrowserUI/templates/xMatter/ABC-Reader-XMatter/ABC-Reader-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3900)
=> One last ABC xmatter change

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/branding/Juarez-USDA-PCI-Guatemala/branding.css, src/BloomBrowserUI/branding/branding-base.less, src/BloomBrowserUI/templates/common-mixins.less, src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less, src/BloomExe/Book/Layout.cs, src/BloomExe/Book/SizeAndOrientation.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3901)
=> BL-8882 Fix regression in layout naming & specify which comic size

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3897)
=> Talking Book: Fix bug if user changes page while audio playing (BL-8797) 

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
When you Listen to the whole page, they are played in sequence. After the 1st text box finishes, the 2nd text box starts playing its audio, which updates the audioPlayStartTime (good). The 1st audio is emptied and triggers an onemptied event. When onemptied is handled, it sets audioPlayStartTime to null (but audioPlayStartTime had already been updated to the correct value!), so you end up in a bad staet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3902)
=> Talking Book: Fix bug for multiple text boxes (BL-8797)

src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3903)
=> Fix test that was failing on Linux due to system differences (20200826)

src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug
* fix English alphabetization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3904)
=> 'More' tools order

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
Goes with Bloom-player changes: https://github.com/BloomBooks/bloom-player/pull/144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3906)
=> Talking Book: Scroll highlighted element into view (BL-8860)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs
* when looking for template pages for add page/change layout dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3907)
=> [4.8] BL-8893 Skip unauthorized folders

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3909)
=> Support for rounded corner captions (BL-8193).

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3910)
=> Prevent bloom-player analytics inside Bloom Desktop preview (BL-8874)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3912)
=> Fix scaling to not report bogus overflow for full bleed (BL-8915)

src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStarterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3913)
=> Fix error when getting originalTitle from title with ampersand (BL-8920)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3911)
=> Refactor Talking Book highlighting code (BL-8906)

src/BloomExe/Collection/BookCollection.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3914)
=> [4.8] BL-8893 Better permission denied solution

src/BloomExe/Book/BookCompressor.cs, src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/XmlHtmlConverter.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs, src/BloomTests/TestDoubles/CollectionTab/FakeLibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3920)
=> Ignore unnecessary HTM files when making bloomd (BL-8943)

src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3921)
=> Update comicaljs in yarn.lock (20200915)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3923)
=> Merge Version4.9 into master

src/BloomExe/Program.cs, src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3936)
=> Fix crashes on Linux from the UI language menu (BL-9054)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/FileIOApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3940)
=> Handle special characters when importing recordings (BL-9066)

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3938)
=> Ensure pages refreshed for new pictures (BL-9039)

src/BloomBrowserUI/react_components/stringListCheckbox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3943)
=> Fix Accessibility checkboxes in Metadata dialog (BL-9022)

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3944)
=> Fix BL-9021 Quiz Header Overflow

src/BloomBrowserUI/templates/template books/Big Book/Big Book.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3945)
=> Fix BL-9017 Big Book Title Page Font Size

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3947)
=> Fix LeveledReader bug where checkbox doesn't find cell to update (BL-9002)

src/BloomBrowserUI/publish/metadata/BookMetadataTable.less, src/BloomBrowserUI/publish/metadata/SubjectChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3949)
=> Merge from 4.8 to 4.8CS  (20200925)

src/BloomBrowserUI/publish/metadata/BookMetadataTable.less, src/BloomBrowserUI/publish/metadata/SubjectChooser.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3950)
=> Merge from 4.8_CS to 4.9 (20200924)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3956)
=> Fixes a couple of problems caught in code review

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3955)
=> Fix ePUB creation when OS culture uses commas for decimals (BL-9079)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/utils/bloomApi.ts, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookCompressorTests.cs, src/BloomTests/web/controllers/ApiTest.cs, src/BloomTests/web/controllers/FileIOApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3942)
=> TalkingBook: Import Recording unit tests (BL-9066)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3962)
=> Fix epub creation for book title with period then special character (BL-9040)

src/BloomExe/Book/BookStorage.cs
* this one fixes the original user's stack trace problem
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3964)
=> [4.8] BL-8893 Skip over denied template folders

.gitignore, build/getDependencies-windows.sh, src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3960)
=> Include Firefox dependencies msvcp140.dll and vcruntime140.dll in the installer (BL-9065)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3965)
=> Make Bloom format version parsing culture invariant (BL-9077)

src/BloomBrowserUI/bookEdit/toolbox/comic/comic.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3966)
=> [4.9] BL-9071 Hide 'Show Tail' checkbox

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/split_sentencesSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js, src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3968)
=> Fix word count for leveled reader (BL-8997)

Bloom.sln.DotSettings, src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.less, src/BloomExe/Browser.cs, src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, src/BloomExe/Publish/HtmlPublishPanel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3967)
=> Open Ace by Daisy checker links in system browser (BL-9026)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3972)
=> BL-9095 add "epub" to body class of every epub page

src/BloomBrowserUI/publish/metadata/BookMetadataTable.less, src/BloomBrowserUI/react_components/stringListCheckbox.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3975)
=> Fix Windows glitches in metadata table (BL-9022)

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3979)
=> Fix switching enterprise setting between local and none (BL-9103)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3977)
=> [4.9] BL-9011 Stop saving a new placeHolder image on cut

src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3983)
=> Ensure BloomPdfMaker has proper environment on Linux (BL-9069)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3985)
=> Add automatic "video" feature for books with at least one video (BL-9106)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3988)
=> [4.9] BL-8439 move playback controls inside the TranslationGroup

src/BloomBrowserUI/pageChooser/page-chooser.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3989)
=> Fix pageChooser error if path to Bloom has punctuation in it (BL-9109)

src/BloomTests/Publish/BloomReaderPublishTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3990)
=> Fix test for new video feature (BL-9106)

src/BloomExe/Book/BookData.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3993)
=> [4.9] BL-9111 Handle ampersand in cover image name

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3999)
=> Fix setting decodable stages by word list files on Linux (BL-9038)

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/BloomExe.csproj, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3976)
=> Add initial Sentry error capturing (with Andrew)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4000)
=> Fix javascript error (BL-9114)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomBrowserUI/react_components/colorChooser.tsx, src/BloomBrowserUI/react_components/customColorPicker.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/typings/css-element-queries.d.ts, src/BloomBrowserUI/typings/jquery.easytabs.d.ts, src/BloomBrowserUI/typings/jquery.i18n.custom.d.ts, src/BloomBrowserUI/typings/jquery.qtip.d.ts, src/BloomBrowserUI/typings/jquery.qtipSecondary.d.ts, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4002)
=> Optional Chaining Support

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/3997)
=> Fixes for Kyrgyz layouts and add A3 for full bleed (BL-8930)

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/bloomFrames.ts, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4006)
=> Strong typing of frame exports

debian/bloom-alpha.appdata.xml, debian/changelog, debian/rules
Also fix packaging for recent Sentry work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4009)
=> Fix Linux packaging for version 5.0 (20201008)

src/BloomBrowserUI/problemDialog/ProblemDialog.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4010)
=> Merge from 4.8 to master 20201008

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4012)
=> Merge from 4.9 to master again - 20201008

src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4013)
=> Fix failing test on linux 20201008

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/Publish/ExportEpubWithVideoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4016)
=> Fix export ePUB tests that were flaky on Linux (20201009)

src/BloomExe/ImageProcessing/ImageUtils.cs
* fix bug from earlier work on Cut
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4018)
=> BL-9009 Image Paste problems

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, src/BloomTests/Publish/ExportEpubWithVideoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4017)
=> Fix ExportEpubTests that frequently fail on Linux (20201012)

src/BloomExe/Publish/Epub/EpubMaker.cs
* add isbn, copyright holder, copyright year to metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4015)
=> [4.9] BL-8703 better ePub metadata

src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4020)
=> [4.9] BL-8703 Fix one text add another

debian/rules, lib/BloomPdfMaker.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4022)
=> Get BloomPdfMaker working properly on Linux for Bloom 4.9 (BL-9069)

src/BloomExe/Edit/EditingView.cs
* so the page thumbs get video links from right book folder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4026)
=> [4.9] BL-9133 Get Edit View to update page list on title change

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4031)
=> Update Geckofx60 for Linux for Ubuntu 20 sound/video playback (BL-9138)

src/BloomExe/web/controllers/AudioSegmentationApi.cs
This slipped through the cracks with the other sound problems being
more obvious.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4034)
=> Fix Ubuntu 20.04 problem in finding python for aeneas (20201021)

build/getDependencies-Linux.sh, debian/rules, lib/BloomPdfMaker.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Publish/PDF/MakePdfUsingGeckofxHtmlToPdfProgram.cs
This doesn't need to be merged to 4.9/5.0.  They already have the necessary fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4035)
=> Cherry pick pdf fix from 4.9 20201021

src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4038)
=> Merge from 4.8 cs to real 4.9 (20201022)

src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4036)
=> Fix scaling issue with full-bleed comics (BL-9116)

src/BloomExe/Edit/WebThumbNailList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4044)
=> Bl 9167 crash updating thumbnails language change

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/package.json, src/BloomBrowserUI/pageChooser/page-chooser.less, src/BloomBrowserUI/pageChooser/page-chooser.ts, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomBrowserUI/publish/metadata/A11yLevelChooser.tsx, src/BloomBrowserUI/react_components/bloomSelect.tsx, src/BloomBrowserUI/react_components/smallNumberPicker.less, src/BloomBrowserUI/react_components/smallNumberPicker.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/Book.cs, src/BloomExe/Command.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/web/controllers/AddOrChangePageApi.cs
2 commits
* 1st cleans up some types in BloomSelect
* 2nd does the multiple pages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4043)
=> BL-9158 Add multiple pages with dialog

src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManager.ts, src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManagerSpec.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4042)
=> Align comic bubbles middle (BL-8247)

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4045)
=> Fix country name font on title page (BL-8545)

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4047)
=> Simplify and fix country name font fix (BL-8545)

src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManager.ts, src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManagerSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4048)
=> Arrow key handles selection using Shift (BL-5227)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowSpec.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManagerSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/numbersSpec.js, src/BloomBrowserUI/utils/testHelper.ts
The HTML documents need to be cleaned up better/more reliably between test suites.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4053)
=> Fix intermittent failures in unit tests.

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4054)
=> Fix bug where activities w/space or punc in name are deleted (BL-9174)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/XMatterHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4058)
=> Set lang attribute on xmatter pages (BL-8545)

src/BloomExe/Publish/SHRP_TeachersGuideExtension.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4062)
=> Cherry-pick fix for BL-9210 back to 4.8

src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4064)
=> Add necessary package missing on Linux (20201105)

src/BloomExe/BloomFileLocator.cs, src/BloomExe/Book/XMatterHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4063)
=> Allow Harvester to find custom XMatter directories. (BL-9084)

src/BloomExe/UpdateVersionTable.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4067)
=> Better exception handling when failing to get UpdateVersionTable (BL-9211)

src/BloomBrowserUI/templates/template books/Paper Comic Book/Paper Comic Book.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4068)
=> Add Footer style for Paper Comic Template (BL-9116)

src/BloomExe/BloomExe.csproj, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4071)
=> Revert upgrade of Analytics.NET (BL-8947)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4070)
=> Handle pasting text with audio spans properly (BL-9221)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomBrowserUI/react_components/CopyContentButton.tsx, src/BloomBrowserUI/react_components/icons/ContentCopyIcon.tsx
* actually allows copy to clipboard from ANY source bubble
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4072)
=> BL-9198 Copy from Comic source bubbles

src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less, src/BloomBrowserUI/react_components/CopyContentButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4076)
=> Fix js test failure; UI review chgs

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4077)
=> Folio: Fix folio pages inserted twice; Number pages cumulatively instead of resetting count each book. (BL-9223)

src/BloomExe/CollectionTab/LibraryModel.cs, src/BloomTests/CollectionTab/LibraryModelTests.cs, src/BloomTests/TestDoubles/CollectionTab/FakeLibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4073)
=> Making bloompack of single book doesn't fail if invalid HTML (BL-8943)

Bloom.sln.DotSettings, src/BloomBrowserUI/branding/Afghan-Children-Read/branding.json, src/BloomBrowserUI/templates/customXMatter/Afghanistan-XMatter.less, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Edit/EditingView.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookStarterTests.cs
And make changes for Afghanistan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4078)
=> Properly set copyright and license using branding

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4081)
=> Fix failing unit test

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4082)
=> Updated expected value of unit test (BL-9223)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4083)
=> Merge from 4.8 to 4.8_CS - 20201117

src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/UserPrefs.cs, src/BloomExe/Utils/BloomUnauthorizedAccessException.cs, src/BloomExe/XmlHtmlConverter.cs, src/BloomExe/web/BloomApiHandler.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)
=> Improve error notification if UserAccessException occurs.

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4084)
=> Merge from 4.8_CS to 4.9 - 20201117

src/BloomBrowserUI/bookEdit/js/arrowKeyWorkaroundManagerSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4086)
=> Fix ArrowKeyWorkaroundManager Tests to run on Linux and Windows

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4087)
=> Allow cropping of newly selected pictures (BL-8638)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomTests/CLI/CreateArtifactsCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4090)
=> Fix incorrect exit codes if ThreadPool throws exception

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/ImageUpdater.cs, src/BloomTests/Book/BookStarterTests.cs
Also, the message is updated so that the exact file with the problem is easier to see in the problem report.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4089)
=> Catch unauthorized access exceptions in more places. (BL-8960)

src/BloomExe/Edit/EditingView.cs
Handle images from .bmp and .tif files properly while processing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4095)
=> Allow cropping when first importing image (BL-8638)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/CopyContentButton.tsx
* also alphabetized the "Common" section of the xlf file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4094)
=> BL-9198 Add tooltip to source bubble copy button

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/CopyContentButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4099)
=> Cherry-pick Bl-9198 tooltip for source copy btn

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4088)
=> Handle audio spans better during pasting (BL-9221)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4100)
=> Avoid loading an image a second time when importing (BL-8638)

src/BloomExe/BloomExe.csproj, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4091)
=> Mark Bloom LargeAddressAware (BL-9120)

src/BloomBrowserUI/templates/xMatter/ABC-Reader-Device-XMatter/ABC-Reader-Device-XMatter.less
* Keep "Not For Sale" visible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4097)
=> [4.9] BL-9188 Fix ABC Device xmatter

debian/control, debian/rules, src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4101)
=> Get Bloom packages and program working on Linux (20201203)

src/BloomBrowserUI/bookEdit/pageThumbnailList/PageThumbnail.tsx, src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4103)
=> BL-9169 Fix multiple delete lazy load problem

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4104)
=> BL-9169 Try again to solve gap in page list after deletes

src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/ErrorBook.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookStorageTests.cs, src/BloomTests/web/controllers/ProblemReportApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4093)
=> Allow clickable links in Problem Report dialog (BL-8960)

src/BloomExe/MiscUI/ToastNotifier.designer.cs
* to handle up to three lines of text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4108)
=> BL-8998 Increase vertical size of toast

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomExe/Edit/EditingView.cs
This belongs on master, not 4.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4113)
=> Revert "Trace memory leaks changing pages (BL-9261)"

build/getDependencies-Linux.sh, build/getDependencies-windows.sh, src/BloomExe/BloomExe.csproj, src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Linux/packages.config, src/BloomExe/app.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/Publish/ExportEpubTests.cs, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4111)
=> Get libpalaso dependencies from Nuget instead of TC (BL-9332) 

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4115)
=> Fix broken Linux build (20201215)

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4116)
=> Fix broken audio on Linux after nuget changes (20201216)

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4118)
=> Fix Windows build broken by fix for Linux build (20201216)

debian/install, debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4120)
=> Fix Linux packaging for nuget package libraries (20201216)

src/BloomExe/BloomExe.csproj, src/BloomExe/app.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4122)
=> Update L10NSharp to correct version. Also update other packages too.

src/BloomExe/Linux/packages.config, src/BloomExe/packages.config
The two files should be easier to compare now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4123)
=> Update Linux packages.config to match Windows (20201218)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4128)
=> Make header height fixed regardless of text height (BL-9355)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4129)
=> Remove fudge for keeping header heights the same (BL-9351)

src/BloomBrowserUI/bookPreview/previewMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4127)
=> Hide overflow for screen preview (BL-9352)

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4126)
=> Center full-bleed cover image and make it full width (BL-9350)

src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/bookPreview/previewMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4133)
=> Hide anything overflowing the page (doesn't hide bleed) (BL-9352)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4137)
=> Ensure back cover diamonds cover whole page (BL-9352)

src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs
Note that this is on Version4.9.  Testing on Windows indicates that the current code is needed there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4138)
=> Fix ghostscript failure on Ubuntu 20.04 Linux (BL-9379)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4141)
=> BL-9045 Restore page label for edit in templates

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4145)
=> Fix Kyrgyz Device16x9Portrait and implement Device16x9Landscape (BL-9357)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4146)
=> Vertically center Kyrgyz landscape back cover text (BL-9356)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4148)
=> Fix null axios post by downgrading from 0.21.1 to 0.19.2 (BL-9409)

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4149)
=> Remove obsolete img attributes in BringBookUpToDate (BL-9401)

src/BloomTests/Book/HtmlDomTests.cs
* api change caused test failures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4155)
=> BL-8537 fix tests

src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4156)
=> Update removal of recordingmd5 attributes for ePUB publishing (BL-9406)

src/BloomBrowserUI/bookEdit/sourceBubbles/sourceBubbles.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4154)
=> Prevent overflow scrollbars in translation bubbles (BL-9394)

DistFiles/InstallAce.sh, src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.cs, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4160)
=> Allow Ace by Daisy checker to work and display results (BL-9341)

src/BloomBrowserUI/branding/branding-base.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4161)
=> Fix display of inside front cover branding image (BL-9433)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4163)
=> Keep readonly book folder from crashing Bloom altogether (BL-9226)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4164)
=> Prevent submitting error due to folder permissions (BL-9226)

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/ToPalaso/DirectoryUtils.cs, src/BloomExe/web/controllers/EditingViewApi.cs
This has not been tested with Tumult Hype output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4165)
=> Improve widget import to handle folders with .html files (BL-9190)

build/getDependencies-Linux.sh, build/getDependencies-windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4170)
=> Update PdfDroplet dependencies to use PreNuGet branch (BL-9472)

src/BloomExe/NonFatalProblem.cs, src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4168)
=> Skip Sentry report for missing L10Ns

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/pageThumbnailList/PageThumbnail.tsx, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4169)
=> BL-9460 Support cover images with border w/out using filter

src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4177)
=> Ensure translations are found for collection level code (BL-9499)

src/BloomExe/ApplicationUpdateSupport.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4180)
=> Disable checking for updates on developer builds

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4181)
=> BL-9516 Way to tell illustrators what size to make images

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
* skips file info for placheHolder.png
* compacts the image file info into one line
* shows a ✓ or ⚠ next to DPI label
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4184)
=> Simplify Image DPI messages

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4187)
=> Calculate dpi based on whichever dimension uses up the container

src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
These were intended for the earlier changeset, but inadvertantly were not
committed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4190)
=> Minor image import tweaks for handling BMP and TIFF images (BL-9377)

src/BloomBrowserUI/react_components/l10nComponents.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionPanel.tsx, src/BloomBrowserUI/teamCollection/teamCollectionSettings.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4192)
=> Temporarily disable i18n warnings (BL-9545)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4193)
=> Fix various issues when modifying files in the shared TC folder (BL-9537)

src/BloomBrowserUI/lib/localizationManager/localizationManager.ts, src/BloomBrowserUI/react_components/bloomSelect.tsx, src/BloomBrowserUI/react_components/l10n.ts, src/BloomBrowserUI/react_components/l10nComponents.tsx, src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4197)
=> Fix param population when suppressing i18n warnings (BL-9545)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/statusPanelCommon.tsx, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4198)
=> Add avatars to TC book status panel (BL-9534)

src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4202)
=> Fix a filename capitalization build problem on Linux

src/BloomExe/TeamCollection/FolderTeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4203)
=> Ensure TC Books directory exists (BL-9561)

src/BloomBrowserUI/react_components/bloomAvatar.tsx, src/BloomBrowserUI/react_components/stories.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/stories.tsx, src/BloomExe/TeamCollection/BookStatus.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs
Also use full name rather than email in status panel.
Also outline current user avatar in yellow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4205)
=> Use initials if we can't get a user image for avatar (BL-9534)

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
* other language priority version wasn't used
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4204)
=> BL-9217 Fix for copyright license issue

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/ProgressLoggerTests.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs
* where book .htm filename is not exactly the folder name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4207)
=> BL-9573 Fix creation bug

src/BloomBrowserUI/bookPreview/previewMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4212)
=> BL-9586 Show page labels in templates in preview mode

src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs
This looks like a lot of changes, but all it is is plumbing of one bit through a bunch of methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4213)
=> BL-9585 Bloomds of Templates should stick with the template xmatter

src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.less, src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx, src/BloomExe/TeamCollection/TeamCollectionApi.cs
* Implement enterprise only TC Settings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4215)
=> BL-9542 TC Settings modes

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
* We will be using the same string for the
TC Status button too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4219)
=> Move "Team Collection" string to Common

src/BloomExe/TeamCollection/TeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4223)
=> Fix problem where StartMonitoringOnIdle was not resumed. (BL-9593)

src/BloomExe/TeamCollection/TeamCollection.cs
Also re-order instructions to require less mental (and CPU) gymnastics
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4224)
=> Fix potential deadlock in TC for StartMonitoringOnIdle (BL-9593)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)
=> Fix duplicate audio ids added by earlier bug (BL-9503)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Linux/packages.config, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4218)
=> Handle updating license icons more robustly and quietly (BL-9533)

src/BloomBrowserUI/teamCollection/statusPanelCommon.less, src/BloomBrowserUI/teamCollection/statusPanelCommon.tsx, src/BloomBrowserUI/teamCollection/stories.tsx
* left align eventual children with Avatar
* right align eventual children and eventual menu with
Check in button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4226)
=> BL-9577 tweaks to TC book status panel layout

src/BloomExe/TeamCollection/FolderTeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4227)
=> Fix bug suppressing recent notifications.

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4229)
=> BL-9518 Fix template thumb regression

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/teamCollection/NewTeamCollection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4231)
=> BL-9566 Pick up "0" variable in TC Join dlg

src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4237)
=> Fix TC test problem

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Collection/BookCollection.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/Event.cs, src/BloomExe/Palette.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/TeamCollection/BookStateChangeEventArgs.cs, src/BloomExe/TeamCollection/BookStatus.cs, src/BloomExe/TeamCollection/CheckoutStatusChangeEventArgs.cs, src/BloomExe/TeamCollection/FileSystemEventRecord.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/Utils/FileSystemWatcherExtensions.cs, src/BloomTests/CollectionTab/LibraryListViewTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs, src/BloomTests/TeamCollection/TestFolderTeamCollection.cs, src/BloomTests/TestDoubles/CollectionTab/FakeLibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235)
=> Team Collections - Add checkout status icon over book list

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
* also changing from other style to caption will make
any background color opaque
* separate PRs will allow Just Text to have straight line tails
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4241)
=> BL-8537 Turn off alpha for captions

src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/yarn.lock
* upgrade comical for devs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4242)
=> BL-8194 Allow straight line tails on Just Text boxes

Bloom.sln.DotSettings, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/utils/bloomApi.ts, src/BloomExe/Registration/RegistrationDialog.Designer.cs, src/BloomExe/Registration/RegistrationDialog.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4246)
=> Require registration email to use Team Collections (BL-9528)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4244)
=> BL-9578 Make bubble focusable after style change

src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4250)
=> Ensure registration before creating TC (BL-9528)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4266)
=> Fix new Windows-only dialog for Linux (20210309)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4253)
=> Catch exceptions in TeamCollectionApi and log them (BL-9480)

src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4272)
=> Prevent reload with uncommitted rename recreating book (BL-9576)

src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4270)
=> Filter out redundant Team Collection messages (BL-9664)

src/BloomBrowserUI/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4279)
=> BL-9320 Keep pre-existing Digital Comic Books working

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
* Link to book after published
* Link to Terms of Use
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4280)
=> [4.9] BL-9512 Fix Publish to web links

src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/web/controllers/CommonApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4274)
=> Fix a couple of TeamCollection glitches on Linux (20210310)

src/BloomExe/Utils/PerformanceMeasurement.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4282)
=> Fix memory deltas and for linux 20210315

src/BloomExe/Workspace/WorkspaceView.cs
* UI approved by JH ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4285)
=> BL-9044 Auto Update dlg tweaks

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
Move away from the done() callback syntax. This syntax makes it easy to lose unhandled error messages (you get a timeout instead). As you can see, many of these tests weren't handling exceptions properly.
By changing this syntax, we can have a clearer picture of whether the timeouts are due to an unhandled error vs the code actually taking longer than 5 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4290)
=> Improve async unit tests

src/BloomExe/CollectionTab/LibraryBookView.cs, src/BloomExe/CollectionTab/LibraryView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4284)
=> Fix problematic "Edit this book" button showing (BL-9687)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
An easy thing we can try to see if the unit test failures are related to it taking too long or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4291)
=> Increase unit test timeout to 15 seconds

src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooser.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomExe/Browser.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/web/controllers/EditingViewApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4289)
=> Replace all FireCSharpEvents with BloomApi.post calls

src/BloomTests/BloomTests.csproj, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4298)
=> Fix TeamCollection unit tests that fail on Linux (20210322)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4299)
=> Reload the top page in the edit view only when mem usage is high

src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4297)
=> Fix problems with renaming books locally (BL-9680)

src/BloomExe/TeamCollection/TeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4302)
=> Replace incorrect assert with a comment (20210323)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4301)
=> Don't remove "extension" from folder names (BL-9667)

src/BloomExe/Utils/MemoryUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4305)
=> Fix system memory check for Linux (20210323)

src/BloomBrowserUI/branding/fdpm/branding.json
* now defaults to BY-NC-ND
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4306)
=> [4.9] BL-9698 fdpm branding default license

Bloom.sln.DotSettings, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/CLI/GetUsedFontsCommand.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/CLI/GetUsedFontsCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4304)
=> Do not include fonts for languages not in the book (BL-9709)

src/BloomExe/CLI/CreateArtifactsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4310)
=> Fix Bloom for Harvester to process Template books (BL-9650)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4307)
=> Fix freeze of page selection view when changing page layout (BL-9712)

src/BloomBrowserUI/branding/fdpm/branding.json, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Utils/MemoryUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4312)
=> Merge from Version4.9 to master - 20210326

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4308)
=> Add widget feature; Make quiz/widget subcategory of Activity (BL-9682)

build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4316)
=> Fix failing unit tests on TeamCity for Linux (20210329)

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4317)
=> Upgrade libpalaso to include PalasoImage fix (BH-5706)

build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4319)
=> Adjust TeamCity testing for Windows and Linux (20210330)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4314)
=> BL-9468 Make deleting a bubble update correctly

build/Bloom.proj
This should not be merged into master.  master already has this fix, and I had to tweak it for Version4.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4320)
=> Fix failing unit tests on TeamCity for Linux 4.9 (20210329)

src/BloomExe/web/BloomServer.cs
This exception is being thrown instead of HTTP listener exception,
which was already being caught.  This is occurring constantly in unit
tests for Linux on TeamCity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4323)
=> Catch socket exceptions when opening HTTP listener

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4329)
=> Change "Cancel" to "Close" for button in TeamCollection dialog (BL-9745)

src/BloomBrowserUI/performance/PerformanceLogPage.tsx, src/BloomExe/Edit/AudioRecording.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Utils/PerformanceMeasurement.cs, src/BloomExe/web/controllers/FileIOApi.cs, src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4331)
=> BL-9757 Performance Log improvements

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4333)
=> Handle selecting same (PNG) image again without complaint (BL-9737)

src/BloomExe/MiscUI/StartupScreenManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4334)
=> Fix program not starting for unregistered users (BL-9761)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/web/controllers/FileIOApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4335)
=> Handle disposing null PerformanceMeasurements (BL-9762)

src/BloomExe/MiscUI/StartupScreenManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4337)
=> Fix problem of splash form hanging around forever (BL-9759)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookStarter.cs, src/BloomExe/Book/DataSet.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/ElementProxy.cs, src/BloomExe/XmlString.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookDataTests.cs, src/BloomTests/Book/BookStarterTests.cs, src/BloomTests/Book/BookTests.cs, src/BloomTests/Book/DataSetTests.cs, src/BloomTests/XmlStringTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4328)
=> Fix special chars in language location string (BL-9732)

src/BloomExe/CollectionTab/LibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4342)
=> BL-9766 Can't check out a book by double-click

src/BloomBrowserUI/yarn.lock
I like to see my recent fixes when I build BloomDesktop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4341)
=> Upgrade bloom-player to the latest (20210407)

src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/statusPanelCommon.less
* TC Book Status panel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4347)
=> BL-9630 Better Checkin/out buttons

src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/Extensions.cs, src/BloomExe/Utils/TextUtils.cs, src/BloomTests/CollectionTab/LibraryListViewTests.cs, src/BloomTests/TestDoubles/CollectionTab/FakeLibraryModel.cs, src/BloomTests/Utils/TextUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4351)
=> Fix unescaped ampersands in LibraryListView (BL-9732)

src/BloomExe/BloomExe.csproj, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/S3Extensions.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4356)
=> Allow downloading of books with >1000 files (BL-9794)

src/BloomExe/Program.cs, src/BloomExe/web/controllers/CommonApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4360)
=> Fix copy/paste not working (BL-9793)

src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, src/BloomBrowserUI/bookPreview/bookPreview.ts, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/utils/WireUpReact.ts, src/BloomExe/CollectionTab/LibraryBookView.Designer.cs, src/BloomExe/CollectionTab/LibraryBookView.cs, src/BloomExe/web/ReactControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4354)
=> Fix Team Collection book status display to not ruin PDFs (BL-9786)

src/BloomExe/CollectionTab/LibraryBookView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4371)
=> Fix "Create a book" button to appear over react control (20210415)

src/BloomExe/MiscUI/ReactDialog.cs, src/BloomExe/MiscUI/StartupScreenManager.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, src/BloomExe/web/controllers/CommonApi.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs
* Report button in TC Activity sync progress dialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4368)
=> BL-9800 Fix crash when clicking Report

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This includes a fix for updating image licenses from creative commons
to custom or all rights reserved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4378)
=> Update the palaso packages to get latest (BL-9622)

src/BloomBrowserUI/infoPages/aboutBox-fr.htm, src/BloomBrowserUI/infoPages/aboutBox.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4383)
=> Update copyright year (BL-9829)

src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4386)
=> Ignore fonts for invisible text when harvesting (BL-9831)

src/BloomExe/MiscUI/ReactDialog.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/web/controllers/CommonApi.cs
* removed CurrentOpenModal
* added CloseAllReactDialogs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4379)
=> BL-9800 Simplification of ReactDialog

src/BloomExe/Book/HtmlDom.cs, src/BloomExe/CLI/GetUsedFontsCommand.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4388)
=> Adjust check for fonts to include invisible content text (BL-9831)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4385)
=> Add some book total counts for Leveled Reader (BL-9828)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4390)
=> Adjust unit tests for non-rounded leveled reader stats (BL-9828)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4393)
=> Reword Leveled Reader measurement (BL-9828)

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4398)
=> Adjust quiz page to not overflow device landscape (BL-9823)

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4399)
=> Disable "Team Collection" checkbox when in a Team Collection (BL-9842)

src/BloomExe/CollectionTab/LibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4404)
=> Allow books in "Books From BloomLibrary.org" to be deleted (BL-9861)

src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4405)
=> Fix broken links in Team Collection tab of settings dialog (BL-9860)

src/BloomExe/CollectionTab/LibraryListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4406)
=> BL-9634 Fix Template Starter border

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4407)
=> Fix crash after creating leveled reader (BL-9859)

debian/bloom-alpha.appdata.xml, debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4411)
=> Update the Linux bloom-desktop-alpha package to 5.1 (20210429)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs
Note that this breaks all existing team collections.  (They can be
fixed by renaming and editing the link file if so desired.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4414)
=> Change TeamCollectionSettings.xml to TeamCollectionLink.txt (BL-9873)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4415)
=> Merge5.0 to master 20210430

DistFiles/ReleaseNotes.md, src/BloomExe/Workspace/WorkspaceView.cs
Also fix some other minor problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4422)
=> Fix dialog and image widths for Release Notes dialog (BL-9867)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
* extend cover color all the way down the page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4421)
=> [5.0] BL-9844 Kyrgyzstan ePUB xmatter

DistFiles/localization/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4426)
=> Update instructions for merging translations from Crowdin (202010503)

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, src/BloomBrowserUI/templates/template books/Sign Language/Sign Language.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4420)
=> Remove enterprise requirement for sign language (BL-9877)

src/BloomExe/Book/Book.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/TeamCollection/DisconnectedTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/DataBuilders/BookFolderBuilder.cs, src/BloomTests/DataBuilders/TeamCollectionApiBuilder.cs, src/BloomTests/DataBuilders/TeamCollectionBookBuilder.cs, src/BloomTests/TeamCollection/SyncAtStartupTests.cs, src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, src/BloomTests/TeamCollection/TeamCollectionTests.cs, src/BloomTests/web/controllers/ApiTest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4417)
=> Add unit tests to TeamCollectionApi (BL-9500)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4430)
=> Ignore invalid pages when computing book level reader stats (BL-9876)

DistFiles/ReleaseNotes.css, DistFiles/ReleaseNotes.md, src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4436)
=> Limit image widths in the Release Notes dialog (BL-9867)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4438)
=> [4.9] BL-9844 another fix for Kyrgyzstan ePubs

src/BloomBrowserUI/bookEdit/toolbox/readers/ReaderSettings.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4441)
=> Fix check for max number of sentences in a book (BL-9885)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Workspace/WorkspaceView.Designer.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4444)
=> Refresh Help menu (BL-9893)

src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/Utils/DropboxUtils.cs
Also use it for possible starting point when creating a team collection.
(and restore fixes for Linux)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4448)
=> Add DropboxUtils.GetDropboxFolderPath method (BL-9891)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4446)
=> Fix new page early for valid leveled reader counts (BL-9876)

src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4451)
=> Fix tests broken by repairing leveled reader book counts (BL-9876)

src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/MiscUI/ReactDialogFactory.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4452)
=> Bl 9892 fix problem report dialog

src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4453)
=> Fix broken test compilation

src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, src/BloomBrowserUI/teamCollection/stories.tsx, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4455)
=> Prefill Dropbox folder path in Create Team Collection dlg (BL-9891)

src/BloomExe/TeamCollection/DisconnectedTeamCollection.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/Utils/DropboxUtils.cs
Also fix some Linux related issues for Dropbox interaction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4428)
=> Add some basic analytics to Team Collection actions (BL-9868)

DistFiles/localization/Bloom.bn.tmx, DistFiles/localization/Bloom.en.tmx, DistFiles/localization/Bloom.es.tmx, DistFiles/localization/Bloom.fr.tmx, src/BloomExe/Workspace/WorkspaceView.Designer.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/Workspace/WorkspaceView.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4443)
=> Add special REACH upgrade message

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4457)
=> Replace obsolete property references for languages 2 and 3 (20210513)

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/accessibilityCheck/learnAboutAccessibility.tsx, src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx, src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx, src/BloomBrowserUI/react_components/BloomDialog/stories.tsx, src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx, src/BloomBrowserUI/react_components/bloomButton.tsx, src/BloomBrowserUI/react_components/checkbox.tsx, src/BloomBrowserUI/react_components/link.tsx, src/BloomBrowserUI/react_components/pWithLink.tsx, src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4459)
=> Make the Create a Team Collection dialog visually simpler w/ better copy

src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/templates/template books/standard-page-mixins.pug, src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4468)
=> Finish removing enterprise requirement for sign language (BL-9941)

DistFiles/ReleaseNotes.md, src/BloomExe/CollectionTab/LibraryListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4469)
=> BL-9448 show folder name on book thumbnail tooltip

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4461)
=> BL-9844 Kyrg. version that uses media queries to be "responsive"

src/BloomBrowserUI/teamCollection/CreateTeamCollection.tsx, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4472)
=> Fix TC creation when using default Dropbox location (BL-9920)

debian/rules
I think this can leak through to master safely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4475)
=> Add some simple diagnostics for jenkins Linux package building

src/BloomExe/Publish/PDF/PdfViewer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4477)
=> Fix PDF printing for Linux Bloom with Geckofx60 (GTK3) (BL-9957)

src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4479)
=> Robust-ify IO in AudioSegmentationApi.cs

src/BloomExe/WebLibraryIntegration/BookTransfer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4484)
=> Remove formatting lock from books when downloading from BL.org (BL-9996)

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4485)
=> Fix BL-10003 Sign Language checkbox gets disabled while still checked

src/BloomExe/Book/BookData.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4482)
=> Fix Unicode in languagesOfBook displaying incorrectly (BL-9972)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4489)
=> BL-9958 improve error message when copying img metadata fails

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/PublishView.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4492)
=> Update the PDF Options button tooltip to reflect reality (BL-9963)

src/BloomExe/web/controllers/AudioSegmentationApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4493)
=> BL-9959 give warning if we're about to run aeneas but have a unc path

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4494)
=> Copy meta.json correctly when duplicating a book (BL-9956)

src/BloomExe/Book/BookCompressor.cs, src/BloomTests/Book/BookCompressorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4483)
=> Allow music .wav files to be included in published books (BL-9931)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4480)
=> Allow growing answer boxes for non-Device16x9Landscape quiz (BL-9952)

src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/MXBBook-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/MXBBook-XMatter/description-en.txt, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.less, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/MXBPamphlet-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/MXBPamphlet-XMatter/description-en.txt, src/BloomBrowserUI/templates/customXMatter/ReleaseProcess.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4506)
=> BL-9874 another MXB xmatter update

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4518)
=> Call SentrySdk.CaptureException when Application.Run catches (BL-10000)

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4520)
=> Report an emergency shutdown to users safely (BL-10000)

src/BloomExe/Publish/Epub/EpubMaker.cs
* keep Kyrgyzstan-only solution from 4.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4525)
=> BL-9844 Back out "all xmatter css" epub

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4523)
=> Use Win32 MessageBox for fatal crash message on Windows (BL-10000)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/readerTools.less, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts, src/BloomExe/web/ReadersApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4522)
=> Add ability to copy leveled reader stats to clipboard (BL-10018)

src/BloomBrowserUI/bookPreview/BookPreviewPanel.less, src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.less, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomBrowserUI/teamCollection/statusPanelCommon.less, src/BloomBrowserUI/teamCollection/stories.tsx
* add story
* fix overflow
* submitted as draft until UI Review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4513)
=> BL-9949 TC Book Status problem state

src/BloomBrowserUI/templates/customXMatter/StoryProducer-XMatter/StoryProducer-XMatter.less, src/BloomBrowserUI/templates/customXMatter/StoryProducer-XMatter/StoryProducer-XMatter.pug, src/BloomBrowserUI/templates/customXMatter/StoryProducer-XMatter/description-en.txt
Hint bubbles on front cover; allow user to select some text on config page.
=> A few tweaks to StoryProducer custom xmatter - V3

src/BloomBrowserUI/templates/template books/Activity/simpleComprehensionQuiz.ts
* on how quizzes operate in b-p
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4532)
=> Just a note to future selves

src/BloomBrowserUI/bookEdit/css/editMode.less
Will be followed up with BL-10048
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4531)
=> BL-10017 False Overflow with Khmer with language name with large descender

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx, src/BloomBrowserUI/bookPreview/BookPreviewPanel.tsx, src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, src/BloomBrowserUI/problemDialog/ReportDialog.tsx, src/BloomBrowserUI/problemDialog/stories.tsx, src/BloomBrowserUI/problemDialog/theme.ts, src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/CollectionTab/LibraryBookView.Designer.cs, src/BloomExe/CollectionTab/LibraryBookView.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/MiscUI/ReactDialog.cs, src/BloomExe/MiscUI/ReactDialogFactory.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/web/ReactControl.cs, src/BloomExe/web/controllers/CommonApi.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomExe/web/controllers/SignLanguageApi.cs, src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4473)
=> Minor refactorings and fixes in preparation for actual change (BL-9920)

src/BloomBrowserUI/bookLayout/basePage-sharedRules.less, src/BloomBrowserUI/bookLayout/basePage.less, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4538)
=> Fix digitally published back cover for Kyrgyz (BL-10053)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4539)
=> BL-10058 Paragraph Markers

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4540)
=> Change ShouldDoFullReload back to non-test implementation.

src/BloomExe/MiscUI/ReactDialog.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/web/controllers/CommonApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4537)
=> Fix Error.NotifyUserOfProblem while in a locked API call (BL-9920)

src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4541)
=> Add left/right margin to text on Krygyz epub back cover (BL-10053)

environ-xulrunner
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4547)
=> Allow Debug and Release builds to coexist on Linux (20210610)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/web/controllers/CommonApi.cs, src/BloomExe/web/controllers/EditingViewApi.cs
* 1st commit is just refactoring
* moved/renamed an api function that I didn't end up using
* activate bubble editing w/o re-navigating
* update toolbox UI with new bubble
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4546)
=> BL-10002 Do comic manipulation w/o expensive refresh

src/BloomExe/ErrorReporter/SentryErrorReporter.cs, src/BloomExe/NonFatalProblem.cs, src/BloomExe/Program.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/Utils/DropboxUtils.cs, src/BloomExe/web/UrlLookup.cs
And refactor Sentry reporting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4549)
=> Simplify the way we report URL lookup errors (BL-10084)

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4551)
=> Add curly glottal (U+02BC) to longpress (BL-10094)

src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs, src/BloomExe/WebLibraryIntegration/AccessKeys.cs, src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookTransfer.cs, src/BloomTests/WebLibraryIntegration/BookTransferTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4545)
=> Prepare bulk edit for customer use (BL-9997)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx, src/BloomExe/Publish/Android/usb/AndroidDeviceUsbConnection.cs, src/BloomExe/Publish/Android/usb/UsbPublisher.cs, src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4542)
=> Changes needed to USB transfer for Android 11 (BL-10075)

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/CLI/SpreadsheetExportCommand.cs, src/BloomExe/CLI/SpreadsheetImportCommand.cs, src/BloomExe/Program.cs, src/BloomExe/Spreadsheet/ContentRow.cs, src/BloomExe/Spreadsheet/HeaderRow.cs, src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, src/BloomExe/Spreadsheet/SpreadsheetCell.cs, src/BloomExe/Spreadsheet/SpreadsheetExportParams.cs, src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs, src/BloomExe/Spreadsheet/SpreadsheetImportParams.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomExe/Spreadsheet/SpreadsheetRow.cs, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/TranslationGroupManagerTests.cs, src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, src/BloomTests/Spreadsheet/SpreadsheetTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)
=> Spreadsheet import/export stage 1 (BL-9897)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/js/collectionSettings.d.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/toolbox/comic/comicTool.tsx
* much more reliable setup
* takes care of gear icon not being functional
* better handling of child and duplicate bubbles
* a bit of refactoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4555)
=> BL-10002 Lose refresh on comics

src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4559)
=> Add new packages to Linux version of packages.config (20210618)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx, src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/AndroidPublishSettings.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/LanguagePublishInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4561)
=> Add publish control which langs' narration audio to include (BL-10055)

src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/LanguagePublishInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4566)
=> If a language lacks any audio, its checkbox is now disabled (BL-10055)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4568)
=> Good Bloom files names should be NFC (BL-10122)

src/SquirrelInstaller/Bloom.nuspec
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4579)
=> Fix Bloom.nuspec to work with NuGet 5.10

src/BloomExe/BloomExe.csproj, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, src/BloomExe/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4573)
=> BL-9997 add folder source chooser

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomTests/WebLibraryIntegration/BloomParseClientTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
Besides clean up, another goal is to prevent intermittent test failures
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4584)
=> Clean up LegacyLogin (to parse server)

src/BloomExe/CLI/SpreadsheetExportCommand.cs, src/BloomExe/CollectionTab/LibraryListView.Designer.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/LibraryListView.resx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4588)
=> Add Export to Excel command

src/BloomExe/Linux/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4589)
=> Update Linux packages.config to match Windows (20210713)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomExe/web/ReadersApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4569)
=> Ensure book and page counts match in Leveled Readers (BL-10129)

src/BloomTests/web/controllers/ReadersApiTests.cs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4590)
=> Fix test for changes to ReadersApi.GetTextOfContentPagesAsJson (BL-10119)

debian/rules, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, src/BloomTests/BloomTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4594)
=> Fix broken compiling and package building on Linux (20210715)

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4593)
=> Allow more Harvester subclassing of BloomParseClient (BL-10182)

src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, src/BloomExe/TeamCollection/FolderTeamCollection.cs
And various more subtle improvements to various special cases of joining a collection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4596)
=> Allow user to fix things by rejoining moved TC (BL-10183)

src/BloomExe/BloomExe.csproj, src/BloomExe/MiscUI/BloomFolderChooser.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4592)
=> Allow folder level bulk upload for Linux in Bloom GUI (BL-9997)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.resx, src/BloomExe/Publish/Epub/PublishEpubApi.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs
This will affect all existing Team Collections, unfortunately.
But should make bulk uploading more efficient and Team Collection book update checks more reliable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4591)
=> Make book hashes more deterministic (BL-9997)

src/BloomBrowserUI/collectionsTab/BookButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4598)
=> Fix filename capitalization error on Linux (20210719)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markupSpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomExe/web/ReadersApi.cs, src/BloomTests/web/controllers/ReadersApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4599)
=> Cherry picks for leveled readers 20210719

src/BloomBrowserUI/branding/Kyrgyzstan2020/branding.json, src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.pug, src/BloomExe/Book/BookCompressor.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4602)
=> Rename class for preserving image resolution in BloomPubs (BL-10162)

src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4604)
=> Make "updates available" message indicate rename (BL-10124)

src/BloomBrowserUI/publish/ReaderPublish/PublishLanguagesGroup.tsx, src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomExe/Publish/InclusionSetting.cs, src/BloomExe/Publish/LangsToPublishSetting.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomTests/Book/BookInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4610)
=> Persist Talking Book Languages and Text Languages settings (BL-10055)

src/BloomExe/Book/Book.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/RobustIO.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4614)
=> Make publishing ePUB and BloomPub more robust (20210723)

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4618)
=> Fix font for Sync dialog title and restore syncing (BL-10208)

src/BloomExe/Workspace/WorkspaceModel.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4617)
=> Restore book selection only for same collection (BL-10225)

src/BloomExe/Book/Book.cs, src/BloomExe/Workspace/WorkspaceView.Designer.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4616)
=> Prevent redundant calls to BringBookUpToDate for previews (BL-10227)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4624)
=> Fix uninitialized value when switching between LR and DR tool (BL-10243)

src/BloomExe/Book/Book.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs
Added some debugging code which was left commented out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4621)
=> Improve hash reliability and upload reporting (BL-9997)

src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetupDialog.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4629)
=> Fix links to bring up the readers setup dialog (BL-10235)

src/BloomExe/Book/BookSelection.cs, src/BloomExe/CollectionTab/LibraryBookView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4633)
=> Prevent multiple renderings of book preview pane (BL-10227)

src/BloomExe/ProjectContext.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4631)
=> Fix page labels showing in preview pane on template books (BL-10241)

src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4637)
=> Restore sans-serif fonts in Create Team Collection dialog (BL-10228)

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4641)
=> Make no uploadable text a warning instead of a blocking thing (BL-10004)

src/BloomBrowserUI/bookEdit/toolbox/readerTools.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4644)
=> BL-10256 Make Copy Stats button white

src/BloomExe/BloomExe.csproj, src/BloomExe/Linux/packages.config, src/BloomExe/packages.config, src/BloomTests/BloomTests.csproj, src/BloomTests/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4645)
=> Update palaso libs to fix localization spacing problem (BL-10061)

src/BloomExe/WebLibraryIntegration/BulkUploader.cs
This helps minimize re-uploading unchanged books.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4647)
=> Bring book up to date before computing hash in bulk upload (BL-9997)

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4651)
=> Force plain text paste on newly added list items too (BL-10221)

src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.pug, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModelSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/lib/localizationManager/localizationManager.ts, src/BloomBrowserUI/typings/jasmine/jasmine.d.ts, src/BloomBrowserUI/utils/asyncUtils.ts, src/BloomBrowserUI/utils/bloomApi.ts
1) Simplify the structure so that it doesn't require modifying the DOM and inserting these span structures.
2) Make it so that the raw format string/placeholders "Level {0} of {1}" are not rendered to the user
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4632)
=> Refactor Leveled/Decodable Reader - improve level num display (BL-10243)

src/BloomExe/CollectionTab/LibraryListView.Designer.cs, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/Spreadsheet/SpreadsheetIO.cs
https://issues.bloomlibrary.org/youtrack/issue/BL-10259
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4648)
=> Export to Spreadsheet Menu command improvements  (BL-10259)

src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/CollectionTab/LibraryModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4659)
=> Prevent crash when saving .bloom file (BL-10159)

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4660)
=> Only show scrollbar for BR language list if needed (BL-10271)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/BookThumbNailer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4661)
=> Allow users to provide custom thumbnail files for blorg2 (BL-10254)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4667)
=> Keep problem report dialog on top of Bloom window (BL-10292)

src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4668)
=> Improve message for joining team collection errors (BL-10247)

src/BloomExe/Publish/Android/AndroidPublishSettings.cs, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4665)
=> Initialize missing TextLangsToInclude in Bulk Publish (BL-10190)

src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4669)
=> Fix test for languages allowed in comical books (BL-10275)

src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4671)
=> Show proper license icon for book previews (BL-10297)

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4672)
=> Ignore missing audio files when copying/pasting text (BL-10291)

src/BloomBrowserUI/app/selectedBook.ts, src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx, src/BloomBrowserUI/react_components/bloomButton.tsx, src/BloomBrowserUI/react_components/simpleMenu.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx, src/BloomExe/Book/BookSelection.cs, src/BloomExe/CollectionTab/LibraryBookView.cs, src/BloomExe/TeamCollection/BookRepoChangeEventArgs.cs, src/BloomExe/TeamCollection/BookStatusChangeEventArgs.cs, src/BloomExe/TeamCollection/NewBookEventArgs.cs, src/BloomExe/TeamCollection/RepoChangeEventArgs.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/Workspace/WorkspaceView.cs
* fix Edit button active on TC conflict
* major refactor of collection preview edit/make button
* pulled selectedBookStatus hook up to collection tab
* added key to simpleMenu rows
* remove unused usings
* fire selection changed event on noticing remote change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4663)
=> BL-10270 Fix notification of book status change

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayToolColorHelper.ts, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomBrowserUI/problemDialog/theme.ts, src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/BasePublishScreen.tsx, src/BloomBrowserUI/react_components/link.tsx, src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, src/BloomBrowserUI/teamCollection/ForgetChangesDialog.tsx, src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx, src/BloomBrowserUI/utils/colorUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4680)
=> Bulk Publish requires Bloom enterprise (BL-10190)

DistFiles/localization/duplicateL10nKey.linq, DistFiles/localization/zh-CN/Bloom.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4695)
=> Add missing localization for Common.WhatsThis (BL-10190)

src/BloomExe/BloomExe.csproj, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs, src/BloomExe/Publish/Android/BulkBloomPubPublishSettings.cs, src/BloomExe/Publish/Android/PublishToAndroidApi.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4694)
=> Save BulkPublishBloomPubSettings (BL-10190)

src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4699)
=> Fix a pair of tests for Linux file separators (20210902)

src/BloomExe/Book/BookCompressor.cs, src/BloomTests/Book/BookCompressorTests.cs
* affects .bloomd and bloom packs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4698)
=> BL-8956 Add .tmp/.temp to excluded files

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/Book.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PageListView.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/BookTests.cs
* asks user for a number from 1-999
* duplicates selected page that many times
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4693)
=> BL-10339 Add Duplicate Many Pages

src/BloomExe/TeamCollection/FolderTeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4670)
=> Check for LAN sharing when checking Dropbox access (BL-10272)

src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx, src/BloomExe/BloomZipFile.cs, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4700)
=> Add save bloomBundle option to Bulk Publish (BL-10190)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Publish/Android/BulkBloomPubPublishSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4701)
=> Fix CollectionSettings unit tests (BL-10190)

DistFiles/localization/sw/Bloom.xlf, DistFiles/localization/sw/Palaso.xlf, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/checkStorySpec.js, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4703)
=> Merge from version5.0 to master 20210903

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, src/BloomBrowserUI/templates/template books/Paper Comic Book/Paper Comic Book.htm, src/BloomExe/Book/Book.cs
This PR consists of 2 commits. The first can probably be used as-is in 5.1, whereas the second will need modifying to use recent changes to the BE wrapper.
Therefore, after merging this, we'll need a null merge so this version doesn't get into 5.1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4706)
=> [5.0] BL-10334 Make Overlay Tool Enterprise-only

src/BloomExe/Book/Book.cs
* in Collection tab book preview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4704)
=> BL-10341 Hide image resolution message

src/BloomBrowserUI/react_components/requiresBloomEnterprise.less, src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, src/BloomBrowserUI/utils/WireUpWinform.tsx, src/BloomBrowserUI/utils/colorUtils.ts, src/BloomBrowserUI/webpack.common.js, src/BloomExe/BloomExe.csproj, src/BloomExe/CollectionTab/LibraryListView.cs, src/BloomExe/MiscUI/Enterprise.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4707)
=> Import/Export to Spreadsheet requires Bloom Enterprise (BL-10260)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/settings/Settings.pug, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/publish/stories.tsx, src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx, src/BloomBrowserUI/templates/template books/Digital Comic Book/Digital Comic Book.htm, src/BloomBrowserUI/templates/template books/Paper Comic Book/Paper Comic Book.htm, src/BloomExe/Book/Book.cs, src/BloomExe/MiscUI/ReactDialog.cs, src/BloomExe/Publish/Android/BulkBloomPubPublishSettings.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/Publish/PublishView.Designer.cs, src/BloomExe/Publish/PublishView.cs, src/BloomExe/Publish/PublishView.resx
2 commits
* 1st commit cherry-picked from 5.0
* 2nd commit makes the tool require B.E. and displays a message in
the Publish tab if publishing an overlay book w/ no B.E.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4711)
=> BL-10334 Overlay Tool requires Bloom Enterprise

debian/bloom-alpha.appdata.xml, debian/changelog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4718)
=> Update the Linux master branch package to 5.2 (20210915)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/CollectionTab/LibraryListView.Designer.cs, src/BloomExe/CollectionTab/LibraryListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4728)
=> Merge 5.1 to master - 20190917

build/getDependencies-Linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4730)
=> Update help to 5.1 in getDependencies-Linux.sh for Version5.1

src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4732)
=> Address jenkins failures with yarn timeout for Linux builds

src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4733)
=> Adjust Linux yarn setting to fix jenkins build failures (20210918)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx, src/BloomExe/BloomExe.csproj, src/BloomExe/Publish/Android/BulkBloomPubCreator.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Utils/BloomArchiveFile.cs, src/BloomExe/Utils/BloomTarArchive.cs, src/BloomExe/Utils/BloomZipFile.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Utils/BloomArchiveFileTests.cs, src/BloomTests/Utils/BloomTarArchiveTests.cs, src/BloomTests/Utils/BloomZipFileTests.cs, src/BloomTests/WebLibraryIntegration/ProblemBookUploaderTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4722)
=> Fix bloomBundles made by Bulk Publish (BL-10190)

src/BloomExe/Book/Book.cs
* only for 5.0, don't merge into 5.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4738)
=> [5.0-don't merge up!] BL-10334 Remove Overlay publish restriction

src/BloomExe/Edit/EditingView.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4739)
=> Include problem image in more error reports (BL-10310)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomBrowserUI/collection/enterpriseSettings.tsx, src/BloomExe/BloomFileLocator.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs
This allows new enterprise subscriptions to be used before the branding
files have been created and added to Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4721)
=> Show placeholder message for unimplemented branding (BL-10312)

src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This allows images larger than 25MB to be uploaded.  It also makes sense
for where it is listed for being part of the upload.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4741)
=> Include problem image in book zip file instead of issue (BL-10310)

src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4743)
=> Fix problem displaying books with unimplemented branding (BL-10312)

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4746)
=> Ensure bookshelf updates as needed after setting dialog (BL-10419)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/jquery.text-markup.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
Also remove highlighting when it no longer applies to a page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4748)
=> Highlight pages with too many sentences in leveled reader (BL-10447)

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/synphony_lib.js
Highlighting unknown words was broken for some choices of characters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4750)
=> Improve regular expression handling for decoding words (BL-10446)
