BloomBooks/BloomDesktop

src/BloomBrowserUI/react_components/colorChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4753)

Trim hex color value before using (BL-10190)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/CollectionCreating/NewCollectionWizard.Designer.cs
src/BloomExe/CollectionCreating/NewCollectionWizard.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4756)

Change "Project Name" to "Collection Name" in wizard (BL-10478)

---

src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4757)

Save latest edits before reporting error (BL-10480)

---

src/BloomBrowserUI/templates/template books/Digital Comic Book/ReadMe-en.md
src/BloomBrowserUI/templates/template books/Paper Comic Book/ReadMe-en.md

* reference Overlay tool
* update comments about setting playback order
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4759)

[5.1] BL-10412 Update Comic template instructions

---

src/BloomExe/web/controllers/SignLanguageApi.cs

* Use Invariant Culture where not part of UI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4761)

[5.1] BL-10465 Fix SL conversion in Swedish

---

DistFiles/localization/en/Publish-Android-Troubleshooting.xlf
src/BloomBrowserUI/help/Publish-Android-Troubleshooting-en.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4762)

BL-10433 Update Publish->USB troubleshooting doc

---

src/BloomExe/Edit/EditingModel.cs
src/BloomExe/web/controllers/CommonApi.cs
src/BloomExe/web/controllers/EditingViewApi.cs

The previous code was hanging on Linux whenever a copy was done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4763)

Use PortableClipboard for clipboard operations (BL-10469)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx

* Zip up -> Compress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4765)

BL-10506 Fix wording in bulk BloomPUB publish

---

DistFiles/ReleaseNotes.md

This is only a start / rough draft.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4760)

Update release notes for Bloom 5.1 (BL-10432)

---

src/BloomExe/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4781)

Switch from sentry.keyman.com to sentry.io (BL-10474)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/Program.cs
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4780)

Update libpalaso for fixed PortableClipboard (BL-10469)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/LibraryBookView.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4787)

BL-10526 Mismatch between instructions and error buttons

---

src/BloomExe/ProjectContext.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4794)

Tweak code to get around Linux compilation error (20211015)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4807)

Don't strip pages with overlay elements at publish time (BL-10586)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4811)

Fix error when changing to Title-On-Cover style (BL-10583)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4816)

Decodable Reader update parsed word list when letters change (BL-9993)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/WebLibraryIntegration/BookUpload.cs

This fix will be enhanced with UI in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4820)

Skip creating/uploading PDF if book has video (BL-10632)

---

src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/TeamCollection/BookHistory.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4827)

Add more history events (BL-10550)

---

src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4829)

Send zip file in problem report even without book (BL-10637)

---

src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4828)

Fix TCol history header alignment (BL-10652)

---

src/BloomBrowserUI/bloomMaterialUITheme.js
src/BloomBrowserUI/bloomWebFonts.less
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
src/BloomBrowserUI/problemDialog/theme.ts
src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx
src/BloomBrowserUI/react_components/confirmDialog.tsx
src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
src/BloomBrowserUI/react_components/stories.tsx
src/BloomBrowserUI/themes/bloom-jqueryui-theme/jquery-ui-1.8.16.custom.css
src/BloomBrowserUI/utils/bloomApi.ts
src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs

Also improved storybook to be able to call api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4831)

Fixes and improvements for font consistency

---

src/BloomBrowserUI/templates/xMatter/project-specific/Afghan-Children-Read-Pashto-Device-XMatter/Afghan-Children-Read-Pashto-Device-XMatter.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4845)

Fix a filename case problem (20211201)

---

src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4840)

Don't duplicate image data div nodes on import (BL-10499)

---

DistFiles/localization/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4847)

Update the Distfiles/localization/README.md instructions (20211201)

---

src/BloomExe/MiscUI/BloomFolderChooser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4848)

Comment out some Windows-only code on Linux with #if (20211202)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx
src/BloomExe/Book/Book.cs
src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

* update wording per Koen
* fix thumb top-alignment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4841)

BL-10507 ID Collision dialog

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomTests/Book/BookTestsBase.cs
src/BloomTests/CollectionTab/LibraryListViewTests.cs
src/BloomTests/web/controllers/ReadersApiTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4844)

Fix problems if book title contains period (BL-10520)

---

src/BloomExe/Utils/PerformanceMeasurement.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4834)

Handle failure to get performance counter (BL-10689)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/BookData.cs
src/BloomExe/CLI/SpreadsheetExportCommand.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Spreadsheet/Header.cs
src/BloomExe/Spreadsheet/HeaderRow.cs
src/BloomExe/Spreadsheet/InternalSpreadsheet.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/Spreadsheet/SpreadsheetIO.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomExe/Spreadsheet/SpreadsheetRow.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs
src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs
src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs
src/BloomTests/Spreadsheet/SpreadsheetTests.cs
src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4839)

Spreadsheet Export: Add second header row w/friendly names (BL-10363)

---

src/BloomExe/Spreadsheet/InternalSpreadsheet.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4859)

Don't hide cover image (BL-10750)

---

src/BloomExe/TeamCollection/FolderTeamCollection.cs
src/BloomExe/TeamCollection/TeamCollectionManager.cs

* regression involved the localNetwork code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4864)

BL-10704 recognize Disconnected repo state

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4866)

Add BookHistoryEventType.Renamed event for book title changes (BL-10550)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4867)

Fix tests broken by previous checkin (BL-10550)

---

src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/ToPalaso/DirectoryUtils.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/app.manifest

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4860)

Fix downloading a book with absurdly long image filename (BH-5988)

---

src/BloomExe/CLI/SpreadsheetImportCommand.cs
src/BloomExe/MiscUI/BrowserProgressDialog.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomExe/web/IBloomWebSocketServer.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs
src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs
src/BloomTests/web/WebSocketServerSpy.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4872)

Add progress dialog and messages for spreadsheet import (BL-10751)

---

src/BloomExe/FontProcessing/FontFileFinder.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4875)

Fix failing tests due to prior checkin (BL-10387)

---

src/BloomExe/Book/Book.cs
src/BloomExe/CollectionTab/LibraryListView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4873)

Fix redundant / confusing book rename events (BL-10550)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/CLI/UploadCommand.cs
src/BloomExe/Publish/Android/AndroidPublishSettings.cs
src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.resx
src/BloomExe/Publish/LangsToPublishSetting.cs
src/BloomExe/Resources/current-service-urls.json
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomExe/WebLibraryIntegration/BulkUploader.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4876)

Persist language settings when uploading (BL-10308)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomExe/web/controllers/BookCommandsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4881)

On import, make a backup as a .bloom in a temp folder (BL-10774)

---

src/BloomExe/CLI/CreateArtifactsCommand.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/web/controllers/BookCommandsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4879)

Enable harvester to create .bloom files (BL-10673)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4882)

Fix excessive URL encoding of the cover image filename (BL-10786)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CLI/CreateArtifactsCommand.cs
src/BloomExe/CollectionTab/LibraryListView.Designer.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/Utils/RobustZip.cs
src/BloomExe/web/controllers/BookCommandsApi.cs

This does not include changing the extension in TeamCollection
repositories.  That requires some more thinking and design to prevent
chaos when different team members have different versions of Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4884)

Rename .bloom files to .bloomSource files (BL-10673)

---

debian/rules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4890)

Update node to 16.3.1 for Bloom 5.2 Linux package build (20211220)

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4898)

Restrict Bulk Upload to Enterprise subscriptions (BL-10589)

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Palette.cs
src/BloomExe/Publish/Android/BulkBloomPubPublishSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4899)

Show hex color value in Bulk BloomPub dialog color popup (BL-10573)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4896)

Fix broken defaultLangStyles.css creation when it exists (BL-10821)

---

src/BloomBrowserUI/bookEdit/css/origami.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4901)

BL-9953 Fix origami rule precedence

---

src/BloomExe/TeamCollection/TeamCollectionApi.cs

* on Checkin we now check connection just after checkin
in case the Internet failed while checking in
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4900)

BL-10704 Undetected Disconnected state

---

src/BloomExe/FatalExceptionHandler.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4902)

Prevent gui error handling in harvester mode (BL-10540)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/CollectionTab/HistoryAndNotesDialog.cs
src/BloomExe/CollectionTab/LibraryListView.cs
src/BloomExe/CollectionTab/ReactCollectionTabView.cs
src/BloomExe/Publish/PDF/AdobeReaderControl.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/Workspace/TabStripRenderer.cs
src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4894)

Fix compile warnings

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/web/ReadersApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4907)

Add "All Usable Words" field to decodable reader report (BL-10544)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4909)

Update palaso nuget packages (needed for BL-10784)

---

src/BloomBrowserUI/bloomMaterialUITheme.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4916)

BL-10845 Fix theme color

---

src/BloomExe/Publish/Android/AndroidPublishSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4923)

BL-10840 Fix Harvester

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/Layout.cs
src/BloomExe/Book/SizeAndOrientation.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Publish/PublishView.cs

* there is still a Layout class, which I didn't change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4919)

BL-9636 Rename GetLayoutChoices

---

src/BloomBrowserUI/lib/split-pane/split-pane.js

* 2 commits; 1st is just a Prettier update, 2nd is actual change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4918)

BL-10593 Fix origami divider so it works when page is scaled

---

src/BloomBrowserUI/collectionsTab/spreadsheet/SpreadsheetExportDialog.tsx
src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx
src/BloomBrowserUI/react_components/experimentalBadge.tsx
src/BloomBrowserUI/utils/colorUtils.ts
src/BloomExe/Spreadsheet/SpreadsheetApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4932)

BL-10770 Spreadsheet export warnings

---

src/BloomExe/Book/Book.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

* checkbox will be disabled unless there is at least one image description
in the book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4926)

BL-10308 Persist 'Accessible to the Blind' setting

---

src/BloomExe/CollectionTab/LibraryListView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4936)

Fix problems when renaming / creating books (BL-10881)

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4937)

Include sign language in book upload comparison dlg (BL-10790)

---

src/BloomExe/Book/BookData.cs
src/BloomExe/CollectionTab/LibraryListView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4945)

Fix renaming books as well as changing titles (BL-10881)

---

src/BloomExe/Book/HtmlDom.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4947)

Fix failing unit tests (20220202)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/Program.cs
src/BloomExe/Spreadsheet/SpreadsheetApi.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/Spreadsheet/SpreadsheetIO.cs
src/BloomExe/Spreadsheet/SpreadsheetImportCommand.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs
src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs

* also removed some usings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4944)

BL-10884 Fix SS Importer to update side classes

---

build/getDependencies-Linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4954)

Try to debug Jenkins build failures since Jan 31 (trial 1)

---

build/getDependencies-Linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4955)

Try to debug Jenkins build failures since Jan 31 (trial 2)

---

build/getDependencies-Linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4956)

Try to debug Jenkins build failures since Jan 31 (trial 3)

---

build/getDependencies-Linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4957)

Try to debug Jenkins build failures since Jan 31 (trial 4)

---

debian/bloom-alpha.appdata.xml
debian/changelog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4960)

Update Linux packaging for Bloom 5.3 alpha (20220208)

---

src/BloomExe/Spreadsheet/SpreadsheetApi.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs
src/BloomTests/Spreadsheet/SpreadsheetImporterWithBookTests.cs
src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs

* cover image now gets copied
* after importing we bring the xmatter up-to-date and
save the book
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4949)

BL-10891 Get xmatter import working better

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4980)

Fix BL-10953 Double click on book does not open it

---

DistFiles/localization/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4982)

Update Crowdin merge instructions in localization/README.md (20220217)

---

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4984)

Fix CollectionSettings dialog crash (BL-10956)

---

build/getDependencies-windows.sh
debian/control
src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/MiscUI/BloomIntegrityDialog.cs
src/BloomTests/ImageProcessing/ImageUtilsTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4983)

Remove optipng from Bloom installation (BL-9378)

---

src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4991)

Stop ignoring "Show Experimental Book Sources" setting (BL-10963)

---

src/BloomExe/CollectionTab/LibraryModel.cs
src/BloomExe/web/controllers/BookCommandsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4990)

Update TitleBestForUserDisplay -> NameBestForUserDisplay (BL-10960)

---

DistFiles/ReleaseNotes.md
src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomBrowserUI/collectionsTab/bookSelectionManager.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4995)

Merge from Version5.2 to master - 20220222

---

src/BloomExe/FontProcessing/FontFileFinder.cs
src/BloomExe/FontProcessing/FontMetadata.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4999)

Fix broken Linux build (20220225)

---

src/SquirrelInstaller/Bloom.nuspec

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5001)

Remove nunit related DLLs from installer (BL-10848)

---

src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5003)

Fix background colors in collection settings dialog (BL-10973)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx
src/BloomBrowserUI/react_components/fontDisplayBar.tsx

* fix font control spacing
* get font control to look like the size control
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5004)

BL-10388 new Font UI tweaks

---

DistFiles/ffmpeg/BuildingFfmpeg.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5005)

Update ffmpeg instructions

---

debian/rules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5007)

Stop packaging NUnit on linux (BL-10848)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/react_components/fontInformationPane.tsx
src/BloomExe/FontProcessing/FontMetadata.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5013)

BL-10388 Font UI - better version handling

---

src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5012)

Tweak spacing for Sources For New Books book buttons (BL-10994)

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5014)

Remove borders around BookButton elements (BL-10994)

---

src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx
src/BloomBrowserUI/react_components/fontDisplayBar.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5016)

BL-10388 add delay to font information popover

---

src/BloomExe/Book/Book.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Publish/PublishHelper.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5006)

Improve page removal messaging in BR preview and blorg publish (BL-9954)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5035)

Fix CC-BY License problems if the license was once CC0 (BL-11032)

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomExe/web/controllers/AppApi.cs

* also fixed a wrong l10nId on BookButton
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5034)

BL-10944 Fix Spreadsheet menu item bug

---

src/BloomExe/app.config
src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs
src/BloomTests/app.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5038)

Fix failing unit tests for Version5.2 (20220316)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5040)

Merge from version5.2 20220316

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomExe/CollectionTab/CollectionTabView.Designer.cs
src/BloomExe/CollectionTab/CollectionTabView.cs
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5039)

Move "Make Bloom Pack" menu item to collection menu (BL-10365)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Publish/Video/RecordVideoWindowTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5044)

Publish to video: Use YouTube recommended sizes (BL-10992)

---

src/BloomBrowserUI/react_components/localizableMenuItem.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5047)

Fix menu font family and size (BL-11039)

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5056)

BL-11020 restore book thumb tooltips

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomTests/Publish/Video/RecordVideoWindowTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5053)

Publish to video: Cap YouTube sizes at 1080p HD max (BL-10991,10992)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Publish/Android/BloomPubMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5061)

BL-10318 tweak bad font message

---

src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomTests/Publish/BloomReaderPublishTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5063)

Fix failing BRPublish tests

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/Publish/Video/Resolution.cs
src/BloomExe/TempFiles.cs
src/BloomTests/Publish/Video/RecordVideoWindowTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5062)

Publish to video: Flip video if screen size insufficient (BL-10992)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5065)

Publish to video: mp3 settings (BL-10992)

---

src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx

Because the C# code ignores this value anyway
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5066)

Publish to mp3: disable no-narration delay slider if mp3 (BL-10991)

---

src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx
src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5067)

Normalize background colors in settings dlg tab (BL-11074)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Publish/PublishView.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5069)

Change "Video" to "Audio or Video" for publishing (BL-11067)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightAndLicenseDialog.tsx
src/BloomBrowserUI/bookEdit/copyrightAndLicense/LicensePanel.tsx
src/BloomBrowserUI/bookEdit/copyrightAndLicense/stories.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5072)

Reference "image" rather than "book" as appropriate (BL-6259)

---

src/BloomBrowserUI/react_components/colorPickerDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5077)

Click outside color picker saves choice (BL-9930)

---

src/BloomExe/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5078)

Fix BL-11004 Cannot rename collection 

---

src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx
src/BloomExe/Spreadsheet/SpreadsheetApi.cs
src/BloomExe/TeamCollection/BookHistory.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5079)

BL-10771 Create a History event on spreadsheet import

---

src/BloomBrowserUI/bookEdit/copyrightAndLicense/LicensePanel.tsx
src/BloomBrowserUI/bookEdit/js/bloomImages.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5080)

Fix two issues with the Copyright/License dialog (BL-6259)

---

src/BloomBrowserUI/publish/commonPublish/PublishProgressDialogInner.tsx
src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx
src/BloomBrowserUI/publish/video/VideoOptionsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5082)

Clean-up, mostly console warnings

---

src/BloomBrowserUI/react_components/bloomButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5083)

Clean up console errors from BloomButton

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx
src/BloomBrowserUI/bookEdit/StyleEditor/stories.tsx
src/BloomBrowserUI/react_components/fontDisplayBar.tsx
src/BloomBrowserUI/react_components/fontInformationPane.tsx
src/BloomExe/FontProcessing/FontMetadata.cs
src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Publish/PublishHelper.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomTests/Publish/BloomReaderPublishTests.cs

Also distinguish between font license problem and font format problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5085)

Check font metadata consistently for upload and ePUB (BL-10389)

---

src/BloomTests/Publish/BloomReaderPublishTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5092)

Fix a broken unit test (20220407)

---

src/BloomExe/ErrorReporter/ErrorReportUtils.cs
src/BloomExe/ErrorReporter/HtmlErrorReporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5094)

Fix null reference exception in HtmlErrorReporter

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less
src/BloomBrowserUI/bookEdit/StyleEditor/fontSelectComponent.tsx
src/BloomBrowserUI/bookEdit/StyleEditor/stories.tsx
src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx
src/BloomBrowserUI/collection/commonTabSettings.ts
src/BloomBrowserUI/collection/enterpriseSettings.less
src/BloomBrowserUI/collection/enterpriseSettings.tsx
src/BloomBrowserUI/collection/fontScriptSettingsControl.tsx
src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx
src/BloomBrowserUI/react_components/formsSelect.tsx
src/BloomBrowserUI/react_components/pageNumberStyleControl.tsx
src/BloomBrowserUI/react_components/singleFontSection.tsx
src/BloomBrowserUI/react_components/stories.tsx
src/BloomBrowserUI/react_components/winFormsStyleSelect.tsx
src/BloomBrowserUI/react_components/xmatterChooserControl.tsx
src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.less
src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx
src/BloomBrowserUI/webpack.common.js
src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/web/ReactControl.cs
src/BloomExe/web/controllers/CollectionSettingsApi.cs

* get font list popover over Style Editor
* fix scrolling tab panes
* all controls exist in React now
* finish off UI parts
* get api calls working
* unfortunate need for Segoe font to get bold
* get Select to work
* clean out unused stuff in CollectionSettingsDialog
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5087)

BL-10974 Replace Book Making tab w/React

---

src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5104)

Fix failing tests introduced by css cleanup (BL-11109)

---

src/BloomExe/web/BloomWebSocketServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5109)

Improve attempt to send on a closed/closing web socket (BL-11124)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
src/BloomExe/Program.cs
src/BloomExe/Utils/MiscUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5111)

Prevent users from trying to open from inside zip file (BL-11115)

---

src/BloomExe/XmlHtmlConverter.cs
src/BloomTests/XmlHtmlConverterTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5112)

Remove extraneous BOMs introduced by hand-editing (BL-11127)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomLowPriority.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5114)

Move string from Bloom.xlf to BloomLowPriority.xlf (BL-11115)

---

src/BloomExe/XmlHtmlConverter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5115)

Fix some failing tests with empty html content (20220418)

---

src/BloomExe/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5118)

Fix build failure for method which had moved (20220419)

---

src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5110)

MP3 option only enabled if book has narration (BL-10991)

---

src/BloomExe/web/BloomWebSocketServer.cs
src/BloomExe/web/CommandAvailabilityPublisher.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5121)

Make sure socket is available before sending on it (BL-11124)

---

src/BloomBrowserUI/bookEdit/TopicChooser/topicChooser.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5122)

Revert topic chooser font to Segoe UI (BL-11154)

---

src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5126)

Fix broken Linux build due to filename capitalization (20220425)

---

build/getDependencies-Linux.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5128)

Update Linux getDependencies script for 5.2 pins (20220425)

---

src/BloomExe/MiscUI/ToastNotifier.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5129)

Make toasts always on top (BL-10537)

---

src/BloomExe/NonFatalProblem.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5130)

Fix upload collision dialog help button (BL-11130)

---

src/BloomExe/MiscUI/ToastNotifier.cs
src/BloomExe/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5131)

Make toasts on top without losing focus (BL-10537)

---

src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx
src/BloomExe/CollectionTab/CollectionTabView.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs
src/BloomExe/TeamCollection/TeamCollectionManager.cs

* the specific case is checking out a book just after the
connection goes bad
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5133)

BL-11059 Detect Disconnected state in Status panel

---

environ
src/LinuxBloomLauncher/BloomLauncher.c
src/LinuxBloomLauncher/LinuxBloomLauncher.cproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5137)

Fix LinuxBloomLauncher and environ for gtk3 and system mono (BL-11168)

---

src/BloomExe/Book/Book.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs
src/BloomTests/TeamCollection/TeamCollectionApiTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5136)

Fix TeamCollectionApi test

---

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5139)

BL-9961 Enable multi-paragraph paste from Notepad

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/MiscUI/BrowserProgressDialog.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5134)

Show progress dialog while audio/video is processing (BL-11136)

---

src/BloomExe/Publish/Android/PublishToAndroidApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5144)

Remove another source of failed web socket messages

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5156)

Update L10NSharp to remove progress dialogs (BL-11157)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/ErrorReporter/CompositeErrorReporter.cs
src/BloomExe/ErrorReporter/ErrorReportUtils.cs
src/BloomExe/ErrorReporter/HtmlErrorReporter.cs
src/BloomExe/ErrorReporter/SentryErrorReporter.cs
src/BloomExe/Linux/packages.config
src/BloomExe/Program.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/packages.config
src/BloomExe/web/controllers/ProblemReportApi.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5145)

Implement new IErrorReporter interface from libpalaso 9.0.0-beta0167

---

src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5160)

[5.2] BL-11135 Fix Collection Settings error saving page

---

environ-xulrunner

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5162)

Improve environ-xulrunner script for Linux (20220519)

---

src/BloomExe/Linux/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5164)

Fix broken Linux build by updating palaso packages (20220523)

---

src/BloomBrowserUI/utils/WireUpWinform.tsx
src/BloomExe/web/ReactControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5165)

Prevent Shell from losing focus on collection change (BL-11092)

---

.gitignore
src/BloomBrowserUI/gulpfile.js
src/content/package.json
src/content/templates/template books/Activity/tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5166)

Fix missing simpleComprehensionQuiz.js (BL-11221)

---

DistFiles/localization/en/Bloom.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/4714)

Clarify confusing localization

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/MiscUI/BrowserProgressDialog.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/WebSocketProgress.cs

and hide cancel button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5182)

Provide estimate of time remaining during video creation (BL-11136)

---

src/BloomBrowserUI/bloomMaterialUITheme.ts
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx
src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5207)

Fix BL-11287 transparency and overlay of Enterprise warning

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/PublishSettings.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomTests/Publish/Video/RecordVideoWindowTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5206)

Publish to video: Suggest filename based on language chooser (BL-11081)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomLowPriority.xlf
src/BloomBrowserUI/bookEdit/copyrightAndLicense/LicensePanel.tsx
src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomExe/Publish/PublishView.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs

Copyright/license dialog and record video feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5204)

Finalize i18n for 5.3 (BL-11178)

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomBrowserUI/utils/isLinux.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5212)

Publishing "Audio or Video" is unavailable on Linux (BL-11011)

---

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5213)

[5.2] BL-11291 Fix dropdown arrow regression

---

src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/Publish/Android/file/FilePublisher.cs
src/BloomExe/Publish/Epub/PublishEpubApi.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomExe/web/controllers/CommonApi.cs

…
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5215)

Fix glitches in preventing exporting to Bloom collection folders (BL-11188)

---

src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5219)

[5.3] BL-6259 Fix up Publishing as SIL link color

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Publish/PublishView.Designer.cs
src/BloomExe/Publish/PublishView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5222)

Update publish button tooltips (BL-11297)

---

src/BloomExe/Publish/PublishView.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5223)

Change publish tooltip background gradient (BL-11297)

---

src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx
src/BloomBrowserUI/bookEdit/toolbox/toolIds.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5218)

Fix SL placeholder click handler often not working (BL-11279)

---

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5224)

Fix a broken link for "Publishing to Bloom Reader" (BL-11049)

---

src/BloomBrowserUI/templates/xMatter/bloom-xmatter-mixins.pug
src/BloomBrowserUI/templates/xMatter/project-specific/ABC-Reader-XMatter/ABC-Reader-common.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5228)

Fix duplicate cover bottom branding for ABC (BL-11323)

---

src/BloomExe/web/controllers/BookCommandsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5234)

Revert to using book folder for exporting to Word (BL-11314)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBHelpGroup.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5232)

Adjust help links on publish tab tasks (BL-11049)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5235)

A lighter approach to removing unwanted `fullBleed` from Kyrgyzstan2020

---

src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5244)

Don't show "More" menu item unless it has sub-items (BL-11341)

---

src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/bookEdit/js/bloomImages.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5240)

Fix image url retrieval for C/L dialog (BL-11336)

---

src/BloomExe/web/BloomServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5247)

Fix BL-11319

---

src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5243)

Fix book download while closed not launched (BL-11340)

---

src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5241)

Improve UI for license restrictions on publishing (BL-11328)

---

src/BloomExe/Collection/ScriptSettingsDialog.cs
src/BloomExe/MiscUI/BrowserProgressDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5252)

Cherry picks from5.3 20220621

---

src/BloomBrowserUI/.eslintrc.js
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
src/BloomBrowserUI/bookEdit/copyrightAndLicense/LicensePanel.tsx
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
src/BloomBrowserUI/bookEdit/toolbox/music/musicToolControls.tsx
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.io.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerTools.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx

"unexpected lexical declaration in case block"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5264)

Fix some easy eslint warnings

---

src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomExe/web/controllers/CommonApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5260)

Save "Export to Word" content as separate folder (BL-11335)

---

src/BloomBrowserUI/.eslintrc.js
src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
src/BloomBrowserUI/custom.d.ts
src/BloomBrowserUI/performance/PerformanceLogPage.tsx
src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx
src/BloomBrowserUI/react_components/l10nComponents.tsx
src/BloomBrowserUI/react_components/markdown.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5271)

Eslint warnings "no-empty-interface" and "no-var-requires"

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx

* BloomPUB Viewer
* link to Related Software on blorg Downloads page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5273)

BL-11257 tweaks

---

src/BloomBrowserUI/package.json
src/BloomBrowserUI/yarn.lock

The commit will be blocked if eslint returns any linting errors on TypeScript files. (warnings won't matter though). (.d.ts files are ignored too)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5275)

Check eslint before committing

---

src/BloomBrowserUI/publish/ReaderPublish/LanguageSelectionSettingsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5278)

BL-11257 Fix Option Panel layout in BloomPUB

---

src/BloomBrowserUI/publish/LibraryPublish/LoginDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5283)

Stop pointing at next.bloomlibrary.org

---

src/BloomBrowserUI/publish/video/AudioVideoOptionsGroup.tsx
src/BloomBrowserUI/publish/video/IFormatDimensionsResponseEntry.ts
src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/Video/FormatDimensionsResponseEntry.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/Publish/Video/Resolution.cs
src/BloomExe/Utils/NumUtils.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Publish/Video/ResolutionTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5284)

Make Publish to Audio/Video tooltips dynamic (BL-10992)

---

debian/bloom-alpha.appdata.xml
debian/changelog

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5286)

Update the version to 5.4 for debian package on master (20220707)

---

src/BloomExe/MiscUI/BloomFolderChooser.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5285)

Use BloomFolderChooser for selecting team collection folder (BL-11166)

---

src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomTests/Publish/PublishModelTests.cs
src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5288)

Stop removing css style rules for L2 and L3 (BL-11357)

---

src/BloomTests/BloomTests.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5290)

Fix failing Release build (only on Linux?) (20220711)

---

src/BloomExe/CollectionTab/CollectionTabView.Designer.cs

The program was hanging forever at the end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5299)

Fix broken harvester (CLI) processing (BH-6238 etc)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5308)

Fix broken build on Linux (20220727)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/app.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/app.config
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5310)

Update libpalaso in Bloom to 10.0.0-beta0081 (20220728)

---

debian/bloom.appdata.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5320)

Update bloom.appdata.xml to work with flatpak and debian (20220804)

---

src/BloomBrowserUI/react_components/colorChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5322)

Close color chooser when losing focus or typing Escape (BL-11404)

---

src/BloomBrowserUI/bookEdit/css/editMode.less
src/content/bookLayout/basePage.less
src/content/bookLayout/common-mixins.less
src/content/templates/template books/Digital Comic Book/common-comics.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5325)

Remove editMode.less dependency on basePage.less

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5324)

Convert align left/right to start/end instead (BL-11400)

---

src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug

* from a native speaker
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5327)

[5.3] BL-11273 Updated Spanish text from Bruce

---

src/content/templates/template books/Activity/simple-dom-choice-activities.less

* simple-dom-choice-activities (especially landscape)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5326)

BL-11418 Better Activity layout

---

debian/rules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5328)

Fix failing Linux debian package build on master (5.4) (20220809)

---

debian/bloom-beta.appdata.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5329)

Merge from5.2 to5.3 20220809

---

debian/bloom-alpha.appdata.xml
src/BloomExe/Book/SizeAndOrientation.cs
src/content/branding/MXB-Book-Literacy/branding.json
src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/MXBLiteracy-Device-XMatter.less
src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/MXBLiteracy-Device-XMatter.pug
src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/description-en.txt
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.less
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.pug
src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/MXBScripture-Device-XMatter.less
src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/MXBScripture-Device-XMatter.pug
src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/description-en.txt
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5330)

Merge from 5.3 to master - 20220809

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5331)

Never exclude required language for upload (BL-11417)

---

src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/MXBLiteracy-Device-XMatter.pug
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.pug
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.pug
src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/MXBScripture-Device-XMatter.pug
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5332)

[5.3] BL-11273 Fix MXB XMatter device page ordering

---

src/BloomBrowserUI/publish/ReaderPublish/ThumbnailGroup.tsx
src/BloomBrowserUI/utils/bloomApi.ts
src/BloomExe/Publish/Android/PublishToAndroidApi.cs

Another related issue is that the background color in the preview is often outdated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5333)

Fix changing background color causing error (BL-11403)

---

src/BloomExe/web/BloomServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5339)

Ignore requests for "/host/fonts/" (BL-11388)

---

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/ExperimentalFeatures.cs
src/BloomExe/IBrowser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5340)

Allow switching between Geckofx and WebView2 browsers (BL-11362)

---

src/BloomBrowserUI/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5341)

Require active Node LTS version or higher (BL-11342)

---

src/BloomExe/Publish/Epub/EpubMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5338)

Order audio files properly for ePUB concatenation (BL-9016)

---

src/BloomExe/web/controllers/EditingViewApi.cs
src/BloomTests/web/BloomServerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5342)

BL-11159 Fix Topic tests

---

src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/IBrowser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5346)

Allow Linux build in presence of WebView2 work (20220817)

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/FontProcessing/FontsApi.cs
src/BloomExe/GeckoFxBrowser.cs
src/BloomExe/IBrowser.cs
src/BloomExe/MiscUI/LanguageFontDetails.cs
src/BloomExe/WebView2Browser.cs
src/BloomExe/XmlHtmlConverter.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5345)

Minor cleanup for WebView2 (BL-11362)

---

src/BloomExe/Publish/AudioProcessor.cs
src/BloomExe/Publish/Epub/EpubMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5343)

Warn user better about ePUB audio merge problems (BL-11435)

---

src/content/templates/template books/Activity/simple-dom-choice-activities.less

* get bloom-player output to match edit better
* and BloomPUB Viewer too
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5347)

BL-11418 better simple activity layout

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.less
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.pug
src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayToolColorHelper.ts
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
src/BloomBrowserUI/react_components/colorPickerDialog.less
src/BloomBrowserUI/react_components/colorPickerDialog.tsx
src/BloomBrowserUI/react_components/colorSwatch.tsx

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5319)

Add color chooser to style dialog (BL-7859)

---

src/content/templates/template books/Activity/simple-dom-choice-activities.less

* get image then words pages looking better
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5350)

BL-11418 Simple Activity

---

src/BloomBrowserUI/bookEdit/pageThumbnailList/PageThumbnail.tsx
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
src/BloomExe/Edit/PageListView.cs
src/BloomExe/Edit/WebThumbNailList.cs
src/BloomExe/GeckoFxBrowser.cs
src/BloomExe/IBrowser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5353)

Get page list using WebView2

---

src/content/branding/ABC-BARMM/branding.json
src/content/branding/ABC-RegionV/branding.json
src/content/branding/ABC-RegionVI/branding.json

* Credits page text changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5355)

BL-11436 ABC Branding update

---

src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx

Gives https://i.imgur.com/s0kbg6C.png
* remove the background of the title
* remove fix sizing of the dialog
* make everything grow as needed with localizations
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5369)

Tweak Topic Chooser

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomLowPriority.xlf
src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx
src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx
src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx
src/BloomBrowserUI/react_components/color-picking/stories.tsx

* use new dialog
* small UI change approved by JH
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5367)

BL-11432 switch BR bookshelf color picker

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5376)

Prevent premature closing of Styles dialog due to color chooser (BL-7859)

---

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5377)

Fix inserting overlay text and caption boxes (BL-11508)

---

src/BloomExe/Publish/AudioProcessor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5378)

Don't allow import of .wav files for music (BL-11481)

---

src/BloomExe/Utils/MiscUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5379)

Never think the Downloads folder is a collection folder (BL-11444)

---

src/BloomExe/Edit/EditingView.cs
src/BloomExe/GeckoFxBrowser.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/IBrowser.cs
src/BloomExe/Publish/PDF/PdfViewer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5375)

Fix Linux build problems related to WebView2 work (20220906)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Publish/Epub/PublishEpubApi.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/ToPalaso/FontAnalytics.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomExe/web/UrlLookup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5380)

Report simplistic font analytics for upload, save pdf, print pdf, save ePUB, and any kind of make bloomPUB

---

src/BloomExe/ProjectContext.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5383)

BL-11484 Prevent moving collection directory while Bloom is running

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5382)

Disable "Import Recording" when overall tool is disabled (BL-11327)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5387)

Fix glitch in picture page not importing audio (BL-11327)

---

src/BloomExe/Publish/AudioProcessor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5388)

Fix epub creation when successfully converting audio files (BL-11435)

---

src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx
src/BloomBrowserUI/publish/metadata/BookMetadataDialog.tsx
src/BloomBrowserUI/publish/stories.tsx
src/BloomExe/Publish/Epub/PublishEpubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5386)

Manual refresh of ePUB publish screen instead of automatic (BL-11043)

---

src/BloomBrowserUI/react_components/muiCheckBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5391)

Make checkbox label grey when checkbox disabled (BL-11491)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5392)

List sign language first on book cover (BL-11414)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5396)

Insert sign language name only if needed for book (BL-11414)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5390)

Clean up obsolete files/folders when uploading (BL-7616)

---

src/BloomExe/Edit/Configurator.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5397)

Fix HTML conversion for wall calendar configuration (BL-11529)

---

src/BloomExe/Publish/Epub/EpubMaker.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomExe/Utils/MiscUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5398)

Fix broken linux build 20220920

---

src/BloomExe/Book/Book.cs

* other than our built-in templates
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5403)

BL-11490 Preserve cover color of Sources

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.less
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
src/BloomBrowserUI/typings/jasmine/jasmine.d.ts
src/BloomBrowserUI/utils/testHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5395)

Disable highlight of multiple spaces (BL-11485) 

---

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5409)

Collapse multiple whitespace in source bubbles (BL-11501)

---

build/Bloom.proj
src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
src/BloomTests/WebLibraryIntegration/BloomParseClientTests.cs
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5408)

Prevent unit tests from attempting to load firebase dialog

---

src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx
src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx
src/BloomBrowserUI/react_components/color-picking/hexColorInput.tsx

* make the actual Bloom picker look closer to the design mockup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5407)

BL-11492 sizing tweaks

---

src/BloomBrowserUI/react_components/color-picking/bloomSketchPicker.tsx
src/BloomBrowserUI/react_components/color-picking/colorPicker.tsx
src/BloomBrowserUI/react_components/color-picking/stories.tsx

* add Alpha percentage tooltip
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5404)

BL-11492 Color Picker tweaks

---

src/content/branding/Kyrgyzstan2020/summary.htm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5414)

Fix broken icon in Enterprise Settings tab (BL-11543)

---

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5417)

Assign bubble outline colors only to actual bubbles (BL-11480)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/js/pageDragToolbox.js
src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5420)

Clarify language tag variable names in typescript (BL-9854)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/CLI/HydrateBookCommand.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/CollectionCreating/NewCollectionWizard.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Publish/Android/PublishToAndroidApi.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomTests/Book/BookCollectionTests.cs
src/BloomTests/Book/BookCopyrightAndLicenseTests.cs
src/BloomTests/Book/BookStarterTests.cs
src/BloomTests/Book/BookStorageTests.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/BookTestsBase.cs
src/BloomTests/Book/TestBook.cs
src/BloomTests/Book/TranslationGroupManagerTests.cs
src/BloomTests/Collection/CollectionSettingsTests.cs
src/BloomTests/Edit/ConfiguratorTest.cs

This is the second stage of fixing C# code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5422)

Fix lang tag names in Bloom.Collection.CollectionSettings (BL-9854:3)

---

src/BloomExe/Book/AccessibilityCheckers.cs
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/BookStarter.cs
src/BloomExe/Book/RuntimeInformationInjector.cs
src/BloomExe/Book/TranslationGroupManager.cs
src/BloomExe/Book/XMatterHelper.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomExe/web/I18NApi.cs
src/BloomExe/web/controllers/CommonApi.cs
src/BloomTests/Book/AccessibilityCheckersTests.cs
src/BloomTests/Book/BookDataTests.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs

This is the third stage of fixing C# code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5424)

Fix lang tag names in Bloom.Book files (BL-9854:4)

---

src/BloomExe/CLI/GetUsedFontsCommand.cs
src/BloomExe/CLI/HydrateBookCommand.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/WritingSystem.cs
src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs
src/BloomExe/CollectionCreating/LanguageIdControl.Designer.cs
src/BloomExe/CollectionCreating/LanguageIdControl.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/LanguageSettings.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/SHRP_PupilBookExtension.cs
src/BloomExe/Publish/SHRP_TeachersGuideExtension.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/ToPalaso/LanguageLookupModelExtensions.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/I18NApi.cs
src/BloomExe/web/ReadersApi.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomExe/web/controllers/EditingViewApi.cs
src/BloomExe/web/controllers/ProblemReportApi.cs
src/BloomTests/CLI/HydrateBookCommandTests.cs
src/BloomTests/Collection/CollectionSettingsTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5426)

Fix remaining language tag names (BL-9854:5)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

* removed unused variable
* a few small refactorings too
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5428)

BL-11238 Fix orphan Styles dropdown

---

src/BloomBrowserUI/bloomWebFonts.less
src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5427)

Fix Roboto normal displaying bolder than it should (BL-11170)

---

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5436)

Adjust test for "isBubble" to cover child bubbles properly (BL-11480)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5441)

Use current color when creating a new style (BL-11531)

---

src/content/templates/template books/Activity/simple-dom-choice-activities.less

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5444)

Change picture background to transparent for simple choice quiz (BL-11557)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Book/WidgetHelper.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/web/controllers/EditingViewApi.cs
src/BloomTests/BloomTests.csproj
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/WidgetHelperTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5443)

Copy widget files when copying page between books (BL-11200)

---

src/BloomExe/CLI/UploadCommand.cs
src/BloomExe/WebLibraryIntegration/BulkUploader.cs

Also added an initialization step needed for the upload command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5446)

Fix upload command to work when collection changes language (BL-10330)

---

src/BloomExe/Book/BookStorage.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5447)

Ignore HTML files whose name starts with a period (BL-11415)

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordable.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5439)

Ensure new text is handled for talking book tool (BL-11522)

---

src/BloomExe/Linux/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5449)

Bring Linux packages.config up to date with Windows (20221006)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightPanel.tsx
src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBHelpGroup.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
src/BloomBrowserUI/react_components/BloomDialog/commonDialogComponents.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5457)

Add links and warnings for ePUB (BL-11570)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/CLI/CreateArtifactsCommand.cs
src/BloomExe/CLI/SendFontAnalyticsCommand.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/Android/BloomPubMaker.cs
src/BloomExe/Publish/PublishHelper.cs
src/BloomExe/ToPalaso/FontAnalytics.cs

This includes the programming work for BL-11512.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5458)

Write a minimal set of font analytics when harvesting a book (BL-11512)

---

src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/GeckoFxBrowser.cs
src/BloomExe/IBrowser.cs
src/BloomExe/Program.cs
src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5473)

Hide wv2 UI from real users (BL-11622)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookSelection.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5472)

Fix basic book preview not working (BL-11625)

---

src/BloomExe/ImageProcessing/ImageUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5461)

Fix a problem when pasting an image (BL-11558)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
src/BloomBrowserUI/pageChooser/page-chooser.ts
src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx
src/BloomExe/Book/Page.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/ToolboxToolState.cs
src/BloomExe/web/controllers/AddOrChangePageApi.cs
src/content/templates/template books/Decodable Reader/Decodable Reader.pug
src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm
src/content/templates/template books/Leveled Reader/Leveled Reader.pug
src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm
src/content/templates/template books/Sign Language/Sign Language.pug
src/content/templates/template books/standard-page-mixins.pug

* add data-tool-id attribute to template pages that require
a particular tool
* add comments explaining things called by RunJavascript
* delete some unused code
* adding "Comic" pages activate Overlay Tool
* adding Sign Language pages activate Sign Language Tool
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5471)

[5.3] BL-11560 Add page activates required Tool

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/js/bubbleManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5477)

Select new image/video boxes when dropped from overlay tool (BL-11620)

---

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5479)

Fix cursor when adding image and video overlays (BL-11647)

---

src/BloomExe/ImageProcessing/ImageUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5485)

BL-11643 Fix temp image file problem

---

src/BloomExe/CLI/CreateArtifactsCommand.cs
src/BloomExe/CLI/SendFontAnalyticsCommand.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5492)

Tweak harvester font analytics to trim unwanted items (BL-11512)

---

src/BloomExe/MiscUI/ToastNotifier.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5497)

Fix toast location when taskbar is top or left (BL-11677)

---

src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5499)

Don't crash while selecting book on startup (BL-11678)

---

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts

* handle image on image case
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5508)

[5.4] BL-11621 Fix overlay bug

---

src/BloomBrowserUI/react_components/Progress/progressBox.tsx
src/BloomExe/web/controllers/AccessibilityCheckApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5511)

Restore seeing Ace by DAISY install instructions (BL-11696)

---

src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
src/BloomExe/web/controllers/AccessibilityCheckApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5512)

Reduce noise in Ace by DAISY error handling (BL-11696)

---

src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx
src/BloomBrowserUI/react_components/Progress/progressBox.tsx
src/BloomExe/web/controllers/AccessibilityCheckApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5513)

Bl 11696 cherry pick from master

---

src/BloomExe/Book/BookStorage.cs
src/BloomTests/Book/BookStarterTests.cs
src/BloomTests/Book/BookStorageTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5498)

Create unique folder/file names without parentheses (BL-11663)

---

src/BloomExe/Edit/EditingView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5514)

BL-11709 Fix image pasting problem

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5515)

Fix bulk upload for Linux (BL-11716)

---

src/BloomExe/Utils/LongPathAware.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5520)

Make Bloom.Utils.LongPathAware methods safe for Linux (BL-11721)

---

src/BloomExe/Book/BookData.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5518)

Safely remove inserted BOM after span.bloom-linebreak (BL-11717)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Book/BookInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5521)

Extend fix for titles with linebreaks (BL-11717)

---

src/BloomBrowserUI/bloomUI.less
src/BloomBrowserUI/bookEdit/js/bubbleManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5505)

Fix resize handles missing/broken (BL-11684)

---

src/BloomBrowserUI/.vscode/settings.json
src/BloomBrowserUI/lib/split-pane/split-pane.js
src/BloomExe/web/controllers/EditingViewApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5523)

Handle splitters which have never moved (BL-11724)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomExe/Edit/EditingModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5529)

BL-11746 Tweak some Edit mode links

---

src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx

* small refactor
* boost z-index of Imp. Visualizer canvas if its for an image
overlaying another image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5527)

[5.4] BL-11731 Fix Impairment Visualizer bug

---

src/BloomExe/CollectionTab/CollectionModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5532)

Bl 11741 include audio in bloom pack

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5533)

[5.4] BL-11733 Update color button with new style

---

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
src/content/bookLayout/bubble.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5531)

Disable resize pointer if Ctrl key pressed (BL-11748)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5534)

[5.4] BL-11700 Update link on Publish to BloomPUB

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/Collection/WritingSystem.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

* After merging, we can try updating Harvester to see if it works there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5545)

BL-11754 Follow-up to remembering Custom SL name

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

The previous fix was necessary but not sufficient when running an installed Bloom.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5546)

Finish fixing bulk upload for Linux (BL-11716)

---

src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

This is a cherry-pick from Version5.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5550)

Finish fixing bulk upload for Linux (20221116)

---

src/BloomExe/BookThumbNailer.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5554)

Fix two more image transparency problems (BL-11708)

---

src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx

Note that this change is on the Version5.3 branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5556)

Update a document link to Team Collection Introduction (BL-11805)

---

src/BloomExe/Publish/PublishModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5555)

USB errors no longer terminate SavePdf (BL-11788)

---

src/BloomExe/Book/SizeAndOrientation.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5558)

Don't report "missing" customBookStyles.css (BL-11544)

---

src/BloomBrowserUI/lib/jquery.qtip.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5561)

Fix left-to-right source bubbles (BL-7477)

---

src/BloomExe/Book/BookInfo.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomTests/TeamCollection/TeamCollectionTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5562)

Safeguards and reporting problems reading meta.json from TC (BL-11821)

---

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5564)

Fix image overlay button clicks not firing (BL-11765)

---

src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5568)

BL-11761 Always show Bloom Pack command

---

src/BloomBrowserUI/app/selectedBook.ts
src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/pageChooser/page-chooser.ts
src/BloomExe/Book/Book.cs
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/SourceCollectionsList.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/controllers/AddOrChangePageApi.cs

* In TheOneEditableCollection, a template can now be
used to create a new book
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5570)

BL-11760 Make new book using Template

---

src/BloomExe/Edit/EditingView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5567)

Fix crashing from rapid zooming with WebView2 (BL-11530)

---

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
src/content/bookLayout/bubble.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomdesktop/5544)

Fix a few resize handle problems (BL-11738)

---

src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5585)

Prevent double-click from editing TC book not checked out (BL-11865)

---

src/BloomBrowserUI/lib/split-pane/split-pane.js
src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomBrowserUI/react_components/RadioGroup.tsx

* split-pane.js isn't our code so I just made eslint be quiet
* the other 2 files BloomApi refs were in comments
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5598)

Missed a couple of BloomApi spots

---

src/WebView2PdfMaker/WebView2PdfComponent.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5602)

Tweak WebView2PdfMaker initialization code (BL-11437)

---

src/BloomBrowserUI/bookEdit/js/BloomHintBubbles.ts
src/content/templates/Sample Shells/A Family Learns about Immunisations/A Family Learns about Immunisations.htm
src/content/templates/Sample Shells/The Moon and the Cap/The Moon and the Cap.htm
src/content/templates/xMatter/bloom-xmatter-mixins.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5601)

Remove javascript being embedded in book html (BL-11879)

---

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/BloomTests/PdfMakerTests.cs
src/WebView2PdfMaker/ConversionHost.cs
src/WebView2PdfMaker/Program.cs
src/WebView2PdfMaker/WebView2PdfComponent.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5604)

Add debugging output for BloomPdfMaker program

---

src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This seems to help locally with the PDF tests running in VS 2022.

Update the NUnit3TestAdapter package to the latest version (BL-11437)

---

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.less
src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.less
src/BloomBrowserUI/bookEdit/toolbox/motion/motion.less
src/BloomBrowserUI/bookEdit/toolbox/music/music.less
src/BloomBrowserUI/bookEdit/toolbox/overlay/overlay.less
src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5606)

Fix toolbox icons

---

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx
src/BloomBrowserUI/utils/bloomApi.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5603)

Show image info tooltip only when no bubbles selected (BL-11738)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/app.config
src/BloomExe/packages.config
src/WebView2PdfMaker/WebView2PdfMaker.csproj
src/WebView2PdfMaker/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5609)

Update WebView2 to latest stable release (20230131)

---

src/BloomExe/Publish/PDF/PdfMaker.cs
src/BloomExe/Publish/PublishModel.cs
src/WebView2PdfMaker/WebView2PdfComponent.cs
src/content/bookLayout/basePage.less
src/content/bookLayout/device.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5608)

More work on PDF publishing (BL-11437)

---

src/BloomBrowserUI/react_components/localizableMenuItem.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5618)

Fix font weight for LocalizableMenuItems (BL-11858)

---

src/content/templates/template books/Wall Calendar/wallCalendar.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5619)

Fix BL-11537 WV2 calendar is taller on the page

---

src/content/branding/PNG-AUS-PIE/branding.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5621)

Adjust back page for PNG-PIE branding (BL-11914)

---

build/Bloom.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5617)

Output Squirrel log on error

---

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/react_components/bookProblem.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5622)

Fix incorrect paths to Attention.svg (BL-11923)

---

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs

Don't error out if in dry run mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5623)

Fix Bulk Uploader dry-run mode

---

src/BloomExe/CLI/UploadCommand.cs
src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5626)

Bulk Upload: dry-run as a flag instead of a destination

---

src/BloomExe/Book/TranslationGroupManager.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5627)

Handle hidden English for data-book="smallCoverCredits" (BL-11869)

---

src/BloomExe/WebLibraryIntegration/BookUpload.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5628)

Fix unit tests related to IsDryRun

---

src/BloomBrowserUI/patches/loader-utils+2.0.0.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5631)

Patch loader-utils to workaround node18/storybook issue (BL-11930)

---

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/BloomExe/Publish/PDF/PdfMaker.cs
src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs
src/BloomExe/Publish/PublishModel.cs
src/WebView2PdfMaker/WebView2PdfComponent.cs
src/content/bookLayout/basePage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5620)

Tweak PDF output for full bleed pages (BL-11437)

---

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx
src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx

* add button to AddPage dialog
* use more basic version of the Mui button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5633)

BL-11539 Add Close button

---

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5638)

Further simplify publish screen layout (BL-11820)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5639)

Don't let the browser focus the translation group (BL-11922)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5640)

Improvement for translation group focus issue (BL-11922)

---

src/BloomBrowserUI/bookEdit/css/editMode.less

* "Needs Copyright" button
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5645)

[5.4] BL-11941 Make button use UI font

---

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/BloomExe/Publish/PDF/PdfMaker.cs
src/BloomExe/Publish/PublishModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5647)

Add metadata to the PDF files produced by Bloom (BL-11437)

---

src/BloomExe/Book/XMatterHelper.cs
src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
src/BloomExe/Spreadsheet/SpreadsheetIO.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs

Also handle images being reused without new copies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5642)

Handle unnumbered content pages for Spreadsheet export (BL-11924)

---

src/BloomExe/Edit/Configurator.cs
src/BloomTests/Edit/ConfiguratorTest.cs

This looks safe enough for 5.4 to me.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5651)

Allow quotes in month/date names (BL-11943)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx
src/BloomExe/BloomExe.csproj
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs
src/BloomExe/web/controllers/LibraryPublishApi_Obsolete.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5649)

New upload screen: display book info and set summary (BL-11581)

---

src/content/templates/template books/Activity/simple-dom-choice-activities.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5643)

[5.4] BL-11915 Improve alignment of activity text

---

src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5652)

Warn about audio in video before starting to show the video (BL-11947)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5656)

New upload screen: finish localization of what is done so far (BL-11581)

---

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx
src/BloomBrowserUI/pageChooser/PageThumbnail.tsx
src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx

* count the template books as they return their pages to
determine when to scroll
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5655)

further work on Add Page dialog

---

src/BloomBrowserUI/lib/long-press/jquery.longpress.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5666)

BL-11962 Fix invalid longpress problem

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomExe/Publish/PublishView.Designer.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/Publish/PublishView.resx

* removed old PDF Options
* added Choose a PDF option initial screen
* might need better disabled Print/Save buttons
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5662)

BL-11954 Publish Initial screen

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5667)

New upload screen: Make UI for title, etc. match final mockup (BL-11581)

---

src/BloomExe/Spreadsheet/SpreadsheetApi.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs
src/BloomExe/TeamCollection/BookHistory.cs
src/BloomExe/WebLibraryIntegration/BookDownload.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

* added message to "ImportSpreadsheet" history event
* added Bloom version to history events
* added book history to problem report
* moved AddEvent for import into Importer where it will
get recorded before any error reporting
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5669)

BL-11381 Book History improvements

---

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5672)

BL-11954 Make initial PDF screen more responsive

---

src/BloomExe/Program.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5680)

Move bulk upload into model (BL-11581)

---

src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/react_components/BloomDialog/BloomDialogPlumbing.tsx
src/BloomBrowserUI/react_components/confirmDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5676)

Bring ConfirmDialog up to our latest dialog standards

---

src/BloomExe/Publish/PublishView.Designer.cs

* this is for 5.4; previous changes mean we probably need
a different PR for 5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5686)

[5.4] BL-11956 Add affordance to Publish AV Radio

---

src/BloomExe/Publish/PublishView.Designer.cs

* version 5.5
* will need null merge after 5.4 PR is merged
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5687)

BL-11956 Add affordance to Publish AV Radio

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/bookEdit/editViewFrame.ts
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomBrowserUI/react_components/Progress/progressBox.tsx
src/BloomBrowserUI/react_components/bloomButton.tsx
src/BloomBrowserUI/react_components/bloomSplitButton.tsx
src/BloomBrowserUI/react_components/confirmDialog.tsx
src/BloomBrowserUI/react_components/l10nHooks.ts
src/BloomBrowserUI/react_components/localizableMenuItem.tsx
src/BloomBrowserUI/react_components/requiresBloomEnterprise.tsx
src/BloomBrowserUI/react_components/stories.tsx
src/BloomExe/Book/Book.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/web/WebProgressAdapter.cs
src/BloomExe/web/controllers/BrowserDialogApi.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5685)

Make Upload button work (BL-11581)

---

src/BloomBrowserUI/.yarnrc.yml
src/BloomBrowserUI/bookEdit/StyleEditor/AudioHilitePage.tsx
src/BloomBrowserUI/package.json
src/BloomBrowserUI/react_components/color-picking/bloomPalette.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5692)

Give Talking Book highlight background its own palette

---

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5693)

[5.4] BL-11992 Update to Front Cover L2 size

---

src/BloomExe/MiscUI/BloomMessageBox.cs
src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs

* and fix test failure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5695)

Make BloomMessageBox testable

---

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5699)

Restore phrase marker bars more reliably in talking book tool (BL-11632)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5696)

Enable uploadCollisionDlg for new upload screen (BL-11581)

---

src/BloomExe/Book/HtmlDom.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5702)

Fix broken Wall Calendar preview (BL-12001)

---

src/BloomExe/MiscUI/ToastNotifier.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5706)

Prevent crash in GoUpTimerTick same as in GoDownTimerTick

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomBrowserUI/package.json
src/BloomBrowserUI/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5708)

Ensure that thumbnails of new books are displayed (BL-12026)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5710)

Fix publish to video when OS user has a space (BL-12027)

---

src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5707)

Show Status pane for Team Collection dialog when disconnected (BL-12021)

---

src/BloomExe/Book/HtmlDom.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5712)

Merge from 5.3 to 5.4 - 20230320

---

src/BloomExe/Book/BookData.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5713)

Improve deficient error reporting exposed by bug report (BL-12020)

---

src/BloomBrowserUI/teamCollection/TeamCollectionSettingsPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5716)

Open TC link in external browser... even in wv2! (BL-12036)

---

src/BloomTests/Book/BookDataTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5715)

Remove extra code left in by mistake

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5717)

Allow users to add/remove collections as sources of books (BL-12011)

---

src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5727)

Don't ask server to localize user collection names

---

src/BloomExe/Publish/Android/AndroidPublishSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5728)

Fix harvester when audio languages are not initialized (BL-12039)

---

src/BloomExe/Book/BookData.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs

* had to update LangData cache
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5729)

BL-12020 Fix SL Publish error

---

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx

* keep the text and arrow up pointing at the Options
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5723)

BL-11954 Initial PDF screen

---

src/BloomExe/Book/Book.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomTests/Book/BookTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5732)

Include required languages when gathering "all languages" (BL-12039)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomBrowserUI/react_components/BloomToolTip.tsx
src/BloomExe/Shell.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5730)

Improve the user interaction for adding/removing book sources (BL-12011)

---

src/BloomExe/Spreadsheet/InternalSpreadsheet.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5739)

BL-12007 Update spreadsheet lang * comment

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomExe/BloomExe.csproj
src/BloomExe/Book/UserPrefs.cs
src/BloomExe/ProjectContext.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.Designer.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs
src/BloomExe/Shell.cs
src/BloomExe/WebLibraryIntegration/BloomLibraryAuthentication.cs
src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/controllers/CommonApi.cs
src/BloomExe/web/controllers/ExternalApi.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5740)

More tweaks to the new Web publish screen (BL-11581)

---

src/BloomBrowserUI/collectionsTab/BooksOfCollection.less
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5745)

Give book list opacity 20% when hovering over remove button (BL-12011)

---

src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Edit/EditingView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5746)

Update the toolbox text when changing UI language (BL-10430)

---

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5747)

Allow print settings banner to span across settings panel (BL-11953)

---

src/BloomExe/Book/Book.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5749)

Improve bulk upload ignoring already uploaded books (BL-10675)

---

src/BloomBrowserUI/publish/commonPublish/LanguageSelectionSettingsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5752)

Remove unnecessary scrollbars from language lists (BL-12095)

---

src/BloomBrowserUI/publish/commonPublish/PublishLanguagesGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5751)

Don't show Talking Book Languages when none available/enabled (BL-12100)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5753)

Move cover color to bottom of publish settings (BL-12102)

---

src/BloomExe/Book/Book.cs
src/BloomExe/web/controllers/PublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5757)

Don't offer xmatter-only languages for publication (BL-11581)

---

src/BloomExe/Book/Book.cs
src/BloomTests/Book/BookTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5756)

Don't let template hint text make language complete (BL-12109)

---

src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5759)

Default SL feature to true when SL set (BL-11582)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5767)

Don't enable upload button while canceling (BL-12110)

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/web/controllers/CollectionSettingsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5766)

Fix enterprise status initialization (BL-12122)

---

src/BloomBrowserUI/StartKarma Firefox.bat
src/BloomBrowserUI/karma.conf.js
src/BloomBrowserUI/package.json
src/BloomBrowserUI/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5772)

Remove Firefox from Test runner

---

src/BloomExe/web/controllers/PublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5773)

Default Motion feature to true after adding motion to book (BL-11581)

---

src/BloomBrowserUI/app/SelectedBookContext.tsx
src/BloomBrowserUI/app/selectedBook.ts
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx
src/BloomBrowserUI/react_components/BloomToolTip.tsx
src/BloomBrowserUI/react_components/MustBeCheckedOut.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5769)

Disable summary field if book is not checked out (BL-12124)

---

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.pug
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5778)

BL-12120 Remove L3 from Title page; MXB

---

build/Bloom.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5780)

Stop trying to sign an obsolete font install program (BL-11389)

---

DistFiles/localization/en/Bloom.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5784)

Add translator notes for PDF booklet help strings (BL-12127)

---

src/BloomExe/Program.cs
src/BloomExe/UpdateVersionTable.cs

Also make developing/debugging a bit more pleasant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5782)

Start splash screen sooner for installs to reassure users (BL-12085)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
src/BloomBrowserUI/react_components/BloomToolTip.tsx
src/BloomBrowserUI/react_components/MustBeCheckedOut.tsx
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5765)

Give links to fix missing info during Web publish (BL-12103)

---

src/BloomExe/Book/Book.cs
src/BloomExe/FontProcessing/FontServe.cs
src/BloomExe/FontProcessing/FontsApi.cs
src/BloomExe/web/BloomServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5786)

Fix a couple of bugs in serving Andika and other fonts (BL-11389)

---

src/BloomExe/Publish/PublishModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5789)

Ensure license URL and description exist in BloomPubs (BL-12132)

---

src/BloomExe/CollectionTab/CollectionModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5792)

Check network connection on delete only for team collections (BL-12024)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/Program.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5795)

Check WebView2 runtime availability and version on startup (BL-12049)

---

src/BloomExe/RobustIO.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5804)

Add file path to corrupt PNG file report (BL-12147)

---

src/content/bookLayout/basePage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5805)

Prevent scrollbars on user-made template page thumbnails (BL-11855)

---

src/BloomExe/Edit/EditingModel.cs
src/BloomExe/Publish/PublishHelper.cs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5806)

Don't complain about missing Andika New Basic. Just use Andika (BL-12148)

---

src/BloomExe/ProjectContext.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5812)

Stop making "source collections" automatic sources of books (BL-12084)

---

src/BloomExe/IBrowser.cs
src/BloomExe/Publish/PublishHelper.cs
src/BloomExe/WebView2Browser.cs
src/BloomExe/web/BloomApiHandler.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5798)

BL-11513 Get around WV2 1st ePUB build fail

---

src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/TeamCollection/TeamCollectionManager.cs
src/BloomExe/web/ReactControl.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5808)

Fix glitches in deleting books for disconnected TC (BL-12024)

---

build/getDependencies-windows.sh
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/PDF/PublishPdfApi.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.Designer.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomExe/WebLibraryIntegration/BulkUploader.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5785)

Remove as much cruft as possible from PublishView (BL-12126)

---

DistFiles/localization/en/BloomLowPriority.xlf
src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/RobustIO.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5811)

Handle getting metadata from corrupt image files better (BL-12147)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/IBrowser.cs
src/BloomExe/WebView2Browser.cs

Open edge when asked
Drop Linux-specific stuff
Drop the "Troubleshooting info" which isn't implemented and wasn't missed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5813)

BL-12166 Dev menu to edge

---

src/BloomBrowserUI/.eslintrc.js
src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx
src/BloomBrowserUI/react_components/Progress/stories.tsx
src/BloomExe/MiscUI/BrowserProgressDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5810)

Fix ProgressDialog not closing/opening properly (BL-12140)

---

src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5816)

BL-12116 Fix default method for bloomPUB

---

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/CollectionsTabBookPane.tsx
src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5825)

Handle disconnected state better in TC book status panel (BL-12154)

---

src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5822)

BL-12116 Found another PublishAndroid default

---

src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less
src/content/bookLayout/basePage.less

* Edit vs Publish -> PDF vs Collection tab Preview
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5827)

[5.4] BL-12163 Fix Title page mismatch

---

src/BloomExe/Edit/EditingView.cs
src/BloomExe/Edit/WebThumbNailList.cs
src/BloomExe/IBrowser.cs
src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5830)

Clean up context menu in wv2 (BL-12165)

---

src/BloomBrowserUI/bookEdit/css/editMode.less

* Edit mode > 100% scale
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5835)

BL-11640 Fix long-standing horizontal scroll bug

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5836)

BL-11582 Pub Features Activity Tooltip tweak

---

src/BloomExe/Spreadsheet/SpreadsheetExporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5837)

Check for URL-encoded src attributes in spreadsheet export (BL-12145)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/BookThumbNailer.cs
src/BloomExe/HtmlThumbNailer.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/Publish/Android/wifi/WiFiPublisher.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/ToPalaso/RobustImageIO.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/controllers/ProblemReportApi.cs
src/BloomTests/ImageProcessing/RuntimeImageProcessingTests.cs
src/BloomTests/PageEditingModelTests.cs

Also fix a few places to use Robust calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5832)

Use RetryUtility.Retry around uses of FileStream where needed (BL-12179)

---

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5842)

Stop PageChooserDialog from constantly rerendering (BL-11855)

---

src/BloomBrowserUI/lib/long-press/jquery.longpress.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5841)

Longpress: handle browser using \00a0 for spacebar (BL-12191)

---

src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5839)

Fix "Show another collection..." link underline (BL-12192)

---

src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5843)

Hide splash screen for selecting book: possible error dialog (BL-12155)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5844)

Prevent audio/video screen from creating zombie browsers (BL-12164)

---

src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5850)

BL-12182 Fix TC Sync Close button

---

src/BloomBrowserUI/react_components/Progress/ProgressDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5853)

BL-12182 Update comments

---

src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5855)

Don't report fonts used only for empty text nodes (BL-12204)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5856)

Detect and fix improper license changes (BL-11903)

---

src/BloomBrowserUI/package.json
src/BloomBrowserUI/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5862)

Update bloom-player to 2.1.28 (BL-12203)

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx
src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx
src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx
src/BloomBrowserUI/publish/commonPublish/PublishVisibilityGroup.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBSettingsGroup.tsx
src/BloomBrowserUI/react_components/ApiCheckbox.tsx
src/BloomBrowserUI/react_components/BloomCheckBox.stories.tsx
src/BloomExe/Book/BookInfo.cs
src/BloomExe/web/controllers/PublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5864)

Bl-11583 draft publishing

---

src/BloomExe/Utils/DropboxUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5866)

Enhance detecting an active Dropbox on Linux/flatpak (BL-12244)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Linux/packages.config
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5868)

Update libpalaso packages to get PalasoImage.FromFile fix (BL-12213)

---

src/BloomBrowserUI/bookEdit/css/editMode.less
src/content/templates/template books/Digital Comic Book/common-comics.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5863)

Fix "Just Text" boxes having a border outside of Editing (BL-12187)

---

src/BloomExe/Publish/PDF/PdfMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5881)

Fix excess PDF page problem with full-bleed book (BL-12231)

---

src/BloomTests/Collection/CollectionSettingsTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5879)

Fix test for changes to CollectionSettings.DefaultBookshelf (BL-12215)

---

src/BloomExe/web/BloomWebSocketServer.cs
src/BloomExe/web/IBloomWebSocketServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5878)

[5.5] BL-12245 Fix Web Socket error

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/Spreadsheet/SpreadsheetImporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5882)

Ensure truncated image filenames have only single spaces (BL-12261)

---

src/BloomTests/Book/BookStorageTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5890)

Fix a broken test of sanitized book file/folder names (BL-12261)

---

src/BloomExe/web/RequestInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5886)

[5.5] BL-12237 Fix for Endpoint handler error

---

src/BloomBrowserUI/publish/ReaderPublish/MethodChooser.tsx
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
src/BloomBrowserUI/publish/commonPublish/PublishProgressDialog.tsx
src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5876)

Publish BloomPUB handles cases where Preview is not pressed before publishing (BL-12241)

---

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5897)

Prevent double-clicking enterprise pages from inserting them (BL-12302)

---

src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx
src/BloomExe/Book/Book.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs

* Harvester thumbs and uploaded thumbs are stored in
different places.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5885)

[5.5] BL-12240 Fix broken thumbnail

---

src/BloomExe/TeamCollection/TeamCollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5893)

Allow link in error report dialog to open new issue (BL-12278)

---

src/BloomBrowserUI/publish/ReaderPublish/BulkBloomPub/BulkBloomPubDialog.tsx
src/BloomBrowserUI/react_components/helpLink.tsx

* fix scrolling of dialog
* fix layout of ConditionallyEnabledBlock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5884)

[5.5] BL-12249 Make All BloomPUBs dialog

---

src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5900)

Fix BL-12312 work around wv2 failure

---

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/BloomExe/WebView2Browser.cs
src/WebView2PdfMaker/Program.cs
src/WebView2PdfMaker/WebView2PdfComponent.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5902)

Let PDF maker use alternative WV2

---

src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5898)

Update ep plus for bloom tests

---

src/BloomBrowserUI/publish/commonPublish/PublishLanguagesGroup.tsx
src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookData.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomPub/BloomPubMaker.cs
src/BloomExe/Publish/BloomPub/BloomPubPublishSettings.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Publish/PublishModelTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5869)

Don't force publication of xmatter-only languages (BL-12254)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Edit/LameEncoder.cs
src/BloomExe/FontProcessing/FontMetadata.cs
src/BloomExe/HelpLauncher.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/AudioProcessor.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/ToPalaso/CommandLineRunnerExtra.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/controllers/AccessibilityCheckApi.cs
src/BloomExe/web/controllers/AudioSegmentationApi.cs
src/BloomExe/web/controllers/CollectionApi.cs
src/BloomExe/web/controllers/CommonApi.cs
src/BloomExe/web/controllers/SignLanguageApi.cs
src/BloomTests/ToPalaso/ProgresDialogTests.cs

(The Help viewer should run in the normal user culture, but not programs that do file processing like ffmpeg, ghostscript, and GraphicsMagick.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5904)

Run external programs with invariant culture when appropriate (BL-12235)

---

src/BloomExe/Program.cs
src/BloomExe/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5907)

Keep the shell open to choose a collection to switch to (BL-12319)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5909)

Don't require copyright for templates (BL-12331)

---

src/BloomExe/web/controllers/LibraryPublishApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5910)

Prevent crash when uploading unlicensed content (BL-12335)

---

src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx
src/BloomExe/Publish/PDF/PublishPdfApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5911)

Restore license check for PDF publishing (BL-12332)

---

src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5912)

[5.4] BL-12047 Fix font-family bug

---

src/BloomExe/WebView2Browser.cs
src/BloomExe/web/controllers/ApiRequest.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5908)

Disable webview2 "status bar" messages (BL-12325)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5914)

[5.4] BL-12047 Fix bad font-family rule

---

src/BloomExe/Edit/EditingModel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5916)

Properly save the copyright/license from publish tab (BL-12346)

---

src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-Xmatter-common.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5920)

[5.4] BL-12047 Fix full-bleed cover image width

---

src/content/bookLayout/basePage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5921)

Fix overflow warning icon (BL-12311)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5905)

Add missing audio highlighting CSS rules for padded sentences (BL-12287)

---

src/BloomExe/web/BloomWebSocketServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5924)

Fix a glitch in reporting websocket connection errors

---

src/BloomExe/Registration/LicenseDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5923)

Clean up some LicenseDialog code (BL-12257)

---

src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5922)

Clean up extraneous wv2 setup call (BL-12257)

---

src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs
src/BloomExe/web/controllers/PublishApi.cs

* part 2 (BloomPUB)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5931)

BL-12333 Close unauthorized licensed content hole

---

src/BloomExe/ErrorReporter/HtmlErrorReporter.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5938)

Enhance fallback problem dialog for Report button/action (BL-12223)

---

src/content/bookLayout/basePage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5940)

Allow extremely long words to wrap/break themselves (BL-12330)

---

src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5941)

HandleThumbnailRequest gracefully fails if bookInfo is null (BL-12354)

---

src/BloomExe/Publish/Epub/PublishEpubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5937)

Enforce ePUB license checking for Save before Preview (BL-12334)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomExe/web/controllers/LibraryPublishApi.cs
src/BloomExe/web/controllers/PublishApi.cs
src/BloomTests/Book/BookTests.cs
src/BloomTests/Book/HtmlDomTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5945)

Fix issues with language publication settings (BL-12254, BL-12368)

---

src/BloomExe/Publish/Epub/PublishEpubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5948)

Ensure license error message seen when trying to save ePUB (BL-12334)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5942)

Handle pages without text in Toolbox.doWhenPageReady (BL-12381)

---

src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/Collection/WritingSystem.cs

This fix targets Version5.4.  It's very straightforward.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5949)

Buffer changes in language settings (BL-12371)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/utils/shared.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5953)

Refactor/optimize ckeditableSelector (BL-12381)

---

src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx
src/BloomExe/web/WebSocketProgress.cs
src/BloomExe/web/controllers/PublishApi.cs

* bloomPUB publishing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5952)

[5.5] BL-12333 Second try at unauthorized content pt 2

---

src/BloomBrowserUI/publish/commonPublish/PublishVisibilityGroup.tsx

BL-11583 fix draft icon and text alignment
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5957)

BL-11583 fix draft icon and text alignment

---

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs
src/BloomExe/web/controllers/CollectionSettingsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5958)

Merge from 5.4 to 5.5 - 20230626

---

src/BloomExe/Spreadsheet/MarkedUpText.cs
src/BloomExe/Spreadsheet/SpreadsheetIO.cs
src/BloomTests/Spreadsheet/SpreadsheetFormattingTests.cs
src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs
src/BloomTests/Spreadsheet/SpreadsheetTests.cs

Support color import from and export to spreadsheet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5930)

BL-12339 round-trip color in spreadsheet

---

src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5959)

Disable swipe gestures for navigation in WebView2 (BL-12405)

---

src/BloomExe/MiscUI/LanguageFontDetails.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5960)

Fix wording for line spacing checkbox (BL-12414)

---

LICENSE.txt
src/BloomBrowserUI/infoPages/aboutBox.htm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5963)

Update the "About Bloom" information (BL-12395)

---

src/BloomBrowserUI/collection/bookMakingSettingsControl.tsx
src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx
src/BloomBrowserUI/react_components/localizableMenuItem.tsx
src/BloomBrowserUI/react_components/pageNumberStyleControl.tsx
src/BloomBrowserUI/react_components/singleFontSection.tsx
src/BloomBrowserUI/react_components/xmatterChooserControl.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5965)

Standardize UI font for book-making settings, context menus (BL-12425)

---

src/BloomExe/Collection/BookCollection.cs
src/BloomExe/CollectionTab/CollectionTabView.cs

I'd guess / expect these changes will be useful things in 5.5 and onward too
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5966)

Prevent exceptions RE FileSystemWatcher from crashing app (BL-12398)

---

src/BloomBrowserUI/bookEdit/editablePage.ts
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxSpec.ts
src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5964)

Cleanup errant spaces from ckeditor (BL-12391)

---

src/BloomExe/web/IRequestInfo.cs
src/BloomExe/web/RequestInfo.cs
src/BloomExe/web/controllers/ApiRequest.cs
src/BloomExe/web/controllers/PageTemplatesApi.cs
src/BloomTests/PretendRequestInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5968)

Remove 10-second browser cache (BL-12440)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5967)

Fix ckeditor instances loop and add crossreference comment (BL-12426)

---

src/BloomExe/Book/BookData.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5971)

Fix "Level Letters" (BL-12447)

---

src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/ReaderSetup.pug

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5974)

[5.4] BL-12422 Remove SynPhony link in Reader setup

---

src/BloomExe/Program.cs
src/BloomExe/Shell.cs
src/BloomExe/Workspace/WorkspaceModel.cs
src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5975)

Make program exit after canceled Choose collection, quit (BL-12442)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5978)

CTRL+Space to toggle between invisibles and their emojis

---

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs
src/WebView2PdfMaker/WebView2PdfComponent.cs

* one-line addition to WV2 print settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5981)

BL-12450 PDF should print background colors

---

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5983)

Fix broken Collection Settings dialog Restart actions (BL-12371)

---

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5986)

Merge from 5.4 to 5.5 - 20230710

---

src/BloomBrowserUI/bookEdit/editablePage.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
src/BloomExe/Edit/WebThumbNailList.cs
src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5987)

Fix BL-12420, make the page thumbnail context menu close

---

src/BloomExe/ApplicationUpdateSupport.cs
src/BloomExe/Collection/CollectionSettingsDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5992)

BL-12489 Make 5.4 the end of the line for pre-win10

---

src/BloomExe/Book/BookInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5993)

Ignore UnauthorizedAccessException when fixing book ids (BL-12458)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5994)

More fixes for zero-width spaces (BL-12391, BL-12460)

---

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5970)

Ensure color character spans copy/paste between pages (BL-12434)

---

src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/ErrorReporter/HtmlErrorReporter.cs
src/BloomExe/ErrorReporter/NotifyUserOfProblemSettings.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5989)

[5.4] BL-12486 Add more User Info to YouTrack issues

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/Edit/EditingView.cs
src/BloomExe/FontProcessing/FontMetadata.cs
src/BloomExe/IBrowser.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
src/BloomExe/Publish/BloomPub/BulkBloomPubCreator.cs
src/BloomExe/Publish/PublishModel.cs
src/BloomExe/Publish/PublishView.cs
src/BloomExe/Publish/SHRP_PupilBookExtension.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/Shell.cs
src/BloomExe/Spreadsheet/SpreadsheetApi.cs
src/BloomExe/ToPalaso/ProcessExtra.cs
src/BloomExe/Utils/PerformanceMeasurement.cs
src/BloomExe/WebLibraryIntegration/BloomLibraryAuthentication.cs
src/BloomExe/WebView2Browser.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/ReadersApi.cs
src/BloomExe/web/controllers/AppApi.cs
src/BloomExe/web/controllers/BookCommandsApi.cs
src/BloomExe/web/controllers/CollectionApi.cs
src/BloomExe/web/controllers/ExternalLinkController.cs
src/BloomExe/web/controllers/FileIOApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5979)

Add ProcessExtra.SafeStartInFront() to foreground new programs (BL-12432)

---

src/BloomBrowserUI/bookEdit/css/editMode.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5997)

Ensure cursor appears for multiply highlighted text (BL-11633)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/BloomIntegrityChecker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5999)

BL-12506 5.5 localization changes

---

src/BloomBrowserUI/lib/ckeditor/config.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6003)

BL-12540 allow pasting of text formatted in small caps

---

src/BloomBrowserUI/.vscode/settings.json
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
src/BloomBrowserUI/bookEdit/js/editableDivUtilsSpec.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts
src/BloomBrowserUI/bookEdit/toolbox/readers/readerToolsModel.ts
src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6001)

Fix various issues with ckeditor and markup (BL-12391, BL-12460)

---

src/BloomExe/web/controllers/CollectionApi.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6002)

Fix error report to upload bad book, not previous selection (BL-12470)

---

src/BloomBrowserUI/bookEdit/css/editMode.less
src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6004)

bl-12448 prevent ckeditor flash

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6005)

Add the rest of the Help section to the new Web upload screen (BL-12415)

---

src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6006)

Fix Linux build error in Windows specific code (20230717)

---

src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/ToPalaso/ProcessExtra.cs
src/BloomExe/web/controllers/CommonApi.cs

1) search for filenames in titles of program windows 2) add method starting explorer with selected file 3) log debugging information to the log file for alpha/beta
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6015)

Improve handling of starting windows in front (BL-12432)

---

src/BloomExe/WebView2Browser.cs

* Sets an additional command line argument for WV2
* Unfortunately, users won't see the results of switching language in the
browser (e.g. decimal separators) until the program is
restarted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6016)

BL-12451 Get WV2 to respond to Bloom's UI language

---

src/BloomExe/Book/BookCompressor.cs
src/BloomExe/Utils/BloomZipFile.cs

* check by filetype when BookCompressor is making
.bloomPUB files.
* does not compress further files that are already
compressed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6021)

BL-12561 Avoid compressing some files

---

src/BloomExe/Publish/PublishHelper.cs

This greatly speeds up publishing for BloomPub and ePUB when using WebView2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6019)

Optimize javascript execution in RemoveUnwantedContent (BL-12402)

---

src/BloomExe/Book/BookData.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6027)

Preserve language location when harvester running (BL-12583)

---

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6028)

Don't remove xmatter pages with only L2 or L3 (BL-12592)

---

src/BloomExe/Book/BookData.cs

Reverts BloomBooks/BloomDesktop#6027 (invalid fix for the problem)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6033)

Revert "Preserve language location when harvester running (BL-12583)"

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

Chastened, intentionally  aiming only at master/5.6 this time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6034)

Robust delete of s3 client artifacts, round 2

---

src/BloomExe/ToPalaso/RobustIO.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6031)

Fix exception message to contain path (BL-12603)

---

src/BloomExe/Book/BookCompressor.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6032)

Prevent imposing transparency on non-greyscale PNG images (BL-12570)

---

src/BloomExe/TeamCollection/FolderTeamCollection.cs
src/BloomExe/Utils/DropboxUtils.cs

Note that this targets Version5.4.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6039)

Try to improve check for whether Dropbox is running (BL-12605)

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs

(also removed some unused code)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6037)

Upload sanitized collection settings for harvester use (BL-12583)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomLowPriority.xlf
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomBrowserUI/react_components/AutoUpdateSoftwareDialog.tsx
src/BloomBrowserUI/react_components/forumInvitationDialog.tsx
src/BloomBrowserUI/react_components/stories.tsx
src/BloomExe/Properties/Settings.Designer.cs
src/BloomExe/Properties/Settings.settings
src/BloomExe/WebView2Browser.cs
src/BloomExe/app.config
src/BloomExe/web/controllers/AppApi.cs

Show forum invitation dialog every two weeks, shortly after launch, until they click "How to Join".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6035)

BL-12410 forum invitation dialog

---

debian/control
debian/rules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6044)

Add explicit clean target to debian/rules (20230808)

---

debian/rules

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6045)

Another tweak to debian/rules (20230808)

---

DistFiles/localization/en/BloomLowPriority.xlf
src/BloomExe/WebLibraryIntegration/BookDownload.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6041)

[5.4] BL-12618 Add download logging

---

src/BloomExe/Book/Book.cs
src/BloomTests/Book/BookTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6036)

Don't let harvester break font synthesis (BL-12594)

---

src/BloomBrowserUI/collectionsTab/BookButton.tsx
src/BloomBrowserUI/collectionsTab/BooksOfCollection.less

* I thought it fixed the related Activity problem (BL-12598), but I wasn't testing with the right kind of Activity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6053)

BL-12597 Fix renaming layout problem

---

src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6054)

BL-12451 Redux

---

src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx
src/BloomExe/History/HistoryEvent.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6056)

BL-12613 add history events for tc checkout

---

src/BloomExe/WebLibraryIntegration/BookUpload.cs

* if upload is in Bulk mode, it will now update all features in a book before
uploading
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6047)

BL-12553 Update Features before bulk uploading

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
src/BloomBrowserUI/bookEdit/pageThumbnailList/pageThumbnailList.tsx
src/BloomExe/Edit/EditingModel.cs
src/BloomExe/web/controllers/CommonApi.cs

* switched test function to Ctrl+Alt+pageClick to activate
* brought some comments up-to-date
* got rid of some JQuery
* log event in log file, if it does get triggered
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6057)

[5.5] BL-12616 Page Selection Changing error

---

src/BloomExe/web/I18NApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6058)

Stop logging missing l10n errors

---

debian/bloom.appdata.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6059)

Trim version description to make flathub happy (20230817)

---

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6060)

remove a small bit of JQuery

---

build/Bloom.proj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6062)

Remove the git hash from the assembly version number (BL-12611)

---

src/BloomExe/BloomExe.csproj
src/BloomTests/BloomTests.csproj
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6064)

Update C# version number and add polyfill for missing classes (BL-12611)

---

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6066)

Allow BloomPUB creation if book folder has readerStyles.css (BL-12609)

---

src/BloomExe/BloomExe.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6070)

Restore file copying after build for BloomExe (BL-12639)

---

src/BloomBrowserUI/.vscode/settings.json
src/BloomBrowserUI/collection/CollectionSettingsDialog.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomExe/CollectionTab/CollectionTabView.Designer.cs
src/BloomExe/CollectionTab/CollectionTabView.cs
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/controllers/CommonApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6069)

Add new Collection Settings button and dialog (BL-12409)

---

src/BloomExe/BloomExe.csproj
src/BloomTests/BloomTests.csproj
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6071)

Change Company back to SIL in csproj files (BL-12611)

---

src/BloomExe/Book/Book.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6068)

Fix renaming books with Active Presenter activities (BL-12598)

---

src/BloomBrowserUI/collection/CollectionSettingsDialog.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomExe/web/controllers/CollectionSettingsApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6074)

Simplify CollectionSettingsDialog and fix error on launch (BL-12409)

---

src/BloomExe/Book/BookFileFilter.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs
src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs

* if the talking book language checkbox isn't checked,
or if the text in that language is not included, don't upload
the audio for that language.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6076)

BL-12642 Upload the right talking book audio

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6077)

Reinstate uploading the collection settings (BL-12583)

---

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6079)

Fix broken collection settings download (BL-12583)

---

DistFiles/localization/en/Bloom.xlf
src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx
src/BloomBrowserUI/booksOnBlorg/stories.tsx
src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
src/BloomBrowserUI/publish/stories.tsx
src/BloomBrowserUI/react_components/Progress/ProgressBar.tsx
src/BloomBrowserUI/react_components/Progress/stories.tsx
src/BloomExe/Collection/CollectionSettings.cs
src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
src/BloomExe/web/controllers/CollectionApi.cs
src/BloomExe/web/controllers/CollectionSettingsApi.cs
src/BloomExe/web/controllers/ProgressDialogApi.cs

* progress bar itself looks good
* now gets book counts from BL.org
* transition doesn't really work the way I'd like
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6065)

BL-12403 Books on Blorg progress bar

---

src/BloomExe/BloomExe.csproj
src/BloomExe/Program.cs
src/BloomExe/packages.config

https://github.com/BloomBooks/BloomDesktop/pull/6061 to 5.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6080)

[5.5] Send Analytics through blorg BL-12617 

---

src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx
src/BloomExe/web/controllers/CollectionSettingsApi.cs

* Books on Blorg
* Add tooltip link to blorg books in current language
* Fix "-1" problem
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6085)

BL-12403 Tweaks to Progress bar

---

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6081)

Fix inserting paragraphs for instruction pages (BL-12654)

---

src/BloomExe/Book/Book.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/TeamCollection/TeamCollectionMessageLog.cs
src/BloomExe/ToPalaso/RobustIO.cs
src/BloomExe/web/controllers/SignLanguageApi.cs
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6092)

Merge from version5.5 to master again 20230906

---

build/check-csharp-files.sh
src/BloomBrowserUI/package.json
src/BloomExe/Book/BookCompressor.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/ImageUpdater.cs
src/BloomExe/RobustFileIO.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/web/controllers/ImageApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6090)

Add git hook to check for non-Robust File operations (BL-12669)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6098)

Add analytics event for audio/video publication

---

src/BloomBrowserUI/webpack.common.js
src/BloomExe/Program.cs

* everything seems to work fine without this
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6094)

BL-12666 Remove outdated webpack rule

---

src/BloomExe/History/BookHistory.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6101)

Make book history more robust (BL-12669)

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/TeamCollection/FolderTeamCollection.cs
src/BloomExe/TeamCollection/TeamCollectionMessage.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6102)

[5.5] BL-12681 Link to docs about Dropbox

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomLowPriority.xlf
src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowSpec.ts
src/BloomBrowserUI/bookEdit/html/font-awesome/Readme.txt
src/BloomBrowserUI/bookEdit/toolbox/toolbox.less
src/BloomBrowserUI/lib/localizationManager/localizationManager.ts
src/BloomExe/Book/BookStorage.cs
src/BloomExe/Book/HtmlDom.cs
src/BloomExe/Program.cs
src/BloomExe/Publish/PublishView.Designer.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/Utils/PerformanceMeasurement.cs
src/BloomExe/WebView2Browser.cs
src/BloomExe/web/BloomServer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6082)

Clean up a few references to Firefox or Gecko (BL-12573)

---

src/BloomExe/TeamCollection/TeamCollection.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6105)

Improve Team Collection sync problem report (BL-12680)

---

src/BloomBrowserUI/react_components/forumInvitationDialog.tsx
src/BloomExe/Workspace/WorkspaceView.cs
src/BloomExe/web/controllers/AppApi.cs

This prevents the AutoUpdateDialog and ForumInvitationDialog from appearing at the same time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6072)

Use C# StartupScreenManager for React ForumInvitationDialog (BL-12410)

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6109)

Fix publishing to audio (BL-12706)

---

src/BloomExe/Utils/PerformanceMeasurement.cs

This targets Version5.5 (the beta).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6118)

Enhance performance measurement to include subprocess memory (BL-12158)

---

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx
src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6121)

Require book checkout in TC for publish cover color button (BL-12588)

---

src/BloomBrowserUI/teamCollection/TeamCollectionBookStatusPanel.tsx
src/BloomBrowserUI/teamCollection/statusPanelCommon.tsx
src/BloomBrowserUI/teamCollection/stories.tsx
src/BloomBrowserUI/teamCollection/teamCollectionApi.tsx
src/BloomExe/Registration/RegistrationDialog.cs
src/BloomExe/TeamCollection/BookStatus.cs
src/BloomExe/TeamCollection/TeamCollection.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs
src/BloomTests/TeamCollection/SyncAtStartupTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6063)

Fixes and improvements for Team Collection syncing (BL-12590)

---

src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6123)

Fix i18n bug in (relatively) new Add Pages dialog (BL-12572)

---

src/BloomExe/MiscUI/StartupScreenManager.cs
src/BloomExe/Workspace/WorkspaceView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6112)

Try to ensure forum invitation dialog is actually displayed (BL-12410)

---

src/BloomExe/Utils/RobustZip.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6108)

Avoid storing/restoring hidden files from zip archives (BL-12680)

---

src/BloomExe/web/controllers/CollectionApi.cs

* If we are displaying a sign language, use it to query
the number of books on blorg too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6125)

BL-12403 Books on Blorg Progress update

---

src/BloomExe/Utils/BloomArchiveFile.cs
src/BloomExe/Utils/BloomZipFile.cs

* just some unnecessary usings and a wording change
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6126)

BL-12689 Zip file CRC error logging

---

DistFiles/localization/en/Bloom.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6127)

Add l10n strings missing from Add Page dialog (BL-12572)

---

build/getDependencies-windows.sh
src/BloomExe/BloomExe.csproj
src/BloomExe/FileMeddlerManager.cs
src/BloomExe/Program.cs
src/BloomExe/Shell.Designer.cs
src/BloomExe/Shell.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6100)

Add File meddling for debugging (BL-12669)

---

src/BloomExe/web/controllers/AccessibilityCheckApi.cs

* I apparently don't have AbD installed. I thought I did.
But now Bloom correctly tells me it can't find it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6130)

[5.4] BL-12712 Ace by Daisy catastrophic failure

---

src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6135)

BL-12403 Progress bar tweak

---

src/BloomExe/Utils/BloomArchiveFile.cs
src/BloomExe/Utils/BloomZipFile.cs
src/BloomExe/Utils/RobustZip.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6134)

Cherry pick fixes from master for hidden files in zip archives (BL-12680)

---

src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx
src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6136)

Bl-12491 publish tab UI fixes

---

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6133)

[5.5] BL-12198 MXB XMatter tweaks

---

src/BloomBrowserUI/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6137)

Update bloom-player to fix video recording margin bug (BL-12729)

---

src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6139)

Fix l10n for Add Page selection descriptions (BL-12572)

---

src/BloomExe/Program.cs
src/BloomExe/WebView2Browser.cs
src/BloomExe/web/controllers/ProblemReportApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6141)

BL-12702 Add WebView2 version to error log

---

src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less

Hopefully our last 2 tweaks to this... Hah!
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6145)

[5.5] BL-12198 MXB 2 tweaks to Scripture xmatter

---

src/BloomExe/Edit/EditingView.cs
src/BloomExe/IBrowser.cs
src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.Designer.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/WebView2Browser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6138)

Record video full screen when appropriate (BL-12729)

---

src/BloomExe/IBrowser.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6147)

Add missing fix for ReplaceContextMenu (BL-12729)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/packages.config
src/BloomTests/BloomTests.csproj
src/BloomTests/packages.config
src/WebView2PdfMaker/WebView2PdfMaker.csproj
src/WebView2PdfMaker/packages.config

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6148)

Update Palaso libraries used by Bloom 5.5 (20231016)

---

src/BloomExe/Edit/EditingView.cs
src/BloomExe/IBrowser.cs
src/BloomExe/Publish/AccessibilityChecker/AccessibilityCheckWindow.Designer.cs
src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
src/BloomExe/Publish/Video/RecordVideoWindow.cs
src/BloomExe/WebView2Browser.cs
src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less
src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6149)

Merge version 5.5 to master 20231016

---

src/BloomExe/BloomExe.csproj
src/BloomTests/BloomTests.csproj
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6150)

Update the Palaso libraries on master (20231016)

---

src/BloomExe/CollectionTab/CollectionTabView.Designer.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6154)

Fix localization priority for (legacy) Settngs button (BL-12777)

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6156)

Finish initial minimal Book Settings dialog (BL-12130)

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6157)

Tweak capitalization of BloomPUBs in a user string (BL-12130)

---

src/BloomExe/Book/BookFileFilter.cs
src/BloomExe/Book/BookInfo.cs
src/BloomExe/Book/BookStorage.cs
src/BloomExe/CLI/DownloadBookCommand.cs
src/BloomExe/CollectionTab/CollectionModel.cs
src/BloomExe/Program.cs
src/BloomExe/WebLibraryIntegration/BloomLinkArgs.cs
src/BloomExe/WebLibraryIntegration/BloomS3Client.cs
src/BloomExe/WebLibraryIntegration/BookDownload.cs
src/BloomExe/WebLibraryIntegration/BookUpload.cs
src/BloomTests/Book/BookInfoTests.cs
src/BloomTests/WebLibraryIntegration/BloomLinkArgsTests.cs
src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6142)

Cleanup related to bookOrderUrl (BL-12568)

---

src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6158)

BL-12403 Progress spacing

---

src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx

Well that was an oops 🤦‍♀️
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6160)

BL-12491 publish tab unselected background color fix

---

src/BloomBrowserUI/bookEdit/toolbox/readers/libSynphony/bloomSynphonyExtensions.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6161)

Add a sentence final punctuation character for Khmer (BL-12757)

---

src/BloomExe/Book/BookStorage.cs
src/BloomExe/ImageProcessing/ImageUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6164)

Improve robustness replacing files (BL-12669)

---

src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx
src/BloomExe/Publish/PublishView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6166)

BL-12491 fix old publish tab content flashing when reentering tab

---

src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6165)

Prevent white bar displaying on focused publish tab button (BL-12791)

---

src/BloomExe/BloomExe.csproj
src/BloomExe/app.config
src/BloomTests/BloomTests.csproj
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6168)

Update libpalaso to get newly robustified methods (BL-12669)

---

src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx
src/BloomBrowserUI/teamCollection/teamCollectionApi.tsx
src/BloomExe/History/BookHistory.cs
src/BloomExe/TeamCollection/TeamCollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6163)

BL-12779 Minimal Check In All

---

src/BloomExe/Extensions.cs
src/BloomExe/Program.cs
src/BloomExe/Utils/MiscUtils.cs
src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6151)

Show Unicode codes in error messages with surrogate pairs (BL-12587)

---

src/BloomExe/Publish/PublishView.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6171)

BL-12491 fix publish tab initial white flash 

---

src/content/branding/Juarez-UNIDOS/branding.less

* some layouts were overflowing
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6172)

BL-12783 Juarez brand tweaks

---

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
src/BloomExe/Book/PublishSettings.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6174)

Set default published image maximum size to 1280x720 aka HD (BL-12803)

---

DistFiles/localization/en/Bloom.xlf
DistFiles/localization/en/BloomMediumPriority.xlf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6173)

Remove obsolete l10n strings

---

src/BloomExe/ImageProcessing/ImageUtils.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6179)

Don't delete image file when shrunk unless it's temporary (BL-12779)

---

src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6183)

Merge from5.5 to5.6 20231030

---

DistFiles/localization/en/Bloom.xlf
src/BloomExe/ImageProcessing/ImageUtils.cs
src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6184)

Update from 5.6 to master - 20231030

---

src/BloomExe/Command.cs
src/BloomExe/web/controllers/PageTemplatesApi.cs

* on change in book selection reset the most recent page
added
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6185)

[5.6] BL-12810 Reset AddPage dialog to default

---

src/BloomExe/Publish/Video/RecordVideoWindow.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6186)

Handle portrait orientation for fullscreen video recording (BL-12729)

---

src/BloomExe/Resources/current-service-urls.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6187)

Add missing entry for lastVersionForPreWindows10 url (BL-12467)

---

src/BloomExe/Edit/AudioRecording.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6188)

Make WAV to MP3 conversion more robust (BL-12801)

---

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6190)

Fix js error when calculating cog position (BL-12804)

---

src/BloomExe/web/controllers/CollectionApi.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6191)

BL-12825 copy list to fix collection was modified error

---

src/BloomExe/TeamCollection/FolderTeamCollection.cs
src/BloomExe/WebLibraryIntegration/BloomParseClient.cs

I can't test these changes locally, but they make sense for preventing useless internet accesses.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6194)

Check internet availabity for TC and Parse lookups (BL-12828)

---

DistFiles/localization/en/BloomMediumPriority.xlf
src/BloomBrowserUI/react_components/BookOnBlorgBadge.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6198)

BL-12786 harvesting badge text change and localization fix

---

src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx
src/BloomExe/web/BloomServer.cs
src/BloomTests/web/BloomServerTests.cs

* I actually found one in testing (see PublishTabPane)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6196)

BL-5482 Report case errors in local server requests

---

src/BloomExe/TeamCollection/TeamCollectionManager.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6197)

BL-11856 Make TC email match disregard case

---

src/BloomTests/web/BloomServerTests.cs

* I still do not really know why the build fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6199)

Fix broken build

---

src/content/bookLayout/basePage.less

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6200)

Fix page creeping for PDF output (BL-12834)

---

src/BloomExe/web/controllers/AudioSegmentationApi.cs

This presumably avoids file sync programs which should ignore files in the temp folder.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6204)

Make aeneas more robust by running in the temp folder (BL-12801)

---

src/BloomExe/web/controllers/PageTemplatesApi.cs

* for some unknown reason I had lowercased all the
template urls if we were on Windows!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6208)

BL-5482 Fix Add Page template handling

---

src/BloomExe/BloomExe.csproj
src/BloomTests/BloomTests.csproj
src/WebView2PdfMaker/WebView2PdfMaker.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6210)

Update libpalaso to fix Script&Variant dialog bug (BL-12373)
