BloomBooks/BloomDesktop

src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomTests/web/controllers/PageTemplatesApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6211)
=> BL-5482 casing fix

src/BloomTests/web/controllers/PageTemplatesApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6214)
=> BL-5482 Remove ignored test

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6212)
=> BL-11937 Clarify message about audio in video

src/content/bookLayout/basePage-sharedRules.less, src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6206)
=> BL-12805 Use text-wrap property

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6216)
=> BL-12162 Upload missing L1 to web gives warning

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomExe/Book/BookInfo.cs, src/BloomExe/CLI/UploadCommand.cs, src/BloomExe/Collection/BookCollection.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/AccessKeys.cs, src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookDownload.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomExe/WebLibraryIntegration/S3Extensions.cs, src/BloomExe/web/controllers/CollectionApi.cs, src/BloomExe/web/controllers/ExternalApi.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs, src/BloomTests/WebLibraryIntegration/BloomLibraryBookApiClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6162)
=> Upload books using an API (BL-12568)

src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6218)
=> BL-12805 Add title page title to balanced rule

src/BloomBrowserUI/collectionsTab/BookButton.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6220)
=> Don't allow right-click to double-click a book (BL-12820)

src/BloomExe/BloomExe.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6223)
=> Fix project file for SDK8 breaking change (20231115)

src/BloomExe/Book/BookInfo.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
Ready for review but depends on https://github.com/BloomBooks/bloom-azure-functions/pull/65
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6213)
=> Bl 12759 Hide parse create language behind API

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/WebLibraryIntegration/ProblemBookUploader.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6222)
=> Clean up S3 access (BL-12568)

src/BloomExe/WebLibraryIntegration/BookDownload.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6225)
=> Inform user if version is too old to download books (BL-12568)

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6227)
=> Fix "Duplicate page many times" when LR/DR tool open (BL-12876)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6228)
=> Fix timeout errors when calling API (BL-12568)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/web/controllers/CopyrightAndLicenseApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6219)
=> Handle pasting image file with bad metadata better (BL-11933)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6231)
=> Fix BL-12911 basePage-legacy-5-6.css is not getting into book folder

src/BloomExe/Book/HtmlDom.cs
(I think this will fix it, but it was very rare)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6233)
=> Fix BL-12919 Occasional Error removing links

src/content/bookLayout/basePage-legacy-5-6.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6230)
=> Fix BL-12918 cover titles in legacy mode

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6234)
=> Add Help link to an image error report dialog (BL-11911)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6238)
=> Make checking for book records report errors and add logging (BL-12921)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6236)
=> Allow for long-running actions (BL-12568)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6240)
=> Handle cancel during long-running action (BL-12568)

src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6241)
=> Preserve page numbers when changing page format (BL-12903)

src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6244)
=> Improve performance of new upload (BL-12568)

src/content/appearanceThemes/appearance-theme-default.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6235)
=> Update appearance-theme-default.css with all defaults (BL-12860)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6246)
=> Allow template upload (BL-12968)

src/BloomExe/Book/Book.cs, src/BloomTests/Book/BookTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6245)
=> Fix possible NullReferenceException in ElementIsInXmatter (BL-12938)

src/content/branding/RobotsMali/branding.json, src/content/branding/RobotsMali/branding.less, src/content/templates/xMatter/bloom-xmatter-mixins.pug
All I need a review on is the change to the pug file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6247)
=> Fix RobotsMali branding in bloom player

src/content/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/content/templates/xMatter/bloom-xmatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Common/Afghan-Children-Read-XMatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Dari-Device-XMatter/Afghan-Children-Read-Dari-Device-XMatter.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Pashto-Device-XMatter/Afghan-Children-Read-Pashto-Device-XMatter.pug
We preserve the split page for the Afghan Children Reading projects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6249)
=> Merge outside back cover back together for device xmatter (BL-12969)

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6250)
=> Fix failing unit tests related to changed Device xmatter (20240116)

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6255)
=> BL-12904 fix image description bubbles

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6258)
=> Cherrypick to 5.6 BL-12904 fix image description bubbles

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/content/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/content/templates/xMatter/bloom-xmatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Common/Afghan-Children-Read-XMatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Dari-Device-XMatter/Afghan-Children-Read-Dari-Device-XMatter.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Pashto-Device-XMatter/Afghan-Children-Read-Pashto-Device-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6261)
=> Cherry pick end page fix from master (BL-12969)

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/content/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/content/templates/xMatter/bloom-xmatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Common/Afghan-Children-Read-XMatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Dari-Device-XMatter/Afghan-Children-Read-Dari-Device-XMatter.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Pashto-Device-XMatter/Afghan-Children-Read-Pashto-Device-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6262)
=> Update harvester for End Page fix (BL-12969)

src/BloomTests/Publish/EpubValidAndAccessible.cs, src/BloomTests/Publish/ExportEpubTests.cs, src/content/templates/xMatter/Device-XMatter/Device-XMatter.pug, src/content/templates/xMatter/bloom-xmatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Common/Afghan-Children-Read-XMatter-mixins.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Dari-Device-XMatter/Afghan-Children-Read-Dari-Device-XMatter.pug, src/content/templates/xMatter/project-specific/Afghan-Children-Read-Pashto-Device-XMatter/Afghan-Children-Read-Pashto-Device-XMatter.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6263)
=> Update production harvester for end page fix (BL-12969)

src/BloomExe/Book/AppearanceMigrator.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/WebLibraryIntegration/BloomS3Client.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomTests/WebLibraryIntegration/BloomS3ClientTests.cs, src/BloomTests/WebLibraryIntegration/BloomS3StandardUpDownloadTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6252)
=> Change upload API - client sends files and hashes (BL-12568)

src/BloomExe/Collection/CollectionSettings.cs
Reverts BloomBooks/BloomDesktop#6273
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6274)
=> Revert "Keep language display names more consistent (BL-12992)"

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6275)
=> Make language names more consistent in different places (BL-12992)

src/BloomExe/Book/Book.cs, src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6278)
=> Merge from 5.6 to pick up language name fixes (BL-12992)

src/BloomExe/Book/Book.cs
A 5.7 regression
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6284)
=> BL-13016 fix the "title missing" ui

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less, src/content/templates/template books/Activity/Activity.pug, src/content/templates/template books/Arithmetic Template/ArithmeticTemplate.pug, src/content/templates/template books/Basic Book/Basic Book.pug, src/content/templates/template books/Big Book/Big Book.pug, src/content/templates/template books/Decodable Reader/Decodable Reader.pug, src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm, src/content/templates/template books/Leveled Reader/Leveled Reader.pug, src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm, src/content/templates/template books/Picture Dictionary/Picture Dictionary.pug, src/content/templates/template books/Sign Language/Sign Language.pug, src/content/templates/template books/Template Starter/Template Starter.pug, src/content/templates/template books/Wall Calendar/Wall Calendar.pug, src/content/templates/template books/preview-xmatter-mixins.pug, src/content/templates/template books/standard-page-mixins.pug, src/content/templates/xMatter/preview-xmatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6285)
=> Add minimal xmatter (front cover) to factory templates (BL-13030)

src/content/branding/Chetana-Trust/branding.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6281)
=> Tweak XMatter layout for Device16x9Landscape and Chetana (BL-13029)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/react_components/BookInfoIndicator.tsx, src/BloomExe/Book/AppearanceMigrator.cs, src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/controllers/BookSettingsApi.cs, src/BloomExe/web/controllers/IndicatorInfoApi.cs, src/content/appearanceMigrations/efl-ebook-1/appearance.json, src/content/appearanceMigrations/efl-ebook-1/customBookStyles.css, src/content/appearanceMigrations/efl-ebook-2/appearance.json, src/content/appearanceMigrations/efl-ebook-2/customBookStyles.css, src/content/appearanceMigrations/efl-ebook-3/appearance.json, src/content/appearanceMigrations/efl-ebook-3/customBookStyles.css, src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-efl-ebook-1.css, src/content/appearanceThemes/appearance-theme-efl-ebook-2.css, src/content/appearanceThemes/appearance-theme-efl-ebook-3.css, src/content/bookLayout/basePage.less, src/content/bookLayout/pageNumbers.less
Also fix a few bugs in the appearance migration code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6271)
=> Add an initial set of appearance migrations (BL-13021)

src/BloomExe/Utils/LongPathAware.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6253)
=> Don't throw if file doesn't exist in GetLongPath (BL-12986)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/react_components/BookInfoIndicator.tsx, src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/web/controllers/IndicatorInfoApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6290)
=> Internationalize BookSettingsDialog (BL-12957)

src/BloomBrowserUI/problemDialog/NotifyDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6293)
=> BL-12977 onedrive dialog adjust font

src/BloomExe/Book/AppearanceSettings.cs, src/content/appearanceMigrations/efl-ebook-1/appearance.json, src/content/appearanceMigrations/efl-ebook-2/appearance.json, src/content/appearanceThemes/appearance-theme-efl-narrow-margin-ebook.css, src/content/appearanceThemes/appearance-theme-efl-zero-margin-ebook.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6296)
=> Adjust handling page number hiding on migration to themes (BL-13069)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/web/controllers/BookCommandsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6303)
=> Bl-13058 include collection settings in .bloomSource files

src/BloomExe/Book/BookInfo.cs, src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomTests/Book/BookInfoTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6297)
=> Implement the new API design

src/BloomExe/Book/AppearanceSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6309)
=> Fix a crash after migrating from an EFL theme (BL-13057)

src/content/appearanceMigrations/little-zebra-1/appearance.json, src/content/appearanceMigrations/little-zebra-1/customBookStyles.css, src/content/appearanceMigrations/little-zebra-2/appearance.json, src/content/appearanceMigrations/little-zebra-2/customBookStyles.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6304)
=> Add migration for Little Zebra's custom A4, A5, and A6 CSS (BL-13062)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6311)
=> Add correct docs.blorg hrefs to BookSettingsDialog (BL-12956)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomExe/Book/AppearanceSettings.cs, src/content/appearanceMigrations/efl-ebook-1/appearance.json, src/content/appearanceMigrations/efl-ebook-2/appearance.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6310)
=> Add "Show Page Numbers" to Book Settings dialog (BL-13091)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/Book.cs, src/BloomExe/web/controllers/PublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6313)
=> BL-12038 remove warning of audio elements missing ids

src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6315)
=> Prevent calling audio Recorder.BeginMonitoring multiple times (BL-13003)

src/BloomExe/Book/AppearanceMigrator.cs, src/content/appearanceMigrations/little-zebra-2/appearance.json
This also fixes problems mentioned in testing BL-13062.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6316)
=> Fix migration errors related to Little Zebra custom CSS (BL-13104)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/content/bookLayout/pageNumbers.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6317)
=> Harden image buttons against overlaying page numbers (BL-13098)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6318)
=> BL-13067 Link to page theme catalog

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6314)
=> Allow focus in Format dialog when decodable reader is active (BL-13043)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/AppearanceSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6319)
=> Move legacy theme to end of menu choices (BL-13095)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6321)
=> Show hand cursor when clicking would delete custom CSS file (BL-13097)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomExe/web/controllers/CollectionSettingsApi.cs
Also disable "Show Written Language 3 Title" if languge 3 is not defined.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6320)
=> Show language names for written languages 2 and 3 (BL-13067)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6323)
=> Update config-r to fully disable disabled checkboxes (BL-13093)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6324)
=> Handle timing variation for fetching agreement status (BL-13117)

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6322)
=> BL-13103 fix prevent running multiple blooms at the same time

src/BloomExe/Utils/OneDriveUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6328)
=> BL-13133 narrow OneDrive error codes to prevent false positives

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6334)
=> BL-12930 fix editor trimming spaces at edges of paragraphs

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6346)
=> BL-13145 don't infinite loop if tbt recording fails

src/BloomExe/WebLibraryIntegration/BloomParseClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6348)
=> BL-13137 don't cache internet check on book upload

src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, src/BloomExe/History/BookHistory.cs, src/BloomExe/History/CollectionHistory.cs, src/BloomExe/History/HistoryEvent.cs, src/BloomTests/History/HistoryEventTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6345)
=> Mask problematic history event type enumeration change (BL-13140)

src/content/branding/Guatemala-RTI-GBEQT/branding-common.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6343)
=> Update Guatemala brandings to use appearance system (BL-13047)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6344)
=> Prevent text shifting when recording by text-box (BL-13128)

src/BloomBrowserUI/bookEdit/css/origamiEditing.less, src/BloomBrowserUI/bookEdit/js/origami.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6329)
=> Adjust (localized) origami toggle switch to display nicely (BL-13129)

src/BloomBrowserUI/bookEdit/EditViewFrame.pug, src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-narrow-margin-ebook.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css, src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css, src/content/bookLayout/basePage.less, src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6326)
=> BL-13084 Text Padding

src/BloomBrowserUI/bookEdit/EditViewFrame.pug, src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-narrow-margin-ebook.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css, src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css, src/content/bookLayout/basePage.less, src/content/templates/xMatter/project-specific/Uzbekistan2023-XMatter/Uzbekistan2023-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6354)
=> BL-13192 In Edit, Hide markup if you click out of the page

src/BloomExe/Utils/LocalizationHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6359)
=> Protect localization check against unit tests running (BL-13115)

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6361)
=> Prevent localization exceptions in unit tests (20240326)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6358)
=> BL-13203 copy font-size of first bloom-editable to translationGroup

src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Utils/LocalizationHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6363)
=> Cherry pick fix to 5.6 (BL-13115)

src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css, src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6365)
=> BL-13205 Padding for rounded ebook theme

src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/appearanceThemes/appearance-theme-default.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css, src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css, src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6366)
=> BL-13206 Page UI Fixes

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6367)
=> Check for missing page content at strategic spots (BL-13123)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6368)
=> Merge from 5.5 to 5.6 (20240327)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6369)
=> Merge from 5.6 to master - 20240327

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6370)
=> Prevent unit test failures from checking empty marginBox (BL-13123)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6371)
=> Merge fix from 5.5 to 5.6 20240327

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6372)
=> Merge fix from 5.6 to master 20240327

src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6377)
=> Fix check for empty page to new data instead of old (BL-13123)

src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6378)
=> Merge from 5.5 to 5.6 (20240402)

src/BloomExe/IBrowser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6379)
=> Merge from 5.6 to master (20240402)

src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6380)
=> Make editing overlay text more stable (BL-13135)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6382)
=> Fix additional page layouts to adjust format cog position (BL-13206)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6384)
=> Fix blorg badges (BL-13225)

src/BloomExe/CollectionTab/CollectionModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6388)
=> Clear upload agreement flag when duplicating a book (BL-13125)

src/BloomExe/CollectionTab/CollectionModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6389)
=> Merge from 5.6 to master (20240404)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6391)
=> Tweak check for empty page to look only on current page (BL-13123)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6392)
=> Merge 5.5 to 5.6 (20240404)

src/content/templates/template books/Activity/simple-dom-choice-activities.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6387)
=> Fix Activity page number color in Rounded Border theme (BL-13222)

src/BloomBrowserUI/bookEdit/copyrightAndLicense/CopyrightPanel.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6399)
=> BL-13250 fix spacing of copyright prompt

src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6401)
=> Wait to set up l10n before asking for localized string (BL-13245)

src/BloomExe/web/controllers/CollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6402)
=> Get book count in the background (BL-13227)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6403)
=> BL-12872 fix error messages regression

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/Page.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PlaceHolderPage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6404)
=> Open Book Settings to page-specific context (BL-13257)

src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6421)
=> Enhance logging for long-running API calls (BL-13253)

src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/Book.cs, src/BloomTests/Book/AppearanceSettingsTests.cs, src/BloomTests/Book/TranslationGroupManagerTests.cs, src/content/appearanceThemes/appearance-theme-default.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6423)
=> Fix failing unit tests related to front cover fixes (BL-13264)

src/BloomBrowserUI/bookEdit/pageThumbnailList/pageControls/pageControls.less, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Book/StyleSheetLinkSorter.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs
- Fix dark oval around collection name dropdown menu triangle
- editing tab left pane color consistency
- Fix flashing white outline around "Add Page" button when changing page selection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)
=> BL-13215 fix background colors and flashing button outline

src/BloomExe/BloomExe.csproj, src/BloomExe/Book/BookCopyrightAndLicense.cs, src/BloomExe/Program.cs, src/BloomExe/Publish/PublishView.cs, src/BloomTests/BloomTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6429)
=> Upgrade L10nSharp to 8.0.0-beta0003 (BL-13266)

src/BloomExe/Book/AppearanceSettings.cs
when xmatter.json appearance settings are present
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6419)
=> Fix page number affect on bottom margin (BL-13281)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/WebLibraryIntegration/BloomLibraryBookApiClient.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6435)
=> BL-13253 add upload messages

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterSettings.cs, src/content/templates/xMatter/project-specific/ABC-Reader-Device-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/ABC-Reader-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/MXBBook-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/MXBLiteracy-Device-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/MXBPamphlet-Mothballed/xmatter.json, src/content/templates/xMatter/project-specific/MXBScripture-Device-XMatter/xmatter.json, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/xmatter.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6431)
=> Allow harvester to convert some books to default theme (BL-13260)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6437)
=> Prevent publishing to the web without a title (BL-13317)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6440)
=> Improve check for book title when publishing to web (BL-13317)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6443)
=> BL-13327 add to the "|" tooltip message - "Bloom will hide these..."

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6445)
=> BL-13211 fix check of whether collection is tc

src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomTests/CLI/CreateArtifactsCommandTests.cs, src/content/templates/xMatter/project-specific/unit-test-project-specific-xmatter/unit-test-project-specific-xmatter.less, src/content/templates/xMatter/project-specific/unit-test-project-specific-xmatter/xmatter.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6447)
=> Harvester can fully convert books to default theme when allowed (BL-13260)

build/Bloom.proj, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6449)
=> Prepare Bloom alpha for diagnosing "wipe out" bug (BL-13346)

src/BloomExe/Edit/EditingModel.cs
This is another method calling javascript methods that shouldn't be called again before it has finished.  Probably not the problem, but it's in the stack trace we received for BL-13298.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6450)
=> Another check for possible diagnosis of "wipe out" bug (BL-13346)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx, src/BloomBrowserUI/react_components/BookInfoIndicator.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6457)
=> Extract common strings for incompatible css messages (BL-13341)

src/BloomExe/WebView2Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6463)
=> Don't Debug.Fail when filter catches an event (BL-13120)

src/content/appearanceMigrations/efl-ebook-3/appearance.json, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css
Also tweak the rounded border ebook theme to work better for activity pages, which don't have rounded corners.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6464)
=> Improve migration for EFL rounded border custom css (BL-13372)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6472)
=> Fix false positive empty margin box for calendar pages (BL-13423)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomExe/Book/AppearanceSettings.cs, src/content/bookLayout/basePage-sharedRules.less, src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6473)
=> BL-13373 fix gray background

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6478)
=> Fix call to removeToolboxMarkup (BL-13120)

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/web/controllers/CopyrightAndLicenseApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6480)
=> Don't save before launching the C&L dialog (BL-13429)

.gitignore, src/BloomExe/web/YouTrackIssueSubmission.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/web/YouTrackIssueSubmitterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6482)
=> BL-13407 Supply URL to problem book in restricted comment

src/BloomExe/Edit/EditingView.Designer.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6483)
=> Temporary easter egg to save and reload page (BL-13120)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/Program.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomExe/web/controllers/CollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6481)
=> BL-13426 Ensure bloomcollection file is .bloomcollection or .bloomlibrary

src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6486)
=> BL-13341 fix book button menu logic - "Duplicate" showing

src/content/templates/template books/Wall Calendar/wallCalendar.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6488)
=> Bring Wall Calendar into the appearance system (BL-13422)

.vscode/settings.json, ReadMe.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6492)
=> Prettier autoformat on save

src/BloomExe/Publish/Video/RecordVideoWindow.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6490)
=> BL-13401 don't rename audio to existing filenames

src/BloomBrowserUI/bookEdit/js/origami.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6487)
=> Fix l10n of origami strings (BL-13459)

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs
Also for our easter egg save with Ctrl-Shift-Click in the top bar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6489)
=> Not fatal if we fail to save when zooming (BL-13461)

.gitignore, src/BloomExe/Utils/BloomZipFile.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6484)
=> Create .BloomProblemBook files

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6493)
=> If the book isn't included, just send a normal zip without branding info file

src/content/appearanceThemes/appearance-theme-default.css, src/content/bookLayout/pageNumbers.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6446)
=> Center page numbers in bloom-player for non-device layouts (BL-13311)

src/BloomExe/web/controllers/ProblemReportApi.cs
This will be useful in making a better collection name for the collection history dialog.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6494)
=> Add issue ID to .BloomProblemBook

src/BloomExe/Publish/Video/RecordVideoWindow.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6495)
=> BL-13401 fix dont rename audio file to existing filename

src/BloomExe/Utils/MiscUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6499)
=> Fix check for opening collection from .zip in Win Explorer (BL-13446)

src/BloomBrowserUI/bookEdit/StyleEditor/AudioHilitePage.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6498)
=> Align audio highlight controls (BL-13491)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6496)
=> Fixes for audio highlighting (BL-13428)

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/IBrowser.cs, src/BloomExe/WebView2Browser.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/EditingViewApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6479)
=> Improvements made while investigating page wipeout (BL-13120)

src/BloomExe/Book/BookCompressor.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomTests/Publish/ExportEpubTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6451)
=> BL-13337 fix unwanted transparency in cover images

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6500)
=> Handle zero-width spaces for audio highlighting (BL-13428)

src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6468)
=> BL-13357 fix error changing page size

src/content/appearanceThemes/appearance-theme-default.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6506)
=> BL-13503 fix USComic  margins to 12mm

DistFiles/localization/Big Book/ReadMe-en.xlf, src/content/templates/template books/Big Book/Big Book.less, src/content/templates/template books/Big Book/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6508)
=> Allow Portrait orientation for Big Books (BL-13510)

DistFiles/localization/Big Book/ReadMe-en.xlf, src/content/templates/template books/Big Book/Big Book.less, src/content/templates/template books/Big Book/ReadMe-en.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6509)
=> Merge from version5.6 to master 20240528

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStarter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6504)
=> Fix BL-13504 Duplicate ID after duplicating a page

src/BloomExe/XmlHtmlConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6510)
=> Improve performance of RemoveSvgs and RestoreSvgs (BL-13515)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6511)
=> Allow Report a Problem for Collection and Publish tabs (BL-13523)

src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6513)
=> Keep Add Page dialog from endless axios API requests (BL-13418)

src/content/appearanceMigrations/efl-rounded/appearance.json, src/content/appearanceMigrations/efl-rounded/customBookStyles.css, src/content/appearanceMigrations/efl-rounded1/appearance.json, src/content/appearanceMigrations/efl-rounded1/customBookStyles.css, src/content/appearanceMigrations/efl-rounded2/appearance.json, src/content/appearanceMigrations/efl-rounded2/customBookStyles.css, src/content/appearanceMigrations/efl-rounded3/appearance.json, src/content/appearanceMigrations/efl-rounded3/customBookStyles.css, src/content/appearanceMigrations/efl-rounded4/appearance.json, src/content/appearanceMigrations/efl-rounded4/customBookStyles.css, src/content/appearanceMigrations/efl-zeromargin/appearance.json, src/content/appearanceMigrations/efl-zeromargin/customBookStyles.css, src/content/appearanceMigrations/efl-zeromargin1/appearance.json, src/content/appearanceMigrations/efl-zeromargin1/customBookStyles.css, src/content/appearanceMigrations/efl-zeromargin2/appearance.json, src/content/appearanceMigrations/efl-zeromargin2/customBookStyles.css, src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css
Also fix a minor glitch in the rounded-border-ebook theme.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6503)
=> Add several new custom CSS migrations (BL-13455)

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6519)
=> Safety fix for change layout check in willLoseData() method (BL-13534)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6521)
=> Ensure English is the default UI language, not "Invariant" (BL-13545)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6520)
=> Prevent page wipeout (BL-13120)

src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6522)
=> Cherry pick fix for BL-13418 from master to Version5.6

src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6523)
=> Merge from Version5.6 to master (20240605)

src/BloomExe/Utils/PerformanceMeasurement.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6515)
=> Speed up the performance monitoring code (BL-13516)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6527)
=> Fix metadata button properly for changed images (BL-13558)

src/content/appearanceThemes/appearance-theme-zero-margin-ebook.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6528)
=> Fix zero margin ebook theme page number for right side pages (BL-13561)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6530)
=> Fix mistake in converting migration code (BL-12853)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6531)
=> Move from Spiritual topic to Bible (BL-13538)

src/BloomExe/Registration/RegistrationDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6534)
=> Require valid email address in registration

src/BloomExe/Book/TranslationGroupManager.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6533)
=> Reinstate null check in TranslationGroupManager (BL-13564)

src/BloomBrowserUI/lib/jquery.qtip.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6532)
=> Use page scale when calculating qtip position (BL-13538)

src/BloomExe/WebView2Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6536)
=> Guard against using a disposed webview2 (BL-13580)

src/BloomExe/Book/Book.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingStateMachine.cs, src/BloomExe/Event.cs, src/BloomExe/Shell.cs, src/BloomExe/web/controllers/EditingViewApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6535)
=> Fix up error handling around save failures in the state machine

src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/PublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6537)
=> Do not cache BloomPUB preview files or dynamic css files (BL-13586)

src/BloomExe/WebLibraryIntegration/BookDownload.cs
Note that this targets Version5.5, the current release.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6540)
=> Prevent Bloom from running after rejecting a download (BL-13566)

src/BloomExe/WebLibraryIntegration/BookDownload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6541)
=> Merge from 5.5 to 5.6 (20240613)

src/BloomExe/WebLibraryIntegration/BookDownload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6542)
=> Merge from5.6 to master 20240613

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6543)
=> Prevent toast error when add Story Primer page (BL-13577)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6546)
=> Merge from 5.6 to master - 20240617

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/XMatterHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6539)
=> Create flyleaf pages with a margin box (BL-13589)

src/content/templates/template books/Digital Comic Book/common-comics.less, src/content/templates/template books/Paper Comic Book/Paper Comic Book.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6547)
=> Fix comic book templates for no margins or page numbers (BL-13602)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6551)
=> Fix style name l10n (BL-13141)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6545)
=> Ensure book caption and preview are updated (BL-13597)

src/BloomExe/Book/Book.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6549)
=> Limit default publication languages to those in collection (BL-13162)

src/BloomExe/web/RequestInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6538)
=> Cache .woff2 files

src/BloomExe/web/IRequestInfo.cs, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/ApiRequest.cs, src/BloomExe/web/controllers/EditingViewApi.cs, src/BloomTests/PretendRequestInfo.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6564)
=> Don't unescape page content data (BL-13627)

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs, src/BloomExe/Publish/PDF/PdfMaker.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebView2Browser.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6565)
=> Prevent spurious error messages in bulk upload (BL-13593)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/AppearanceMigrator.cs, src/BloomExe/Book/XMatterSettings.cs, src/BloomExe/WebLibraryIntegration/BookDownload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6567)
=> Reinstate pre-commit hook

src/BloomTests/SafeXml/SafeXmlTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6568)
=> Tweak SafeXml unit tests to improve robustness (BL-13560)

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6569)
=> Fix error in problem report dialog when no registration email (BL-13650)

src/BloomBrowserUI/problemDialog/ProblemDialog.less, src/BloomBrowserUI/problemDialog/ReportDialog.tsx, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6570)
=> Improve error handling when submitting error report (BL-13650)

src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6561)
=> Add properties to upload analytics (BL-13611)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6574)
=> Check installed branding for appearance compatibility (BL-13683)

src/BloomExe/Collection/WritingSystem.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6575)
=> Fix display of right-to-left checkbox (BL-13674)

src/content/appearanceThemes/appearance-theme-rounded-border-ebook.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6576)
=> Fix rounded corners on images (BL-13697)

src/BloomBrowserUI/collection/enterpriseSettings.less, src/BloomExe/BloomFileLocator.cs, src/BloomExe/Collection/BrandingProject.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/web/controllers/BrandingSettings.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs, src/content/branding/World-Vision-International/summary.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6578)
=> BL-13710 Enabled "subunit" for enterprise codes

src/content/bookLayout/pageBoxesSizing.less
There's only one non-formatting change in the file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6584)
=> Adjust page number location for full-bleed standard pages (BL-13685)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6582)
=> Ensure default image license is CC-BY (BL-11093)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6585)
=> Improve error reporting for writing image metadata (20240730)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6591)
=> Merge from 5.6 to 6.0 (20240805)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Edit/EditingView.cs, src/BloomExe/Edit/PageEditingModel.cs, src/BloomExe/ImageProcessing/ImageUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6593)
=> Merge from 6.0 to master (20240805)

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/PageTemplatesApi.cs
Also fix an annoying misspelled URL parameter name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6595)
=> Allow generated thumbnails to be displayed in Add Page dialog (BL-13722)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/TopicChooser/TopicChooserDialog.tsx, src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishScreen.tsx, src/BloomBrowserUI/publish/commonPublish/CoverColorGroup.tsx, src/BloomBrowserUI/publish/commonPublish/PublishScreenBaseComponents.tsx, src/BloomBrowserUI/publish/commonPublish/PublishScreenTemplate.tsx, src/BloomBrowserUI/publish/commonPublish/PublishTopic.tsx, src/BloomExe/web/controllers/LibraryPublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6586)
=> Add topic chooser to Web Publish screen (BL-13751)

src/content/appearanceMigrations/efl-rounded/customBookStyles.css, src/content/appearanceMigrations/efl-rounded1/customBookStyles.css, src/content/appearanceMigrations/efl-rounded3/customBookStyles.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6601)
=> Fix custom css for appearance system migrations (BL-13782)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bloomMaterialUITheme.ts, src/BloomBrowserUI/bookEdit/bookSettings/StyleAndFontTable.tsx, src/BloomExe/web/controllers/StylesAndFontsApi.cs
This is mostly the work that @hatton did over the weekend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6603)
=> Enhance Fonts section of the Book Settings dialog (BL-13763)

src/BloomExe/ToPalaso/ProcessExtra.cs, src/BloomExe/web/controllers/ApiRequest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6606)
=> Handle URLs with parameters nicely in external links (BL-13008)

src/BloomExe/Collection/CollectionSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6604)
=> Page number line-height should not be changed by L1 setting (BL-13699)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/DataSet.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6605)
=> Allow users to delete copied credit field contents (BL-13779)

src/BloomExe/Edit/WebThumbNailList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6616)
=> Prevent zooming in page list chooser pane (BL-13799)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomExe/FontProcessing/FontMetadata.cs, src/BloomExe/FontProcessing/FontsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6619)
=> Process font licenses more accurately and stringently (BL-13806)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomExe/FontProcessing/FontMetadata.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6620)
=> Code review fixes for font license information (BL-13806)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/fontInformationPane.tsx, src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/FontProcessing/FontMetadata.cs, src/BloomExe/FontProcessing/FontsApi.cs, src/BloomTests/FontProcessingTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6623)
=> Merge from version 6.0 to master (20240828)

src/BloomExe/BloomExe.csproj, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/app.config, src/BloomExe/web/controllers/CopyrightAndLicenseApi.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookCopyrightAndLicenseTests.cs, src/BloomTests/app.config, src/WebView2PdfMaker/App.config, src/WebView2PdfMaker/WebView2PdfMaker.csproj
This involves an update to the libpalaso packages (SIL.Windows.Forms to be exact for clipboard code).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6624)
=> Handle pasting transparent images better (BL-13810)

src/content/templates/template books/Games/simpleComprehensionQuiz.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6625)
=> Merge from 6.0 to master (again 20240828)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookCompressor.cs, src/BloomExe/Book/BookFileFilter.cs, src/BloomExe/Collection/BloomPack/ReaderToolsBloomPackCollectionFileFilter.cs, src/BloomExe/Collection/CollectionFileFilter.cs, src/BloomTests/Book/BookFileFilterTests.cs, src/BloomTests/Collection/CollectionFileFilterTests.cs
Also rename some book filter methods for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6634)
=> Fix template folder name for book filtering (BL-13825)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6631)
=> Prevent a javascript crash when clicking on the format icon (BL-13829)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6630)
=> Various improvements to overlays

src/BloomBrowserUI/react_components/localizableMenuItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6639)
=> BL-13842 Bubbles Menus are too spread out

src/BloomExe/web/controllers/AppApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6643)
=> Make "Upgrade to the latest Bloom" link work properly (BL-13767)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/web/controllers/BrandingSettings.cs, src/content/branding/INADE-PATII-Angola/branding.json, src/content/templates/xMatter/bloom-xmatter-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6628)
=> BL-13805 Branding control over credits lang

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomMediumPriority.xlf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6653)
=> Activate new xliff strings for upcoming release (BL-13850)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6648)
=> Remove menu as well as overlay control on overlay deletion (BL-13852)

src/BloomBrowserUI/problemDialog/ReportDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6655)
=> Open external browser for issue link in Report a Problem (BL-13839)

src/BloomBrowserUI/infoPages/aboutBox.htm
Also update "SIL International" to "SIL Global".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6658)
=> Update about box HTML to launch external browsers for links (BL-13872)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx, src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6663)
=> Bl 13877 improve bubble sound chooser

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/ToPalaso/ProcessExtra.cs, src/BloomExe/Utils/BloomZipFile.cs, src/BloomExe/web/RequestInfo.cs, src/BloomExe/web/controllers/SignLanguageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6661)
=> Enable importing any kind of video file for experiments (BL-13849)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6659)
=> Adjust position of #overlay-context-controls (BL-13874)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomExe/Book/Page.cs, src/BloomExe/Book/XMatterHelper.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/PlaceHolderPage.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/web/controllers/EditingViewApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6673)
=> Allow pasting link to cover page or to another book (BL-13880)

src/BloomBrowserUI/bookEdit/toolbox/signLanguage/signLanguageTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6675)
=> Remove video placeholder when a video is selected (BL-13918)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6676)
=> Update overflow when adjusting overlay text box height (BL-13902)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6677)
=> Fix broken bubble menu commands (BL-13928)

src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/bubble.less
This bug is similar to one fixed earlier for normal text boxes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6674)
=> Don't center text in overflowing bubble text boxes (BL-13606)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6679)
=> Preserve Auto Height when duplicating bubbles (BL-13931)

src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6682)
=> Fix another page layout padding (BL-13768)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6681)
=> Fix some more problems with outlines (BL-13895)

src/BloomBrowserUI/lib/long-press/jquery.longpress.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6683)
=> Add non-breaking hyphen to long press, label dashes

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6685)
=> From JT: fix qtip display (BL-13943)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6686)
=> Copy data-sound when duplicating overlay (BL-13931)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/editablePage.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bloomFrames.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/DragActivityTabControl.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialogSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/readers/readerSetup/readerSetup.ui.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts, src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx, src/BloomBrowserUI/utils/textUtils.ts, src/BloomBrowserUI/utils/textUtilsSpec.ts, src/BloomBrowserUI/webpack.common.js, src/BloomBrowserUI/yarn.lock, src/BloomExe/Book/BookStorage.cs, src/BloomExe/web/ReactControl.cs, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less, src/content/templates/template books/Games/blueOnTanTheme.less
Started out as updating Games to work with various recent changes, especially to how we do overlays. Ended up incorporating various refactorings and bug fixes and a couple more Games-related Notion cards.
Possibly easier to review individual commits, which indicate the purpose of each step. However, note the final commit cleans up various things.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6684)
=> Various improvements to Games

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx, src/BloomBrowserUI/pageChooser/stories.tsx, src/BloomBrowserUI/tsconfig.json, src/content/templates/template books/Activity/Activity.pug
Creates a general mechanism whereby, if multiple books have the same title, their pages get merged under that heading.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6680)
=> Merge Activity pages into Games

src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6689)
=> Prevent EnsureUptoDate messing up cropping (BL-13945)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescriptionUtils.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6687)
=> Fix problems from new overlay controls in image descriptions (BL-13946)

src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6691)
=> Update collection pane when deleting single remaining book (BL-13970)

src/BloomBrowserUI/bookEdit/js/bloomVideo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6690)
=> Handle multiple video overlays better (BL-13930)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6696)
=> Fix overlays and image descriptions (try 2) (BL-13946)

src/BloomExe/Collection/WritingSystem.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6699)
=> Fix the new way of saving  language RTL setting (BL-13982)

src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescription.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6698)
=> ImageDescriptionEdit should be on editable (BL-13979)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/toolbox/imageDescription/imageDescriptionUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6701)
=> Third try at fixing overlays in image description mode (BL-13946)

src/BloomBrowserUI/Readium/ReadMe.txt, src/BloomBrowserUI/Readium/indexRtl.html, src/BloomExe/Publish/Epub/PublishEpubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6700)
=> Make epub preview left and right buttons work for RTL (BL-12185)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/img/pauseIcon.ts, src/BloomBrowserUI/bookEdit/img/playIcon.ts, src/BloomBrowserUI/bookEdit/img/replayIcon.ts, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6703)
=> Use our own video controls (simplified) in edit mode (BL-13957)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6705)
=> Remove some fudge factors messing up overflow detection (BL-13835)

src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6706)
=> Pull in a couple of JT's overflow fixes from 6.1 (BL-13942)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6707)
=> Improvements to video controls, mainly for Game Play mode (BL-13957)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6709)
=> Remove "Show Sign Language Tool" from toolbox (BL-13990)

src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6711)
=> Fix a crash from replacing with a custom template page (BL-13977)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6710)
=> Lock aspect ratio of overlay videos (BL-13991)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/img/pauseIcon.ts, src/BloomBrowserUI/bookEdit/img/playIcon.ts, src/BloomBrowserUI/bookEdit/img/replayIcon.ts, src/BloomBrowserUI/bookEdit/js/bloomVideo.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts
Probably only the second commit needs review. The first is just cherry-picking with a little conflict resolution
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6715)
=> Cherry pick video controls and clean up some related issues

src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6718)
=> Ensure closing tag for book history in problem report (BL-14035)

src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6720)
=> Fix the order of looking for new style to fix a failing test (BL-13977)

src/BloomExe/Edit/WebThumbNailList.cs, src/BloomExe/Utils/MiscUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6726)
=> Prevent Windows text size setting from modifying page list (BL-13955)

src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6727)
=> Update overlay height after pasting into it (BL-14004)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/DataSet.cs, src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomTests/Utils/MiscUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6728)
=> Handle incorrectly capitalized language codes (BL-14038)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6732)
=> Clean up PublishSettings from improper language tags (BL-14038)

src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6731)
=> Handle asynchronous paste for bubble height adjustment (BL-14004)

src/BloomBrowserUI/bookEdit/js/niceScrollBars.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6733)
=> Fix the nicescroll position when the page is zoomed (BL-13796)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6730)
=> Another fix to prevent overflow calc from scrolling text box (BL-13942)

src/BloomExe/FontProcessing/FontMetadata.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6729)
=> Refactor FontMetadata for use by harvester font backup (BL-10035)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6735)
=> Include drag targets and overlays that never had an old background

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6736)
=> Copy all bubble text if there is no selection (BL-14051)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6739)
=> Bl 14053 overflow detection problems

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomBrowserUI/pageChooser/stories.tsx, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/web/controllers/AddOrChangePageApi.cs, src/content/templates/template books/Activity/Activity.pug, src/content/templates/template books/Arithmetic Template/ArithmeticTemplate.pug, src/content/templates/template books/Basic Book/Basic Book.pug, src/content/templates/template books/Decodable Reader/Decodable Reader.pug, src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Leveled Reader/Leveled Reader.pug, src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm, src/content/templates/template books/Sign Language/Sign Language.pug, src/content/templates/template books/Special/Special.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6740)
=> Improve sorting and duplication in add page dialog (BL-14058)

src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx
Also removes left-over source bubble.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6743)
=> Close Game Prompt dialog on Enter (BL-13993)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6746)
=> Prevent extra line break on bubble copy/paste (BL-14051)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6748)
=> Don't stop drag when mouse leaves container (BL-14067)

src/BloomBrowserUI/gulpfile.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6749)
=> Properly copy bloom-player files (BL-13998)

ReadMe.md, src/BloomBrowserUI/bookEdit/js/niceScrollBars.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6752)
=> Update readme (and fix a compile error)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6753)
=> Prevent mouseUp missing that we clicked a resize handle (BL-14071)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/react_components/localizableMenuItem.tsx, src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6755)
=> Tweak overlay menu item size and casing (BL-14070)

src/BloomExe/Program.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6758)
=> Resume properly if new collection NOT chosen (BL-14066)

src/BloomBrowserUI/booksOnBlorg/BooksOnBlorgProgressBar.tsx, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6759)
=> Update book count after new upload (BL-12922)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6760)
=> Merge6.1 to master 20241118

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6761)
=> Ensure overflow height is accurate (BL-14053)

src/content/bookLayout/basePage-legacy-5-6.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6764)
=> Make cropping work for legacy books (BL-13952)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityRuntime.ts
This duplicates the change made to the file in bloom-player.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6766)
=> Don't show game answers while swiping pages (BL-14064)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/StyleAndFontTable.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6767)
=> Show font in book settings font table even when not installed (BL-14093)

src/BloomBrowserUI/lib/split-pane/split-pane.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6765)
=> Remove padding from horizontal splitter (BL-13965)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6768)
=> Patch to revert background overlays in 6.1 (BL-14096)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6775)
=> Prevent showing image toolbox after choosing a gif image (BL-13985)

src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts, src/BloomBrowserUI/bookEdit/bloomField/hyperlinks.ts, src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/react_components/localizableMenuItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6780)
=> Paste Hyperlinks for images

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6778)
=> Don't rely on style settings for element position and size (BL-14106)

src/BloomBrowserUI/bloomWebFonts.less, src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6777)
=> Allow Andika to be used in the UI when not installed (BL-14102)

src/BloomExe/Program.cs, src/BloomExe/Registration/Registration.cs, src/BloomExe/Registration/RegistrationDialog.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/web/DynamicJson.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/TeamCollection/TeamCollectionApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6774)
=> Replace SIL.W.F.Registration with simpler storage (BL-14101)

src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/ServerHandlerForBloomPlayer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6782)
=> Jumping back to original book goes to bloompub staging (BL-13881)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6785)
=> Handle more cases of source bubbles not appearing (BL-14109)

src/BloomBrowserUI/gulpfile.js, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6786)
=> Fix some breakage in bloompub publishing/preview (BL-14195)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6789)
=> Improve visibility of empty overlay (canvas) text boxes (BL-14193)

src/BloomExe/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6791)
=> BL-14217 only upload collection file when failure on initial open

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6788)
=> Fix image copyright button when no copyright/license (BL-14151)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6793)
=> Fix problems with overflow in overlays with padding (BL-14182)

src/BloomExe/Edit/EditingModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6792)
=> Fix removing a new page after relocating it (BL-14133)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6794)
=> Prevent overflow when changing overlay padding (BL-14182)

src/BloomBrowserUI/yarn.lock, src/BloomExe/Publish/Video/RecordVideoWindow.cs, src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6800)
=> Fix publish to audio/video when there is audio (BL-14227)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomTests/Publish/PublishHelperTests.cs
This is basically a cherry-pick of part of a 6.2 change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6802)
=> Publishing should really crop images (BL-14185)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/TeamCollection/DisconnectedTeamCollection.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs
I added a 2-line bug fix as a separate commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6799)
=> Cherry pick independent color palettes from master (BL-14129)

src/BloomExe/InstallerLogger.cs, src/BloomExe/InstallerSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6804)
=> Enhance logging for Bloom install and try to ensure shortcut (BL-14084)

src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6808)
=> Repair test broken by last commit

src/BloomTests/TeamCollection/FolderTeamCollectionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6809)
=> Try to fix a flaky test

src/BloomBrowserUI/bookEdit/js/bloomQtipUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6814)
=> Fix a problem in detecting possible source bubble conflict (BL-14109)

DistFiles/localization/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6821)
=> Update crowdin URL in localization README (20250127)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6823)
=> Avoid image description for initial focus with source bubble (BL-14264)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6806)
=> Properly handle readonly book folder (BL-14174)

src/BloomBrowserUI/bloomMaterialUITheme.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6827)
=> BL-14727 remove grey background from dialog for language chooser

src/BloomBrowserUI/react_components/bookInfoCard.tsx, src/BloomExe/ImageProcessing/RuntimeImageProcessor.cs, src/BloomExe/web/controllers/PublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6812)
=> Make thumbnails in collision dialog more uniform (BL-13769)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6829)
=> Possible improvement to overflow checking on page load (BL-14088)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/utils/measureText.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6816)
=> Optimize overflow checks, especially in origami drags (BL-14234)

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx, src/BloomExe/ApplicationContainer.cs, src/BloomExe/Book/BookSelection.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/web/BloomApiHandler.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/CommonApi.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/ExportEpubTestsBaseClass.cs, src/BloomTests/web/BloomServerTests.cs, src/BloomTests/web/ImageServerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6832)
=> BL-14233 Make language chooser dialog work before project

src/BloomExe/web/BloomServer.cs, src/BloomTests/web/controllers/ReadersApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6834)
=> BL-14233 fix broken tests

src/BloomExe/TeamCollection/FolderTeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6835)
=> Prevent a spurious collection settings update message (BL-14254)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/content/bookLayout/bubble.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6836)
=> Merge from 6.1 to master (20250204)

src/BloomBrowserUI/utils/measureText.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6837)
=> Fix optimization to allow for varied fonts (BL-14088)

src/BloomExe/ApplicationContainer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6840)
=> Force CommonApi to be a singleton object (BL-14293)

src/BloomExe/ApplicationContainer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6841)
=> Explanation of the prior fix in a comment (BL-14293)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bloomImages.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, src/BloomExe/Book/BookData.cs, src/content/bookLayout/basePage.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6830)
=> Restore reasonable display for missing images (BL-14241)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6846)
=> Properly get unique name for file with period in name (BL-14213)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6849)
=> Keep focus in GamesPromptDialog when typing (BL-14317)

src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6847)
=> Preserve image hyperlinks in bloompub books (BL-14318)

src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomTests/Book/RuntimeInformationInjectorTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6852)
=> Use user-defined names to label source bubble langs (BL-14327)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/shared/dragActivityRuntime.ts, src/BloomBrowserUI/bookEdit/shared/event.ts, src/BloomBrowserUI/bookEdit/shared/narration.ts, src/BloomBrowserUI/bookEdit/shared/scrolling.ts, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx, src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx
This is stage one, getting the files into sync and adjusting a couple of BloomDesktop files for one method call change.  Note that niceScrollBars.ts is the same as bloom-player's scrolling.ts except for the very first line.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6839)
=> Update for files shared with bloom-player (BL-14008)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6853)
=> Reset Cropping on Expand (BL-14297)

src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, src/BloomTests/Spreadsheet/InternalSpreadsheetTests.cs, src/BloomTests/Spreadsheet/SpreadsheetAudioImportTests.cs, src/BloomTests/Spreadsheet/SpreadsheetAudioTests.cs, src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, src/BloomTests/Spreadsheet/SpreadsheetXmatterTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6854)
=> Make exported XLSX row labels more consistent (BL-14334)

src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6858)
=> Fix expand to fit and other tweaks (BL-14297)

src/BloomBrowserUI/bookEdit/js/collectionSettings.d.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/bookEdit/sourceBubbles/SourceBubblesSpec.ts, src/BloomExe/Book/RuntimeInformationInjector.cs, src/BloomExe/Properties/Settings.Designer.cs, src/BloomExe/Properties/Settings.settings, src/BloomExe/app.config, src/BloomExe/web/controllers/EditingViewApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6855)
=> BL-14330 Remember 2 Source Tabs

src/BloomExe/Book/RuntimeInformationInjector.cs, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6861)
=> Make games data-hint work properly (BL-14354)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/HtmlDom-Json.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Book/HTMLDom-Json-Tests.cs, src/BloomTests/CLI/CreateArtifactsCommandTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6867)
=> Merge version 6.1 into master 20250224

src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts, src/BloomBrowserUI/bookEdit/sourceBubbles/BloomSourceBubbles.tsx, src/BloomBrowserUI/lib/jquery.qtip.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6868)
=> Fix positioning of GamesPromptDialog tooltip (BL-14347)

src/BloomExe/Book/HtmlDom-Json.cs, src/BloomTests/Book/HTMLDom-Json-Tests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6869)
=> Don't include bubble text (BL-14360)

src/BloomExe/web/controllers/StylesAndFontsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6870)
=> Ensure default font is shown in Book Settings -> Fonts (BL-14359)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsControl.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6876)
=> More small fixes to Adjust Timings (BL-12953)

src/BloomExe/web/controllers/CollectionSettingsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6877)
=> Fix the expiration date for deprecated brandings (BL-14363)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6880)
=> Don't put Bubble-style class on .bloom-translationGroup (BL-14223)

src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6883)
=> Disable record button until preview is created (BL-14321)

DistFiles/localization/en/Bloom.xlf, src/content/templates/template books/Basic Book/template/Bilingual + Picture in Middle-landscape.svg, src/content/templates/template books/Basic Book/template/Bilingual + Picture in Middle.svg, src/content/templates/template books/standard-page-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6872)
=> Add "Bilingual & Picture in Middle" to the basic page types (BL-14348)

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/Publish/BloomReaderPublishTests.cs, src/BloomTests/Publish/PublishHelperTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6851)
=> Don't try to embed unused fonts (BL-14267)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6887)
=> Hide book selected in previous collection in preview pane (BL-14313)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6886)
=> Improve algorithm for detecting new language in prompt dlg (BL-14352)

src/content/templates/template books/standard-page-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6891)
=> Fix textbox sizes in Bilingual & Picture in Middle page (BL-13768)

src/BloomBrowserUI/bookEdit/toolbox/dragActivity/GamePromptDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6889)
=> Try harder still to make sure Prompt dialog keeps focus (BL-14383)

src/BloomBrowserUI/bookEdit/js/OverlayContextControls.tsx, src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6892)
=> Merge from 6.1 to master (20250305)

src/BloomBrowserUI/collection/enterpriseSettings.tsx, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx, src/BloomExe/web/controllers/CollectionSettingsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6888)
=> BL-14363 Avoid time zones in expiration calculations

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6895)
=> Patch 6.1 to reverse-migrate canvas-element (BL-14189)

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/web/controllers/CollectionSettingsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6893)
=> Allow a branding to be replaced by a newer subscription (BL-14381)

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomBrowserUI/pageChooser/TemplateBookPages.tsx, src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx, src/BloomExe/Book/HtmlDom.cs, src/content/templates/template books/Basic Book/template/Bilingual + Picture in Middle-landscape.svg, src/content/templates/template books/Basic Book/template/Bilingual + Picture in Middle.svg, src/content/templates/template books/standard-page-mixins.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6896)
=> Improve display of bilingual page in Add Page Dialog (BL-14364)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6901)
=> Restore full information for image tooltips (BL-14380)

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx, src/BloomBrowserUI/collection/NewCollectionLanguageChooser.tsx, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6899)
=> Language chooser localization (BL-14005)

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6904)
=> BL-14370 fix language chooser display name entry

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6909)
=> Don't delete sound files with uppercase letters in name (BL-14429)

src/BloomBrowserUI/collection/LanguageChooserDialog.tsx, src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx, src/BloomExe/MiscUI/ReactDialog.Designer.cs, src/BloomExe/MiscUI/ReactDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6912)
=> Allow Escape key to cancel react dialogs (BL-14378)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6908)
=> Fix "Change image" icon response in background images (BL-14331)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6913)
=> Prevent talking book markup on game pages (BL-14434)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bloomMaterialUITheme.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/games/ThemeChooser.tsx, src/BloomBrowserUI/utils/getVariationsOnClass.ts
Some UI tweaks and refactoring. May be helpful to review commits separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6914)
=> Games themes cleanup

src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6916)
=> Allow dragging tail midpoints over background images (BL-14407)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/HtmlDomTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6917)
=> Preserve imageContainer size on change layout (BL-14230)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6919)
=> Update comicaljs to at least 0.3.100 explicitly

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6921)
=> Select required tool on page change when it's already displayed (BL-14434)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6925)
=> Allow custom css to override appearance settings (BL-14467)

src/BloomExe/Book/BookStorage.cs, src/content/templates/template books/Activity/simpleComprehensionQuiz.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6923)
=> Fix broken quiz page activity (BL-14450)

src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6926)
=> Repair Change Layout to show image placeholder again (BL-14464)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6922)
=> Ensure image descriptions are enabled for audio recording (BL-14436)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6924)
=> Comment out the Order Words game page for now (BL-14457)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6918)
=> Keep text inside canvas overlays when editing image description (BL-14312)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6928)
=> Merge 6.1 into master (20250325)

src/BloomExe/Book/BookFileFilter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6927)
=> Restore "wrong answer" sound playing in BloomPub games (BL-14452)

src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/ExperimentalFeatures.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6933)
=> Remove spreadsheet export/import from being experimental (BL-14432)

src/BloomExe/web/controllers/BrandingSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6935)
=> BL-14494 False Flavor Failure

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/games/DragActivityTabControl.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6936)
=> Change appearance of "Edit Word to Spell" button (BL-14448)

src/BloomExe/Book/BookData.cs
This change does not affect what gets uploaded/published.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6937)
=> Retain ai language data while editing/sharing collection (BL-14485)

src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6938)
=> Fix check for publishing bookshelf 20250531

src/BloomExe/Collection/Subscription.cs, src/BloomTests/web/controllers/SubscriptionTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6939)
=> Fix subscription parsing - number segments in descriptor (BL-14379)

src/BloomExe/web/controllers/CollectionSettingsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6940)
=> Fix Enterprise bookshelves (BL-14379)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This should be null-merged into master (don't want any of these changes) and eventually cherry-picked to 6.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6931)
=> Back migration for level 7 canvasElement

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6942)
=> Make sure overlay is big enough for "dim English" prompt (BL-14489)

src/BloomExe/Book/BookFileFilter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6943)
=> Allow audio files with uppercase letters to pass filter

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6944)
=> Drag item from toolbox to page should show proper cursor (BL-14490)

src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx
...rather than the other way around
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6945)
=> When adding a new draggable, set its size from existing (BL-14449)

src/BloomBrowserUI/bookEdit/toolbox/games/GamePromptDialog.tsx, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6946)
=> Ensure letters look scrambled in "Drag the Letters" game (BL-14446)

src/BloomExe/Book/BookData.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6950)
=> Allow "Local Community" subscription books to be edited (BL-14513)

src/content/branding/GSLT-MLDE/branding[NGO-Gov].json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6954)
=> Add wording for GSLT-MLDE[NGO-Gov] branding flavor (BL-14478)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6949)
=> Allow targets to be clicked through in play mode (BL-14483)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/games/gameUtilities.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6953)
=> Prevent auto-shrinking of all-same-size elements (BL-14449)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6958)
=> Disable Delete for background placeholder (BL-14486)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6959)
=> Restrict page-load focus to normal visible elements (BL-14505)

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomLowPriority.xlf, DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6947)
=> Fix remaining issues with subscription/branding (BL-14379, BL-14504)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6962)
=> canvas-element implementation of bloom-imageObjectFitCover (BL-14208)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6968)
=> Fix size of new draggable image (BL-14449)

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6969)
=> Use "Default" for subscription for analytics / upload dialog (BL-14379)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6967)
=> Don't let game correct/wrong sound appear twice in select (BL-14533)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/IAudioRecorder.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxBootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6964)
=> BL-14507: fix TBT wrongly opening image descriptions

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6972)
=> Fix a bug in Comic back-migration (BL-14491)

src/content/templates/template books/Digital Comic Book/Digital Comic Book.htm, src/content/templates/template books/Paper Comic Book/Paper Comic Book.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6973)
=> Remove class attr from data-book coverImage in comic templates

src/BloomBrowserUI/react_components/BloomSwitch.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6974)
=> Allow BloomSwitch to be used in controlled mode (BL-14538)

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/web/controllers/SubscriptionSettingsEditorApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6975)
=> Properly handle subscription when cancelling settings dialog (BL-14379)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6977)
=> Restore target shadow in play mode (BL-14534)

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/bloomImages.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6979)
=> Adjust zIndex of image button and make it work on new page (BL-14473)

src/BloomExe/Book/AppearanceSettings.cs, src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6981)
=> Fix appearance system detection of legacy canvas elements (BL-14550)

src/BloomExe/web/controllers/CollectionSettingsApi.cs, src/BloomTests/web/controllers/CollectionSettingsApiTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6983)
=> Fix expiry date parsing for deprecated brandings (BL-14525)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6984)
=> Fix expired subscription message (BL-14563)

src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomTests/ImageProcessing/ImageUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6986)
=> Fix publication image cropping for non-ASCII filepaths (BL-14566)

DistFiles/localization/en/BloomLowPriority.xlf, DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/AdjustTimingsDialog.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx
And fixed i18n
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6989)
=> Fix hyperlink url displaying null (BL-14576)

src/BloomBrowserUI/bookEdit/toolbox/overlay/canvasElementUtils.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/IAudioRecorder.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordable.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordingMode.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6985)
=> BL-14507 small refactor

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6990)
=> Don't try to adjust control frame when no active element (BL-14593)

DistFiles/localization/en/BloomLowPriority.xlf, src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx, src/BloomBrowserUI/teamCollection/CollectionHistoryTable.tsx, src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/History/HistoryEvent.cs, src/BloomExe/web/controllers/BookCommandsApi.cs, src/BloomExe/web/controllers/CollectionApi.cs, src/BloomTests/History/HistoryEventTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6988)
=> BL-14590 move book into collection

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/games/ThemeChooser.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx, src/BloomBrowserUI/react_components/icons/ImagePlaceholderIcon.tsx, src/content/bookLayout/basePage-sharedRules.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6993)
=> Add the Rectangle canvas element type

src/BloomExe/Book/ImageUpdater.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6991)
=> BL-14592 don't copy gif metadata

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6995)
=> Allow showing answer without showing target in drag games (BL-14532)

src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/react_components/icons/AudioIcon.tsx, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6997)
=> Add sound game element (BL-14595)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6999)
=> Make a duplicated rectangle go behind other elements (BL-14596)

src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBCommon-XMatter.less, src/content/templates/xMatter/project-specific/MXBLiteracy-XMatter/MXBLiteracy-XMatter.less, src/content/templates/xMatter/project-specific/MXBScripture-XMatter/MXBScripture-XMatter.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6996)
=> BL-14617 allow Device16x9 sizes in MXB branding

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7000)
=> Better approach to applying theme colors to draggable svg (BL-14595)

src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7001)
=> Enable upload of "different book" when changing subscription (BL-14611)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx, src/BloomBrowserUI/react_components/icons/GifIcon.tsx, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7002)
=> Rearrange parts of the game tool and add Target Label (BL-14603)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7005)
=> Handle Change Image button clicks on Drag Letters page (BL-14614)

src/BloomExe/Book/BookFileFilter.cs, src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7007)
=> Preserve BloomPUB sound playing for background images (BL-14642)

src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7008)
=> Update help link for Bloom Subscription tab (BL-14647)

src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7009)
=> Show game pages in play mode when publishing PDFs (BL-14620)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7010)
=> Duplicate draggable target elements properly (BL-14638)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7006)
=> Add "Drag Images to Shadows" game page (BL-14650)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7012)
=> Add Rectangle choice to the Correct/Wrong palettes (BL-14628)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/overlay/CanvasElementItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7015)
=> Fix default draggable size (BL-14644)

DistFiles/localization/en/Bloom.xlf, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7014)
=> Add "Match Words with Images" game (BL-14571)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7016)
=> Back out play mode target opacity for now (BL-14534)

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx, src/BloomExe/web/controllers/PageTemplatesApi.cs, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
Also line up the shadow and the image better when the image has been dragged to the shadow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7019)
=> Add landscape oriented page for shadow matching game (BL-14650)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7020)
=> Show images instead of shadows in the Correct tab (BL-14663)

src/BloomExe/CollectionTab/CollectionModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7021)
=> BL-14621 don't allow moving book out of a tc

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7023)
=> Adjust wording for "Drag Word to Image" game (BL-14571)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7026)
=> Add "Match Each Image to a Word" game (BL-14615)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less, src/content/bookLayout/basePage-sharedRules.less, src/content/templates/template books/Activity/Activity.pug, src/content/templates/template books/Activity/simple-dom-choice-activities.less, src/content/templates/template books/Activity/simpleComprehensionQuiz.less, src/content/templates/template books/Games/Games.less, src/content/templates/template books/Games/gamesThemes.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7025)
=> Update game theme system model (BL-14622)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7027)
=> BL-14656 make dashed border consistently visible in games

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less, src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs, src/content/templates/template books/Games/gamesThemes.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7028)
=> Match theme key to name and a few other fixes (BL-14622)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/js/CanvasGuideProvider.ts
CanvasGuideProvider is mostly by AI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7022)
=> BL-14635 Add alignment guides

src/BloomBrowserUI/collectionsTab/collectionsTabBookPane/previewMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7029)
=> Fix display of game elements in BloomPUB (BL-14622)

src/BloomBrowserUI/pageChooser/selectedTemplatePageControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7030)
=> Fix portrait page thumbnails in Add Page dialog (BL-14692)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7031)
=> Prevent overflow marking on empty Word draggable in games (BL-14643)

src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7036)
=> Initialize Word-style with horizontal centering (BL-14697)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7037)
=> Make game template titles as wide as ebook pages (BL-14685)

DistFiles/localization/en/Bloom.xlf, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7034)
=> BL-14569 Two Matching Audio with word games

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7043)
=> Remove Header and simplify Text in game pallete (BL-14704)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/react_components/localizableMenuItem.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7045)
=> Add sound submenu help text (BL-14718)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7046)
=> Fix BL-14728 Word Target Vertical Alignment

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7047)
=> Fix BL-14646 by making only the targets auto-resize

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7049)
=> Add header text for Custom Game (BL-14729)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7050)
=> Remove talking book tool vestiges from games page templates (BL-14724)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7044)
=> Copy sound file and attributes when copying canvas editables (BL-14715)

src/BloomBrowserUI/bookEdit/js/CanvasElementKeyboardProvider.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7052)
=> Ignore keyboard actions for background image elements (BL-14737)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7051)
=> Assign game styles (BL-14693)

src/BloomBrowserUI/bookEdit/css/editMode.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7054)
=> Fix a CSS syntax error introduced earlier today (BL-14734)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7055)
=> Add audio menu item for text game elements (BL-14717)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7056)
=> Keep talking book selection in sync with selection

src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7058)
=> Ensure correct file locator after collection changes (BL-14743)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7059)
=> Adjust built-in game elements to the grid (BL-14732)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7060)
=> Change GameDraggableWord*-style to GameDrag*-style (BL-14693)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/js/CanvasGuideProvider.ts, src/BloomBrowserUI/bookEdit/js/CanvasSnapProvider.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7057)
=> Snap game targets

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7061)
=> Prevent endlessly shrinking game images (BL-14740)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7063)
=> Fix a Bloom freeze adding a game page when toolbox closed (BL-14719)

src/content/templates/template books/Games/Games.less, src/content/templates/template books/Games/gamesThemes.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7064)
=> Fix up style/theme name discrepancy (BL-14693)

src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7070)
=> Adjust the sounds labels up (BL-14759)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7072)
=> Fix control frame width bug by removing jquery use (BL-14750)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7073)
=> Keep shadow copies in all tools (BL-14755)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/HtmlDom.cs, src/content/.vscode/settings.json, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7069)
=> Move default game user styles to html template (BL-14732)

src/BloomExe/Edit/EditingView.cs, src/BloomExe/web/controllers/CopyrightAndLicenseApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7074)
=> Fix gif metadata

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7075)
=> Handle canvas element location when percentage-based (BL-14761)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7076)
=> Update bloom-player in package.json (BL-14756)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7077)
=> Remove "Add child bubble" from game items (BL-14769)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7078)
=> Move Duplicate menu item before Delete (BL-14772)

src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
With JT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7080)
=> Fix thrashing on horizonal draggable text resize (BL-14771)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/games/GameIntroText.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7081)
=> Remove misleading instructions for drag games (BL-14780)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7082)
=> Make canvas text elements fixed height for games (BL-14779)

src/BloomExe/web/BloomServer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7084)
=> Prevent annoying WebView2 error message that we can't fix

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GameInfo.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7083)
=> Turn off overflow in drag games (BL-14783)

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7092)
=> Always hide target contents in play mode -- unless turned on (BL-14776)

src/BloomExe/XmlHtmlConverter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7091)
=> Prevent void HTML tags from having full end tag (BL-14695)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This code is for the Version6.0 branch.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7085)
=> Revert from data-feature attribute to enterprise-only class (BL-14584)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7093)
=> BL-14549 keep canvas menu mounted so it calculates position correctly

src/BloomBrowserUI/collection/useSubscriptionInfo.ts, src/BloomBrowserUI/publish/PublishTab/PublishingBookRequiresHigherTierNotice.tsx, src/BloomBrowserUI/react_components/featureStatus.ts, src/BloomBrowserUI/react_components/l10nHooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7086)
=> BL-14774 avoid calling l10n with each render

src/BloomBrowserUI/react_components/featureStatus.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7096)
=> Bl-14774 fix stupid mistake

src/BloomExe/CollectionTab/CollectionModel.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, src/BloomTests/TestDoubles/CollectionTab/FakeCollectionModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7068)
=> BL-14621 allow moving book from tc

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomExe/Book/BookData.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomTests/Book/BookDataTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7089)
=> Support cropping cover image (BL-14422)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/PlaceholderProvider.ts, src/BloomBrowserUI/bookEdit/toolbox/games/GamePromptDialog.tsx, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/lib/localizationManager/localizationManager.ts, src/BloomBrowserUI/react_components/l10nHooks.ts, src/BloomExe/web/I18NApi.cs, src/content/templates/template books/Games/Games.html, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7095)
=> Properly support both eager and ordinary placeholders (BL-14781) (

src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7100)
=> Fix a glitch in publishing a possibly cropped cover image (BL-14802)

src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/canvasElement.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7101)
=> Fix cropping for legacy theme (BL-14812)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7106)
=> Handle migration level and required feature in back migration (BL-14584)

src/BloomBrowserUI/bloomUI.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7104)
=> Remove obsolete less code that hides page numbers (BL-14831)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7110)
=> Merge from6.0 to6.1 20250528

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7114)
=> Update kMaintenanceLevel for data-feature attributes (BL-14511)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7116)
=> Revert back migration from data-feature to enterprise-only (BL-14584)

src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7117)
=> Merge from 6.0 to 6.1 - 20250529

src/BloomExe/Book/Book.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7120)
=> Remove need for .enterprise-only for subscription check (BL-14511)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomTests/Book/BookStorageTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7121)
=> Fix level 8 migration to only remove .enterprise-only (BL-14511)

src/BloomExe/web/controllers/AddOrChangePageApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7122)
=> Remove data-feature attribute when adding pages (BL-14511)

src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7115)
=> Prevent an infinite render in settings dialog (BL-14821)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7107)
=> Don't force activeElement in canvas init (BL-14719)

src/BloomExe/Utils/MiscUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7130)
=> Fix a broken unit test (BL-14597)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx, src/BloomExe/SubscriptionAndFeatures/FeatureRegistry.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7127)
=>  BL-14814 require subscription for whole text box recording

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.less, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx, src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx, src/BloomBrowserUI/react_components/markdown.tsx, src/BloomExe/Book/TranslationGroupManager.cs, src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs, src/BloomExe/SubscriptionAndFeatures/Subscription.cs, src/BloomExe/web/controllers/BrandingSettings.cs, src/BloomExe/web/controllers/LibraryPublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7131)
=> Support "Pro" subscriptions more fully (BL-14777)

src/BloomExe/BloomFileLocator.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7134)
=> BL-14826 don't error on bad subscription code chars

src/BloomBrowserUI/yarn.lock, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7128)
=> Restores the Order Words game and fixes problems (BL-14866)

src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx, src/BloomBrowserUI/react_components/featureStatus.ts, src/BloomExe/SubscriptionAndFeatures/FeatureStatus.cs, src/BloomExe/web/controllers/FeatureStatusApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7136)
=> Finish making music and motion require Pro (BL-14813)

DistFiles/localization/en/BloomLowPriority.xlf
Removed some unused ones.
Added missing TierWithColon
One reordering
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7148)
=> XLF cleanup related to subscriptions

src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7146)
=> Fix race condition for double click to add page (BL-14775)

src/BloomBrowserUI/bookEdit/js/origami.ts, src/BloomExe/Edit/PageListView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7147)
=> BL-14659 disable the Choose Layout menu item for pages with activities

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx, src/BloomExe/Collection/CollectionSettingsDialog.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7149)
=> Don't allow Pro subscriptions in TCs (BL-14873)

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7152)
=> Point print bleed link at wikipedia (BL-14427)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecordingSpec.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/recordable.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookSpec.ts, src/BloomExe/Edit/AudioRecording.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7108)
=> Fix checkForAnyRecording to return boolean (BL-14850)

src/BloomBrowserUI/bookEdit/js/bubbleManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7155)
=> Keep intellectual property attributes when reverting images (BL-14511)

src/BloomExe/Collection/CollectionSettingsDialog.Designer.cs, src/BloomExe/ExperimentalFeatures.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7154)
=> Turn off and hide experimental sources (BL-14553)

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/toolbox/games/GameIntroText.tsx, src/BloomExe/Book/RuntimeInformationInjector.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7156)
=> Clean up Game l10n (BL-14886)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7160)
=> Remove Duplicate and Delete options for sentence word game (BL-14883)

.vscode/settings.json, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7150)
=> BL-14827 randomly shuffle draggables

src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs, src/BloomExe/Publish/PublishModel.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7161)
=> BL-14444 improve error message for unsupported full bleed paper sizes

src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7162)
=> Provide padding to show descenders in Order Words game (BL-14885)

src/BloomExe/SubscriptionAndFeatures/FeatureStatus.cs, src/BloomExe/WebLibraryIntegration/BookUpload.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7172)
=> Restore filtering pages on upload, using Feature system (BL-14587)

src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/content/templates/template books/Games/Games.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7179)
=> BL-14827 ensure shuffled game draggables aren't already in correct order

src/BloomBrowserUI/bookEdit/toolbox/games/ThemeChooser.tsx, src/BloomBrowserUI/utils/getVariationsOnClass.ts, src/BloomExe/Book/HtmlDom.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7174)
=> Handle missing theme gracefully (BL-14801)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7176)
=> Prevent Bloom freezing when showing Playback Order buttons (BL-14898)

ReadMe.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7184)
=> Added a line about installing volta to the readme

src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7187)
=> Fully restore allowing motion in derivative (BL-14906)

src/BloomExe/web/controllers/CopyrightAndLicenseApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7188)
=> Fix a crash I've hit a few times selecting an image (20250617)

src/BloomExe/SubscriptionAndFeatures/FeatureRegistry.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7192)
=> Games may be published in derivatives (BL-14917)

src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx, src/BloomExe/SubscriptionAndFeatures/FeatureRegistry.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7193)
=> Part 2 of allowing Games to publish in derivatives (BL-14917)

src/content/templates/template books/Games/Games.html
The "Match each image to a word" or "Drag Images to Word" page
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7199)
=> Adjust target layout for portrait game page (BL-14795)

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7202)
=> Preserve publish changes to DOM that should go in data div (BL-14907)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBookAdvancedSection.tsx, src/BloomExe/SubscriptionAndFeatures/FeatureRegistry.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7178)
=> Require Pro subscription for Import Audio button (BL-14900)

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
There are at least two (related) ways to trigger this recursion.  The second one cannot be prevented a priori so easily.  From comments in the code, this method has had other problems with unterminated recursion in the past.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7195)
=> Stop recursing through setCurrentAudioElementToDefaultAsync (BL-14898)

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomBrowserUI/bookEdit/toolbox/games/ThemeChooser.tsx, src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/react_components/color-picking/colorPickerDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7201)
=> Hide popups when closing toolbox (BL-14451)

src/BloomBrowserUI/bookEdit/toolbox/overlay/overlayTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7213)
=> Another try at closing popups on page change (BL-14451)

src/BloomBrowserUI/bookEdit/js/CanvasElementContextControls.tsx, src/BloomBrowserUI/bookEdit/toolbox/games/GameTool.tsx, src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7211)
=> BL-14817 hyperlinks in games

DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/bookEdit/bookSettings/BookSettingsDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7218)
=> Add Book Settings item for Page Gutter (BL-14468)

src/BloomBrowserUI/bookEdit/toolbox/games/ThemeChooser.tsx, src/BloomBrowserUI/react_components/BloomToolTip.tsx, src/BloomBrowserUI/react_components/icons/InfoIconUrl.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7221)
=> Add info link popup for Game Theme (BL-14778)

src/BloomBrowserUI/app/selectedBook.ts, src/BloomBrowserUI/collectionsTab/BookButton.tsx, src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7234)
=> Fix some typos Typescript missed in enabling Delete (BL-14939)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Book/BookInfo.cs, src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/TeamCollection/TeamCollection.cs
Remove Report button
Add link for getting help if errors reported
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7233)
=> Improve Team Collection error reporting

DistFiles/localization/en/Bloom.xlf, DistFiles/localization/en/BloomMediumPriority.xlf, src/BloomBrowserUI/.vscode/settings.json, src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx, src/BloomBrowserUI/publish/video/PublishAudioVideo.tsx, src/BloomBrowserUI/react_components/icons/GameIcon.tsx, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookInfo.cs, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/PublishHelper.cs, src/BloomExe/Publish/Video/PublishAudioVideoAPI.cs, src/BloomExe/SubscriptionAndFeatures/FeatureRegistry.cs, src/BloomExe/web/controllers/PublishApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7236)
=> Activity -> Game in the UI; new drag-game feature on blorg (BL-14909)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/SourceCollectionsList.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7239)
=> Migrate old template books before adding their pages (BL-14960)

src/BloomBrowserUI/collectionsTab/spreadsheet/SpreadsheetExportDialog.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7244)
=> Remove Experimental badge from Export Spreadsheet dialog (BL-14974)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx, src/BloomExe/Book/HtmlDom.cs, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs, src/BloomExe/ImageProcessing/ImageUtils.cs, src/BloomExe/Program.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Publish/PublishModel.cs, src/BloomExe/WebView2Browser.cs, src/BloomExe/Workspace/WorkspaceView.cs, src/BloomExe/web/controllers/LoggerApi.cs
Part of this change is to add explicit logging from typescript code via a new api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7240)
=> Revamp Bloom logging by removing old and adding new events (BL-13484)

DistFiles/localization/en/Bloom.xlf, src/BloomExe/Publish/BloomPub/PublishToBloomPubApi.cs, src/BloomExe/Publish/BloomPub/file/FilePublisher.cs, src/BloomExe/Publish/BloomPub/usb/AndroidDeviceUsbConnection.cs, src/BloomExe/Publish/BloomPub/usb/UsbPublisher.cs, src/BloomExe/Publish/BloomPub/wifi/WiFiPublisher.cs, src/BloomTests/Publish/MockUsbPublisher.cs, src/BloomTests/Publish/UsbPublisherTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7260)
=> Stop trying to confirm successful USB file transfer BL-14992()

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7264)
=> Preserve GIF-ness when duplicating GIF images (BL-15037)

build/Bloom.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7265)
=> Make installer set organization (BL-14956)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7262)
=> Allow pasting for book renaming and other places (BL-15034)

src/BloomExe/TeamCollection/FolderTeamCollection.cs, src/BloomExe/Utils/FileSystemWatcherExtensions.cs, src/BloomExe/Utils/FileSystemWatcherWrapper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7271)
=> Possible fix for some test failures

src/BloomExe/web/controllers/BrandingSettings.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7273)
=> Add Gereja-Protestan-Maluku branding - uses default (BL-15046)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7274)
=> Fix paste in Template page label (BL-15043)

DistFiles/localization/en/Bloom.xlf, src/BloomBrowserUI/collectionsTab/SubscriptionStatus.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7277)
=> Fix problem with markdown class in XLF (BL-15048)

src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7278)
=> Show Subscription dialog for icons in More... list (BL-14720)

src/BloomExe/TeamCollection/FolderTeamCollection.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7279)
=> Clean up old tmp files in TC shared folder (BL-15012)

src/BloomExe/ErrorReporter/ErrorReportUtils.cs, src/BloomExe/FontProcessing/FontMetadata.cs, src/BloomExe/WebView2Browser.cs, src/BloomExe/web/BloomServer.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7272)
=> Remove some gratuitous exceptions being thrown (BL-15013)

src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7282)
=> Fix pasting image with no text selection (BL-14720)

src/BloomBrowserUI/bookEdit/editViewFrame.ts, src/BloomExe/Edit/EditingModel.cs, src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7285)
=> Adjust zoom by changing page in place (BL-14787)

src/BloomBrowserUI/bookEdit/editViewFrame.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7288)
=> Fix width of scaling container (BL-14787)

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7289)
=> Don't adjust controls for BG image when it is not active (BL-14720)

src/BloomExe/FontProcessing/FontMetadata.cs
(Removing a thrown exception recently wasn't handled quite right.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7290)
=> Determine font suitability for served woff2 fonts (BL-15073)

src/BloomBrowserUI/teamCollection/TeamCollectionDialog.tsx, src/BloomExe/TeamCollection/TeamCollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7295)
=> Disable "Check in All" when disconnected (BL-15062)

src/BloomExe/web/I18NApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7297)
=> Warn if Localization output has bad use of braces (BL-15048)

src/BloomExe/Collection/CollectionSettingsDialog.cs, src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7292)
=> Preserve bookshelf setting for expired subscriptions better (BL-15056)

src/BloomBrowserUI/package.json, src/BloomBrowserUI/yarn.lock, src/content/package.json, src/content/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7302)
=> Use the latest typescript (BL-15094)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/FontProcessing/FontsApi.cs, src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7306)
=> Add a problem font report for the createArtifacts command (BL-15003)

src/BloomExe/FontProcessing/FontsApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7309)
=> Fix failing unit test related to font metadata lookup (BL-15003)

src/BloomExe/Book/Book.cs, src/BloomExe/CLI/GetUsedFontsCommand.cs, src/BloomExe/Collection/CollectionSettings.cs, src/BloomExe/CollectionChoosing/OpenAndCreateCollectionDialog.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/ProjectContext.cs, src/BloomExe/Spreadsheet/SpreadsheetExportCommand.cs, src/BloomExe/TeamCollection/TeamCollection.cs, src/BloomExe/TeamCollection/TeamCollectionApi.cs, src/BloomExe/TeamCollection/TeamCollectionManager.cs, src/BloomExe/Utils/MiscUtils.cs, src/BloomExe/WebLibraryIntegration/BookDownload.cs, src/BloomExe/WebLibraryIntegration/BulkUploader.cs, src/BloomExe/web/controllers/CollectionApi.cs, src/BloomExe/web/controllers/ProblemReportApi.cs, src/BloomTests/Collection/CollectionSettingsTests.cs, src/BloomTests/OpenCreateDialogTests.cs, src/BloomTests/TeamCollection/FolderTeamCollectionTests2.cs, src/BloomTests/TeamCollection/TeamCollectionApiTests.cs, src/BloomTests/WebLibraryIntegration/BookUploadAndDownloadTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7303)
=> Normalize getting collection settings filename (BL-14788)

src/BloomExe/Publish/BloomPub/BloomPubMaker.cs, src/BloomExe/Publish/Epub/EpubMaker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7311)
=> Allow any image on a .coverColor page to be made transparent (BL-15105)

src/BloomBrowserUI/bloomUI.less, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7307)
=> Rewrote Ken Burns animation to clone entire canvas (BL-15020)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7316)
=> Fix bloom-canvas back migration requirement (BL-15108)

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx, src/BloomBrowserUI/bookEdit/toolbox/readers/decodableReader/decodableReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/readers/leveledReader/leveledReaderToolboxTool.ts, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/talkingBook.ts, src/BloomBrowserUI/bookEdit/toolbox/toolbox.ts, src/BloomBrowserUI/bookEdit/toolbox/toolboxToolReactAdaptor.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7325)
=> Fix various problems with cropping and impairment (BL-15138)

src/BloomBrowserUI/bookEdit/toolbox/impairmentVisualizer/impairmentVisualizer.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7326)
=> Restore image placeholder above BG in color-blind tool (BL-15136)

src/BloomExe/CollectionChoosing/OpenAndCreateCollectionDialog.cs, src/BloomExe/CollectionChoosing/OpenCreateCloneControl.cs, src/BloomExe/CollectionCreating/NewCollectionWizard.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7328)
=> Open Create Collection dialog on parent window screen (BL-14833)

src/BloomBrowserUI/lib/ckeditor/config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7327)
=> Allow colored text to be pasted (BL-15148)

.vscode/settings.json, src/BloomBrowserUI/.vscode/settings.json, src/content/.vscode/settings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7336)
=> Improve end-of-line settings for VS Code (BL-15158)

src/content/.vscode/settings.json, src/content/templates/template books/Games/Games.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7337)
=> Only apply game page number background rule games (BL-15164)

src/BloomExe/Collection/CollectionSettings.cs, src/BloomTests/Book/RuntimeInformationInjectorTests.cs, src/BloomTests/Collection/CollectionSettingsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7335)
=> Don't choke on invalid language subtag (BL-15159)

build/run-csharpier.sh, src/BloomBrowserUI/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7341)
=> Add a precommit hook for csharpier (BL-15176)

src/BloomExe/Edit/EditingView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7343)
=> Fix a crash opening the edit tab (BL-15181)

src/BloomBrowserUI/bookEdit/OverflowChecker/OverflowChecker.ts, src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7338)
=> Refactor overflow checking code to reduce duplication (BL-15173)

src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7345)
=> Hide background placeholder image in published game pages (BL-15201)

src/BloomExe/BloomIntegrityChecker.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7354)
=> Update PdfDroplet from exe to dll for integrity checklist

src/BloomBrowserUI/bookEdit/js/CanvasElementManager.ts, src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7357)
=> Fix bloom canvas resize while motion tool open (BL-15211)

src/BloomExe/ApplicationUpdateSupport.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7364)
=> Fix ApplicationUpdateSupport.ChannelName (BL-14973)

src/BloomExe/Publish/PublishHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7359)
=> Fix a bug in publishing images (BL-15203)

src/BloomExe/Workspace/WorkspaceView.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7362)
=> Don't crash changing UI lang if creating initial collection (BL-15230)

src/content/bookLayout/basePage-legacy-5-6.less, src/content/bookLayout/pageBoxesSizing.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7381)
=> Another tweak to full-bleed (BL-14442)

src/BloomExe/Book/BookStorage.cs, src/BloomExe/Utils/BloomUnauthorizedAccessException.cs, src/BloomExe/Utils/MiscUtils.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7379)
=> Enhance Unauthorized access report if caused by hidden folder (BL-15197)

src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7384)
=> Handle export when no widget is set (BL-15087)

src/BloomBrowserUI/bookEdit/bookLinkSetup/BookLinkTypes.ts, src/BloomBrowserUI/bookEdit/bookLinkSetup/LinkCard.tsx, src/BloomBrowserUI/bookEdit/bookLinkSetup/LinkGridSetupDialog.tsx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts, src/BloomExe/Book/BookInfo.cs, src/BloomExe/web/controllers/CollectionApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7386)
=> Show the real book titles in the FAL book grid page (BL-15252)

src/BloomExe/Book/BookStorage.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7387)
=> Update link for help on handling file permission problems (BL-15208)

src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx, src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts, src/BloomBrowserUI/package.json, src/BloomBrowserUI/utils/shared.ts, src/BloomBrowserUI/yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7374)
=> Various fixes to audio in motion preview (BL-15210, BL-15020)

build/Bloom.proj, src/BloomExe/BloomExe.csproj, src/BloomExe/BloomFileLocator.cs, src/BloomTests/BloomFileLocatorTests.cs, src/BloomTests/BloomTests.csproj, src/BloomTests/Book/BookTestsBase.cs, src/BloomTests/Book/TestBook.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7396)
=> Move test output to a separate folder (BL-15267)

src/BloomExe/CLI/CreateArtifactsCommand.cs, src/BloomExe/Collection/WritingSystem.cs, src/BloomExe/Program.cs, src/BloomTests/Utils/MiscUtilsTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7404)
=> Ignore BadImageFormatException when initializing Sldr

src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7402)
=> Prevent extra para insertion from motion (BL-15293)

src/content/branding/CABTAL/branding.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7408)
=> Add CABTAL logo to the title page (BL-15303)

src/BloomExe/Workspace/WorkspaceView.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7409)
=> BL-15296 fix layout regression bad bottom block

src/BloomExe/Edit/WebThumbNailList.Designer.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7412)
=> BL-15296 white line on page list

src/BloomBrowserUI/bookEdit/bookLinkSetup/BookLinkTypes.ts, src/BloomBrowserUI/bookEdit/bookLinkSetup/BookTargetList.tsx, src/BloomBrowserUI/bookEdit/bookLinkSetup/LinkCard.tsx, src/BloomBrowserUI/bookEdit/bookLinkSetup/LinkGridSetup.tsx, src/BloomBrowserUI/bookEdit/bookLinkSetup/LinkGridSetupDialog.tsx, src/BloomBrowserUI/bookEdit/js/bloomEditing.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7424)
=> BL-15252 fal grid title and tooltip

src/BloomBrowserUI/bookEdit/css/editMode.less, src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/content/templates/template books/Activity/Activity.pug, src/content/templates/template books/Activity/simple-dom-choice-activities.less, src/content/templates/template books/Activity/simple-dom-choice-activities.pug, src/content/templates/template books/Activity/simpleComprehensionQuiz.less, src/content/templates/template books/Activity/simpleComprehensionQuiz.pug
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7414)
=> Replace QuizHeader- and Prompt-style with GameHeader-style (BL-14794)

src/BloomExe/Utils/LongPathAware.cs, src/BloomExe/web/controllers/ProblemReportApi.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7435)
=> Merge from version6.2 again - 20251007

src/BloomBrowserUI/bookEdit/toolbox/motion/motionTool.tsx
Removing a picture also disables Motion Tool controls (BL-15321)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7427)
=> Adding a picture enables Motion Tool controls (BL-15320)

src/BloomExe/Book/Book.cs, src/BloomExe/Book/BookStorage.cs, src/BloomExe/Book/WidgetHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/7411)
=> Limit widget folder names to about 50 characters (BL-15307)
